### ISSUE TITLE
creating install media Error 'v.0.0.3'

### ISSUE THREAD

**Issue by ai-utt** [BenSova/Patched-Sur#10]
issue 1 password:
after updating to v.0.0.3 the first step 'patching usb' doesn't ask for password and i get this error: 

> error 1x1
> password: sorry, try again.
> password:
> sudo: no password was provided
> sudo: 1 incorrect password attempt

issue 2 usb:
now for the patching usb part can the usb be chosen manually again and not automatically detect it and patch it. unless this isn't the first step anyway and it's the step after choosing the usb drive, and it's already manual like the older versions of the patcher. 

thank you for the great work btw :)

**Comment by ramonenghaw** [comment]
i have this problem too

**Comment by BenSova** [comment]
Umm... oops... I left it in testing mode. I just replaced it with a real release, try that.

**Comment by ai-utt** [comment]
> Umm... oops... I left it in testing mode. I just replaced it with a real release, try that.

it works now!! thank u so much.
