### ISSUE TITLE
Error 1x1 password

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#101]
on my friend's mac this error occurs:

Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/usuario/.patched-sur/InstallAssistant.pkg'."

**Comment by BenSova** [comment]
Let's just keep this in #15 for now.

**Comment by ramonenghaw** [comment]
@BenSova I would have to download it through the direct link, correct? But it would be for 11.1. Beta 1 is there a link available?

**Comment by BenSova** [comment]
@ramonenghaw Here -> [InstallAssistant.pkg 11.1 Dev Beta 1](http://swcdn.apple.com/content/downloads/28/33/001-83606-A_VNU4WZ8Q6O/vupekyt2yqcwguho5q4zmxns1zw9qivaui/InstallAssistant.pkg)
