### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by andysinn** [BenSova/Patched-Sur#103]
After installing the upgrade, it gets tuck on a “less than a minute” sign, it stays there, it’s been more than an hour with that same sign. I tried to restart Mac Book pro mid 2012 but it re installed the upgrade and same thing happened... any suggestions? I need your help.

**Comment by BenSova** [comment]
All the information the GitHub Issue template gives you exist for a reason. Where are you coming from (Catalina v10.15.7 in most cases) and where are you going to (Big Sur v11.0.1 in most cases)? Also, that screen can take a while (the time remaining is not actually that helpful), I suggest you just let it go overnight and see what happens.

**Comment by BenSova** [comment]
It's been a couple of months with no response, so I'm closing this issue.

**Comment by ericgoe** [comment]
@andysinn I am experiencing the same problem. Did you manage to install Big Sur somehow ?
