### ISSUE TITLE
iMac 21,5 2009

### ISSUE THREAD

**Issue by baumph** [BenSova/Patched-Sur#104]
Hey,

first of all, thanks for your effort! I got Big Sur running on my 2012 MacBook Pro and my 2014 iMac with your awesome patcher. 

But i have a second iMac 21,5" from 2009. In the supported devices it is not mentioned (only the one with Nvidia Graphics). 
My device has a Radeon HD 4670. So i wonder if my iMac is compatible with this patcher?

**Comment by BenSova** [comment]
So, I'm assuming you meant 2013 iMac, because 2014 iMacs are supported last time I checked. 

I **absolutely would not** install Big Sur on a 2009 Mac. The lack of graphics acceleration is a huge thing, and it being really old too it's not going to preform that well at all.

**Comment by baumph** [comment]
Yeah, you're right. Its a 2013 iMac. 
Is there any hope for graphics acceleration for this AMD card? 

It doesn't have to be fast, because it is essentially only used as a secondary monitor.
Its only doing light web browsing.
