### ISSUE TITLE
Issue with beta v4

### ISSUE THREAD

**Issue by jameslatief** [BenSova/Patched-Sur#105]
Unable to enter password after downloading the installpackage file. Had to use beta v3 and it work flawlessly there.

**Comment by BenSova** [comment]
Do you have any special characters in your password? How I check your password changed to prevent this problem, but I'm sure it could persist. (Anything like a space, a single quote ('), ￼or maybe something like ç)

**Comment by jameslatief** [comment]
Hello BenSova,

Maybe that’s the problem. My Macbook’s password is 4 single quotes ( ‘’’’) and is probably an issue.

Regards,
James L.

**Comment by BenSova** [comment]
Yeah, I previously set it up to support double quotes and not single quotes. I'll remember that for the next update. If you want to install patched Big Sur, just change your password and try again. 

Just quick warning, make sure to turn off FileVault before you do so (Patched Sur v0.1.0 will check for this, but I should put this warning in more places until then).

**Comment by BenSova** [comment]
Fixed with Patched Sur v0.0.5, let me know if it works!

**Comment by BenSova** [comment]
Since this could be tracked in another issue and I already release something that should cover you `'`, I'm going to close this issue.
