### ISSUE TITLE
Error 1x18

### ISSUE THREAD

**Issue by rcmcminn** [BenSova/Patched-Sur#107]
**Describe the bug**
Selected the button to download the Big Sur 11.0.1 Release. The download begins. After a few minutes, the following error appears:

Error 1x18
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.3G    0 2972k    0     0  3815k      0  0:51:58 --:--:--  0:51:58 3811k
  0 11.3G    0 8628k    0     0  4927k      0  0:40:14  0:00:01  0:40:13 4925k
  0 11.3G    0 13.8M    0     0  5159k      0  0:38:26  0:00:02  0:38:24 5157k
  0 11.3G    0 19.2M    0     0  5267k      0  0:37:38  0:00:03  0:37:35 5266k
  0 11.3G    0 24.7M    0     0  5329k      0  0:37:12  0:00:04  0:37:08 5328k
  0 11.3G    0 30.1M    0     0  5370k      0  0:36:55  0:00:05  0:36:50 5614k
  0 11.3G    0 35.6M    0     0  5400k      0  0:36:43  0:00:06  0:36:37 5565k
  0 11.3G    0 41.0M    0     0  5422k      0  0:36:34  0:00:07  0:36:27 5566k
  0 11.3G    0 46.4M    0     0  5437k      0  0:36:28  0:00:08  0:36:20 5565k
  0 11.3G    0 51.8M    0     0  5440k      0  0:36:27  0:00:09  0:36:18 5544k
  0 11.3G    0 55.6M    0     0  5298k      0  0:37:25  0:00:10  0:37:15 5216k
  0 11.3G    0 60.6M    0     0  5287k      0  0:37:30  0:00:11  0:37:19 5134k
  0 11.3G    0 65.2M    0     0  5242k      0  0:37:49  0:00:12  0:37:37 4964k
  0 11.3G    0 70.0M    0     0  5219k      0  0:37:59  0:00:13  0:37:46 4838k
  0 11.3G    0 74.5M    0     0  5171k      0  0:38:20  0:00:14  0:38:06 4647k
  0 11.3G    0 79.6M    0     0  5180k      0  0:38:16  0:00:15  0:38:01 4924k
  0 11.3G    0 84.5M    0     0  5170k      0  0:38:20  0:00:16  0:38:04 4898k
  0 11.3G    0 89.9M    0     0  5187k      0  0:38:13  0:00:17  0:37:56 5046k
  0 11.3G    0 95.2M    0     0  5199k      0  0:38:08  0:00:18  0:37:50 5145k
  0 11.3G    0  100M    0     0  5214k      0  0:38:01  0:00:19  0:37:42 5344k
  0 11.3G    0  106M    0     0  5232k      0  0:37:54  0:00:20  0:37:34 5397k
  0 11.3G    0  111M    0     0  5247k      0  0:37:47  0:00:21  0:37:26 5504k
  1 11.3G    1  116M    0     0  5262k      0  0:37:41  0:00:22  0:37:19 5527k
  1 11.3G    1  122M    0     0  5266k      0  0:37:39  0:00:23  0:37:16 5514k
  1 11.3G    1  127M    0     0  5271k      0  0:37:37  0:00:24  0:37:13 5495k
  1 11.3G    1  132M    0     0  5279k      0  0:37:33  0:00:25  0:37:08 5474k
  1 11.3G    1  138M    0     0  5275k      0  0:37:35  0:00:26  0:37:09 5393k
  1 11.3G    1  141M    0     0  5226k      0  0:37:56  0:00:27  0:37:29 5065k
  1 11.3G    1  146M    0     0  5206k      0  0:38:05  0:00:28  0:37:37 4927k
  1 11.3G    1  150M    0     0  5195k      0  0:38:10  0:00:29  0:37:41 4818k
  1 11.3G    1  155M    0     0  5158k      0  0:38:26  0:00:30  0:37:56 4542k
  1 11.3G    1  159M    0     0  5152k      0  0:38:29  0:00:31  0:37:58 4487k
  1 11.3G    1  165M    0     0  5162k      0  0:38:24  0:00:32  0:37:52 4805k
  1 11.3G    1  170M    0     0  5173k      0  0:38:19  0:00:33  0:37:46 4980k
  1 11.3G    1  175M    0     0  5180k      0  0:38:16  0:00:34  0:37:42 5090k
  1 11.3G    1  181M    0     0  5186k      0  0:38:14  0:00:35  0:37:39 5361k
  1 11.3G    1  186M    0     0  5184k      0  0:38:14  0:00:36  0:37:38 5384k
  1 11.3G    1  191M    0     0  5202k      0  0:38:06  0:00:37  0:37:29 5468k
  1 11.3G    1  197M    0     0  5208k      0  0:38:04  0:00:38  0:37:26 5443k
  1 11.3G    1  202M    0     0  5214k      0  0:38:01  0:00:39  0:37:22 5451k
  1 11.3G    1  207M    0     0  5222k      0  0:37:58  0:00:40  0:37:18 5478k
  1 11.3G    1  211M    0     0  5192k      0  0:38:11  0:00:41  0:37:30 5252k
  1 11.3G    1  216M    0     0  5180k      0  0:38:16  0:00:42  0:37:34 5014k
  1 11.3G    1  221M    0     0  5169k      0  0:38:21  0:00:43  0:37:38 4874k
  1 11.3G    1  226M    0     0  5174k      0  0:38:19  0:00:44  0:37:35 4854k
  1 11.3G    1  230M    0     0  5169k      0  0:38:21  0:00:45  0:37:36 4742k
  2 11.3G    2  236M    0     0  5177k      0  0:38:17  0:00:46  0:37:31 5053k
  2 11.3G    2  241M    0     0  5184k      0  0:38:15  0:00:47  0:37:28 5211k
  2 11.3G    2  247M    0     0  5189k      0  0:38:12  0:00:48  0:37:24 5365k
  2 11.3G    2  252M    0     0  5194k      0  0:38:10  0:00:49  0:37:21 5377k
  2 11.3G    2  257M    0     0  5200k      0  0:38:07  0:00:50  0:37:17 5478k
  2 11.3G    2  263M    0     0  5206k      0  0:38:05  0:00:51  0:37:14 5469k
  2 11.3G    2  268M    0     0  5210k      0  0:38:03  0:00:52  0:37:11 5465k
  2 11.3G    2  272M    0     0  5190k      0  0:38:12  0:00:53  0:37:19 5203k
  2 11.3G    2  277M    0     0  5194k      0  0:38:10  0:00:54  0:37:16 5191k
  2 11.3G    2  283M    0     0  5199k      0  0:38:08  0:00:55  0:37:13 5191k
  2 11.3G    2  288M    0     0  5203k      0  0:38:06  0:00:56  0:37:10 5182k
  2 11.3G    2  292M    0     0  5191k      0  0:38:11  0:00:57  0:37:14 4988k
  2 11.3G    2  297M    0     0  5193k      0  0:38:10  0:00:58  0:37:12 5222k
  2 11.3G    2  302M    0     0  5188k      0  0:38:13  0:00:59  0:37:14 5126k
  2 11.3G    2  307M    0     0  5190k      0  0:38:12  0:01:00  0:37:12 5087k
  2 11.3G    2  313M    0     0  5196k      0  0:38:09  0:01:01  0:37:08 5113k
  2 11.3G    2  318M    0     0  5202k      0  0:38:07  0:01:02  0:37:05 5331k
  2 11.3G    2  324M    0     0  5208k      0  0:38:04  0:01:03  0:37:01 5380k
  2 11.3G    2  329M    0     0  5213k      0  0:38:02  0:01:04  0:36:58 5514k
  2 11.3G    2  335M    0     0  5219k      0  0:37:59  0:01:05  0:36:54 5571k
  2 11.3G    2  340M    0     0  5224k      0  0:37:57  0:01:06  0:36:51 5572k
  2 11.3G    2  346M    0     0  5229k      0  0:37:55  0:01:07  0:36:48 5569k
  3 11.3G    3  351M    0     0  5229k      0  0:37:55  0:01:08  0:36:47 5507k
  3 11.3G    3  356M    0     0  5233k      0  0:37:53  0:01:09  0:36:44 5491k
  3 11.3G    3  361M    0     0  5235k      0  0:37:52  0:01:10  0:36:42 5445k
  3 11.3G    3  367M    0     0  5240k      0  0:37:50  0:01:11  0:36:39 5444k
  3 11.3G    3  372M    0     0  5239k      0  0:37:50  0:01:12  0:36:38 5372k
  3 11.3G    3  376M    0     0  5229k      0  0:37:55  0:01:13  0:36:42 5230k
  3 11.3G    3  381M    0     0  5227k      0  0:37:56  0:01:14  0:36:42 5143k
  3 11.3G    3  386M    0     0  5224k      0  0:37:57  0:01:15  0:36:42 5074k
  3 11.3G    3  392M    0     0  5231k      0  0:37:54  0:01:16  0:36:38 5101k
  3 11.3G    3  397M    0     0  5235k      0  0:37:52  0:01:17  0:36:35 5183k
  3 11.3G    3  402M    0     0  5236k      0  0:37:52  0:01:18  0:36:34 5325k
  3 11.3G    3  408M    0     0  5240k      0  0:37:50  0:01:19  0:36:31 5431k
  3 11.3G    3  413M    0     0  5249k      0  0:37:46  0:01:20  0:36:26 5630k
  3 11.3G    3  419M    0     0  5254k      0  0:37:44  0:01:21  0:36:23 5617k
  3 11.3G    3  424M    0     0  5258k      0  0:37:42  0:01:22  0:36:20 5607k
  3 11.3G    3  429M    0     0  5245k      0  0:37:48  0:01:23  0:36:25 5397k
  3 11.3G    3  434M    0     0  5248k      0  0:37:46  0:01:24  0:36:22 5380k
  3 11.3G    3  439M    0     0  5252k      0  0:37:45  0:01:25  0:36:20 5292k
  3 11.3G    3  445M    0     0  5254k      0  0:37:44  0:01:26  0:36:18 5259k
  3 11.3G    3  449M    0     0  5249k      0  0:37:46  0:01:27  0:36:19 5095k
  3 11.3G    3  454M    0     0  5245k      0  0:37:48  0:01:28  0:36:20 5242k
  3 11.3G    3  459M    0     0  5245k      0  0:37:48  0:01:29  0:36:19 5197k
  4 11.3G    4  465M    0     0  5249k      0  0:37:46  0:01:30  0:36:16 5200k
  4 11.3G    4  470M    0     0  5252k      0  0:37:45  0:01:31  0:36:14 5208k
  4 11.3G    4  476M    0     0  5255k      0  0:37:44  0:01:32  0:36:12 5365k
  4 11.3G    4  481M    0     0  5257k      0  0:37:42  0:01:33  0:36:09 5479k
  4 11.3G    4  486M    0     0  5261k      0  0:37:41  0:01:34  0:36:07 5539k
  4 11.3G    4  492M    0     0  5263k      0  0:37:40  0:01:35  0:36:05 5517k
  4 11.3G    4  497M    0     0  5266k      0  0:37:39  0:01:36  0:36:03 5524k
  4 11.3G    4  501M    0     0  5254k      0  0:37:44  0:01:37  0:36:07 5246k
  4 11.3G    4  507M    0     0  5257k      0  0:37:43  0:01:38  0:36:05 5250k
  4 11.3G    4  512M    0     0  5259k      0  0:37:42  0:01:39  0:36:03 5230k
  4 11.3G    4  517M    0     0  5262k      0  0:37:41  0:01:40  0:36:01 5242k
  4 11.3G    4  523M    0     0  5264k      0  0:37:39  0:01:41  0:35:58 5232k
  4 11.3G    4  527M    0     0  5258k      0  0:37:42  0:01:42  0:36:00 5323k
  4 11.3G    4  532M    0     0  5255k      0  0:37:43  0:01:43  0:36:00 5218k
  4 11.3G    4  537M    0     0  5249k      0  0:37:46  0:01:44  0:36:02 5052k
  4 11.3G    4  541M    0     0  5244k      0  0:37:48  0:01:45  0:36:03 4882k
  4 11.3G    4  547M    0     0  5242k      0  0:37:49  0:01:46  0:36:03 4804k
  4 11.3G    4  551M    0     0  5237k      0  0:37:51  0:01:47  0:36:04 4804k
  4 11.3G    4  556M    0     0  5236k      0  0:37:52  0:01:48  0:36:04 4849k
  4 11.3G    4  561M    0     0  5231k      0  0:37:54  0:01:49  0:36:05 4853k
  4 11.3G    4  566M    0     0  5237k      0  0:37:51  0:01:50  0:36:01 5101k
  4 11.3G    4  571M    0     0  5238k      0  0:37:51  0:01:51  0:36:00 5139k
  4 11.3G    4  576M    0     0  5234k      0  0:37:53  0:01:52  0:36:01 5171k
  5 11.3G    5  581M    0     0  5239k      0  0:37:51  0:01:53  0:35:58 5285k
  5 11.3G    5  587M    0     0  5236k      0  0:37:52  0:01:54  0:35:58 5339k
  5 11.3G    5  592M    0     0  5239k      0  0:37:50  0:01:55  0:35:55 5283k
  5 11.3G    5  597M    0     0  5242k      0  0:37:49  0:01:56  0:35:53 5339k
  5 11.3G    5  602M    0     0  5238k      0  0:37:51  0:01:57  0:35:54 5343k
  5 11.3G    5  607M    0     0  5236k      0  0:37:52  0:01:58  0:35:54 5183k
  5 11.3G    5  612M    0     0  5234k      0  0:37:52  0:01:59  0:35:53 5200k
  5 11.3G    5  617M    0     0  5234k      0  0:37:52  0:02:00  0:35:52 5120k
  5 11.3G    5  622M    0     0  5237k      0  0:37:51  0:02:01  0:35:50 5118k
  5 11.3G    5  628M    0     0  5239k      0  0:37:50  0:02:02  0:35:48 5265k
  5 11.3G    5  633M    0     0  5242k      0  0:37:49  0:02:03  0:35:46 5368k
  5 11.3G    5  635M    0     0  5195k      0  0:38:09  0:02:05  0:36:04 4353k
  5 11.3G    5  637M    0     0  5211k      0  0:38:03  0:02:05  0:35:58 4589k
curl: (18) transfer closed with 11515121336 bytes remaining to read
**To Reproduce**
1. Mount the Patched Sur DMG'
2. Right click the icon and select Open
3. Follow the prompts to select the Release candidate and the Upgrade option
4. Select the button to download Big Sur 11.0.1
5. Download begins
6. After a few minutes, the Error 1x18 occurs.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to:  Big Sur v11.0.1
 - Mac Model: Mac (27-inch, Late 2013) iMac14,2 
- Version v0.0.4

**Additional context**
Made 3 separate attempts. Failed with the same error each time at different points in the download process.

If there are any red boxes, click on them to copy the logs.

**Comment by h092211** [comment]
Same error 3 attemps, a Day Lost downloading the image. 
is there a way to use the official image instead of downloading it any time that the program fails?

**Comment by BenSova** [comment]
1. I changed some of the mechanics with v0.0.5 that might fix this.
2. You can download [this](http://swcdn.apple.com/content/downloads/04/34/071-00838-A_16DMRFYPPS/g072hb2wh066rj040ekzry97wx2hggfuse/InstallAssistant.pkg) then choose View Other Versions and Browse.
