### ISSUE TITLE
Error creating USB

### ISSUE THREAD

**Issue by paulcheatham** [BenSova/Patched-Sur#108]
Error 1x250
Message: "Password:Erasing Disk: 0%... 10%... 20%... 30%... 100%
Couldn't mount dmg /Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
"Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

I've used multiple copies of the Big Sur Installer and still get stuck as described above. I'm a total novice and could be doing something wrong. I have followed the instructions to the best of my abilities. 

This happens about 10-15 minutes into copying the installer.

 - Upgrading from: Caltalina 10.15.7
- Upgrading to:  Big Sur 11.0.1
 - Mac Model: 15" mid 2012 Macbook Pro
 - Version 0.0.4

I have tried different USB sticks. I have also used downloaded copies of  Big Sur as well as the one that the patcher downloads. I have also downloaded the patcher more than once

Copied red box is at top of this post

**Comment by BenSova** [comment]
Try again with the latest version of macOS and patcher, I think this was fixed.

**Comment by BenSova** [comment]
Since this hasn't happened in forever and you didn't respond I'm going to close this issue.
