### ISSUE TITLE
Error path

### ISSUE THREAD

**Issue by nihiladmirari** [BenSova/Patched-Sur#109]
**Describe the bug**
Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/Luca/.patched-sur/InstallAssistant.pkg'."
But it is false. The package path is rally that. I've a McOs Catalina on iMac late2013
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by nbaroudi** [comment]
I am having the same issue.  I do have Big Sur installed on an unsupported Late 2013 iMac 27"

Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/myprofile/.patched-sur/InstallAssistant.pkg'."

![image](https://user-images.githubusercontent.com/20829469/102848638-42a9e600-43e3-11eb-89e3-3990f30878bf.png)

![image](https://user-images.githubusercontent.com/20829469/102848694-62d9a500-43e3-11eb-9fba-39222ffbbd66.png)

**Comment by BenSova** [comment]
I'm just going to close this, it is being tracked in more than enough duplicate issues already, plus it's an error that comes from a built in macOS utility. I improved the macOS package downloader, so it really shouldn't be an issue anymore after v0.1.0.
