### ISSUE TITLE
Error mounting disk image

### ISSUE THREAD

**Issue by aleksd2000** [BenSova/Patched-Sur#110]
So I downloaded Patched-Sur.dmg and it fails to open giving the error message:

The following Disk Images could not be opened:
Image:                       Reason:
Patched-Sur.dmg      no mountable filesystems

Anyone know how to fix this?

**Comment by Cyberdroid1** [comment]
Maybe try downloading again.

**Comment by BenSova** [comment]
Oh, sorry I didn't see this earlier. @aleksd2000 The app is designed to run on macOS Catalina, so even if you could mount the dmg you wouldn't be able to run it since your Mac must be running something before High Sierra (the dmg is APFS). So, since your macOS version isn't supported to begin with, this isn't an issue.

**Comment by aleksd2000** [comment]
I'm using El Capitan

On December 4, 2020 at 16:23 GMT, Pro <notifications@github.com> wrote:

Maybe try downloading again.

**Comment by BenSova** [comment]
Therefore the app won't even open, so I have no idea what you are trying to achieve by opening the dmg.

**Comment by aleksd2000** [comment]
I wanted to update my current os to big sur, and I thought that your way would be possible. But hey its not.

No worries, sorry to have bothered you.

On December 4, 2020 at 18:37 GMT, Ben Sova <notifications@github.com> wrote:

Therefore the app won't even open, so I have no idea what you are trying to achieve by opening the dmg.

**Comment by BenSova** [comment]
If you want, you can use [BarryKN's micropatcher](https://github.com/barrykn/big-sur-micropatcher) which can be run on any macOS version (as far as I know). You just need to be fine with using terminal.
