### ISSUE TITLE
“Install to this machine” with csrutil trick same as “dosdude1” Catalina patcher

### ISSUE THREAD

**Issue by calos9999** [BenSova/Patched-Sur#111]
Could you implement “Install to this machine” with csrutil trick same as “dosdude1” Catalina patcher to not use USB devices?

**Comment by BenSova** [comment]
Yeah, I'm working on it. I won't do it until later because I need to test with updating in the post install app first *and* setting the nvram while still inside a full macOS not a custom environment like the EFI Boot.

**Comment by tonyyang123** [comment]
Looking forward to the hackintosh installed by catalina patcher can also be adapted
