### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gufranco** [BenSova/Patched-Sur#112]
Do you mind adding a license file to the project so we can contribute?

**Comment by BenSova** [comment]
I'll come up with a license I like later on, but for now take this.

You can fork the project, make changes, then make a pull request to your hearts content. 

I'm curious, what do you plan to do?

**Comment by gufranco** [comment]
Since my MacBook Pro Mid 2012 isn't supported anymore and I enjoyed using Patched Sur to install macOS 11.0.1, I'd like to contribute to the project validating bug reports, fixing bugs, doing code review, etc... but I'll wait for the license to be defined and included.

This page may help you choose a license that fits your needs: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

**Comment by BenSova** [comment]
The main reason why I'm holding off right now is that I don't want to push my working copy since it has a ton of changes I don't really what "wen eta"s for the release of them. It'll probably be GNU GPLv3 though.

**Comment by johncaling40** [comment]
@BenSova I am thinking about a license for a project of mine. Can you
please give me your reasoning to use GNU GPLv2

**Comment by BenSova** [comment]
@johncaling40 It means people can't fork Patched Sur and make it closed source.

**Comment by johncaling40** [comment]
ah ok thanks

>

**Comment by southerndevz** [comment]
I think this software is better off being under control of one person. Accountability will be better managed. Too many fingers will ruin it or even use it maliciously. We appreciate your effort bro... I'm still scared to overwrite/upgrade my Catalina, I'm waiting for the tool that allows a fresh install to install in a different volume.
