### ISSUE TITLE
Patched-Sur Error

### ISSUE THREAD

**Issue by Frank63-beep** [BenSova/Patched-Sur#114]
Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/Frank/.patched-sur/InstallAssistant.pkg'."

What can i do to solve this problem?

**Comment by dennisk333** [comment]
I am receiving the same on my late 2013 IMAC

Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/Dennis/.patched-sur/InstallAssistant.pkg'."

**Comment by rzztked** [comment]
There was exactly the same mistake.  It helped to add the catalina patcher to the program folder and give universal access to the confidentiality settings.

**Comment by rzztked** [comment]
> Error 1x1
> Message: "Password:"
> "installer: Error - the package path specified was invalid: '/Users/Frank/.patched-sur/InstallAssistant.pkg'."
> 
> What can i do to solve this problem?

There was exactly the same mistake.  It helped to add the catalina patcher to the program folder and give universal access to the confidentiality settings.

**Comment by rzztked** [comment]
> I am receiving the same on my late 2013 IMAC
> 
> Error 1x1
> Message: "Password:"
> "installer: Error - the package path specified was invalid: '/Users/Dennis/.patched-sur/InstallAssistant.pkg'."
> 
> 
> 

There was exactly the same mistake.  It helped to add the catalina patcher to the program folder and give universal access to the confidentiality settings.

**Comment by amdoni** [comment]
Mac mini late 2012

Folowed the tutorial of Mr Macintoch by the minute. All installations worked well until I needed to install the kext tool and receive this message: 

Error 1x1
Message: "Password:nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found"
"csr-active-config appears to be set incorrectly:

Big sure works fine, USB works fine but not able to get WIFI activated. 

Now I am stuck...

Thanks,

 al

**Comment by BenSova** [comment]
Try booting into the EFI Boot. And you didn’t make the usb on a different Mac right?

**Comment by amdoni** [comment]
Hi Ben,

May thanks for your quick reply! 

On your question did you made the usb on a different device I am  beginning to doubt myself.

I swapped the HDD of the mini to an SSD. I used the mini with an external SSD so it could be that I did it on the external SSD but I am not sure since before using patched sur I installled Catalina on the new SSD.

Not being a programmer, stupid question maybe, but how do I booting into the EFI boot?

I take that if I used the external SSD I need to reinstall Catalina again on my mini and start the complete process again right?

Thanks for your help, I really appreciate it.

Best,

Albert

**Comment by amdoni** [comment]
Hi Ben,

Stupid me. I rebooted the mini with holding the option key. Chosed the RED ‘EFI BOOT’

Nothing happens after doing that...

Thanks,

Al

**Comment by BenSova** [comment]
Yeah that’s how it works (if it didn’t instantly turn off I would be concerned). Now try patch kexts again.

**Comment by amdoni** [comment]
Ben that did the job!!

Many many thanks!!! 🙏 

I am so happy!!

Best,

Al 

(From Holland)


Verstuurd vanaf mijn iPhone

**Comment by BenSova** [comment]
@Frank63-beep Try downloading [this](http://swcdn.apple.com/content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/InstallAssistant.pkg) and choosing View Other Version then Find an Installer when it prompts you to download/use the already downloaded installer.

**Comment by dennisk333** [comment]
@BenSova I had worked around this challenge earlier and should have posted.
I manually downloaded an installer and as you suggest above selected it when prompted and everything wen smoothly after that

**Comment by BenSova** [comment]
OP hasn't responded at all and this is like the 500th duplicate issue of this, so I'll just close this and move on. You can continue the discussion in an issue yet to be determined.
