### ISSUE TITLE
Patch Kexts error after install

### ISSUE THREAD

**Issue by fogman123** [BenSova/Patched-Sur#115]
I've successfully installed Bis Sur on iMac 21.5 Late 2013.
After login in my account, I've tried to run Patch Kexts from the patched Sur app in launchpad... but I have this error message. Usb stick is plug.
Anyway, Big Sur seems correctly installed and all working (wifi, usb... are ok).

Error 1x1
Message: "Password:nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found"
"csr-active-config appears to be set incorrectly:

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option."

**Comment by hugydoc** [comment]
i don't know how force line option
it's the same for me

**Comment by xxslimstaxx** [comment]
I ran the patch Kexts sh using terminal on the mounted usb drive, I had to use  - - force at the end. It provided a message that my iMac was a 2013 and didn’t need any of the patches, but if I try to run the Update MacOS from the GUI, it still displays it will only work in a POST Pexts OS.

**Comment by BenSova** [comment]
Well, I figured this out. The EFI Boot only saves the day when the EFI Boot needs to save the day. If you have a support EVERYTHING you don't need to patch the kexts, so therefore you don't need SIP to be turned off. I really need to make this more obvious.

**Comment by BenSova** [comment]
This is both a duplicate and code working properly, therefore not an issue, and this can be closed.
