### ISSUE TITLE
Nachdem NVRAM zurück gesetzt wurde, kein Big Sur mehr möglich!

### ISSUE THREAD

**Issue by schmutzige-dame** [BenSova/Patched-Sur#118]
Ich hatte Big Sur erfolgreich auf einem iMac ende 2013 imstalliert. Habe ab und an von einer externen Festplatte Catalina gebootet. Nach einer weile hatte Big Sur dann beim Bootvorgang fast 4 min gebraucht bis er den Desktop brachte. Nach dem löschen des NVRAM _(Alt ((Opionn)) + Command + P + R))_ war Big Sur nicht mehr bootbar. Das Startbios mit gedrückter Alt -Taste konnten ebenfalls nicht mehr aufgerufen werden. Der iMac blieb in einem schwarzen Bildschirm hängen. Es war nicht mehr möglich ein neues oder anderes Betriebssystem von einer Externen Festplatte zu booten. Ich war am verzweifeln der iMac war somit nicht mehr nutzbar. Als ich den iMac dann mit Command + R gestartet hatte kam ich in den Wiederherstellungsmodus. So dass ich wenigstens wieder Catalina installieren konnte. Dies habe ich nun auf meinem iMac und ich kann auch wieder in das Bootmenu gelangen. Dort wird mir nun das Bootmenü von (Bios) von BigSur angezeigt (Orangene Laufwerge). Doch das booten von gepachten USB-Sticks mit BiGSur ist nicht mehr möglich, es wird folgende Fehlermeldung angezeigt "(Durchgestrichener Kreis) mit Fehlermeldung supprt.apple.com/mac/startup" mittlerweile ist BigSur Version 16.1.04 veröffentlicht worden.

Ein erneutes Installieren von BigSur auf dem iMac Ende 2013 ist somit nicht mehr möglich. 

Hat jemand einen Tip wie ich es nun wieder Installiert bekomme?

Schönen Tag noch.  

________________________________________
Google translator.

I successfully installed Big Sur on an iMac in late 2013. From time to time I booted Catalina from an external hard drive. After a while it took Big Sur almost 4 minutes to boot up to bring up the desktop. After deleting the NVRAM _ (Alt ((Opionn)) + Command + P + R)) _, Big Sur was no longer bootable. The startbios with pressed Alt key could also no longer be called. The iMac got stuck on a black screen. It was no longer possible to boot a new or different operating system from an external hard drive. I was desperate, the iMac was no longer usable. When I started the iMac with Command + R, I went into recovery mode. So that I could at least install Catalina again. I now have this on my iMac and I can get back to the boot menu. There the boot menu of (Bios) of BigSur is displayed to me (orange drives). But booting from leased USB sticks with BiGSur is no longer possible, the following error message is displayed "(crossed out circle) with error message supprt.apple.com/mac/startup" Meanwhile, BigSur version 16.1.04 has been released.

It is therefore no longer possible to reinstall BigSur on the iMac at the end of 2013.

Does anyone have a tip how I can get it installed again?

Have a good time.

**Comment by BenSova** [comment]
PRAM Resets wipe all of the things Patched Sur seeds into the NVRAM to make sure macOS boots and ignores the incompatibility and custom kexts. That's why the EFI Boot drive exists, it places information into the NVRAM. Even then you could have recovered Big Sur from Catalina Recovery with a couple of Terminal commands. Your computer is still compatible, you just deleted the information Patched Sur needs in the NVRAM (I have no idea how that erased the boot picker too, but you got into recovery mode and that's enough to save your installation).

**Comment by schmutzige-dame** [comment]
Ja das mag möglich sein, doch eine erneute Installation von BigSur Patcher ist nicht  mehr möglich, dann kommt die besagte Fehlermeldung und ein durchstrichener Kreis. Wie kann ich BigSur nun wieder neu installieren?

______________________________________

Google translator

Yes that may be possible, but a new installation of BigSur Patcher is no longer possible, then the said error message appears and a circle with a line through it. How can I reinstall BigSur now?

**Comment by BenSova** [comment]
Boot into the yellow/red EFI Boot on the drive just like you did to initially install it.

**Comment by schmutzige-dame** [comment]
BenSowa, das funktioniert nicht. Es dann ein durchstichener Kreis und die Meldung "supprt.apple.com/mac/startup" angezeigt. Wartet man eine Minunte, schaltet sich der Mac aus. Eine Installation ist von dem gepatchten BiGSur Ihrer Version so nicht mehr mögloch. 

______________________________________________________

Goolgel translator

BenSowa, that doesn't work. It then displays a crossed circle and the message "supprt.apple.com/mac/startup". If you wait a minute, the Mac switches off. An installation of the patched BiGSur of your version is no longer possible.

**Comment by BenSova** [comment]
That only happens when you have a corrupt  version of macOS (the prohibited symbols means unsupported normally, but when there is text too, it means you have a corrupt version). Try reinstalling macOS Big Sur on top of the current installation.

**Comment by schmutzige-dame** [comment]
Ein neuer download von BiGSur aus Ihrem Patcher unter Catalina 10.15.7 ist nicht möglich. 
[http://wamedia.myqnapcloud.com:8080/share.cgi/Bildschirmfoto%202020-12-05%20um%2018.47.15.png?ssid=05xLfG2&fid=05xLfG2&open=normal&ep=](url)
Foldende Fehlermeldung wird angezeigt.

**Comment by schmutzige-dame** [comment]
BenSova schrieb vor zwei Tagen:

_BenSova hat vor 2 Tagen einen Kommentar abgegeben

Dies geschieht nur, wenn Sie eine beschädigte Version von macOS haben (die verbotenen Symbole bedeuten, dass sie normalerweise nicht unterstützt werden, aber wenn auch Text vorhanden ist, bedeutet dies, dass Sie eine beschädigte Version haben). Versuchen Sie, macOS Big Sur zusätzlich zur aktuellen Installation neu zu installieren._

**Lieber Ben,

ich habe nun einen neuen Stick mit Ihrem Patcher unter Catalina auf einem imac Ende 2013 erstellt. Under dem (bereits gepatchten iMac Ende 2013 wo der NVRam gelöscht wurde) ist der Stick mit Ihrem Patch nicht mehr Startfähig. 
Zu Testzwecken habe ich den neuerstellten Stick dann in einen iMac Ende 2011 eingesetzt um zu Testen ob von dem dann gebootet wird. Und ja es wird von dem neuerstellten Stick auf einem iMac Ende 2011 gebootet. 

Somit kann Ihre Aussage dass ich eine defekte Version haben wie Sie oben schreiben nicht stimmen und ist somit nicht zutreffend. 

Mein Fazit, der Patch steckt noch sehr in den Kindernschuhen. Denn so einen Crasch wie hier wenn der NVRAM gelöscht wird darf in keinem Fall vorkommen. Das macht den iMac fast unbrauchbar. Für einen Normal USER der sich nicht zu helfen wüsste, wäre der iMac bereits Totalschaden also schrott. 

Das ich nun von Ihnen keine weitere Hilfe bekomme ist dazu noch trauriger. 

Da sich zur Zeit nur zwei an einen BiGSur Patcher im Internet tummeln Sie und Ihr Kollege, kann man davon ausgehen dass BiGSur zupatchen eine sehr schwierige Angelegenheit ist. Das Sie sich an diese heranwagen ist bemerkenswert. Doch in einer sehr frühen Beta Phase die so nie veröffentlicht werdn dürte.

Also ich bin am Ende und weiß nicht mehr weiter wie BiGSur nun auf den bereits zuvor eimal gepatchten iMac 2013 wieder installiert bekomme. Support -Service lässt also zu wünschen übrig.  Echt schade. 

Haben Sie einen schönen Tag. 

_________________________________________________

Google translator:

BenSova wrote two days ago:

"BenSova commented 2 days ago

_BenSova left a comment 2 days ago

This only happens if you have a damaged version of macOS (the forbidden symbols mean they are usually unsupported, but if there is also text it means you have a damaged version). Try reinstalling macOS Big Sur in addition to the current installation._

Dear ben,

I have now created a new stick with your patcher under Catalina on an imac at the end of 2013. Under the (already patched iMac at the end of 2013 where the NVRam was deleted) the stick with your patch can no longer be started.
For testing purposes, I then inserted the newly created stick into an iMac at the end of 2011 to test whether it would then boot. And yes it will boot from the newly created stick on an iMac at the end of 2011.

So your statement that I have a defective version as you write above may not be correct and is therefore not applicable.

My conclusion, the patch is still very much in its infancy. Because such a crash as here when the NVRAM is deleted must not occur in any case. That makes the iMac almost unusable. For a normal USER who didn't know what to do, the iMac would already be a total write-off.

That I don't get any further help from you is even sadder.

Since there are currently only two people working on a BiGSur patcher on the Internet, you and your colleague can assume that patching BiGSur is a very difficult matter. That you dare to approach this is remarkable. But in a very early beta phase that should never be published.

So I'm at the end and don't know how to get BiGSur reinstalled on the iMac 2013 that was patched before. Support service leaves a lot to be desired. Too bad.

Have a nice day.**

**Comment by BenSova** [comment]
There will never be a day that a PRAM reset doesn't prevent patched macOS from booting. Doing one stops the NVRAM from telling macOS to stop the compatibility check which is the only way Big Sur will boot. You said it yourself, you were able to boot into the _new_ stick, the non-corrupt one, not the old stick the one that installed a corrupt copy of macOS. This is no early beta or two person attempt. We have been going since June and WWDC and it worked for me by Friday that week. The number of people working on this is just amazing. Not two, I don't even know how many. Nothing should be touching your EFI at all. No code in the installer or Patched Sur even cares about it. That's Clover and OpenCore territory. It's never impossible, in fact with one terminal command, you could reinstall macOS Big Sur onto that Mac (Patched Sur v0.1.0). You somehow corrupt your own firmware and I have no idea how, but something in that PRAM reset triggered it. The many reason I seem to be pulling at strings here is because I going through the steps, easiest to hardest.

**Comment by schmutzige-dame** [comment]
Hallo Ben,

nochmal, BiGSur lief träge beim Start. So hab ich gelesen dass man mit dem löschen von NVRAM das problem in den Griff gekommt. Nach dem löschen des NVRams war kein Booten mehr möglich, dass Bios wurde nicht mehr angezeigt wenn die Alt-Taste gedrückt wurde. Erst mit OPtion +R konnte ich wenigstens Catalina wieder auf den iMac Ende 2013 zum gebrauch wieder installieren sonst nichts. Sogar jetzt, wenn ich Glück habe, und mit der Alt-Taste ins Bootmenue komme, sehe ich noch das BIGSur Boot Menue. Dies sollte bei einer installation von Catalina nicht sein, denn hier müsste Catalina sein Bootmenü ins Rom geschrieben haben. Aber dem ist nicht so. 

Sie sagen ich soll meine Boot Menü (Bios) aus welchem Grund auch immer zerschossen haben. Gut und Schön, aber wie bekomme ich es wieder hin? 

Das ist hier die Frage. 

Ich wäre über jede Hilfe dankbar. 

_________________________________________________

Google translator

Hello Ben,

again, BiGSur was sluggish at the start. So I read that you can get the problem under control by deleting NVRAM. After deleting the NVRam, booting was no longer possible, the BIOS was no longer displayed when the Alt key was pressed. Only with OPtion + R could I at least reinstall Catalina on the iMac for use at the end of 2013, nothing else. Even now, if I'm lucky and come to the boot menu with the Alt key, I can still see the BIGSur boot menu. This should not be the case with an installation of Catalina, because here Catalina should have written its boot menu in Rome. But that's not the case.

They say I should have shot my boot menu (bios) for whatever reason. All well and good, but how do I get it back?

That is the question.

I would be grateful for any help.

**Comment by schmutzige-dame** [comment]
Ich bin gerade stink sauer. Der Patch hat mir meinen Mac geschossen. Also mein  Erfahrungen damit können den Patch nicht Empfehlen. Schade hatte so gut angefangen. 
___________________________________________________________

I'm pissed off right now. The patch shot my Mac. So my experience with it can not recommend the patch. Schade had started so well.

**Comment by BenSova** [comment]
@schmutzige-dame Once again, this is nothing the patch could have done, that's Open Core and Clover territory. You are the only person who has reported this so far, so from my perspective it looks like you did something wrong, not the patch. My one last suggestion is to remove **all** power to the Mac and logic board, wait ten seconds, and plug it back it. I'm not sure if this will help, but you would need to do a complete firmware reset if you really wanted the boot screen back.

**Comment by schmutzige-dame** [comment]
Lieber Ben,

der Mac wurde bereits mehrmals wie Sie erwähnt haben vom Stromnetz getrennt und sogar über nacht ohne Strom gelassen. Es hat nichts geholfen. 

Mal davon abgesehen, mag ich zwar nur der einzige sein, der dieses Problem hat, doch bin ich nicht der einzige der ein Problem mit dem Patcher meldet. Sondern andere User haben auch Probleme und die auch nur vereinzelt. 

Dies kann man nicht als Entschuldigung gelten lassen. Fackt ist, dass man nach einem NVRAM -Reset das gepatchte macOS BiGSur nicht mehr lauffähig ist und das Biso (Firmware) wohl geschossen hat. 

Schön dass Sie mir erklären dass ich ein Firmware Reset machen soll. Doch ich meine schon mal gefragt zu haben wie kann ich dies durch führen? Bislang habe ich aber keine Antwort darauf bekommen. 

Hier noch mal meine Frage, wie führe ich denn ein Firmware Reset durch. Da hab ich nähmlich keine Ahnung von. 

Danke im Vorau haben Sie einen schönen Tag. 

___________

Google translator

Dear ben,

As you mentioned, the Mac has already been unplugged several times and even left without power overnight. It didn't help.

That being said, I may be the only one who has this problem, but I'm not the only one reporting a problem with the patcher. But other users also have problems and only sporadically.

This cannot be used as an excuse. It is fake that after an NVRAM reset, the patched macOS BiGSur is no longer functional and the Biso (firmware) has probably been fired.

Nice that you explain to me that I should do a firmware reset. But I think I have already asked how can I do this? So far I have not received an answer.

Here again my question, how do I carry out a firmware reset. I have no idea about that.

Thanks in advance have a nice day.Google translator

Dear ben,

As you mentioned, the Mac has already been unplugged several times and even left without power overnight. It didn't help.

That being said, I may be the only one who has this problem, but I'm not the only one reporting a problem with the patcher. But other users also have problems and only sporadically.

This cannot be used as an excuse. It is fake that after an NVRAM reset, the patched macOS BiGSur is no longer functional and the Biso (firmware) has probably been fired.

Nice that you explain to me that I should do a firmware reset. But I think I have already asked how can I do this? So far I have not received an answer.

Here again my question, how do I carry out a firmware reset. I have no idea about that.

Thanks in advance have a nice day.

**Comment by CK0y0TE** [comment]
Well, that didn't work either.

I have a late 2013 21" too. BigSur works flawless. 
With bootcamp for occasional games. So the setup is different but I am willing to compare settings or try options to get this solved for you and give BenSova a break.
In my experience my i7 and 750M graphics are not yet obsolete by far. Your milage will vary.

off track: 
IMHO  concerning your comment on sluggishness, **the source of all the trouble**, which I experienced myself too, I fixed this way:
1 replaced the hdd with ssd (crucial mx500 1TB Sata), 
_Note if not fusion-drive delivered initially, the PCIe will not work._
_Note the Crucial extra caching boost under MS will not work under MacOS. Still the ssd is an immense permance gain_
2 add RAM to at least 16Gbyte to prevent disk swapping
3 prevent directories with lots of small files. Pack,rar,zip them old projects if you are a developper.

Question How about this procedure, what were the results?

https://discussions.apple.com/docs/DOC-3603

SMC RESET 

- Shut down the computer.
- Unplug the computer's power cord from both the wall and computer.
- Wait 15 seconds.
- Attach the computers power cable.
- Wait another 5 seconds and press the power button to turn on the computer.


PRAM RESET

- Shut down the computer.
- Locate the following keys on the keyboard: Command, Option, P, and R. You will need to hold these keys down simultaneously in step 4.
- Turn on the computer.
- Press and hold the Command-Option-P-R keys. You must press this key combination before the gray screen appears.
- Hold the keys down until the computer restarts and you hear the startup sound for the second time.
- Release the keys.

PS maybe I missed something because of the troubled correspondence?

**Comment by BenSova** [comment]
At this point I can only give one suggestions, which is to install the package I will link below. I have no idea how this happened and I haven't heard anyone tell me that this happened to them so I have no idea what to say. The below link is the most recent Catalina firmware update package from Apple that will grant you the new boot chime and maybe your boot screen back. There is nothing Patched Sur could have done to your firmware that could of caused this to happen, and I have no idea how to support you, something else must have caused this.

Install this package -> http://swcdn.apple.com/content/downloads/17/55/001-88090-A_Z2DJB72P17/0v0174vm0gco9e3hrxypcceq3tdaxlli3y/FirmwareUpdate.pkg
