### ISSUE TITLE
Coming Soon?!?!

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#12]
After downloading the NVRAM or KEXTS files, a black screen appears: Coming Soon.
![Captura de Tela 2020-11-12 às 11 52 18](https://user-images.githubusercontent.com/71452954/98955543-c667dd00-24dd-11eb-9641-df2ed734e76c.png)

**Comment by BenSova** [comment]
Well, you did click on the release update track. The release isn't till later from what I know.

**Comment by ramonenghaw** [comment]
I tried to do it with Releaser Candidate 2, and this error occurs, including I downloaded the 0.0.3 patch
![Captura de Tela 2020-11-12 às 12 45 32](https://user-images.githubusercontent.com/71452954/98962095-08e0e800-24e5-11eb-8dcd-57350d397f06.png)

**Comment by BenSova** [comment]
@ramonenghaw Click on the red box with your mouse, then paste the error to GitHub.

**Comment by ramonenghaw** [comment]
Error 1x1
Message: "Password:Error 2x1: Installer Not Found"
"Welcome to Patched Sur! (v0.0.2 build 10)
This script *should only* be used through
the Patched Sur app unless being tested
for patcher development

Detecting Installer USB at /Volumes/Install macOS Big Sur [Beta]...
Installer USB was not detected.
Please be sure to not rename the USB before
running patch-usb.sh.
"

**Comment by BenSova** [comment]
@ramonenghaw 

How long did it take you to get to that section in the app? If you never saw a welcome screen, then you still have the older version of Patched Sur. (I broke v0.0.3 so just redownload it if that's the case)

**Comment by ramonenghaw** [comment]
@BenSova 

I downloaded version 0.0.3 a few minutes ago, the error occurs after selecting the usb sticker.

**Comment by BenSova** [comment]
@ramonenghaw [Try This](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

**Comment by ramonenghaw** [comment]
> @ramonenghaw [Try This](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)
@BenSova 
I downloaded this link that you provided, it gets to format the usb sticker, but now this error appears:

Error 1x1
Password:sudo: /Applications/Install macOS Big Sur Beta.app/Contents/Resources/createinstallmedia: command not found

**Comment by greenimpala** [comment]
I just get stuck on this screen now, nothing happens when I press Continue:

 
<img width="612" alt="Screenshot 2020-11-12 at 16 17 06" src="https://user-images.githubusercontent.com/1367878/98965928-8ebf5c00-2502-11eb-85fa-efb4311c708c.png">

**Comment by ramonenghaw** [comment]
> I just get stuck on this screen now, nothing happens when I press Continue:

Are you entering your user password?

**Comment by greenimpala** [comment]
Yes of course

> > I just get stuck on this screen now, nothing happens when I press Continue:
> 
> Are you entering your user password?

**Comment by BenSova** [comment]
@greenimpala Do you have admin access on your Mac? If not maybe there's some sort of special character in your password that's interfering with the command like a quote?

@ramonenghaw I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

**Comment by ramonenghaw** [comment]
> @greenimpala Do you have admin access on your Mac? If you do maybe there's some sort of special character in your password that's interfering with the command like a quote?
> 
> @ramonenghaw I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

Now the file is being copied to the usb sticker, and it also appears in the "Application" folder that did not appear before.

**Comment by ramonenghaw** [comment]
@BenSova 
when I try to download the reseler or other beta versions, this error appears:

Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/ramonferreira/.patched-sur/InstallAssistant.pkg'."

**Comment by BenSova** [comment]
@ramonenghaw Apple's servers are down, so the download may have finished without being all the way downloaded.

**Comment by darksaviorx** [comment]
I was getting that password error too. I use # for part of the password. This new link seems to be working now. Thanks.
