### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by eliaspapas** [BenSova/Patched-Sur#120]
First of all congratulations for your project!!!😀
Can you update us about your plans and your schedule?
Thanks!

**Comment by BenSova** [comment]
1. Updating (WIP)
2. Clean installs
3. Lots of polish
4. Start using my own resources (right now I depend on the micropatcher, I want that dependency to be gone)
5. Even more Polish
6. Add some settings, show licensing for package dependencies
7. Whatever else I see fit at this point

That’ll probably become a project board at some point.
