### ISSUE TITLE
GPU Switching

### ISSUE THREAD

**Issue by manuredd** [BenSova/Patched-Sur#121]
I have a mid 2012 MacBook Pro 15in laptop with capabilities to switch between GT Geforce 650m and intel hd graphics 4000. I saw that you mentioned that the big sur patch may have issues with the switching. Do you mean it wont be able to auto switch at all? I assume this is an issue you are working on, do you have any idea when gpu switching will be completely compatible with the patcher? Thanks!

**Comment by funk4d** [comment]
> I have a mid 2012 MacBook Pro 15in laptop with capabilities to switch between GT Geforce 650m and intel hd graphics 4000. I saw that you mentioned that the big sur patch may have issues with the switching. Do you mean it wont be able to auto switch at all? I assume this is an issue you are working on, do you have any idea when gpu switching will be completely compatible with the patcher? Thanks!

You are not able switch to integrated video card. As a solution you can terminate **displaypolicyd** process, and Switching will be back.

**Comment by manuredd** [comment]
@funk4d Thanks for the reply. What is displaypolicyd and how do I change it? If i do that the auto switching will be back? Sorry if my questions are stupid.
