### ISSUE TITLE
Big Sur Loading 

### ISSUE THREAD

**Issue by ssthakran** [BenSova/Patched-Sur#125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
What do you mean "Big Sur Loading"? That's not even close to enough context for me to even diagnose this issue.
