### ISSUE TITLE
Update MacOs Not working in post-install.app

### ISSUE THREAD

**Issue by kieferlin** [BenSova/Patched-Sur#128]
Bug: "update MacOs is not working". When I open the post-install.zip file, the app unzips then, it give me this issue when I press "update macOS" --I Sent a screenshot attachment
**To Reproduce**
1. Go to 'Post Install app'
2. Click on 'the app'
3. Press the 'update macOs'

**Screenshots**
<img width="579" alt="Screen Shot 2020-12-09 at 5 14 01 PM" src="https://user-images.githubusercontent.com/67562560/101708365-f30e0680-3a41-11eb-98f0-e7aab6a03751.png">
<img width="599" alt="Screen Shot 2020-12-09 at 5 13 56 PM" src="https://user-images.githubusercontent.com/67562560/101708404-0b7e2100-3a42-11eb-8b40-d0605fade0f5.png">

**Desktop (please complete the following information):**
 - Upgrading from: [Catalina v10.15.7]
- Upgrading to: [ v11.0.1]
 - Mac Model: [15" Mid 2012 MacBook Pro]
 - Version v0.0.4]

**Comment by BenSova** [comment]
*That's because I still haven't even implemented the feature yet...*
