### ISSUE TITLE
Error when tried to download Big Sur Dev Beta 2

### ISSUE THREAD

**Issue by Cyberdroid1** [BenSova/Patched-Sur#139]
**Describe the bug**
After selecting the Dev Beta 2 of Big Sur, I got an error

**To Reproduce**
1. Go to choosing releases of Big Sur to install
2. Click on Dev Beta and select 11.1 Dev Beta 2.
3. See error

**Expected behavior**
It should have downloaded normally.

**Screenshots**

![Screenshot 2020-12-13 at 12 07 09](https://user-images.githubusercontent.com/51435948/102005018-bc830500-3d3b-11eb-8008-c32387c93b10.png)

**Desktop (please complete the following information):**
 - Upgrading from: [Big Sur 11.1 Dev Beta 1]
- Upgrading to: [e.g. Big Sur v11.1 Beta 2]
 - Mac Model: [e.g. 13" 2012 MacBook Pro Non-Retina]
 - Version [e.g. v0.0.4]

**Additional context**
<--Add any other context about the problem here.-->

Error 1x52
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server

**Comment by Cyberdroid1** [comment]
Nevermind, I retried and it is downloading.

Should I close this issue?

**Comment by BenSova** [comment]
Probably a bug with the connect between your Mac and Apple's servers, yeah not much of an issue with Patched Sur, and nothing that can't be solved by trying again.
