### ISSUE TITLE
Error 1x18

### ISSUE THREAD

**Issue by FidelGB** [BenSova/Patched-Sur#14]
when the application is downloading big sur, this error appears after downloading between 20 to 30 percent

Edit: The version is 0.0.3

![image](https://user-images.githubusercontent.com/54261598/98995624-320a7400-24f7-11eb-991d-ef6e617396e4.png)

**Comment by n3rdm0de** [comment]
https://github.com/BenSova/Patched-Sur/issues/8

**Comment by n3rdm0de** [comment]
https://github.com/BenSova/Patched-Sur/issues/8

**Comment by FidelGB** [comment]
Thank you!, although the problem now is with Apple's servers
