### ISSUE TITLE
Stuck  and not finished setup 

### ISSUE THREAD

**Issue by shokry055** [BenSova/Patched-Sur#150]
![image](https://user-images.githubusercontent.com/8462256/102418419-5b428680-4006-11eb-8e7d-705ef1d2a34b.jpg)
From Catalina it stuck here for 50 minutes
iMac early 2013

**Comment by shokry055** [comment]
![image](https://user-images.githubusercontent.com/8462256/102421803-030f8280-400e-11eb-8313-3034c0a91842.jpg)
After removing 2nd monitor it stuck here

**Comment by BUIGSHHIITTEEUURRR** [comment]
I got here also and now can't get anywhere near itzxxx

**Comment by shokry055** [comment]
i have fixed it with formatting system disk and install o it 
luckily i have a full backup for all my files and after installing system 
i returned my files 
if there is a n old system this doesn't work at all .. it keep stuck every where..

**Comment by BenSova** [comment]
Closing since this is old, covered by another issue, and it's resolved according to OP.
