### ISSUE TITLE
Stuck on patching USB

### ISSUE THREAD

**Issue by fheinis** [BenSova/Patched-Sur#156]
All steps went fine but it's stuck on "Patching USB..." since about 4 hours.
MacOS Catalina on a Mac Pro 5,1

**Comment by b1gCHAD** [comment]
I have the same issue, hangs up or stops writing during Patctching USB portion, left run for the entire night. Restarted entire process this morning and seems to be doing the same thing. 
MacBook Pro (13-inch, Early 2011) running Catalina 10.15

**Comment by BenSova** [comment]
I think I know what's going wrong here, and also this is a duplicate issue

**Comment by b1gCHAD** [comment]
I was also running it on mojave, already patched system. I have a catalina partition that im about to try again and see if i can't get it to take. 
I have big sur running on my mac but I can't seen to be able to get wifi working and don't think i have all the proper kexts installed. 
What do you think is happening? 

There should be option to use Big sur already downloaded as well, js.

**Comment by BenSova** [comment]
Uh... buddy... the app doesn't run on Mojave.

**Comment by b1gCHAD** [comment]
Or maybe im just mental but mojave is the latest next to big sur, or maybe it was Catalina, to late now. That system got changed to big sur.

**Comment by BenSova** [comment]
Mojave > Catalina (Introduction of SwiftUI, which is what Patched Sur uses) > Big Sur

**Comment by b1gCHAD** [comment]
My bad then, well hopefully this go around works out. 🤞🏼

**Comment by alexvitoriano** [comment]
Same problem, it got sucked in Patching USB for at least 8h...

MacBook Pro (13-inch, late 2011) running Catalina 10.15.3
2.4 GHz Dual-Core Intel Core i5
16 GB 1600 MHz DDR3
Intel HD Graphics 4000 512 MB
480gb SSD

**Comment by BenSova** [comment]
Can somebody go to the point where they get this, then run `sync` in terminal? The main test here is to see if the sync command is the reason it is failing to finish. If sync doesn't finish, then that's probably the case, I'll have to find a different command for that.

**Comment by alexvitoriano** [comment]
> Can somebody go to the point where they get this, then run `sync` in terminal? The main test here is to see if the sync command is the reason it is failing to finish. If sync doesn't finish, then that's probably the case, I'll have to find a different command for that.

I can! can you include the full command to run, or is just sync?

**Comment by BenSova** [comment]
@alexvitoriano It's just sync

**Comment by alexvitoriano** [comment]
> @alexvitoriano It's just sync

I've typed sync and pressed enter in terminal with the "Patching USB..." message in the screen, but it didn't made anything...
![Captura de Tela 2020-12-23 às 14 23 00](https://user-images.githubusercontent.com/5993149/103022275-6cb9f000-452a-11eb-861f-8dfc79ec09a7.png)

**Comment by RicardoSilva01** [comment]
Same here: typed sync in another window, took a few minutes and return the command prompt but nothing happened.

**Comment by pto199** [comment]
So what is the issue here?  Its been 2 Months now since the release of this patcher and I still cant get it to work as It just gets stuck on Patching USB.  If I pull the stick out and try it on boot, it just says big sur unsupported, so it looks like the USB is not getting patched.

**Comment by BenSova** [comment]
Working on a patcher isn't easy, heh.

Anyone want to try `ls /Volumes/Install\ macOS\ Big\ Sur` while it is stuck patching and send the output here?

> If I pull the stick out and try it on boot, it just says big sur unsupported, so it looks like the USB is not getting patched.

Did you boot into the EFI Boot?

**Comment by alexvitoriano** [comment]
I˜ve tried to run the command and...
![Captura de Tela 2021-01-19 às 12 43 12](https://user-images.githubusercontent.com/5993149/105057561-1ae68600-5a54-11eb-8b22-b0dc624d983a.png)

**Comment by pandjarov** [comment]
There is something wrong with the copy process because I was monitoring the disk usage in Disk Utility while it was writing and it went super slow from 41MB used to 46MB and then to 12.25GB in a second. Meanwhile:

➜  Downloads ll /Volumes/Install\ macOS\ Big\ Sur
total 0
drwxr-xr-x  3 pandjarov  staff   102B Jan 21 15:22 Install macOS Big Sur.app

and that number doesn't change. I am on Catalina 10.15.7 (19H114)

**Comment by yearmillwright** [comment]
Hi I had the same issue and i found the solution : update macos !
I had a beta release so i had to unsubscribe in the update panel and i went to apple siteweb to install 10.15.7 release.

(sorry for my english)

**Comment by yearmillwright** [comment]
But I can’t install the patches....

**Comment by BenSova** [comment]
What do you mean? What goes wrong with installing patches?

**Comment by yearmillwright** [comment]
So finally it works, but i don't know how...

I had 
<img width="590" alt="Capture d’écran 2021-01-23 à 20 14 14" src="https://user-images.githubusercontent.com/77886813/105611767-924f4900-5db7-11eb-97f7-876f3d1c8d21.png">

So i chose "force skip check", i reboot and wifi still didn't work, so I try again and this time i had this message : 
Error 1x1
Message: "Password:mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75"
"No WiFi option specified on command line, so checking for 802.11ac...
No 802.11ac WiFi card detected, so installing mojave-hybrid WiFi patch.
No patch mode specified on command line. Detecting Mac model...
(Use --2010, --2011, or --2012 command line option to override.)
Detected model: MacBookPro10,1
Detected a 2012-2013 Mac. Using --2012 patch mode.
Installing kexts to:
/

Volume appears to have a Big Sur installation (build 20C69). Continuing.
Volume is mounted from device:  /dev/disk1s5s1
Mounted device is a snapshot. Will now mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

Mounting underlying volume failed. Cannot proceed."

So i tried to reinstall Big Sur but i had this issue : https://github.com/BenSova/Patched-Sur/issues/83

So i tried to do a backup with time machine (reboot with cmd+R etc.) but it wasn't possible to do the backup on my disk where macos is installed so i reboot and finally wifi works...

For that move i had to change my password wifi perhaps it had change something...
I don't understand a thing frankly but now it seems works... so thank you !
I hope my experience would helps

(sorry again for my english !)

**Comment by pandjarov** [comment]
I have the latest release version of Catalina and it is not working. Please advise

**Comment by alexvitoriano** [comment]
I've tried many times with no success, turn it off, started again and it magically finished using Catalina 10.15.7, but I have no wi-fi right now...

**Comment by BenSova** [comment]
> When I try to open the Patched-sur in the Launchpad it crashes

This is why clean installs / using the same usb on two different Macs is discouraged. `mkdir ~/.patched-sur && touch ~/.patched-sur/track.txt` fixes the crashing problem.

**Comment by alexvitoriano** [comment]
I've try to run this in terminal and it shows me "File Exists"...

**Comment by damianxd** [comment]
Any news on this problem? has anybody solved it?

**Comment by alexvitoriano** [comment]
> Any news on this problem? has anybody solved it?

if you go for Catalina 10.15.7 is possible to install, I couldn't make it works 100% and I'm stuck in a not functional BigSur, without the Wi-fi and some other things, but I've done a clean install after my first install didn't work full...

**Comment by BenSova** [comment]
I have no idea why your app is crashing so could you please provide the crash report? Also, there are more solutions. `/Volumes/Install\ macOS\ Big\ Sur/patch-kexts.sh` is another way to patch your kexts.

**Comment by alexvitoriano** [comment]
![20210127_164950](https://user-images.githubusercontent.com/5993149/106046090-94b7e880-60c0-11eb-90c0-b708d5f543a5.jpg)
![20210127_165000](https://user-images.githubusercontent.com/5993149/106046096-9681ac00-60c0-11eb-80ce-5bb72fdf91ab.jpg)
![20210127_165009](https://user-images.githubusercontent.com/5993149/106046098-971a4280-60c0-11eb-9450-3e7afe66f2e4.jpg)
![20210127_164919](https://user-images.githubusercontent.com/5993149/106046117-9da8ba00-60c0-11eb-8cbb-005f2181adf5.jpg)
![20210127_164930](https://user-images.githubusercontent.com/5993149/106046124-9ed9e700-60c0-11eb-8eb8-86f7066e7a26.jpg)
![20210127_164941](https://user-images.githubusercontent.com/5993149/106046129-9f727d80-60c0-11eb-8de2-334c556d08a0.jpg)
![20210127_165036](https://user-images.githubusercontent.com/5993149/106046103-98e40600-60c0-11eb-85e1-fe264597bccc.jpg)
![20210127_165048](https://user-images.githubusercontent.com/5993149/106046107-9a153300-60c0-11eb-914b-6c249fdad894.jpg)
![20210127_164207](https://user-images.githubusercontent.com/5993149/106046112-9b466000-60c0-11eb-9d33-cb3e2b78d48c.jpg)
![20210127_164907](https://user-images.githubusercontent.com/5993149/106046114-9c778d00-60c0-11eb-81ca-efc8449e7143.jpg)


Sorry for the pictures, but my mac couldn't connect even with the cable...

**Comment by luchi101** [comment]
is there a solution yet ?

**Comment by BenSova** [comment]
As of Patched Sur v0.0.5, literally every command is logged into Terminal. So, if you run the app with Terminal, you'll get all the output and I only should need the most recent few lines from when this command occurs to find out what's going wrong.  The terminal command to run Patched Sur is as follows:
```
"/Volumes/Patched-Sur/Patched Sur.app/Contents/MacOS/Patched Sur - For Catalina"
```
Make sure to keep the quotes, otherwise it won't work.

**Comment by furkanonver** [comment]
my solution to usb patching stuck problem.

i opened mac to recovery mode. after open terminal and disable Mac system integrity protection.
after usb patching stuck problem finished.

**Comment by BenSova** [comment]
As of Patched Sur v0.1.0, it shows text of exactly what the patcher is doing using the "Patching USB..." text, so could someone try to send a screenshot of Patched Sur when it is stuck?

**Comment by BenSova** [comment]
Anyone?

**Comment by BenSova** [comment]
Okay, so no one responded to my request to try it, so..... closing.
