### ISSUE TITLE
Extended USB Disk problem

### ISSUE THREAD

**Issue by sjh6537** [BenSova/Patched-Sur#162]
**Describe the bug**
Internal disk is not work. I use extended disk as system disk.
After I installed patched sur on my usb extended disk (SSD) and reboot
There is deny sign showed after select ssd disk in boot menu.
When I installed on extended disk (hdd) , I can’t find it in boot menu.
Using patched sur usb install again, I cant find these extended disks in the disk utility and install target.
Using iMac recovery install program I cant find these extended disks in the disk utility and install target.

 - Upgrading from: [Catalina v10.15.? Latest ]
- Upgrading to: [Big Sur v11.1]
 - Mac Model: [ 2013 late iMac27]
 - Version [ v0.0.4]

**Comment by adamhenderson** [comment]
I have a very similar setup and also seeing this same behaviour, so it’s not an isolated issue. 

I also get into an infinite loop during installing on external usb which then unexpectedly shuts down during install, reboots and then retries the install and shuts down. 

Upgrading from: [Catalina v10.15.7]
Upgrading to: [Big Sur v11.1] (not 11.0.1)
Mac Model: [ 2013 late iMac27 14,2, 32GB]
Version [ v0.0.4]

**Comment by MHTRNT** [comment]
I also seeing the same behaviour. I select 32 gb usb flash drive as usb installer on patched sur app. After finished message on app, I reboot the machine. I select "Install macOS Big Sur" disk, but then deny sign shown on screen. I tried same procedure again and again but result is same.

Upgrading from: [Catalina v10.15.7]
Upgrading to: [Big Sur v11.1] 
Mac Model: [2012 mid MacBook Pro 9,1 / 16GB]
Version [ v0.0.4]

**Comment by BenSova** [comment]
Boot into the EFI Boot. Not an issue.

**Comment by kscheff** [comment]
Same behavoir on my mac14,2 / late iMac 2013 27" 
Looks to me that that the boot wants to install a new firmware for SMC and that crashes. I had to pull mains in order to get the SMC rebooting and allow me to select boot disc again. 
My setup uses 2 external SSD via USB for system Catalina and data,
intern HDD was not in use, but carries an bootable Catalina install.

**Comment by BenSova** [comment]
That sounds unrelated to this. They're talking about the prohibited symbol (🚫), which is solved by booting into the EFI Boot. Either way, this issue is from v0.0.4 and has not been reported since, and that version of Patched Sur is terrible compared to v0.2.0, so I'm closing this issue.
