### ISSUE TITLE
Problem with patch kexts

### ISSUE THREAD

**Issue by hugydoc** [BenSova/Patched-Sur#163]
Error 1x1
Message: "Password:nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found"
"csr-active-config appears to be set incorrectly:

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option."

I don't know whhat can i do with terminal
I try too reboot "Efi" and it's the same after

**Comment by BenSova** [comment]
Not an issue on Late 2013 iMacs.
