### ISSUE TITLE
Big Sur 11.2 Public Beta

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#166]
Hi, I'm trying to get Beta 11.2 but this message appears when I click on Public Beta on Patched Sur.

"The data couldn’t be read because it isn’t in the correct format."

**Comment by BenSova** [comment]
Yeah, it's a bug with my catalogs, give me a little bit and it'll be fixed.

**Comment by ramonenghaw** [comment]
@BenSova 
In fact, downloads came back, but it appears until 11.1, 11.2 has not yet

**Comment by BenSova** [comment]
@ramonenghaw Turns out Apple hasn't published an InstallAssistant for that version, thanks Apple!

**Comment by ramonenghaw** [comment]
@BenSova 

Is there a way for me to keep track of when InstallAssistant will be available?

**Comment by ramonenghaw** [comment]
What about 11.2 Beta?

**Comment by BenSova** [comment]
No progress yet from Apple. They haven't released anything beta related for almost a month now, so I have no idea if there will even be a beta package for this version, or even a 11.2 beta 2. All we can do is wait.

**Comment by BenSova** [comment]
Okay, forget that, there is a beta two, but still no installer package.

**Comment by BenSova** [comment]
I'm closing this issue since 11.2 is released and no discussion has happened for almost a month.
