### ISSUE TITLE
Big Sur 11.1 recovery mode restart

### ISSUE THREAD

**Issue by kimi1974** [BenSova/Patched-Sur#168]
When I try to boot into recovery mode (cmd+r) I hear boot chrome, blank screen, after few seconds monitor has "no signal" info.
Restart - black screen boot chrime, and loop until cmd + r is released.
The sam with cmd + opt +r , and shift + cmd + opt +r.
MAc pro 4.1 flashed 5.1 radeon rx 580, 64gb ram

**Comment by BenSova** [comment]
I don't really support Mac Pros, and a lot of times with them the boot screens don't work for whatever reason, so I'm closing this issue.
