### ISSUE TITLE
Automatic graphics switching

### ISSUE THREAD

**Issue by Heiseneit** [BenSova/Patched-Sur#169]
<img width="597" alt="Capture d’écran 2020-12-25 à 22 57 36" src="https://user-images.githubusercontent.com/76598260/103142522-c7a73f00-4704-11eb-90ee-22cb8385b6b1.png">

I'm on MacBook Pro Retina Mi-2012 and i have install Big Sur today with Patched-Sur, all workings fine but at one details.

Since i have install Big Sur i have lost the automatic graphics switching, its not a big problems but this make my MacBook heating up at 80 degrees (The thermal paste have been change) and my battery don't take the same times than before. 

And when i go on "About This Mac", i viewing at all the times the NVIDIA GeForce GT 650M but in normals times (On Catalina) i just have the Intel HD 4000 when i doing nothings and the NVIDIA gpu when i do the more difficult task. And now with Big Sur when i doing NOTHINGS with the animation disable, i have the NVIDIA gpu. 

I esperate to have a correction at the next update !

Without this problems, well done for the tool and thanks you !

Sorry for my english fault, i'm french baguette

**Comment by 15wat** [comment]
Hi, I have been keeping my eye out for an update for GPU switching since installing 11.01 but nothing has appeared so far that I can find, maybe someone else has, I don't know. I have since upgraded to 11.1 but the problem is still there. It looks like its an issue with our 2012 retina models in that "displaypolicyd" locks the GU into the Nvidia GT650M. This what I found on other forums as a work-around and it has solved the problem for me.
In terminal first run "sudo launchctl stop com.apple.displaypolicyd" check that your GPU is now switching as it should. This command will only fix it for the current session so you need to stop displaypolicyd loading at the next boot up by then running the following in terminal. "sudo launchctl disable system/com.apple.displaypolicyd" Good luck

**Comment by Heiseneit** [comment]
Hi, tanks you very much ! But the second command is don't work and i need to keep my Mac power on for keep the automatic graphics switching

**Comment by 15wat** [comment]
So if it's reverting back on each reboot, try running only the disable command in terminal and reboot to check it again... type it without the quotation marks,  sudo launchctl disable system/com.apple.displaypolicyd   Mine is a 10,1 like yours but a 2.7ghz and it's worked for me after only running it once but I have seen where people have said "disable" doesn't work for them. fingers crossed....

**Comment by 15wat** [comment]
Try this, in the **same** Terminal session first run 
"sudo launchctl stop com.apple.displaypolicyd"
once its run and you are back to the prompt **within the same session** run 
"sudo launchctl disable system/com.apple.displaypolicyd" 
then use the exit command to quit.. I forwarded this to someone with the same system as ours and it worked for them as well... worth a try...

**Comment by Heiseneit** [comment]
> Try this, in the **same** Terminal session first run
> "sudo launchctl stop com.apple.displaypolicyd"
> once its run and you are back to the prompt **within the same session** run
> "sudo launchctl disable system/com.apple.displaypolicyd"
> then use the exit command to quit.. I forwarded this to someone with the same system as ours and it worked for them as well... worth a try...

Thanks ! My Mac is perfectly working now !

**Comment by 15wat** [comment]
Excellent .. Now, if you still have the original Airport card you should seriously consider upgrading to a later "ac" model. Inexpensive upgrade and takes 10 minutes to install. Complete gamechanger for wifi and rounds off the Patched-Sur upgrade for our 10,1 machines making them run like a proverbial german washing machine :)

**Comment by BenSova** [comment]
Oh look, what's this?
![Screen Shot 2021-02-12 at 12 00 33 PM](https://user-images.githubusercontent.com/65474198/107810489-febfc700-6d29-11eb-9d81-2a67fdab4b95.png)

**Comment by BenSova** [comment]
https://github.com/BenSova/Patched-Sur/releases/tag/v0.0.6

There it is! Released!

**Comment by 15wat** [comment]
Brilliant !! Thank you Ben.
