### ISSUE TITLE
error erasing disk 1x252

### ISSUE THREAD

**Issue by arso-nist** [BenSova/Patched-Sur#17]
![Screen Shot 2020-11-13 at 4 13 37 PM](https://user-images.githubusercontent.com/74400551/99044789-4881ff80-25cb-11eb-8dd8-9b2dcaa1f8ce.png)

Whenever trying to install, this issue occurs

**Comment by arso-nist** [comment]
I used a different patcher and it worked fine

**Comment by schmutzige-dame** [comment]
@arso-nist,

was haben Sie denn für einen Patcher verwendet?

Besten Dank
____________________________________________________
Google translator:

@ arso-nist,

what did you use for a patcher?

Thank you very much
