### ISSUE TITLE
macOS fails to boot on zapping PRAM

### ISSUE THREAD

**Issue by Cyberdroid1** [BenSova/Patched-Sur#170]
**Describe the bug**
macOS Big Sur fails to boot upon zapping the PRAM and a prohibitory sign is shown when trying to boot the same.

**To Reproduce**

**Expected behavior**
<-- A clear and concise description of what you expected to happen. -->

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->

**Desktop (please complete the following information):**
  - Mac Model: [Non-retina 13" 2012 MacBook Pro]
 - Version [v0.0.4]

**Additional context**
I understand that zapping the PRAM resets the kexts to default and prevent from booting. Is there any way to prevent this?

**Comment by BenSova** [comment]
No, it's not the kexts, it's the compatibility check that is disabled by the EFI Boot drive, when you zap the PRAM it stops telling macOS not to do the compatibility check which prevents it from booting. There's no way to stop this and this is technically everything working as intended, so this is not an issue.

**Comment by Cyberdroid1** [comment]
So the kext check gets disabled when we boot EFI boot drive?
