### ISSUE TITLE
Clean install worked

### ISSUE THREAD

**Issue by david0z3ro** [BenSova/Patched-Sur#171]
Hi,

I formatted my SSD in the OS X boot install wizard and installed. Once installed I was missing the patcher file but I was able to download it via Ethernet from this GitHub and ran the post-install kext. Everything works incl WiFi.

It runs super smooth on earliest Retina MacBook Pro 15" (mid 2012).

However, it says Clean install is not supported. Please explain why I had no issues.

Thanks

**Comment by BenSova** [comment]
**There is no GUI in recovery mode.** You have to either run a terminal command or go all the way through setup without WiFi.

**Comment by david0z3ro** [comment]
What do you mean no graphic interface? I booted from USB stick, formatted SSD and installed everything w/o issues.

**Comment by BenSova** [comment]
You have to run a terminal command to patch the kexts. Even the post install app that gets put on the USB crashes most of the time when you do a clean install.

**Comment by david0z3ro** [comment]
> You have to run a terminal command to patch the kexts. Even the post install app that gets put on the USB crashes most of the time when you do a clean install.

Okay but as said, I have not noticed any issue other than I was missing the Patcher from /Apps folder but I downloaded it again from the repo and ran the post-install and Wi-Fi and everything worked after. Didn't need to do anything from cli. 

Hence my question, maybe I was lucky? 
Thanks for making this possible btw.

**Comment by BenSova** [comment]
Yeah, most of the time the post install app crashes when you do a clean install, I experienced this bug two days ago when I replaced my SSD. Plus, most people can't even download the app from the repo without WiFi unless they have another computer (yes, it is on the usb installer, but most people completely ignore that thing)

**Comment by david0z3ro** [comment]
> Yeah, most of the time the post install app crashes when you do a clean install, I experienced this bug two days ago when I replaced my SSD. Plus, most people can't even download the app from the repo without WiFi unless they have another computer (yes, it is on the usb installer, but most people completely ignore that thing)

Actually I do remember the app was crashing (popped up in dock to disappear immediately) but after a few attempts it suddenly opened and successfully ran the post install kexts.
