### ISSUE TITLE
Post Install Patched Sur Crashes

### ISSUE THREAD

**Issue by bray12345giff** [BenSova/Patched-Sur#172]
I have used this installer for 11.1 on 3 different MacBook pros now, they are all identical Mid 2012 13" with the 2.9Ghz i7. On the first install (on the computer that the install USB was created with), everything went just fine. On the second computer, the post install patched sur wasn't in the applications folder like it was on the first computer. I copied the application that was on the 1st computer to a USB and copied it into the applications on the 2nd computer. It wouldn't run/crashed when I tried running it from the applications folder, but I was able to run it right off the USB. Everything is working great on the 1st and 2nd computers. Now onto the 3rd, it also didn't have patched sur in the applications, so I went to do the same thing that I did with the 2nd and run it off the USB, but it crashes/won't run whether I try copying it to the applications folder or running it directly on the USB. Can some one please give me some info on why it won't run?

**Comment by BenSova** [comment]
This is a known issue when `~/.patched-sur/track.txt` doesn't exist. It will be fixed with v0.1.0.

**Comment by bray12345giff** [comment]
Is there a way for me to fix it?

**Comment by bray12345giff** [comment]
Or another way for me to get the WiFi working?

**Comment by BenSova** [comment]
`mkdir ~/.patched-sur` and press enter then `touch mkdir ~/.patched-sur/track.txt` and press enter again in terminal would make Patched Sur launch. If you want to patch your kexts type `sudo /Volumes/Install\ macOS\ Big\ Sur/patch-kexts.sh` and press enter in terminal (with the USB drive plugged in).

**Comment by bray12345giff** [comment]
@BenSova The above commands worked to get patched sur to launch, but prior to this I had already tried running patch-kexts.sh in terminal and the WiFi still doesn't work. I've run the patch through both patched sur and terminal multiple times now with no success. Any other ideas? I think it's odd that it'd work fine for the first 2 computers, but this last one is problematic.

**Comment by BenSova** [comment]
@bray12345giff Sorry, for the late reply, but can you send me the logs of patch-kexts.sh? If you can connect to Ethernet, then I would prefer text for it, but if you can't a picture works just fine.

**Comment by bray12345giff** [comment]
@BenSova Ill be home in a couple hours, should be able to send it then. Thank you!

**Comment by bray12345giff** [comment]
@BenSova Here is the terminal text

**Comment by bray12345giff** [comment]
@BenSova Any ideas? Or should I just revert back to Catalina for now

**Comment by BenSova** [comment]
@bray12345giff If you need WiFi, yes you should. I've been trying to figure out the same thing in #116, and honestly I'm lost when it comes to this, but I'll do everything I can to figure it out.

**Comment by BenSova** [comment]
Closing in support of #102 and I guess #116 too since this issue changed into something else.
