### ISSUE TITLE
Window does not resize

### ISSUE THREAD

**Issue by alanRfol** [BenSova/Patched-Sur#174]
![Screenshot 2020-12-29 at 15 41 07](https://user-images.githubusercontent.com/76741973/103295631-472a5c00-49ec-11eb-9166-cefa23c186f8.png)

Unable to resize window therefore unable to select options correctly and if you guess then unable to progress when getting to USB create screen 

![Screenshot 2020-12-29 at 16 27 22](https://user-images.githubusercontent.com/76741973/103298730-d9cdf980-49f2-11eb-8a99-4ad4fd69ee4d.png)

**Comment by BenSova** [comment]
**PATCHED SUR DOES NOT SUPPORT CATALINA 10.15.1 BETA**

I cannot develop for a buggy beta version of macOS that broke SwiftUI. End of discussion. The reason why Patched Sur doesn't support resizing is because it doesn't need to, it works in its size.

**Comment by alanRfol** [comment]
Hi

Thanks for the update and understand - I’ll update Cat first
