### ISSUE TITLE
no mountable file system

### ISSUE THREAD

**Issue by dschiller** [BenSova/Patched-Sur#175]
Executing Patched-Sur.dmg v0.0.4 Beta on 10.11.6 (15G22010) result in "Patched-Sur.dmg" no mountable file system.

**Comment by BenSova** [comment]
The Patched Sur app only supports Catalina and up (10.15), so the fact that the dmg doesn't open on anything below High Sierra is none of my concern.

**Comment by dschiller** [comment]
Thank you a lot! Installed Catalina and now it works. Great work!!
