### ISSUE TITLE
Using Startup Disk Tool result in `The bless tool was unable to set the current boot disk`

### ISSUE THREAD

**Issue by dschiller** [BenSova/Patched-Sur#176]
When I try to use the Startuo Disk Tool to set the USB Stick as the Boot Device then it says `The bless tool was unable to set the current boot disk`. Also when pressing Command Key while booting doesn't show the Boot Select Menu because I already patched to Catalina which already uses a slightly modified Boot Screen. I guess because of that the Command Key doesn't work while Booting.

**Comment by BenSova** [comment]
You use the option key, not the command key. Also, if you patched Catalina, that means you probably have a pre-2012 Mac which means you won't have graphics acceleration which means Big Sur will be really slow, **extremely** slow.

**Comment by dschiller** [comment]
Oh yes Ben, you are right. It's the Option Key. I thought I read to use the Command Key in your last Screen of the Patched-Sur Tool. Thanks a lot!! I am aware of the Performance Issues with Big Sur. I wanna try and see how it works. If it doesn't I will go back.
