### ISSUE TITLE
Trusted?

### ISSUE THREAD

**Issue by pomm22** [BenSova/Patched-Sur#179]
Should I trust GitHub? Are there any Hackers? Is this safe for my Mac?

**Comment by BenSova** [comment]
GitHub is wildly known, it hosts open-source projects where anyone can contribute. Remember on the main page it shows some files and folders? Yeah, that's the code for the app, you don't need to trust a binary. Patched Sur gives you the offical versions of macOS downloaded straight from Apple and modifies the drivers so your Mac will work. The only other thing it does is turn off the macOS compatibility check preventing it from detecting that you have an unsupported Mac.

**Comment by pomm22** [comment]
Will people spy on me

**Comment by BenSova** [comment]
No

**Comment by porcherie** [comment]
If you are concerned about safety, be aware that installing patched Big Sur will disable SIP and FileVault, so basically no more apple malware protection nor file encryption. If for you this 2 features are important, you should not upgrade to bigsur

**Comment by BenSova** [comment]
Honestly, FileVault only really matters if someone is actually going to steal your Mac and if you have a Late 2013 iMac Patched Sur will leave on SIP, other than that you might actually be able to turn on SIP if authenticated-root is off.
