### ISSUE TITLE
Error 1x1

### ISSUE THREAD

**Issue by JCDG1964** [BenSova/Patched-Sur#18]
After a minute or so...

Thanks in advance!

![Captura de pantalla 2020-11-13 a las 9 27 16](https://user-images.githubusercontent.com/74402293/99046695-692e6300-2593-11eb-9ee2-359fdab5e6da.png)

**Comment by Gabecar21** [comment]
I am having the same error. 

Error 1x1
Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

**Comment by BenSova** [comment]
Don't take the app off of the dmg file. It should stay on there, and you should run it from there. The dmg should be mounted while you are running the app.

**Comment by JCDG1964** [comment]
OK. THX a lot!
