### ISSUE TITLE
can't update macOS version

### ISSUE THREAD

**Issue by liam2003** [BenSova/Patched-Sur#182]
I used the patcher to upgrade from Catalina to Big Sur 11.0.1 but there is no way to update to Big Sur 11.1. Mid 2012 MBP

**Comment by BenSova** [comment]
**"THERE IS ALWAYS A WAY"** - _BenSova_

Do the same exact thing you did to get from Catalina to Big Sur, except go from Big Sur to Big Sur. Make a usb with the preinstall app and reinstall macOS on top of your current volume. Don't worry, it'll get easier.
