### ISSUE TITLE
Patched Sur Crashes Before Opening

### ISSUE THREAD

**Issue by jackgraddon** [BenSova/Patched-Sur#184]
**Bug Description**
Fresh after installation of macOS Big Sur 11.1 on my 13" Unibody MacBook Pro mid-2012. Patched Sur Post-Install app was no where to be found. Went to download from this GitHub repo, and the app will not open. 

I'll attach what logs showed up with the macOS error popup.
[Patched Sur Error.pdf](https://github.com/BenSova/Patched-Sur/files/5759985/Patched.Sur.Error.pdf)

**To Reproduce**
1. After installing, if app is not present, download it from this GitHub repo.
2. Move to applications, right click to open.
3. App will show on the dock, bounce once, and close.

**Expected behavior**
I expect the normal window with 'patch kexts', 'about this Mac', etc to show, and to allow me to, well, patch my kexts.

**Screenshots**
Error window:
![Screen Shot 2021-01-02 at 1 09 36 AM](https://user-images.githubusercontent.com/61634132/103454276-305b6200-4c97-11eb-8290-68597c0b91ba.png)

**Information:**
 - Upgrading from: Catalina v10.15.5
 - Upgrading to: Big Sur v11.1 Stable (Installed on a clean drive)
 - Mac Model: 13" 2012 Unibody MacBook Pro
 - Version 0.0.4

**Additional context**
The app does not open, and a macOS error report window displays, as shown in screenshot.

*If any more information is needed, please ask!*

**Comment by jempo** [comment]
Same Issue in Mac Mini Late 2012

**Comment by BenSova** [comment]
> Patched Sur Post-Install app was no where to be found.

Looks like you did a clean install.

I don't support that (yet) for several reasons, you found one of them. 

To revive the app, run this in terminal:

```shell
mkdir ~/.patched-sur && ~/.patched-sur/track.txt
```

**Comment by jackgraddon** [comment]
I've never been able to truly do an upgrade, it always completely wipes the disk. Also, just for information, the last few times I have installed Big Sur, my Mac has shown a 'no hard disk' error on boot. I have to go into recoveryOS and wipe the drive and start again.

**Comment by jackgraddon** [comment]
Also, while I was able to patch the kexts, that command didn't work correctly.
