### ISSUE TITLE
Error 1x2

### ISSUE THREAD

**Issue by flatlander2k5** [BenSova/Patched-Sur#19]
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"
/bin/bash: -c: line 1: syntax error: unexpected end of file

Using a Late '12 MBP, coming from Catalina.

**Comment by BenSova** [comment]
@flatlander2k5 What part of the patcher did you notice this in? I'm guessing createinstallmedia right?

**Comment by BenSova** [comment]
This appears to be a corrupt shell script, maybe try downloading it again and seeing what happens?

Also, I suggest checking the contents of the patch-kexts.sh file on your usb drive and seeing what's there.

**Comment by BenSova** [comment]
Closing because there was no response.
