### ISSUE TITLE
Unable to install Patched sur on macbook pro mid 2012 

### ISSUE THREAD

**Issue by yadavpramod994** [BenSova/Patched-Sur#197]
Bootable is shown after holding alt Key but show null (∅) icon on it and unable to start boot from usb drive. Also Patched-Sur.app in bootable drive shown null (∅) icon on it when opend USB drive in finder.

**Comment by BenSova** [comment]
Did you boot into the EFI Boot?

**Comment by yadavpramod994** [comment]
yes

**Comment by BenSova** [comment]
In full macOS, what does `nvram boot-args` say if you run it in terminal?

**Comment by yadavpramod994** [comment]
![Screen Shot 2021-01-09 at 21 59 15](https://user-images.githubusercontent.com/18719063/104102654-f822d780-52c5-11eb-82b1-81723db8fbee.png)

**Comment by rmansillasoto** [comment]
it's happening to me too, but my macbook pro is an early 2013 15"

**Comment by rmansillasoto** [comment]
Finally I've got big sur installed, it was that I didn't select the EFI boot first...sorry.

**Comment by yadavpramod994** [comment]
> 
> 
> Finally I've got big sur installed, it was that I didn't select the EFI boot first...sorry.
Can you explain me how you had fixed that problem?

**Comment by yadavpramod994** [comment]
@rmansillasoto Can you explain me how you had fixed that problem ?

**Comment by rmansillasoto** [comment]
Just followed the install instrctions, I forgot to choose the efi boot first and then once rebooted select install big sur.

Enviado desde mi iPhone

**Comment by kumareshr** [comment]
This tutorial may help:
https://www.youtube.com/watch?v=hgE1ssVAVKI&t=0s

**Comment by mikestrip** [comment]
Thanks for doing this. Truly a great patch as it works perfectly. Only issue is, I decided to do a PRAM reset (command,option P+R) and am getting the dreaded circle with the line through it. Also upon starting in safe mode   “command S” 

I get an error stating that: com.apple.boot.plist and Platformsupport.plist are causing Mac OSX to not be supported on this platform. Should I use another laptop to reinstall the patch or do I have to reformat the drive and start over?
![Uploading 8F1ACEB7-B025-40A2-8C9A-BE65EE02EA1E.jpeg…]()

**Comment by BenSova** [comment]
I don't think people understand this yet... maybe I should make the text bigger so it screams out.

# Did you boot into the EFI Boot?

**Comment by sailman342** [comment]
@BenSova You did a great job, it works fine if you follow exactly your instructions here https://github.com/BenSova/Patched-Sur.

I installed 11.1 on a mid 2011 iMac and to be honest I missed the yellow EFI first time. Second attempt did work like a charm :-) Very usable same without Metal GPU. Plans has a dark backgroud and launcher has sometime a strange behaviour. Visual Studio menu usage is a bit akward but it works. Installing a Metal GPU and it works 100% Great :-)

May be you can emphasis on this EFI boot topic in your instructions, I would appreciate to understand what the thing is doing, understanding the process helps following it faultlessly.

Maybe an advice to the "old" iMAc owners, you need to use the ALT option to be able to boot your mac afterwards, the start drive option found in parameters proved not to alwways work. So now on Big Sur, I need to hold down the ALT key each time rebooting or booting.

Kindest and congratualation for your work :-)

**Comment by glomeg132** [comment]
I have the same problem like yadavpramod994. When holding alt-key it shows EFI Boot option. But the icon is not as typical yellow. It is red and crossed out. Selecting EFI Boot shut down my Mac mini late 2012. After a restard I select install Big Sur. But the loader stops at 1/4 and shows something like https://support.apple.com/.

I'm coming from Catalina.

**Comment by BenSova** [comment]
> But the icon is not as typical yellow. It is red and crossed out.

That's because your boot loader supports custom icons, and red is the color of the icon and the crossed out part is a representation of the prohibited symbol. It's going to be purple in the next release because no one understood it.

> Selecting EFI Boot shut down my Mac mini late 2012.

Good, because if it did anything else I'd be really concerned. It supposed to shut down your Mac.

Now, I need someone to do something for me. Boot into recovery mode, open terminal under utilities, and run this command:
```
nvram boot-args="-v keepsyms=1 debug=0x100 -no_compat_check"
```
Then try to boot into the Install macOS Big Sur drive again. It'll be in verbose mode, so expect a lot of text, but I only need to see the last bit when it shows the prohibited symbol. Take a picture of the screen and send it here and hopefully it says something useful that I can use for debugging.

**Comment by glomeg132** [comment]
I just fixed my problem. This time I used a different USB-Stick with 32GB. Before I used a external HD with Firewire. While using the HD I was wondering that the progress to patch the HD was really fast. Now that I used the USB-Stick it took quite a while. This time the whole progress worked like a sharme. Thank you BenSova. When updating to the next BigSur Version I have to do the whole progress again right?

**Comment by BenSova** [comment]
For now, but sometime once I resolve a bug you'll be able to update without a usb.

**Comment by yadavpramod994** [comment]
Thanks @BenSova for your great work , now i have got  macos big sur installed on my macs.

**Comment by yadavpramod994** [comment]
Hi @BenSova , I have patched kext but wifi error could not join this network.
