### ISSUE TITLE
Patch Kext Error

### ISSUE THREAD

**Issue by prabhangshuk** [BenSova/Patched-Sur#198]
**Describe the bug**
I got an error when I tried to install Patch Kext - 
Error 1x1
Message: "Password:nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found"
"csr-active-config appears to be set incorrectly:

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option."

**To Reproduce**
1. Installed Big Sur
2. Clicked on Patched-Sur
3. Clicked on Patched Kexts
4. Clicked Continue
5. Clicked Force Skip Check

Although I got the error but my USB and my Wifi is working fine.
Did I do anything wrong?
Pls advise.
Thanks heaps anyways.
Have a good day.

**Comment by BenSova** [comment]
Not a bug since you don't need patch kexts anyway. Enjoy Big Sur!
