### ISSUE TITLE
WiFi not working on a MBPR mid 2012

### ISSUE THREAD

**Issue by fpereira-pt** [BenSova/Patched-Sur#206]
Followed the steps in the "How do I use Patched Sur" but WIFI is not working. 

Everything worked well until the last step "Open the Patch Kexts section and enter your password" that nothing happened.

Besides that I think all other things are working 100%.

Thanks in advance

**Comment by BenSova** [comment]
What do you mean "that nothing happened"? Did it reject your password? Did it show your error? Did it go through all the way, no errors, but it didn't work? Did the app not show up in your Applications folder? I need context.

**Comment by fpereira-pt** [comment]
Hi BenSova,

Thanks for your help. In the last step I receive this message.  

<img width="712" alt="Screenshot 2021-01-16 at 19 55 55" src="https://user-images.githubusercontent.com/77550782/104823002-c1f1d480-583e-11eb-8d34-42faaae3202b.png">

**Comment by BenSova** [comment]
Is the installer usb you used to install macOS plugged in? If not, plug it in and click the big blue button. If it is, click the Force Skip Check button.

**Comment by fpereira-pt** [comment]
Yes the usb was plugged but not sure if i did click in that Force Skip Check button. 

I tried to repeat all the steps again in last hour and now I´m not able to finish the process and I receiving this message "Error 1x1 Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"

**Comment by fpereira-pt** [comment]
Yes the usb was plugged but not sure if i did click in that Force Skip Check button. 

I tried to repeat all the steps again in last hour and now I´m not able to finish the process and I receiving this message "Error 1x1 Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"

**Comment by BenSova** [comment]
Don't move the app off of the DMG file. The dmg file you downloaded from github should always be mounted while the preinstall app is running.

**Comment by fpereira-pt** [comment]
Thanks BenSova.
This is a little confusing for me and will try to do the all the process again.

**Comment by fpereira-pt** [comment]
Hi again BenSova,
Just to let you know that everything is 100% after repeting the process. Realised that didnt click the Force Skip Check button.
Thanks again !

**Comment by BenSova** [comment]
Awesome!
