### ISSUE TITLE
Background problems on MS teams

### ISSUE THREAD

**Issue by Solomon-Wood** [BenSova/Patched-Sur#216]
The computer has been able to run MS Teams with background options. I know it works on Mojave. It does not work on Big Sur. I need a blurred background for my work meetings.

I have used the MacBook Pro Late 2012 (Retina), and otherwise I have had no problems with the patcher. To reproduce the problem, simply run MS Teams on a computer like mine.

The background option will simply not be there, same as on my Mid 2010 iMac which I know doesn't support blurred background.

Sorry, I can't get screenshots as I had to roll back to Mojave. That's how serious the problem is.

 - Upgrading from: [Catalina v10.15.7]
- Upgrading to: [Big Sur v11.1]
 - Mac Model: [13" Late 2012 MacBook Pro with Retina display]
 - Version [v0.0.4]

Thanks in advance.

**Comment by LuchoRod** [comment]
I guess apparently is more a decision of Microsoft then an issue for this patcher:
[https://www.digihelpdesk.co.uk/is-microsoft-teams-blur-background-not-available-on-mac/](https://www.digihelpdesk.co.uk/is-microsoft-teams-blur-background-not-available-on-mac/)

**Comment by BenSova** [comment]
Not a patcher bug, but a decision made by Microsoft. If you downgrade it's probably going to be the same.
