### ISSUE TITLE
FaceTime/iMessage not working ?

### ISSUE THREAD

**Issue by IP0HY** [BenSova/Patched-Sur#22]
Hello, 

is it normal that FaceTime and iMessage are not working after the update ?

**Comment by BenSova** [comment]
I'm not 100% sure what's wrong, I'll look into it, but maybe this might help. https://github.com/barrykn/big-sur-micropatcher/issues/12

**Comment by BenSova** [comment]
@IP0HY Hey, can you try again with the latest version of patcher and macOS?
