### ISSUE TITLE
Security and Privacy is not allowing 3rd party developers

### ISSUE THREAD

**Issue by RicardoSilva01** [BenSova/Patched-Sur#224]
**Describe the bug**
After downloading a package not from Apple Store, on the General tab under Security and Privacy option on Preferences is not displaying the 3rd option on the "Allow apps downloaded from:" where I could choose to install 3rd party apps.
![SecurityAndPrivacy](https://user-images.githubusercontent.com/76794327/106078342-18c19e80-60c8-11eb-9e5a-a9845372e72c.png)

**To Reproduce**
1. Download any app not from App Store
2. Install the product
3. OS says that in order to install the app in Application folder, a permission needs to be granted on Security& Privacy preferences.
4. The option is missing (see screenshot)

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
 - Mac Model: 27" late 2012 iMac
 - Version (of what?)
 

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
How could this be a patcher bug? I change two things about your Mac, the rest is handled by macOS. This has nothing to do with how the hardware interacts with the software, so it could easily be a bug in Big Sur.
