### ISSUE TITLE
Mid-2012 Retina MBP 15" - "InstallAssistant is damaged"

### ISSUE THREAD

**Issue by zombienm** [BenSova/Patched-Sur#225]
Every time I try to boot into recovery to install BigSur, I get the notification that the InstallAssistant is damaged and can not be used. I've tried downloading it directly from Apple and then patching it, and also using Patched-Sur to download it. Everything I try gets the same issue. Does anyone know how to solve this?

**Comment by BenSova** [comment]
This is a duplicate of #100. There was a lot of discussion regarding this issue there.
