### ISSUE TITLE
Late 2012 27 iMac WIFI not working after several installs and Patch Kexts (11.0, 11.1, 11.2, 11.3Beta)

### ISSUE THREAD

**Issue by St-Eve-Larr** [BenSova/Patched-Sur#226]
I followed the steps and everything works great except for WIFI.   Running on ethernet until fix. 
The installer used the 11.1 release. 
**To Reproduce**
Removing the wifi settings in Network Preferences does not help. 
Running the Patched Sur (0.0.4) from USB or Applications - Same result.  
Does not see known or unknown networks.
Bluetooth Works. 

Here are the details of the WIFI module:
  Software Versions:
  CoreWLAN:	16.0 (1657)
  CoreWLANKit:	16.0 (1657)
  Menu Extra:	17.0 (1728)
  System Information:	15.0 (1502)
  IO80211 Family:	12.0 (1200.12.2)
  Diagnostics:	11.0 (1163)
  AirPort Utility:	6.3.9 (639.15)
  Interfaces:
en1:
  Card Type:	AirPort Extreme  (0x14E4, 0xF4)
  Firmware Version:	Broadcom BCM43xx 1.0 (7.21.190.34 AirPortDriverBrcm4360-1325.3)
  MAC Address:	ec:35:86:47:bc:8c
  Locale:	FCC
  Country Code:	CA
  Supported PHY Modes:	802.11 a/b/g/n
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  AirDrop:	Supported
  AirDrop Channel:	149
  Status:	Not Associated

**Comment by Stellarspace** [comment]
This isn't a bug. I have the same Mac, the same operating system version, the same Wi-Fi card, and it works.

**Comment by St-Eve-Larr** [comment]
Thanks.  Good to know.  It's working with a usb wifi and ethernet.
I'll try again this weekend with 11.2.

________________________________

**Comment by ozziepadilla** [comment]
My iMac late 2013 works everything in the first time I run patched Sur and also works with updating to 11.2 not need to run patched kexts because wifi works right after installation finish

**Comment by St-Eve-Larr** [comment]
My 27 2012 works well except for the WiFi.   Ran the process 3 times, including the 11.2 update.   I restored the install on a USB - SSD and the image boots flawlessly, just a little slow, on my 27 2011 with WiFi.   However it does boot at all on my 21.5 2012.

**Comment by BenSova** [comment]
Can you send the logs of `patch-kexts.sh`?

**Comment by St-Eve-Larr** [comment]
Thanks for looking into it @BenSova 
[patch-kexts.sh.log](https://github.com/BenSova/Patched-Sur/files/5939715/patch-kexts.sh.log)

**Comment by BenSova** [comment]
That's the contents of the script, not the logs of the script. Run the command then send what it prints as output.

**Comment by St-Eve-Larr** [comment]
Where/How do I go about finding the details on how to capture the logs.

**Comment by BlueG6o** [comment]
same problem here. Worked fine on my mini 2012 on 11.0 and 11.1 but does not after upgrading on 11.2. patching the kexts without any problem and after that the WiFi is recognized from the mac. But can’t find any network.

**Comment by BlueG6o** [comment]
After running wireless diagnostics everything works fine. I don't understand why, but it does.

**Comment by St-Eve-Larr** [comment]
I have the same result for 11.0, 11.1 and 11.2 Wireless Diagnostics didn't help.

**Comment by ososx** [comment]
Ran the post patch twice (aside from having to press "skip" for not recognizing the installer all worked great). Now I am able to connect to the hotspot on my iPhone and the open (visitors) WiFi network at my workplace. I am unable to connect to the secure WPA network ... any ideas?

**Comment by St-Eve-Larr** [comment]
It wouldn't be a big deal to use a USB wifi but this setup does not work with my Paralells VMs - I'm hoping we can find a kext or workaround to make the AirPort work.

**Comment by Stellarspace** [comment]
I restarted my Mac recently, and the Wi-Fi doesn't work anymore. I was using Ethernet anyways.

**Comment by St-Eve-Larr** [comment]
@Stellarspace Maybe this is the motivation I needed to run an Ethernet drop to my standing desk office - not even mad.

**Comment by BenSova** [comment]
Okay, sorry I have slightly ignored this issue, but I want to clarify I don't need the contents of patch-kexts.sh or the crash report from Patched Sur, all I need what patch-kexts.sh prints out into Terminal. So, basically just this:

https://user-images.githubusercontent.com/65474198/108155888-e7bc0480-709c-11eb-9208-60380bffd8a5.mov

Which would give something like this:

```
This is really the real patch kexts script
Totally....
Getting ready to patch the kexts...
Not actually patching the kexts because
this is only an example script.
Realizing I forgot to put echo at the beginning
of each line...
Adding echo to the beginning of each line
Why am I doing this?
It should be done by now...
If you haven't realized by now, this
is only a example script.
Pretending like patch-kexts.sh is done
Oh yeah, patch-kexts.sh is done now by the way.
```

(Obviously with real logs and not some fake thing I made in a couple of minutes)

**Comment by St-Eve-Larr** [comment]
Thank you for the outstanding effort Mr. Sova.  Do you have a buy me a beer/coffee/weed link? I'd love to demonstrate my sincere appreciation.

Here is the terminal output as requested:

No WiFi option specified on command line, so checking for 802.11ac...
No 802.11ac WiFi card detected, so installing mojave-hybrid WiFi patch.
No patch mode specified on command line. Detecting Mac model...
(Use --2010, --2011, or --2012 command line option to override.)
Detected model: iMac13,2
Detected a 2012-2013 Mac. Using --2012 patch mode.
Installing kexts to:
/

Volume appears to have a Big Sur installation (build 20E5172i). Continuing.
Volume is mounted from device:  /dev/disk1s2s1
Mounted device is a snapshot. Will now mount underlying volume
from device /dev/disk1s2 at temporary mountpoint:
/System/Volumes/Update/mnt1

Checking for KernelCollections backup...
Backup found, so not overwriting.
Beginning patched IO80211Family.kext installation
Installing mojave-hybrid WiFi patch
Using kmutil to rebuild boot collection...
Using kmutil to rebuild system collection...
Copying deferred prelinked kernels in /System/Volumes/Update/mnt1...
Copying: /System/Volumes/Update/mnt1/Library/Apple/System/Library/PrelinkedKernels/prelinkedkernel -> /System/Volumes/Update/mnt1/System/Library/PrelinkedKernels
Copying KCs in /System/Volumes/Update/mnt1...
System Volume UUID: B766F8C8-C439-46C0-A1A5-7E03D3BF05E6
Volume Group UUID: CFC381F9-8043-37A5-A256-A9957B653F48
Preboot disk: /dev/disk1s3
Preboot volume: /System/Volumes/Preboot
Copying: /System/Volumes/Update/mnt1/System/Library/KernelCollections/BootKernelExtensions.kc.elides -> /System/Volumes/Preboot/CFC381F9-8043-37A5-A256-A9957B653F48/boot/System/Library/KernelCollections
Copying: /System/Volumes/Update/mnt1/System/Library/KernelCollections/BootKernelExtensions.kc -> /System/Volumes/Preboot/CFC381F9-8043-37A5-A256-A9957B653F48/boot/System/Library/KernelCollections
Copying: /System/Volumes/Update/mnt1/System/Library/PrelinkedKernels/prelinkedkernel -> /System/Volumes/Preboot/CFC381F9-8043-37A5-A256-A9957B653F48/System/Library/PrelinkedKernels
Creating new root snapshot.
Attempting to unmount underlying volume (don't worry if this fails).
This may take a minute or two.
umount(/System/Volumes/Update/mnt1): Resource busy -- try 'diskutil unmount'
Volume 960GB on disk1s2 failed to unmount: dissented by PID 0 (kernel_task)
Installed patch kexts successfully.

**Comment by HannHenne** [comment]
I always get that 

nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
csr-active-config appears to be set incorrectly:
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option.
valent_plesa@Valents-iMac ~ %

**Comment by HannHenne** [comment]
I always get that

nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
csr-active-config appears to be set incorrectly:
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
--force command line option.
valent_plesa@Valents-iMac ~ %

**Comment by Stellarspace** [comment]
When I run patch-kexts.sh, I get the following output:

> No WiFi option specified on command line, so checking for 802.11ac...
> No 802.11ac WiFi card detected, so installing mojave-hybrid WiFi patch.
> No patch mode specified on command line. Detecting Mac model...
> (Use --2010, --2011, or --2012 command line option to override.)
> Detected model: iMac13,2
> Detected a 2012-2013 Mac. Using --2012 patch mode.
> Installing kexts to:
> /
> 
> Volume appears to have a Big Sur installation (build 20D75). Continuing.
> Volume is mounted from device:  /dev/disk5s1s1
> Mounted device is a snapshot. Will now mount underlying volume
> from device /dev/disk5s1 at temporary mountpoint:
> /System/Volumes/Update/mnt1
> 
> Checking for KernelCollections backup...
> Backup not found. Performing backup now. This may take a few minutes.
> Backing up original KernelCollections to:
> /System/Volumes/Update/mnt1/System/Library/KernelCollections/KernelCollections-20D75.tar.lz4
> a BootKernelExtensions.kc
> a SystemKernelExtensions.kc
> Beginning patched IO80211Family.kext installation
> Installing mojave-hybrid WiFi patch
> Using kmutil to rebuild boot collection...
> Using kmutil to rebuild system collection...
> Copying deferred prelinked kernels in /System/Volumes/Update/mnt1...
> Copying: /System/Volumes/Update/mnt1/Library/Apple/System/Library/PrelinkedKernels/prelinkedkernel -> /System/Volumes/Update/mnt1/System/Library/PrelinkedKernels
> Copying KCs in /System/Volumes/Update/mnt1...
> System Volume UUID: B4922D8E-4A2F-4DEE-AFF2-C979A1080070
> Volume Group UUID: BF4477AD-455B-4CC0-AD50-6C2E6658CE04
> Preboot disk: /dev/disk5s3
> Preboot volume: /System/Volumes/Preboot
> Copying: /System/Volumes/Update/mnt1/System/Library/KernelCollections/BootKernelExtensions.kc.elides -> /System/Volumes/Preboot/BF4477AD-455B-4CC0-AD50-6C2E6658CE04/boot/System/Library/KernelCollections
> Copying: /System/Volumes/Update/mnt1/System/Library/KernelCollections/BootKernelExtensions.kc -> /System/Volumes/Preboot/BF4477AD-455B-4CC0-AD50-6C2E6658CE04/boot/System/Library/KernelCollections
> Copying: /System/Volumes/Update/mnt1/System/Library/PrelinkedKernels/prelinkedkernel -> /System/Volumes/Preboot/BF4477AD-455B-4CC0-AD50-6C2E6658CE04/System/Library/PrelinkedKernels
> Creating new root snapshot.
> Attempting to unmount underlying volume (don't worry if this fails).
> This may take a minute or two.
> umount(/System/Volumes/Update/mnt1): Resource busy -- try 'diskutil unmount'
> Volume Macintosh HD on disk5s1 failed to unmount: dissented by PID 0 (kernel_task)
> Installed patch kexts successfully.

**Comment by St-Eve-Larr** [comment]
@gregj66 In your System report/WIFI do you have the same wifi interface?    
I have this one; Supported PHY Modes:	802.11 a/b/g/n

**Comment by St-Eve-Larr** [comment]
Thanks @gregj66 I'll try again.   I've tried at least 5 times.  Last time was with 0.7 with 11.3Beta.   It installs perfectly, minus AirPort. 
I'll give it another go with 0.7beta and 11.2.2.  Maybe I'm not restarting the process back early enough...   wondering if I should go back to Catalina as a starting point.

**Comment by gregj66** [comment]
@St-Eve-Larr I just wanted to clarify that I'm on 11.2.1 and not 11.2.**2** just in case that was the difference between AirPort working or not.

I upgraded straight from Catalina to 11.2.1

**Comment by Stellarspace** [comment]
### System Report... > Network > Wi-Fi:
>   Software Versions:
>   CoreWLAN:	16.0 (1657)
>   CoreWLANKit:	16.0 (1657)
>   Menu Extra:	17.0 (1728)
>   System Information:	15.0 (1502)
>   IO80211 Family:	12.0 (1200.12.2b1)
>   Diagnostics:	11.0 (1163)
>   AirPort Utility:	6.3.9 (639.15)

![Screen Shot 2021-03-04 at 1 59 31 PM](https://user-images.githubusercontent.com/17728506/110015490-e839d980-7cf1-11eb-9fa2-3e98d007d8cc.png)

Wi-Fi worked initially, but then stopped working. I turned it off, and I'm unable to turn it on from System Preferences or the Menu Bar icon. I sometimes see something about localization in the place of the text on the Wi-Fi pan.

**Comment by gregj66** [comment]
@Stellarspace There is a slight difference in our WiFi info:
I have IO80211 Family:	12.0 (1200.12.2) vs yours IO80211 Family: 12.0 (1200.12.2b1)

**Comment by St-Eve-Larr** [comment]
@gregj66 I tried it again and it still doesn't fix the WIFI.   I'm doing all the steps...  but wifi just doesn't work for my 27 or 21.5 2012s.

**Comment by BenSova** [comment]
Is this from a clean install or are you restoring your data each time?

**Comment by St-Eve-Larr** [comment]
@BenSova I don't restore my date, I just prepare a new install package and run it each time.   I'm preparing 11.3beta 2 now and will run it shortly.   Once I get a winner, I'll run it on my other (main) 2012. 

The only error that I consistently get is this one: 
![image](https://user-images.githubusercontent.com/36957564/110192022-b7dd6280-7df9-11eb-86d7-e2ac6fd579d6.png)

**Comment by BenSova** [comment]
What if you completely wipe your Mac with disk utility while booted into the Big Sur installer USB then install macOS on to that.

Also, the beta 2 package doesn't work, beta 3 does though.

**Comment by St-Eve-Larr** [comment]
Wipe data partition too?

**Comment by BenSova** [comment]
Do this, but actually click erase (mine is disabled because I am booted into full macOS, you'd have to do it while booted into the macOS installer USB)

https://user-images.githubusercontent.com/65474198/110194883-2c170680-7df8-11eb-98e9-d80cf33e7bf8.mov

**Comment by St-Eve-Larr** [comment]
@BenSova  Good news!  11.3beta 3 from "scratch" did the trick.   Thanks again.  After I restored my data partition, I had to run the patch kext again to get wifi to work again.  Thank YOU!!!

**Comment by BenSova** [comment]
Awesome! Mind if I close this issue since it probably was just a corruption in the kext cache or something like that?

**Comment by St-Eve-Larr** [comment]
Don't mind at all.  Just a note that every iteration of the install(over existing data), including from Catalina to BigSur worked on my 2011 27"but not on my 2012.    
Thanks again.  @BenSova and others that reported back.   
I've really got "back in the saddle" with Macs since first my SE/30 in 1992...   a few generations ago it seems.

**Comment by jeromenaidu** [comment]
> @BenSova  Good news!  11.3beta 3 from "scratch" did the trick.   Thanks again.  After I restored my data partition, I had to run the patch kext again to get wifi to work again.  Thank YOU!!!  

Hello,

Would you please share the steps used or weblink we can see what was done on this fix?

Faithfully,
Jerome
