### ISSUE TITLE
Install error 1x252

### ISSUE THREAD

**Issue by DougMiner** [BenSova/Patched-Sur#229]
I get this error trying to update from Big Sur 11.01 to 11.1 I get this error while trying to install on zip drive. Previous install from Catalina went well.

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

**Comment by BenSova** [comment]
This is a duplicate issue of #154.

**Comment by DougMiner** [comment]
Can someone plese post a step by step resolution to this? Ive tied the suggestions so far, but keep getting messages that it may lock me out if I continue. Thanks. Or, is it just not possible to update to 11.1 from 1.01 yet?

**Comment by BenSova** [comment]
It is possible still, this is just a bug that some people have. If I can figure out how to stop spotlight indexing for the drive, this bug will be gone. (In other words, it's Apple's fault)

**Comment by DougMiner** [comment]
Would disabling Spotlight altogether temporarily work?

**Comment by BenSova** [comment]
Yeah

**Comment by DougMiner** [comment]
Thanks. Your work is much appreciated. I’ll give it a try.

“Imagination is more important than knowledge." Albert Einstein

**Comment by leboi** [comment]
Has it worked? How did you do it? Thanks in advance!
