### ISSUE TITLE
Buttons now shown correctly

### ISSUE THREAD

**Issue by ccabaleiro** [BenSova/Patched-Sur#23]
Hi!

See attached screenshots: the Patched-Sur buttons are not shown correctly.

![Screen Shot 2020-11-13 at 09 55 22](https://user-images.githubusercontent.com/74385657/99074498-9cbebc80-2596-11eb-815c-9c16bad0da25.png)
![Screen Shot 2020-11-13 at 09 55 04](https://user-images.githubusercontent.com/74385657/99074506-9fb9ad00-2596-11eb-9149-19d2a901a7ef.png)

**Comment by BenSova** [comment]
What version of Catalina are you running? For the most part, it's not something I have control over (the UI is generated by the system, I just tell it what I want), maybe somethings glitched with an older version.

**Comment by andreyoit** [comment]
Hello, same here, I'm using Catalina 10.15.1 Beta, since I'm stuck here by a beta bug that doesn't show updates.

**Comment by BenSova** [comment]
This is an Apple bug and nothing that I can do about it. Catalina v10.15.7 is the latest version of Catalina, therefore the one that you should be on. If you can't update, create a Catalina installer USB and use that to reinstall macOS.
