### ISSUE TITLE
Can't see buttons on Patch-Sur

### ISSUE THREAD

**Issue by davidwaze** [BenSova/Patched-Sur#232]
Hello,

Really strange the interface (v0.0.4) is launching like this.
I was able to continue until usb key selection but i'm blocked as i'm not able to see or select something.
Can you help me ?

Thanks

![Capture d’écran 2021-01-30 à 13 28 15](https://user-images.githubusercontent.com/26407047/106356322-185f1880-62ff-11eb-8d1b-d3b433938a94.png)

**Comment by davidwaze** [comment]
![Capture d’écran 2021-01-30 à 13 30 47](https://user-images.githubusercontent.com/26407047/106356363-6247fe80-62ff-11eb-8c89-98ab2fd9c609.png)

**Comment by BenSova** [comment]
You are on a buggy version of Catalina that I don't support. Just upgrade to the latest version of Catalina (10.15.7) then you can use the app.
