### ISSUE TITLE
Error 1x1 "Error: -69877

### ISSUE THREAD

**Issue by kxxc** [BenSova/Patched-Sur#24]
Error 1x1
Message: "Error: -69877: Couldn't open device"
"Started erase on disk1
Unmounting disk"

and is Mac mini 2012 late working?

thank you!

**Comment by BenSova** [comment]
disk1? What disk were you selecting? Your Mac's drive or an external usb? It should work perfectly fine on the Mac Mini 2012.

**Comment by kxxc** [comment]
> disk1? What disk were you selecting? Your Mac's drive or an external usb? It should work perfectly fine on the Mac Mini 2012.

thank you for replied so quickly,
I tried two USBs, ended up the same error.

**Comment by kaladark** [comment]
Hi, first of all thx for your work, i've the same issue in a mac mini late 2012
Error 1x1
Message: "Error: -69877: Couldn't open device"
"Started erase on disk1
Unmounting disk"

I selected a USB driv, disk12 but the installer sid disk1 and the errore above 👍

**Comment by BenSova** [comment]
Oh! Thank you for that information about it being disk12! That helps a lot. The parser that gets these drive numbers only accounts for the first digit, which in this case is 1, when it should also check to see if there's a second one. It got it now.

**Comment by kaladark** [comment]
Thank you ;) I've a lot of external usb disks, sorry :( I used my secondary internal disk and works ;)

**Comment by kxxc** [comment]
should I wait til the next version? thanks

**Comment by BenSova** [comment]
Okay, thanks for the info, I just committed a change to the source code that should fix this in v0.0.4!

**Comment by Tockman** [comment]
By the way, this one might be a reason for [another 1x1 error](https://github.com/BenSova/Patched-Sur/issues/39), cause in my case USB drive is disk10s1.

**Comment by iTanaus** [comment]
Hi, same error with my iMac 2013
![Schermata 2020-11-18 alle 15 06 24](https://user-images.githubusercontent.com/74664264/99539222-a2613b80-29b6-11eb-9df5-7ae2d4a24b3c.jpg)

**Comment by iTanaus** [comment]
I did it, i have finally prepared the USB stick, i rebooted and i chose the yellow EFi partition but instead of restarting, my iMac just shut down.

**Comment by bas1123** [comment]
Just boot it back up, press and hold option , and then pick “install MacOS Big Sur”. It should work.

**Comment by Tockman** [comment]
So didn't you read? :) "Then, your Mac will quickly turn off, so turn it back on while, again, holding down Option/Alt. Then, select Install macOS Big Sur Beta".

**Comment by iTanaus** [comment]
> Just boot it back up, press and hold option , and then pick “install MacOS Big Sur”. It should work.
> […](#)

Thank you so much, very kind! It worked.
I was thinking my iMac had to restart instead of shutting down.

**Comment by BenSova** [comment]
This should be fixed! Can somebody confirm that?

**Comment by BenSova** [comment]
I'm going to go with yes and close this issue. Comment if this is still going on.
