### ISSUE TITLE
erasing disk 0.....10...... failed macOS big sur 11.2

### ISSUE THREAD

**Issue by JonaathanGlezzz** [BenSova/Patched-Sur#251]
**Describe the bug**
![Captura de pantalla 2021-02-03 a las 16 23 46](https://user-images.githubusercontent.com/77159439/106776725-3f3d8780-663c-11eb-9fbf-66b97ac0404c.png)

is a MacBook Pro mid 2012

**Comment by BenSova** [comment]
This is a duplicate issue of #154

**Comment by JonaathanGlezzz** [comment]
> This is a duplicate issue of #154

ohh sorry
