### ISSUE TITLE
BenSova why is happening this type of error a friend of mine after installing macOS Big Sur 11.0.1 he try to install 11.2 doing the same procedure but he gets this errors when starts creating the media files to the usb , see pictures

### ISSUE THREAD

**Issue by ozziepadilla** [BenSova/Patched-Sur#259]
BenSova why is happening this type of error a friend of mine after installing macOS Big Sur 11.0.1 he try to install 11.2 doing the same procedure but he gets this errors when starts creating the media files to the usb , see pictures 
![14A20B73-93BC-437F-B0A0-2CB8F6C02ABB](https://user-images.githubusercontent.com/78187370/107025497-867c6300-6777-11eb-94ff-28cb1b9fb1f2.jpeg)
![B821071E-980E-41F9-ABA3-473AC27E64F1](https://user-images.githubusercontent.com/78187370/107025500-8714f980-6777-11eb-9c46-bacbf50761dd.jpeg)

_Originally posted by @ozziepadilla in https://github.com/BenSova/Patched-Sur/discussions/258_

**Comment by BenSova** [comment]
This is already tracked in other issues. Just search Erasing in the issues and you'll find it fast. I'm going to close this duplicate issue.
