### ISSUE TITLE
Error 250

### ISSUE THREAD

**Issue by Variatlol** [BenSova/Patched-Sur#26]
First of all, thx for your work.
Im using the patcher on a Macbook Air 2012.
Im using the install PKG you linked in another topic, but at finish it displays a red error msg 250 

"extract Base System to path/Volumes/Install macOS BigSur/BaseSystem ... of the disk failed

**Comment by BenSova** [comment]
Can you try again with v0.0.4? Don't use the custom package. Use the default one that Patched Sur finds.
