### ISSUE TITLE
V0.0.4 Error 1x252 during USB creation phase.

### ISSUE THREAD

**Issue by leigcker** [BenSova/Patched-Sur#266]
During the USB creation phase (app version 0.0.4) I get the following error:

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

I have tried erasing the the USB and trying again and know the USB Drive is good as now using it for something else. This was done on my mid 2012 15" MacBook Pro. I had the initial release of Big Sur installed and was attempting to jump to 11.2, 

I had previously used Barry KN's Micropatcher to get Big Sur on in the first place. From what I have seen of Patched-Sur so far the idea is brilliant and its much easier to use, looks pretty too. For now its no big deal to me as I used the Micropatcher method again to get around the problem. 

Good luck with the development of this very useful tool.

**Comment by BenSova** [comment]
This is a duplicate issue of #154. Please guys, there's a search bar in the issue list for a reason.
