### ISSUE TITLE
11.2.1

### ISSUE THREAD

**Issue by 1984AK** [BenSova/Patched-Sur#270]
After passwort :  for update 11.2.1 come this.

**Describe th
![pic](https://user-images.githubusercontent.com/74621151/107553211-c9559500-6bd4-11eb-9d5b-819c67d9e7c1.png)
e bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![pic](https://user-images.githubusercontent.com/74621151/107553182-bcd13c80-6bd4-11eb-9491-8cfb62795803.png)

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
You can't update to 11.2.1 as of right now, so you weren't paying attention.
