### ISSUE TITLE
Patched Sur 0.0.5

### ISSUE THREAD

**Issue by Petwannar** [BenSova/Patched-Sur#272]
Just dowloaded the new disk image from your site.

I open the image and the disk image mounts on the desktop.

After double clicking Patched Sur application I get a menu with there options open/show disk image/cancel (the wording might be a little different as my operating system language is French.

If I press OPEN, I get an error message with a long explanation starting with the title "Patched Sur DMG Not Detected".

As the disk image is on my desktop and the only Patched Sur application is on this disk image, I think there is a problem.

Any idea ? Many thanks for your great product.

Pierre

Operating Big Sur 11.1 on a iMac late 2012 patched with Patched Sur 0.0.4

**Comment by ososx** [comment]
Having the same problem too.

**Comment by Lut99** [comment]
For me, the v0.0.5 patcher opened and patched exactly once - however, my USB seemed faulty, and when I tried again this issue popped up, and has been preventing me from running the patcher ever since. I even wiped my installation and tried it on a clean & updated installation of Catalina, but it still occurs.

**Comment by prguy1985** [comment]
Having same issue. I have a macbook air 11in mid 2012. It is running a Big Sur Beta release prior to the official 11.0 drop.

**Comment by BenSova** [comment]
v0.0.4 doesn't even have this feature. It was supposed to prevent people from complaining they ran into an error because they didn't read the instructions. I'll look into the code and see what went wrong, but this is not something I expect to be able to reproduce.

**Comment by BenSova** [comment]
I just talked with someone on Discord and figured it out. The next release will fix this, it will probably be soon.

**Comment by Petwannar** [comment]
Thanks for looking at this issue...looking forward for the next update.
Kind regards from Switzerland.

**Comment by BenSova** [comment]
I released it! https://github.com/BenSova/Patched-Sur/releases/tag/v0.0.6

You should only get the popup if you actually didn't read the instructions.

**Comment by Lut99** [comment]
Awesome, thanks! It opens on my mac now :)
