### ISSUE TITLE
Error 1x252 Error erasing disk error number (-69888, 0)

### ISSUE THREAD

**Issue by TW462** [BenSova/Patched-Sur#276]
**Describe the bug**
When I get to the "Create Install Media" window if fails with the error before it completes loading/installing the files on the USB stick.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/77515829/107722920-e3ef4300-6c94-11eb-90c7-256a90788dbf.png)
.

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.1
- Upgrading to: Big SUr 11.2
 - Mac Model: [e.g. 15" Mid 2012 MacBook Pro]
 - Version 0.0.5

**Additional context**
Had this or a similar problem before when I first used Patched-Sur using v 0.0.4 on first install.

On the first go around, someone mentioned changing format of the USB stick to other than Mac OS Extended (Journeled). I used ExFat, and it went all the way thru, installed Mac OS Big Sur and was happy. This go around no such luck with either.

If there are any red boxes, click on them to copy the logs.
Error 1x252
Message: "Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk."
Output: ""

**Comment by progamer562** [comment]
i get the same too

**Comment by BenSova** [comment]
This is a duplicate issue of #154.

**Comment by BenSova** [comment]
I made a commit (a321b3b), that should fix this. Anyone want to try out a build that shouldn't run into this error?

Of course you do! [Patched Sur.app.zip](https://github.com/BenSova/Patched-Sur/files/5969858/Patched.Sur.app.zip) **REMEMBER** This version will require you to right-click then press open since I did not sign it and it also still requires the Patched Sur dmg to be mounted since it has some required files on there.

**Comment by JJFUENTES22** [comment]
Basically having the same issue, I believe my issue has to also being related that Filevault is on and cant be turned off when I am trying to add the patch to my usb. Pretty much stuck.

**Comment by BenSova** [comment]
Just completely turn off spotlight indexing, then it should work.

**Comment by ZoneMR** [comment]
No luck with the version above or 0.0.6. After countless unsuccessful attempts, I tried disabling spotlight - and that did the trick:

```
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
```

**Comment by BenSova** [comment]
My latest demo build in #154 does exactly that!
