### ISSUE TITLE
Error 1x252 

### ISSUE THREAD

**Issue by maurotowers1** [BenSova/Patched-Sur#28]
Password: Erasing disk:0%....10%....
Error erasing disk error number (-69888,0)
An error occurred erasing the disk

**Comment by maurotowers1** [comment]
This ocurrs when i create the pendrive

**Comment by spprichard** [comment]
I am getting this issue as well. I have some additional text in my error message 
```
Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.
```
**USB Drive**: SanDisk Crizer Blade 16GB

**Steps:**
- Erase USB drive via disk utility, Format: MacOS Extended (Journaled), Scheme GUID Partition Map
- Start Patcher, it downloads packages and what not
- Select USB Drive in Patcher UI
- Select Update Option in Patcher UI
- Fails at create media step'

![image](https://user-images.githubusercontent.com/10872240/100545120-ed354b80-321f-11eb-8e95-0a3905ffd3e5.png)

**Comment by ninjasef** [comment]
I get the same error, even after I use something else to repartition and reformat the drive...

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

**Comment by schmutzige-dame** [comment]
Anscheinend wird von BenSova nicht auf den Fehler eingegangen. Habe nun den gleichen Fehler unter einem iMac 2015 mit BiGSur erhalten unter der Beta.0.0.4. 
____________________________
Google translator

Apparently, BenSova does not address the error. I have now received the same error under an iMac 2015 with BiGSur under Beta.0.0.4.

**Comment by BenSova** [comment]
@schmutzige-dame Stop. Now. I'm a person WITH A LIFE. I do not have to reply to an error to see it. My guess, is something like a `sync` before running createinstallmedia might help. I'll look into it.

**Comment by schmutzige-dame** [comment]
Danke Ben. Sorry

**Comment by schmutzige-dame** [comment]
Lieber Ben, 

der Fehler taucht weiterhin auf. Unter BiGSur ist es mit dem Pacht zur Zeit nicht möglich einen gepatchten USB-Stick mit BiGSur zu erstellen. Nicht unter einem iMac 2013 oder 2015. Habe beides getestet. Unter Catalina auf einem iMac 2013 hingegen schon. Da lässt sich eine gepatchter USB-Stick mit BiGSur erstellen. 

Guten Abend

**Comment by BenSova** [comment]
Closing in support of #154
