### ISSUE TITLE
Enable Graphics Switching Error

### ISSUE THREAD

**Issue by tiramipseudonym** [BenSova/Patched-Sur#280]
After entering my password to Enable Graphics Switching, I get the following error message:

Error 1x3
Message: "Password:"
Output: ""

A couple of notes in case this matters: 
- In the past I had used terminal to disable displaypolicyd but have since started the process again.
- Up to this point, I have been using gSwitch to control my graphics switching manually. I disabled it's run on startup and restarted and still encounter this issue.

Thanks so much for all your work!

**Comment by BenSova** [comment]
Oh, I know what went wrong. Just tested it in Terminal, and I think I know an easy fix.

**Comment by BenSova** [comment]
`sudo launchctl disable system/com.apple.displaypolicyd` will disable it for now if the button doesn't work in Patched Sur.

**Comment by BenSova** [comment]
Never mind, it should work now with v0.0.6a

**Comment by tiramipseudonym** [comment]
Confirmed!

Both the terminal command and the new app version worked. Thank you.
