### ISSUE TITLE
Patched Sur failing during "Creating install media"

### ISSUE THREAD

**Issue by aniceberg** [BenSova/Patched-Sur#284]
**Describe the bug**
Error 1x1
Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"
Output: ""

**To Reproduce**
1. Using Patched Sur v.0.0.6a to create Install Media to do an update
2. Click on "Create Install Media"
3. See error

**Expected behavior**
The app should create the macOS v11.2 install media without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/646958/107893388-ebaf2180-6ef8-11eb-9f88-edf90318a270.png)

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.0.1
- Upgrading to: Big Sur v11.2 public release
 - Mac Model: iMac (21.5-inch, Late 2013)
 - Version v0.0.6 (46)

**Additional context**
The Patched-Sur v0.0.6 (46) aka v0.0.6a that I am attempting to use has "Patched Sur - For Catalina" as the app title as seen in the macOS title bar:
![Screen Shot 2021-02-14 at 7 18 31 PM](https://user-images.githubusercontent.com/646958/107893482-77c14900-6ef9-11eb-877a-4fec981f8576.png)
 
If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
![Screen Shot 2021-02-14 at 5 39 30 PM](https://user-images.githubusercontent.com/65474198/107894058-9d475600-6eeb-11eb-8de1-ce5360afd527.png)
When there's a warning popup, you don't ignore it.
