### ISSUE TITLE
Memory available check

### ISSUE THREAD

**Issue by Stefan-CPlanet** [BenSova/Patched-Sur#288]
Hello, I just installed Big Sur but I had a major issue with installation.

MacBook Pro 2012 retina 15"
Version used 0.0.6

I didn't have enough space on SSD installation started, overwrote Catalina however it wouldn't boot as it would fail mid-way while loading. Recovery is not helpful either as it doesn't let you use a terminal or disk utility.

I managed to fix the issue as I had 2 APFS containers ( 1 with System, 1 with some movies) by booting internet recovery and with disk utility removing 2nd container.
I would suggest a check on free memory or at least a notice make sure to have at least XXXGB of space free.

Besides that great job, it worked like a charm :)

**Comment by BenSova** [comment]
That's what Apple's installer already does. If it failed because you don't have enough space, well that's Apple's fault.
