### ISSUE TITLE
Can't install macOS Bis Sur Patchter

### ISSUE THREAD

**Issue by MacIsTheBest** [BenSova/Patched-Sur#291]
Hey Guys,
I have a MacBook Pro 2021 Unibody with Catalina and I like to upgrade to macOS Big Sur.
To create a USB Drive etc. works perfect fine. But when I Restart the Mac and click on "Install macOS Big Sur" I get an rrror that the upgrade is not possible because an error.

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.2]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.6]

**Comment by MacIsTheBest** [comment]
![image](https://user-images.githubusercontent.com/74244852/107978380-f29f6800-6fbc-11eb-883c-e31fd2547d1e.jpg)
 English Tanslation: An error occurred while loading the update

**Comment by ozziepadilla** [comment]
When your usb get finished you reboot your Mac then holding the the option key you Hit the EFI BOOT? if not do it again

**Comment by MacIsTheBest** [comment]
Yes! It worked. Thank you so much! I love it!
