### ISSUE TITLE
MacBook Pro Mid-2012. Personal Hotspot doesn't work unless you cut bluetooth off.

### ISSUE THREAD

**Issue by JumpStumpsMTB777** [BenSova/Patched-Sur#295]
It appears to be a known issue that Personal Hotpot doesn't work on the 2012 Macbook pro, however it does work when you cut bluetooth off. I am new to this. I hope this helps. If there is anything else I can do I would love to help.

**Comment by BenSova** [comment]
Yeah, just say that in the other issue. Since this could be apart of the other personal hotspot issue, and you didn't need to make a new issue for this, I'm going to close this.

**Comment by JumpStumpsMTB777** [comment]
Thanks! My policies for putting in the wrong place.

Chad Ledford
