### ISSUE TITLE
Error 1x250

### ISSUE THREAD

**Issue by Rn1767** [BenSova/Patched-Sur#30]
The following message occurred after I finished copying the installer onto my USB:

Error 1x250 Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100% 2020-11-14 14:44:09.901 createinstallmedia[1185:25331] There was an error parsing the Info.plist for the bundle at URL <0x7f98b2e38710>: NSCocoaErrorDomain - 3840 Couldn't mount dmg /Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed." "Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100% Making disk bootable... Couldn't find InstallInfo.plist"

**Comment by Variatlol** [comment]
I have the same error on my Macbook air 2012

**Comment by cineva78** [comment]
Kind of the same error on my iMac 27" (Late 2013). I'm using the InstallAssistant.pkg you've provided on reddit and the Patched Sur - for Catalina 0.0.3 (13).


Error 1x250
Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100%
Couldn't mount dmg /Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
"Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

**Comment by Rn1767** [comment]
Oh I should also mention that I'm trying to install macOS Big Sur on my iMac (21.5-inch, Late 2013).

**Comment by ErickSamuelGomes** [comment]
I have the same issue on MBP 2012

**Comment by BenSova** [comment]
Try again with the latest version of macOS and the latest version of Patched Sur. Looks like a mess up on Apple's side.

**Comment by cineva78** [comment]
> Try again with the latest version of macOS and the latest version of Patched Sur. Looks like a mess up on Apple's side.

I've managed to install Big Sur 11.0.1 a few months ago, but now I don't know how to update it. :)

**Comment by BenSova** [comment]
https://bensova.gitbook.io/big-sur/postinstall-after-upgrade/updating-macos

Everything you need to know ^

**Comment by cineva78** [comment]
Thank you very much! Already in progress.

> https://bensova.gitbook.io/big-sur/postinstall-after-upgrade/updating-macos
> 
> Everything you need to know ^

**Comment by Rn1767** [comment]
It finally managed to update with the new version on Patched Sur! Although I did use a different USB this time which could have been the problem. Nevertheless, thank you for your help.

**Comment by BenSova** [comment]
Awesome, since no one has reported this bug in a while I will close this issue. Enjoy Big Sur!
