### ISSUE TITLE
Can not Download macOS 11.2.1

### ISSUE THREAD

**Issue by MacIsTheBest** [BenSova/Patched-Sur#302]
**Describe the bug**
Hello, Today Apple released macOS 11.2.1. So, I would like to update, but....  Fail.
I started Patched Sur on my patched machine, click Continue, and when I download macOS 11.2.1 the progress bar goes to 100% immediately, and it don't download macOS.

**To Reproduce**
1. Go to 'Patched Sur'
2. Click on '.Download macOS 11.2.1'
4. See progress bar

**Screenshots**
![Bildschirmfoto 2021-02-17 um 15 51 39](https://user-images.githubusercontent.com/74244852/108248079-b9e5c700-7153-11eb-9dea-3b85216bc88d.png)

**Desktop (please complete the following information):**
- Upgrading from: [macOS 11.2]
- Upgrading to: [Big Sur 11.2.1]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [v0.0.7 Beta]

**Comment by BenSova** [comment]
Just give it a while, I already know I broke the progress bar so this isn't much of an issue.

**Comment by MacIsTheBest** [comment]
Ok. Thanks.
