### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by alfacruxis** [BenSova/Patched-Sur#303]
While creating the installer USB for Big Sur 11.2.1, at the end of "Copying Installer" process, the following error message appears:

_**Error 1x1
Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"
Output: ""**_

I’m using Patched Sur v0.0.7 (49) over an iMac 21" late 2012 with macOS 11.2 (also installed using Patched Sur).

Please help. 
Thanks!

**Comment by BenSova** [comment]
This is not a bug, but rather you either ignored a popup or you downloaded the wrong DMG first and never unmounted it.
