### ISSUE TITLE
an error occurred while applying the software update

### ISSUE THREAD

**Issue by scrcrivera** [BenSova/Patched-Sur#304]
**Describe the bug**
an error occurred while applying the software update, when installing big sur on a macbook pro 13 "from mid 2012

**To Reproduce**
When you try to install the update you get this error, I try to reinstall and in recovery mode my password doesn't work

**Expected behavior**
That the application will be installed to continue with the next steps

**Screenshots**
![image](https://user-images.githubusercontent.com/79241063/108306412-0fcd6580-717a-11eb-8b1b-cc85c8d74d7d.png)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.2
 - Mac Model: 13" mid 2012 MacBook Pro
 - Version v0.0.4

**Additional context**
The cmd + r key combination does not work for me

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
> Version v0.0.4
Yeah, no, use the latest version of the patcher.
