### ISSUE TITLE
Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

### ISSUE THREAD

**Issue by mcplayerteam** [BenSova/Patched-Sur#305]
**Describe the bug**
Unable to create install media
Error 1x1 Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found "Output: ""

**To Reproduce**
1. Own a MacBook Pro 15-inch Early-2013 (i7 2.7GHz, GT 650M 1GB) [MacBook10,1]
2. Use Patched Sur 0.0.4 beta to upgrade from Catalina to Big Sur 11.0.1
3. Use Patched Sur 0.0.7 beta to upgrade form Big Sur 11.0.1 to 11.2.1
4. At stage "create install media", after an hour of copying installer to USB, see error: "Error 1x1 Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found "Output: """

**Expected behavior**
It should go through and the installer should be copied.

**Screenshots**
<img width="500" alt="Screen Shot 2021-02-18 at 00 51 18" src="https://user-images.githubusercontent.com/23158434/108311696-71460200-7183-11eb-985e-4266e8856ddf.png">

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.0.1
- Upgrading to: Big Sur 11.2.1 (Release)
 - Mac Model: MacBook Pro 15-inch Early-2013 (i7 2.7GHz, GT 650M 1GB) [MacBook10,1]
 - Version: 0.0.7 beta

**Comment by mcplayerteam** [comment]
Doing it a few more times fixes it, just slightly inconsistent.
Btw my MacBook is also misidentified as MacBook Pro Mid-2012 possibly due to having same model number.

**Comment by BenSova** [comment]
![Screen Shot 2021-02-18 at 7 46 25 AM](https://user-images.githubusercontent.com/65474198/108373692-68722200-71bd-11eb-84db-61a8c879f66e.png)
Remember this popup (or the Catalina-styled version of this popup)? This is not an issue, but rather a user error.

**Comment by mcplayerteam** [comment]
> ![Screen Shot 2021-02-18 at 7 46 25 AM](https://user-images.githubusercontent.com/65474198/108373692-68722200-71bd-11eb-84db-61a8c879f66e.png)
> Remember this popup (or the Catalina-styled version of this popup)? This is not an issue, but rather a user error.

ok got it, thanks!
