### ISSUE TITLE
Stuck in the password 4ever

### ISSUE THREAD

**Issue by luizaleixo** [BenSova/Patched-Sur#308]
**Describe the bug**
When I reach the point to enter the password at "Download Install Assistant Package". As I do so it keeps asking me for the password, never going further.

**To Reproduce**

**Expected behavior**
I would expect it to start downloading the install assistant package 🤷‍♂️

**Screenshots**
[https://www.dropbox.com/s/6w7u8d81tccehtz/Screen%20Shot%202021-02-18%20at%2008.53.38.png?dl=0](url)

**Desktop (please complete the following information):**
 - Upgrading from:  Catalina v10.15.7
- Upgrading to: Big Sur v11.2.1
 - Mac Model: 13" 2012 MacBook Pro Mid 2012
 - Version v0.0.7

**Comment by cesare-a4b** [comment]
I had the same issue, my password contains dollar symbol ($), once I change it with one more simple it performed the installation

**Comment by luizaleixo** [comment]
> I had the same issue, my password contains dollar symbol ($), once I change it with one more simple it performed the installation

Spot on! mine had an (&) ... and now the installation proceeded! Thanks a lot!

**Comment by BenSova** [comment]
Yeah, there's already an issue open for this, so I'll close it to keep down clutter.
