### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by progamer562** [BenSova/Patched-Sur#310]
**Describe the bug**
i cant download 11.2.1
**To Reproduce**
do the setup to the download page 
 See error bar goes 100% full not doing anything

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [big sur 11.1]
- Upgrading to: [big sur 11.2.1]
 - Mac Model: [MacBook Pro (13-inch, Mid 2012]
 - Version [v0.0.7 i guess]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
It's a known bug that I entirely blame on Apple because their servers are returning three sizes for a single file. I cannot block this, and it is not a patcher bug.

**Comment by progamer562** [comment]
can i download it manually instead the app

**Comment by BenSova** [comment]
https://github.com/BenSova/Patched-Sur#how-do-i-choose-a-my-own-installer
