### ISSUE TITLE
Can't boot to Patched Sur anymore

### ISSUE THREAD

**Issue by anaszulkifli** [BenSova/Patched-Sur#316]
**Describe the bug**
When I boot by pressing alt and chose Patched Sur, mac gives out slash symbol and then shut down like this:
https://support.apple.com/en-us/HT210901#:~:text=A%20prohibitory%20symbol%2C%20which%20looks,until%20your%20Mac%20turns%20off.

I believe I used v.05 to create the installation* and v0.006a patch post installation to get the WiFi. I even got the Migration Assistant working from my iMac to this patched sur. I even created bootcamp partition. Ready. Now, my recovery mode can only reinstall Catalina. Partition Aid, SMC and NVRAM reset still won't solve the issue.

Please help as this may happen to more devices

**To Reproduce**
1. Install Patched Sur, Patched for WiFi, Migration Assistant and Bootcamp Partition

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. See Apple link above.

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1]
 - Mac Model: [13" 2012 MacBook Pro]
 - Version [v0.0.5 install, 0.0.06a post installation patch, it was during that days when you guys had a lot of releases]

**Comment by BenSova** [comment]
# Boot into the EFI Boot on the installer USB

If you ever have a problem, do that first.

**Comment by anaszulkifli** [comment]
Thank you! I recreated the USB installer on my iMac with 0.0.7 since I have reformatted it for Bootcamp. I entered EFI Boot, system shut down. Now booted back into the macOS. Any reasons/things I need to be aware of so that it wont trigger that event again?

**Comment by ozziepadilla** [comment]
After rebooting from EFI boot you must turn on manually holding down option key then selecting install macOS Big Sur and let it go until finish

**Comment by BenSova** [comment]
Try not to reset the NVRAM/PRAM, and you should be good.
