### ISSUE TITLE
Startup Disk

### ISSUE THREAD

**Issue by mrbuttons1** [BenSova/Patched-Sur#318]
Unable to reboot into bootcamp drive from startup disk menu. Error is produced when selecting bootcamp drive as start up disk and clicking restart:

"An error occurred while setting “BOOTCAMP” as the startup disk: The operation couldn’t be completed. (SDErrorDomain error 104.)"

![Screen Shot 2021-02-20 at 5 18 00 PM](https://user-images.githubusercontent.com/79383005/108609944-9e6efc00-739f-11eb-8856-382e01e5d790.png)

**Desktop (please complete the following information):**
 - Mac Model: Mid 2012 Macbook Pro
 - Version: Big Sur 11.1

**Comment by BenSova** [comment]
This has nothing to do with the patcher. Just reboot and hold the option key when your Mac is turning on then select BOOTCAMP to boot into Windows.
