### ISSUE TITLE
Its still really buggy

### ISSUE THREAD

**Issue by HerbJul** [BenSova/Patched-Sur#320]
MacBook pro 9,2
OpenCore 6.6

Cant download or copy to USB-Stick ith app 

Error 1x250
Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100%
2021-02-21 23:36:23.572 createinstallmedia[4521:138308] There was an error parsing the Info.plist for the bundle at URL <0x7f8b2caae190>: NSCocoaErrorDomain - 3840
Couldn't mount dmg /Volumes/Install macOS Big Sur/macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
Output: "Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

**Comment by BenSova** [comment]
What happens if you try again with the latest patcher/macOS version?

**Comment by BenSova** [comment]
Closing due to a lack of a response from the opener.
