### ISSUE TITLE
Will not download the latest versio nof macos

### ISSUE THREAD

**Issue by Seanthebestintheworldnotreally** [BenSova/Patched-Sur#324]
When I go to download 11.2.21 it gets to that point and then the progress bar instantly goes to the end and nothing happens. 
**To Reproduce**
Steps to reproduce the behaviour (you spelled behaviour wrong bud):
Use normally and then use  release

**Expected behaviour**
To go slowly as the download progresses and then continue like it used to do. 

 - Upgrading from: [Big Sur 11.2]
- Upgrading to: [Big Sur v11.2.1]
13" 2012 MacBook Pro and Mac Pro 5,1 both do it 
 - Version [v0.0.7]

**Comment by ozziepadilla** [comment]
On that point you won’t see the progress bar let it go don’t close that window and have some of patience that’s all and don’t reboot your Mac 💻

**Comment by Seanthebestintheworldnotreally** [comment]
I tried that but it’s been sat here for 3 hours and I have fibre internet - I’m pretty sure it’s stick. I’ve tried disabling SIP, a different Mac entirely and using VPN just in case it is my internet and nothing has worked. It used to work just fine...

**Comment by ozziepadilla** [comment]
Disable your VPN and try it again

**Comment by Seanthebestintheworldnotreally** [comment]
I did that to start with beige I enabled it again and it did nothing.

**Comment by Seanthebestintheworldnotreally** [comment]
I’ve managed to sort it now, turns out my DNS was having fun! Sorry and thank you for your help!

**Comment by BenSova** [comment]
Apple managed to make a file with three sizes, so that's why the progress bar doesn't work.

**Comment by Seanthebestintheworldnotreally** [comment]
I see. Maybe it would be good to remove the animation that fills the bar blue from the UI to avoid confusion and leave the progress bar with no fill if that makes sense.
