### ISSUE TITLE
2 Issues - Can't open System preference (settings) - And kernel_task is going crazy !

### ISSUE THREAD

**Issue by parkbankpunk** [BenSova/Patched-Sur#326]
**Describe the bug**
I´m from germany -so I don't know the correct translations ... 

Systemsettings - when I click on the safety pref. (next to extensions) - the loading ball is rolling and rolling and rolling - but nothing happens ... :( 

And kernel_task is going crazy when i open a bigger program like photoshop or obs studio - there are some workarounds but I can't delete the kext - or any kext ... the workaround isn't working with a patched Mac. :( Is there a script or a app to delete a kext in Big Sur ?!? 

Please help :(

**Comment by parkbankpunk** [comment]
Hi. Perhaps a app or script to remove kext in big sur? Cause the patcher
the normal way is nt working :( (restore mode) regards

Ben Sova ***@***.***> schrieb am Mi., 24. März 2021, 15:30:

**Comment by BenSova** [comment]
Kexts are essential to Big Sur, removing the wrong one could ruin your installation, and without a native recovery mode that would cause you to lose all of your data. Whatever is going on with kernel task is up to Apple to fix, it happens on supported Macs too, so I can't give you anything that will fix it.
