### ISSUE TITLE
Plug in USB Installer and Try Again

### ISSUE THREAD

**Issue by Leviticye** [BenSova/Patched-Sur#33]
I installed Big Sur on a seperate partition with the USB Installer. After booting into Big Sur and trying to install the patch kexts, after pressing continue will alert me to "Plug in USB Installer and Try Again", when though the USB is plugged in. Is this because I installed Big Sur on a seperate partition?

**Comment by BenSova** [comment]
No that should not matter, but just to make sure, the usb drive was named Instal macOS Big Sur right?
