### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by iammalexander** [BenSova/Patched-Sur#335]
**Describe the bug**
We get the following error, once booting the USB - This copy of the InstallAssistant application is damged, and can't be used to install macos

**To Reproduce**
1. Launch usb
2. Click new install
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur current release]
 - Mac Model: [e.g. 27" iMac Late 2009]
 - Version [e.g. v0.0.7]

**Comment by ozziepadilla** [comment]
Alexander do you speak Spanish?

**Comment by iammalexander** [comment]
no sorry

**Comment by ozziepadilla** [comment]
It’s ok , follow the steps ,.. 
1- erase your usb with the commands correctly, jornaled extended and GUID map etc etc named as usb 
2- download patched-Sur.dmg ,,, just that file delete any other patched Sur downloaded you have 
3-find patched-Sur.dmg in your downloads folder double click to open 
4-right click over the screen of patched Sur , if security shows up , go to system preferences then security and click where says “open anyway “
5-follow all steps have patience until see the windiwd for select update no clean and where to copy the media files to the usb , if you see erasing let it go and if you see that the usb gone just wait it will appear again with different name Install macOS Big Sur this procedures require time and patience so wait until see FINISH
6-close all your apps that are open then turn off completely your Mac 💻 
7-turn your Mac on holding down OPTION until you see the few options in the middle of the screen, if mouse pointer doesn’t work use key arrows then select EFI boot then hit return or enter
8-turn on your Mac holding down the same option key then select Install macOS Big Sur and follow all steps 
9-wait for the recovery mode to display then select install macOS Big Sur and wait that will ask where to install select your hard drive then click install of just double click and let it until few reboots when the installation is complete

**Comment by ozziepadilla** [comment]
Don’t skip any steps or you will get issues

**Comment by ozziepadilla** [comment]
I have do this three times not issues or errors or crashes I am on macOS Big Sur 11.2.1

**Comment by BenSova** [comment]
99% of the time this mean you have a corrupt download, so just go through the process again.

**Comment by ozziepadilla** [comment]
I did my best benSova to explain this because guys on YouTube are making tutorials with your patched Sur but they skipped very important steps and procedures I have a discussion with one of those guys

**Comment by RL1967** [comment]
> It’s ok , follow the steps ,..
> 1- erase your usb with the commands correctly, jornaled extended and GUID map etc etc named as usb
> 2- download patched-Sur.dmg ,,, just that file delete any other patched Sur downloaded you have
> 3-find patched-Sur.dmg in your downloads folder double click to open
> 4-right click over the screen of patched Sur , if security shows up , go to system preferences then security and click where says “open anyway “
> 5-follow all steps have patience until see the window for select update no clean and where to copy the media files to the usb , if you see erasing let it go and if you see that the usb gone just wait it will appear again with different name Install macOS Big Sur this procedures require time and patience so wait until see FINISH
> 6-close all your apps that are open then turn off completely your Mac 💻
> 7-turn your Mac on holding down OPTION until you see the few options in the middle of the screen, if mouse pointer doesn’t work use key arrows then select EFI boot then hit return or enter your Mac will turn off itself
> 8-turn on your Mac holding down the same option key then select Install macOS Big Sur and follow all steps
> 9-wait for the recovery mode to display then select install macOS Big Sur and wait that will ask where to install select your hard drive then click install of just double click and let it until few reboots when the installation is complete

Hi Ozzie, i am experiencing the same issues once more in upgrading to 11.2.1 I tried disabling spotlight indexing..it did not work so i turned it back on. I re-downloaded the OS file...still same error. Re-started the computer and same issue. :-( dont know what else to try as I thought this error was already solved.

**Comment by ozziepadilla** [comment]
> > It’s ok , follow the steps ,..
> > 1- erase your usb with the commands correctly, jornaled extended and GUID map etc etc named as usb
> > 2- download patched-Sur.dmg ,,, just that file delete any other patched Sur downloaded you have
> > 3-find patched-Sur.dmg in your downloads folder double click to open
> > 4-right click over the screen of patched Sur , if security shows up , go to system preferences then security and click where says “open anyway “
> > 5-follow all steps have patience until see the window for select update no clean and where to copy the media files to the usb , if you see erasing let it go and if you see that the usb gone just wait it will appear again with different name Install macOS Big Sur this procedures require time and patience so wait until see FINISH
> > 6-close all your apps that are open then turn off completely your Mac 💻
> > 7-turn your Mac on holding down OPTION until you see the few options in the middle of the screen, if mouse pointer doesn’t work use key arrows then select EFI boot then hit return or enter your Mac will turn off itself
> > 8-turn on your Mac holding down the same option key then select Install macOS Big Sur and follow all steps
> > 9-wait for the recovery mode to display then select install macOS Big Sur and wait that will ask where to install select your hard drive then click install of just double click and let it until few reboots when the installation is complete
> 
> Hi Ozzie, i am experiencing the same issues once more in upgrading to 11.2.1 I tried disabling spotlight indexing..it did not work so i turned it back on. I re-downloaded the OS file...still same error. Re-started the computer and same issue. :-( dont know what else to try as I thought this error was already solved.

Did you read benSova suggestion? Keeps trying sometimes the downloads get corrupted, I meant I had a experience where I did download patched-Sur.dmg and I had another version already downloaded the new goes downloaded as patched-sur2.dmg and I get a error but deleting all downloads I did it again and bum 💥 it goes until the finish screen without issues , try that way

**Comment by ai-utt** [comment]
same issue here.. tried reinstalling and it didn’t work.

it keeps giving the same error after booting from the usb and clicking install macos.
the error: 
> “This copy of the InstallAssistant application is damged, and can't be used to install macos”


i tired installing older bigsur versions (beta and normal), older patcher versions, changing the usb stick, deleting the ( . ) hidden patcher files (its not necessary because it happens automatically but was trying anything) and they all gave the same error over and over.

so now i’m gonna try to copy the same bigsur installer pkg installed from ur patcher to a usb (without patching it) and see if it let me “install” when booting from the usb.
if it doesn’t work i’ll get the bigsur installer pkg from somewhere else and install it on a usb (not patching again), hoping that would work. 

now depending on which pkg works.. i’ll first try ur patcher latest version with the working bigsur pkg installer. if it doesn’t work i’ll try using mircopatcher by itself to see if the issue also occurs with micropatcher or not. i’ll update in a few.

**Comment by ai-utt** [comment]
> same issue here.. tried reinstalling and it didn’t work.
> 
> it keeps giving the same error after booting from the usb and clicking install macos.
> the error:
> 
> > “This copy of the InstallAssistant application is damged, and can't be used to install macos”
> 
> i tired installing older bigsur versions (beta and normal), older patcher versions, changing the usb stick, deleting the ( . ) hidden patcher files (its not necessary because it happens automatically but was trying anything) and they all gave the same error over and over.
> 
> .
> 
> so now i’m gonna try to copy the bigsur installer pkg installed from ur patcher to a usb (without patching it) then boot to it and see if it let me “install” it.
> if it doesn’t work i’ll get the bigsur installer pkg from somewhere else and install it on a usb (no patching again), hoping that would work.
> 
> now depending on which pkg works.. i’ll first try ur patcher latest version to patch the usb with the working bigsur pkg installer. if it doesn’t work i’ll try using mircopatcher by itself to see if the issue also occurs with micropatcher alone or not. i’ll update in a few.
> all of this assuming the issue is from the bigsur installer pkg.

update: the big sur installer pkg wasn’t the issue. the pkg from ur patcher works! it’s just something with the patcher that gives the error. 

i just downloaded the pkg from ur patcher and installed it, then normal make a bootable usb drive, and just used mircopatcher method to patch the usb. all worked!

**Comment by ozziepadilla** [comment]
There you go , you got it !

**Comment by smoothop3** [comment]
@ai-utt, I have this problem too. Can you explain exactly how you did those last steps in "i just downloaded the pkg from ur patcher and installed it, then normal make a bootable usb drive, and just used mircopatcher method to patch the usb. all worked!".

Thanks

**Comment by ai-utt** [comment]
> @ai-utt, I have this problem too. Can you explain exactly how you did those last steps in "i just downloaded the pkg from ur patcher and installed it, then normal make a bootable usb drive, and just used mircopatcher method to patch the usb. all worked!".
> 
> Thanks

basically just get a copy of macos big sur from anywhere u can get it (i used @BenSova patcher to download a copy of that) then use [mircopatcher](https://github.com/barrykn/big-sur-micropatcher#instructions-for-use) patcher and follow the steps there. 

if u don’t know how to download a copy from ben’s patcher here:

1-open ben’s patcher do the steps just to download the version of macos u want, no need to continue the other steps. 
2-when it’s done downloading go to users > (your user) > then u need to show hidden files (u can do it by clicking shift + command + dot). 
3-after that look for “.patched-sur” folder or similar name, open it. 
4-now u see a .pkg file which is the big sur installer, just double click and install it. 
5- now u have a copy of mac os big sur and u can just follow [mircopatcher](https://github.com/barrykn/big-sur-micropatcher#instructions-for-use) steps. 

i hope this was clear, if u need any more clarifying let me know. goodluck!

**Comment by smoothop3** [comment]
Thanks, that worked immediately!
