### ISSUE TITLE
Patched-Sur Creating Install Media Error

### ISSUE THREAD

**Issue by cotton113** [BenSova/Patched-Sur#338]
Error 1x1
Message: "Error: -69888: Couldn't unmount disk"
Output: "Started erase on disk5
Unmounting disk"

**Comment by ozziepadilla** [comment]
On my knowledge I think your usb isn’t right try with another usb if is posible a brand new sometimes the usb drives stops working I had one that doesn’t allow me to erase but I get a new one and voila it works perfectly

**Comment by guillaumedb64** [comment]
Hello
Same error here with USB hard drive or USB key

**Comment by cotton113** [comment]
Thanks very much for your advice, it was the USB stick, which was quite
new, so I was reluctant to believe that it had failed, but you were correct.

**Comment by ozziepadilla** [comment]
I told you it was that

**Comment by BenSova** [comment]
Seems to be a USB problem, and it's resolved anyway, so closing.
