### ISSUE TITLE
Can’t find post install app

### ISSUE THREAD

**Issue by jsegrue** [BenSova/Patched-Sur#34]
Thank you for making this patcher. Was very easy to use.

Just unable to find the post install app to patch WiFi and be able to carry out future updates.

**Comment by BenSova** [comment]
What method of install did you do? An update, clean install (wipe your entire drive), or fresh install (install on separate partition)?

**Comment by norek1234** [comment]
I found this app in my app folder or in launchpad
maybe the same on your's

![Screenshot 2020-11-15 at 00 24 08](https://user-images.githubusercontent.com/70437484/99158990-ef07f680-26d8-11eb-8e31-1013adef6171.png)

**Comment by Cyberdroid1** [comment]
> I found this app in my app folder or in launchpad
> maybe the same on your's
> 
> ![Screenshot 2020-11-15 at 00 24 08](https://user-images.githubusercontent.com/70437484/99158990-ef07f680-26d8-11eb-8e31-1013adef6171.png)

This is the post-install app.

**Comment by BenSova** [comment]
@jsegrue This seems like you did a clean install which is not supported as of right now like I stated inside the preinstall app. v0.0.4 adds the post install app to the usb and that can error easily, so technically this cannot be an issue anymore.
