### ISSUE TITLE
Patching USB... Forever

### ISSUE THREAD

**Issue by pierre-rs** [BenSova/Patched-Sur#35]
Hi, thanks for Patched-Sur!

I'm stuck in "Patching USB..." (stayed all nigh)... Is there anything different that I can try?

![Patching_USB_forever](https://user-images.githubusercontent.com/57575719/99148050-5a63b100-2664-11eb-900e-1b8630bf6486.png)
 
Running on macOS Catalina 10.15
MacBook Air (11-inch, Mid 2012)

**Comment by ccabaleiro** [comment]
Same here. It took 20 hours and did not finish.  Maybe a log of what is going on could help.

**Comment by pierre-rs** [comment]
I managed to install Big Sur by doing the following _(on MacBook Air (11-inch, Mid 2012) with macOS Catalina 10.15)_:

**1.** I took a look at what was explained on the [Github barrykn/big-sur-micropatcher page](https://github.com/barrykn/big-sur-micropatcher) in items **6** and **7**.

**2.** Even with the "Patched-Sur" window still stuck on "**Patching USB ...**" (it was like this for hours and hours)

**3.** In **Catalina's Finder**, I pressed "**Command + Shift +.**" (**show hidden files**).

**4.** In Catalina's Finder, on my Home directory, I opened the folder "**.patched-sur**" and "**big-sur-micropatcher**". Then, drag and drop the "**micropatcher.sh**" file to the **Terminal.app** window. Right after that, drag and drop my **USB stick** icon from my desktop to the **Terminal.app** window as well and hit **enter**.

**Example:**
`/Users/username/.patched-sur/big-sur-micropatcher/micropatcher.sh /Volumes/Install\ macOS\ Big\ Sur`

**5.** After completing the previous command, still in the same folder opened in the **Catalina's Finder**, drag and drop the file "**install-setvars.sh**" file to the **Terminal.app** window. Right after that, drag and drop my **USB stick icon** from my desktop to the **Terminal.app** window as well and hit **enter** (I believe it was necessary to enter my user password in this step).

**Example:**
`/Users/pierre/.patched-sur/big-sur-micropatcher/install-setvars.sh /Volumes/Install\ macOS\ Big\ Sur`

**6.** After the above commands I restarted the Mac and proceeded with the installation steps as mentioned on the [Github barrykn/big-sur-micropatcher page](https://github.com/barrykn/big-sur-micropatcher) in item **9** (the same as the one on the [BenSova/Patched-Sur page](https://github.com/BenSova/Patched-Sur) on item **10**). Thereafter the installation proceeded normally.

**7.** After Big Sur is installed, by opening the **USB stick icon** ("**Install macOS Big Sur**") in the **Big Sur's Finder**, drag and drop the file "**patch-kexts.sh**" in the **Terminal.app** window and hit enter (it will be necessary to enter the user password). After the command was finished I restarted the Mac. After the restart the Wifi was already working.

**Example:**
`/Volumes/Install\ macOS\ Big\ Sur/patch-kexts.sh`

**Comment by norek1234** [comment]
Did you tired with different USB with at least 16GB.
Try to manually format your stick before you will move to this step.

On my MacBook Pro mid 2012 with SSD and USB 2.0 stick it tooks below 1hr

**Comment by fabiotavares** [comment]
Same error here.
Mac Mini Late 2012 (i5 dual COre, SSD 240 Sandisk, 16 Gb Ram);

In the tip of pierre-rs, I am the next error with micropatcher.sh:

_```
BarryKN Big Sur Micropatcher v0.5.0
Thanks to jackluke, ASentientBot, highvoltage12v, testheit, and
ParrotGeek for their hard work to get Big Sur running on unsupported
Macs! (See the README for more information.)

Checking read access to necessary directories...
Access check succeeded.

Patching com.apple.Boot.plist...
cp: /Volumes/Install macOS Big Sur/Library/Preferences/SystemConfiguration/com.apple.Boot.plist: No such file or directory
cp failed. Probably a permissions error. This is not expected, but
patcher will attempt workaround by trying again as root.

Password:
BarryKN Big Sur Micropatcher v0.5.0
Thanks to jackluke, ASentientBot, highvoltage12v, testheit, and
ParrotGeek for their hard work to get Big Sur running on unsupported
Macs! (See the README for more information.)

Checking read access to necessary directories...
Access check succeeded.

Patching com.apple.Boot.plist...
cp: /Volumes/Install macOS Big Sur/Library/Preferences/SystemConfiguration/com.apple.Boot.plist: No such file or directory
cp failed, even as root. This is unexpected.
**Patcher cannot continue.**
```_

**Comment by BenSova** [comment]
Closing in support of #156
