### ISSUE TITLE
Panic/reboot launching game on patched iMac 12,2.

### ISSUE THREAD

**Issue by Bicoid** [BenSova/Patched-Sur#351]
**Describe the bug**
Launching a game on Steam called Idle Champions of the Forgotten Realms causes an *immediate* panic and hard reboot on an 27” 2011 iMac 12,2 patched with Big Sur 11.2.2 using Patched Sur 0.0.7.  This was replicated on an identically patched 27-inch mid-2011 iMac running the same version of Big Sur.  The issue did not resolve after disabling animations or graphics switching.  This panic/reboot was not replicated on a mid-2012 MacBook Pro 10,1, which launched the game normally.  Prior to upgrading to Big Sur, this game ran reliably on this iMac running High Sierra.  

**To Reproduce**
1. Install Steam and log into account.
2. From Steam, search and install “Idle Champions of the Forgotten Realms” (free game)
3. After installation, click on “Play”
4. iMac panics and reboots.

**Expected behavior**
After step 2 above, a splash screen should appear of the developers and title, and the game should launch.

**Desktop (please complete the following information):**
 - Upgrading from: High Sierra 10.13.6, patched by DosDude.
- Upgrading to: Big Sur v11.2.2 
 - Mac Model:  27” 2011 iMac 12,2
 - Version: 0.0.7

**Additional context**
Panic log is attached.
[panic.txt](https://github.com/BenSova/Patched-Sur/files/6079283/panic.txt)
![IMG_4594](https://user-images.githubusercontent.com/411537/109874461-25905f80-7c3d-11eb-8fdc-298b28cf46a9.jpg)

**Comment by misko64** [comment]
uhh... your iMac is a mid 2011 one right?

**Comment by misko64** [comment]
does it even have metal support?

**Comment by BenSova** [comment]
You do not have metal graphics acceleration, so your game doesn't work. Your 2012 Mac does have metal graphics acceleration, so it does work. There's nothing the patcher can do to fix this.
