### ISSUE TITLE
Error 1x250

### ISSUE THREAD

**Issue by GrandM1961** [BenSova/Patched-Sur#354]
I got this error with Patched Sur on a brand new usb stick on a iMac 27 inch Late 2012 model.

Error 1x250
Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100%
Couldn't mount dmg /Volumes/Install macOS Big Sur Beta/Install macOS Big Sur Beta.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
Output: "Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

**Comment by Witti2** [comment]
Hello, I already had it today, it was due to the installer. The one I loaded first was only about 10.4 GB and apparently incomplete. Then I reloaded Bug Sur and the installer was about 12.5 GB and it worked.

greetings

**Comment by ozziepadilla** [comment]
You guys labeling errors as a bug but none follow the procedures correctly, don’t label a bug that because i have upgrade my iMac yesterday and I didn’t see it get any BUG what I think you guys erase the usb in other formats and not the required format, I find out that with other people from YouTube

**Comment by Witti2** [comment]
Hello, I didn't write that it was a patcher bug, but that it was the Big Sur installer. You can be sure that I know how to format the stick, it's not my first patch.

greetings

**Comment by ozziepadilla** [comment]
whatever

**Comment by Monkiey** [comment]
Make sure you redownload the install assistant as you clearly don't have the full install assist downloaded then it should work.

**Comment by Witti2** [comment]
Hello, that's exactly what I meant.

Thanks

**Comment by GrandM1961** [comment]
> Hello, I already had it today, it was due to the installer. The one I loaded first was only about 10.4 GB and apparently incomplete. Then I reloaded Bug Sur and the installer was about 12.5 GB and it worked.
> 
> greetings

i have the right macOS big Sur installer and is over 12 Gb. and no matter what i do it is throwing error after error, no matter what usb stick i use. A new one or one i have used reguraly. i am doing now the barrykn version i know this one works for me.

**Comment by GrandM1961** [comment]
> You guys labeling errors as a bug but none follow the procedures correctly, don’t label a bug that because i have upgrade my iMac yesterday and I didn’t see it get any BUG what I think you guys erase the usb in other formats and not the required format, I find out that with other people from YouTube

If you have nothing else to say other than stupid remarks, please keep them to yourself. I follow the instructions as it has been given, when something works for you, doesn't mean it should work with everybody. Than you would be busy making stupid remarks to everybody including Apple.

**Comment by ozziepadilla** [comment]
Watch your way to reply because BenSova won’t tolerate that and if you want to be here participating use a better language, no insulting not offending either ok , don’t reply bac …

**Comment by GrandM1961** [comment]
If you would follow your own standards instead of lecturing others, one would not say something back. If somebody is disrespectful it starts with the one who makes a pointless remark. i have been doing this since the beginning and know how to read manuals.

**Comment by ozziepadilla** [comment]
Well many people didn’t read correctly what it’s a BUG and what it’s a human ERROR when skipping procedures, you can ask to benSova if I have report bugs or errors , and do me a favor go away ok

**Comment by GrandM1961** [comment]
Don't assume so much, and keep your assumptions to yourself. And no i am not leaving, whether you like it or not. I guess the point of GitHub is the place to start when there are bugs and where people can go for a answer instead of asking benSova in PM. People ask for help and not smartass comments, so do yourself a favor and give normal answers instead of assumptions and smartass remarks.

**Comment by BenSova** [comment]
The download failed but fell through, so this was a bug. This patcher is not perfect, so that's why it's still in beta: I already have an idea to proof this bug that could be added soon.
