### ISSUE TITLE
nvram: Error setting variable - 'boot-args'

### ISSUE THREAD

**Issue by aniceberg** [BenSova/Patched-Sur#364]
**Describe the bug** 
Both Patched Sur v0.1.0 and Terminal cannot change boot-args on iMac late 2013

**To Reproduce**
1. Open 'Terminal'
2. Type _nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"_
3. Error message: **_nvram: Error setting variable - 'boot-args': (iokit/common) not permitted_**

**Solution**
1. Boot into Recovery Mode (Command (⌘)-R at startup)
2. At the “MacOS Utilities” screen, pull down the “Utilities” menu from the top of the screen and choose “Terminal” to launch Terminal app within Recovery Mode
3. Type _nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"_
4. Type _reboot_
5. Relaunch Patched Sur

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.2 (20D64)
- Upgrading to: Big Sur 11.2.2
 - Mac Model: iMac (21.5-inch, Late 2013)
 - Version: 0.1.0 (61)

**Comment by BenSova** [comment]
This is now added to the popup in v0.1.1!
