### ISSUE TITLE
Error 1x5 Message: "Password:Error: The update cannot be installed on this computer." on an IMac 27' late 2013 

### ISSUE THREAD

**Issue by Duke330** [BenSova/Patched-Sur#367]
Ready to update screen in Patched Sur gives me a red error: (will not let me do click to copy)
Fails to load with error message 1X5 "password:error: The update cannot be installed on this computer." 
Output: " By using the Agreetolicence option, you are agreeing that you......
might be important to note I did have AMFI issue. 
It appears to have been resolved with below in terminal:
Type nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"
Type reboot
After Relaunch Patched Sur
Error 1x5
Message: "Password:Error: The update cannot be installed on this computer."
Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately."If there are any red boxes, click on them to copy the logs.

**To Reproduce**
1. Go to Patch Sur
2. Click on Start the MacOS Update
3. See error after entire download is complete and it starts to update.

**Desktop (please complete the following information):**
 - Upgrading from:Big Sur 11.1
- Upgrading to: Big Sur 11.2.2
 - Mac Model: IMac 27" late 2013

**Comment by heili1094** [comment]
same issue here at iMac 21,5 late 2013 after identical process mentioned above...

**Comment by Monkiey** [comment]
Please refer to issue #[365](https://github.com/BenSova/Patched-Sur/issues/365) for a fix

**Comment by BenSova** [comment]
The patcher should now prevent this from happening as of v0.1.1.
