### ISSUE TITLE
post install doesnt work

### ISSUE THREAD

**Issue by donmichele1** [BenSova/Patched-Sur#38]
so far everything fine on mbpro 9,2 and iMac 14,2 until..... after launch of post install and inserting  password: error csr ?
boot in setvar efi does not work. Need wifi on my mbpro.

**Comment by donmichele1** [comment]
now, after I have detected #21 and #27 I disabled csrutil by USB Big Sur Installer/terminal. Unfortunately not so successful as kimromanov...

**Comment by BenSova** [comment]
I'm closing this because the same thing can be tracked in #27 (I would have done #21 since it was first, but 27 has more discussion around it).
