### ISSUE TITLE
Does SIP have to stay disabled?

### ISSUE THREAD

**Issue by earlthesquirrel** [BenSova/Patched-Sur#382]
I found with the Catalina Patcher that having SIP disabled seems to prevent a fair amount of SW from loading.
I saw that SIP gets disabled by Patched-Sur during the install at least, but does it have to stay disabled after that?

I'm just trying to find out how much I'd be able to use the patched machine... (on Catalina I tried to load 1Password -- fails, iStatMenu -- fails, MacDVDX Ripper -- succeeds, Vivaldi Web Browser -- fails).    I understand what SIP is there for, and I understand why you'd like it turned off.  

However, for the first 4 pieces of SW I tried to install, 3 failed.  I can understand 2, but Vivaldi was a stopping point for me, given it's based on Chrome, I'm really concerned that most SW will have this issue...)

Thanks.

**Comment by BenSova** [comment]
SIP shouldn't matter. It's whether or not you have Metal Graphics Acceleration which makes a lot of difference. You can turn back on SIP, however the post install macOS updater will stop working, and it probably won't make a difference to the programs that work and don't work.

(Either way, this is a question not an issue, so I'll close this)

**Comment by earlthesquirrel** [comment]
Actually the programs listed crash and indicate it’s because SIP is disabled.  I confirmed with 1Password and they confirmed that it will crash with SIP disabled.   It is a question, however if I couldn’t re-enable SIP then I’d want to find a work around.  
( and I thought it was worth documenting at worst as an issue ).
