### ISSUE TITLE
Can't disable SIP and set NVRAM in my iMac Late 2013 27'' 

### ISSUE THREAD

**Issue by cesmed** [BenSova/Patched-Sur#387]
**Describe the bug**
First of all, thank you for the effort you are making in this program. I have used it to update from Catalina to Big sur 11.2.2 with a USB without problems.

With this new version (0.1.1) I have tried to update without USB and I got a message where I had to restart in recovery mode and use a terminal to disable SIP and use NVRAM:

csrutil disable
nvram boot-args = "- no_compat_check amfi_get_out_of_my_way = 1"

When I rebooted again, I got a black screen (sorry, I did not take a photo) where it showed a message to contact apple and the iMac did not start. I had to restart with the USB of the last update that I used with your program (I don't usually delete it) and it restarted without problems in Big Sur again.

Then, I used the USB (as we have done so far with Patched Sur) to upgrade to Big Sur 11.2.3 without issue.

**To Reproduce**
1. Go to restart with alt+R
2. In Terminal write:

csrutil disable
nvram boot-args = "- no_compat_check amfi_get_out_of_my_way = 1"

3. Restart again
4. See Black screen with "No support from Apple"

**Expected behavior**
I thought that the iMac would restart without problems and could update with Patched Sur without problems

**Desktop (please complete the following information):**
 - Upgrading from: Big sur 11.2.2
 - Upgrading to: Big sur 11.2.3
 - Mac Model: iMac Late 2013 27'' SSD 1Tb (iMac14,2), Intel Core(TM) I7-4771 CPU @ 3.50GHz
 - Version: Patched sur v0.1.1

Thanks.

**Comment by EDZUPER** [comment]
Same happened to me also with iMac late 2013 27". Even disabling csrutil before restarting. The only solution was to reflash BigSur 11.2.2. with the USB

**Comment by davidliamfranks** [comment]
I had similar issue on my iMac late 2013 27". What I did was reboot in internet recovery and just do the csrutil disable to disable SIP. I then tried the PatchedSur again which then wanted to do disable the AMFI which the patch did it self and rebooted. I was then able to update using patched sur.

What I dont understand is why we need to disable SIP and AMFI when using the micro patcher on USB we dont need to do this on the iMac late 2013?

The micro patcher says "As of Big Sur Micropatcher v0.4, install-setvars.sh will now install a version of setvars which enables Apple's System Integrity Protection (SIP) and Authenticated Root Volume (ARV) security features if it is run on a Late 2013 iMac, or a version of setvars which disables both of these features if it is run on any other model of Mac."

So why doe we need to disable SIP etc at all on late 2013? Just wondered. Im no expert!

**Comment by BenSova** [comment]
> nvram boot-args = "- no_compat_check amfi_get_out_of_my_way = 1"

There's only one space between the quotes, which is between each boot argument. Like this -> `nvram boot-args = "-no_compat_check amfi_get_out_of_my_way=1"`

You have to disable SIP (and AMFI) because it prevents code injection, which is what Patched Sur does to startosinstall to skip the compatibility check. You can turn it back on after you're done if you want.

In next version of the patcher, you won't need AMFI off, because it turns off something else that's somewhat annoying to have off (you probably haven't noticed yet), so instead it'll turn off Library Validation which is the part of AMFI, but it only is the preventing code injection part.
