### ISSUE TITLE
Keep getting this error (I'm sure it's basic, but I cannot fix)

### ISSUE THREAD

**Issue by Siddhartha666** [BenSova/Patched-Sur#39]
I keep getting this error-please see attached. Doesn't matter which USB drive I try. Also, the window to select the drive to install the patched installer doesn't resize, so I had to eject other connected drives to "give space" to show my intended USB location.
![Screen Shot 2020-11-14 at 5 08 17 PM](https://user-images.githubusercontent.com/10354628/99158023-489e0000-269c-11eb-8ccd-7259f75f3430.png)

**Comment by norek1234** [comment]
I formatted my USB with disk utility to APFS before I've done this step.
It helped on my.

**Comment by BenSova** [comment]
Let me look into this further. But I hope you know that view is a scroll view. You can scroll through the list.

**Comment by BenSova** [comment]
Try to format your drive as MacOS Extended Journaled and try again. I'm not sure if that'll make a difference but it's worth a shot.

**Comment by Tockman** [comment]
Formatting doesn't help. I guess it's related to internal two-digit USB drive number (>9 => 10,11,12...), while disk1s(1) in most cases is macos APFS partition.

**Comment by felsmann** [comment]
Thanks for posting this, I am experiencing the same issue here...  Can't create the installer USB no matter how I format it.

**Comment by BenSova** [comment]
This was fixed in one of the more recent versions of the patcher.
