### ISSUE TITLE
Hello, I'm following the tool and I'm stuck on the "Enter your password" screen. 

### ISSUE THREAD

**Issue by john7887** [BenSova/Patched-Sur#392]
- Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: 11.2.1
 - Mac Model: 13" 2010 MacBook Pro]
 
Hello, I'm following the tool and I'm stuck on the "Enter your password" screen.
![Screen Shot 2021-03-13 at 16 03 51](https://user-images.githubusercontent.com/74682554/111029763-d5bd4f80-8417-11eb-8993-853475236b8e.png)

Is there a reason that every time I enter my password, I cannot access to the next step ?

**Comment by BenSova** [comment]
This is a duplicate issue of #46, so I'll close this issue, but there are two other things I want to say. First, what special characters do you have in your password? And also, if you change your password to abc123 temporarily it will work.
