### ISSUE TITLE
Working as well on MacBook Pro Mid 2012

### ISSUE THREAD

**Issue by michelnyx** [BenSova/Patched-Sur#40]
Hello! I've installed this patch on my old MacBook Pro Mid 2012 (in state of full update on Catalina), even no official support is shown on Patched Sur's wizard, check it out:

![image](https://user-images.githubusercontent.com/32226938/99158750-f5847700-26b4-11eb-89b7-b478b2b71951.png)

All is working as well and I want to say thanks to @BenSova.

Best Regards,

Michel.

**Comment by norek1234** [comment]
The same for me:
Thank you @BenSova.

![Screenshot 2020-11-15 at 00 14 25](https://user-images.githubusercontent.com/70437484/99158885-0397bf00-26d8-11eb-9378-6fd176f54f27.png)

**Comment by xTGHHx** [comment]
Install went well but I can't join WIFI networks: 'The network could not be found'. Also after deleting existing entries in the list no new ones are displayed.

**Comment by BenSova** [comment]
Can I close this? While I appreciate it, the number 22 in the issue count is bugging me...

**Comment by michelnyx** [comment]
> Can I close this? While I appreciate it, the number 22 in the issue count is bugging me...

Yes, please.

It's just a compatibility report.

Thanks.
