### ISSUE TITLE
late 2013 imac using v0.1.2 - cant disable SIP. no csrutil command found

### ISSUE THREAD

**Issue by geapgr** [BenSova/Patched-Sur#404]
Hi Ben. Lobe yoru work. keep us the great effort. i am using a late 2013 imac. i have updated the patchsur app that got me to big sur. i was/am at Big Sur version 11.0.1 and i used the post install app to get me fully updated. i try to start the upgrade and i am immediate;y notified that i have to restart into rwecovery mode and disable SIP via tyhe csrutil disable command. this command is not found. what can i do? thanks in advance

**Comment by BenSova** [comment]
This is more or less a question not an issue, so I'll leave this for your discussion that I already answered.

**Comment by ssthakran** [comment]
Mr Ben ,
I appreciate and Love the work you are doing and am enjoying using Big Sur on my Late 2013 iMac 27" but I also get the same Response when trying to Upgrade and Type in csrutil disable - It says Command not recognised .... Please could you Point me towards the Answer .... I would really appreciate it .... 
Warm Regards
Sanjay
