### ISSUE TITLE
MBP mid 2012 - SOLVED

### ISSUE THREAD

**Issue by Granfio** [BenSova/Patched-Sur#409]
On second reboot while pressing option key I found only the internal hd and not the installer. Using v0.1.2

**To Reproduce**
1. restart first time and select EFI drive
2. mac automatically shutdown
3. Turn on with option key
4. Not showing the installer disk, see only the internal HD

**Comment by BenSova** [comment]
What happens if you unplug the drive then plug it back in on the boot screen?

**Comment by Granfio** [comment]
Nothing. I tried to restart the operation completely by formatting the usb key before and arrive on second boot step. I’m thinking the problem is on my usb hardware because I can’t see the iPhone on finder….

**Comment by BenSova** [comment]
That won't work as of right now with the patcher because of the EFI Boot thing.

**Comment by Granfio** [comment]
yes you are right. But is there any way to fix/recovery the usb ports, something like a kext patch?
Because my mbp is not mounting my iphone on finder but is showing in the mac information and I'm thinking the problem is on the usb and not on your sw...maybe

**Comment by Granfio** [comment]
I solved by using a different usb key. Thank you for your time and patience

**Comment by Granfio** [comment]
I solved by using a different usb key. Thank you for your time and patience
