### ISSUE TITLE
No Boot to Internal Recovery Possible

### ISSUE THREAD

**Issue by netshare-debug** [BenSova/Patched-Sur#417]
hello,
having performed successfully the installation of big sur 11.2.3 onto a cMP 5.1 with a metal capable nvidia geforce gtx 680.
what is now not possible anymore ist the boot into internal recovery partition (cmd + r). with each try it is performing an endless reboot until release. zap the pram did also not help out.

setup steps to big sure were the following:

installation of catalina with the most actual patcher from dosdude1 (-> internal boot to recovery worked)
installation of big sur 11.2.3 with the must actual patcher from BenSova (Patched-Sur, v0.1.2 beta) (-> no internal boot to recovery possible, although partition ist present and visible via diskutil list, csrutil is disabled, nvram no compat check is in).
what is missing?
any targeting advices are welcome.
regards,
netshare

**Comment by BenSova** [comment]
This isn't a bug, it's a feature I haven't yet implemented. Internet Recovery or an installer usb both work fine until I add it (which will be soon).
