### ISSUE TITLE
Photo Booth on imac 14,2 late 2013

### ISSUE THREAD

**Issue by c0x77** [BenSova/Patched-Sur#420]
Hi, after installing Big Sur with latest Patcher Photo Booth only work with 2 filters (screenshot). Preview does not working.
Video recording only Audio.

![Bildschirmfoto 2021-03-19 um 18 35 05](https://user-images.githubusercontent.com/80696406/111820923-5978af80-88e2-11eb-9b14-91ba1d4e0458.png)

**Comment by BenSova** [comment]
There's nothing about the patches that affect that app. Your Mac has a supported camera and GPU, so there has to be a bug with the app and how it applies the filters. Then if you consider how Apple doesn't ￼care about that app at all, it could simply be a Big Sur bug that doesn't really matter in Apple's eyes. There's nothing I can do about this, and I've heard no one complain about this bug, so it's not a priority either. I'll close this issue at that.
