### ISSUE TITLE
Facetime and iMessage stuck on sign in imac 14,2 late 2013 

### ISSUE THREAD

**Issue by c0x77** [BenSova/Patched-Sur#421]
After installing with latest Patcher iMessage and Facetime do not signing in. Facetime aborting after round about 5 Minutes without any error. iMessage aborting also after 5 Minutes with a unknown error.

![Facetime](https://user-images.githubusercontent.com/80696406/111824824-f89fa600-88e6-11eb-9b65-676bf459921a.png)

**Comment by BenSova** [comment]
What happens if you try on an older macOS version?

**Comment by ozziepadilla** [comment]
> What happens if you try on an older macOS version?

People are doing something wrong, my iMac is a Late 2013 Ben , everything works perfectly

**Comment by c0x77** [comment]
I never used this 2 Services. My last apple device was a iPhone 3gs, and this is my first Aplle Desktop Computer. I only try to log in with my Apple Account to this services, with the same Account who i can login to icloud.com.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by c0x77** [comment]
I never logged in a older macOS Version to this Services.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ozziepadilla** [comment]
> I never used this 2 Services. My last apple device was a iPhone 3gs, and this is my first Aplle Desktop Computer. I only try to log in with my Apple Account to this services, with the same Account who i can login to icloud.com. Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
> […](#)

Ok I understand what’s going on, if you actually don’t have an iPhone then FaceTime iMessage are deactivated you must call Apple in your country region I hope they can help you , a friend of mine get an iMac and he don’t have iPhone and I was trying to log in with FaceTime and iMessage and does not allow me , so call Apple

**Comment by ozziepadilla** [comment]
> What happens if you try on an older macOS version?

Ben I know what’s going on, read my reply to the user , that thing happens because FaceTime never was activate and either iMessage if he actually doesn’t have an iPhone

**Comment by c0x77** [comment]
> > I never used this 2 Services. My last apple device was a iPhone 3gs, and this is my first Aplle Desktop Computer. I only try to log in with my Apple Account to this services, with the same Account who i can login to icloud.com. Holen Sie sich Outlook für Androidhttps://aka.ms/AAb9ysg
> > […](#)
> 
> Ok I understand what’s going on, if you actually don’t have an iPhone then FaceTime iMessage are deactivated you must call Apple in your country region I hope they can help you , a friend of mine get an iMac and he don’t have iPhone and I was trying to log in with FaceTime and iMessage and does not allow me , so call Apple

Ok, thank you. 

My Brother has an iPhone 7 that he not use anymore. 
Can i use it for activating the services, or is it to old?

**Comment by ozziepadilla** [comment]
> > > I never used this 2 Services. My last apple device was a iPhone 3gs, and this is my first Aplle Desktop Computer. I only try to log in with my Apple Account to this services, with the same Account who i can login to icloud.com. Holen Sie sich Outlook für Androidhttps://aka.ms/AAb9ysg
> > > […](#)
> > 
> > 
> > Ok I understand what’s going on, if you actually don’t have an iPhone then FaceTime iMessage are deactivated you must call Apple in your country region I hope they can help you , a friend of mine get an iMac and he don’t have iPhone and I was trying to log in with FaceTime and iMessage and does not allow me , so call Apple
> 
> Ok, thank you.
> 
> My Brother has an iPhone 7 that he not use anymore.
> Can i use it for activating the services, or is it to old?

Yes you can but use your Apple ID to log in with that iPhone and go to settings find FaceTime and iMessage to log in or go to the each app of FaceTime and iMessage then log in , after that go to your iMac and log in with FaceTime and iMessage, allow in your iPhone every notification you receive

**Comment by c0x77** [comment]
Signing in with a iphone 7 to iMessage and Facetime was succesful, but i still can not sign in with the iMac. I decided to downgrade to catalina before i call the Apple Support. The Apple Support reseted some Things in activation progress (i dont know what they reseted exactly). After that i can now finally sign in to Facetime and iMessage. 

Do you think, i can now upgrade to big sur without Problems?

**Comment by ozziepadilla** [comment]
> Signing in with a iphone 7 to iMessage and Facetime was succesful, but i still can not sign in with the iMac. I decided to downgrade to catalina before i call the Apple Support. The Apple Support reseted some Things in activation progress (i dont know what they reseted exactly). After that i can now finally sign in to Facetime and iMessage.
> 
> Do you think, i can now upgrade to big sur without Problems?

Sure you can try it

**Comment by ozziepadilla** [comment]
> Signing in with a iphone 7 to iMessage and Facetime was succesful, but i still can not sign in with the iMac. I decided to downgrade to catalina before i call the Apple Support. The Apple Support reseted some Things in activation progress (i dont know what they reseted exactly). After that i can now finally sign in to Facetime and iMessage.
> 
> Do you think, i can now upgrade to big sur without Problems?

Use the same way you did before , Creating the usb

**Comment by c0x77** [comment]
After the Upgrade everything is now working fine. Thank you guys for your Patch and the Support.

**Comment by ozziepadilla** [comment]
> After the Upgrade everything is now working fine. Thank you guys for your Patch and the Support.

Great 👍 you got it now , so you can close the issue anytime
