### ISSUE TITLE
Random Kernel Panics on MBP 15" Retina Late-2012

### ISSUE THREAD

**Issue by cstormsc** [BenSova/Patched-Sur#428]
Hi, I have been getting these random kernel panics apparently during GPU tasks such as Photoshop and Illustrator. They don't seem related to any specific function and I haven't been able to replicate them. This Laptop is stock except from the Wifi Card that was updated to a newer model. I also noticed these panics after updating the patch to 0.1.2 and BS to 11.2.3.

This is the Apple report.

panic(cpu 0 caller 0xffffff80265ee1e6): Kernel trap at 0xffffff8027aa695b, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x000000004d535764, CR3: 0x000000002acf5000, CR4: 0x00000000001626e0
RAX: 0x00000000ed010000, RBX: 0x000000004d535764, RCX: 0x0000000000000000, RDX: 0x0000000001000000
RSP: 0xffffffa0c4b0bc00, RBP: 0xffffffa0c4b0bc20, RSI: 0xffffff93849ade70, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0xffffffa064df9420, R10: 0x00000000000000ff, R11: 0xffffff86c52e7e30
R12: 0xffffff938495e000, R13: 0xffffff8028c92b1e, R14: 0x0000000000000000, R15: 0xffffff938499f800
RFL: 0x0000000000010246, RIP: 0xffffff8027aa695b, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000004d535764, Error code: 0x0000000000000002, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffffa0c4b0b620 : 0xffffff80264bab4d 
0xffffffa0c4b0b670 : 0xffffff80265fd7e3 
0xffffffa0c4b0b6b0 : 0xffffff80265ede1a 
0xffffffa0c4b0b700 : 0xffffff802645fa2f 
0xffffffa0c4b0b720 : 0xffffff80264ba3ed 
0xffffffa0c4b0b840 : 0xffffff80264ba6d8 
0xffffffa0c4b0b8b0 : 0xffffff8026cbef9a 
0xffffffa0c4b0b920 : 0xffffff80265ee1e6 
0xffffffa0c4b0baa0 : 0xffffff80265edecd 
0xffffffa0c4b0baf0 : 0xffffff802645fa2f 
0xffffffa0c4b0bb10 : 0xffffff8027aa695b 
0xffffffa0c4b0bc20 : 0xffffff80287ccb15 
0xffffffa0c4b0bc70 : 0xffffff80287cc44d 
0xffffffa0c4b0bd20 : 0xffffff80287c7c36 
0xffffffa0c4b0bd50 : 0xffffff8026c1964f 
0xffffffa0c4b0bdb0 : 0xffffff80287cb5b9 
0xffffffa0c4b0bdf0 : 0xffffff8026bfcda1 
0xffffffa0c4b0be60 : 0xffffff8026bfcb3a 
0xffffffa0c4b0be80 : 0xffffff80264ff725 
0xffffffa0c4b0bef0 : 0xffffff8026500634 
0xffffffa0c4b0bfa0 : 0xffffff802645f13e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleSMC(3.1.9)[1E48B8EB-7BF3-3366-8520-2C4B31A7D3F8]@0xffffff8027a95000->0xffffff8027aadfff
            dependency: com.apple.driver.watchdog(1)[2C1307C5-FD71-3802-8D68-A67DB24BCB4A]@0xffffff8029f41000->0xffffff8029f42fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[B41AA072-8BB9-3493-9796-6FF849CDABB8]@0xffffff80290c3000->0xffffff80290c4fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]@0xffffff802960a000->0xffffff8029631fff
         com.apple.driver.AirPort.BrcmNIC(1400.1.1)[6720B44C-7F54-387B-BDA5-59A5834BFC62]@0xffffff80287ac000->0xffffff8028cd8fff
            dependency: com.apple.driver.corecapture(1.0.4)[DDCF23B4-962A-3A18-B089-CD07BDAD9A35]@0xffffff8029dc2000->0xffffff8029dd8fff
            dependency: com.apple.driver.mDNSOffloadUserClient(1.0.1b8)[35ABC470-4743-30AC-9BA8-4A62CFA2296D]@0xffffff8029604000->0xffffff8029608fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2)[BB6CCEC8-1778-3FE3-A236-AF9DC84C8CF2]@0xffffff8027e2f000->0xffffff8027ee4fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[CEA28E53-3048-362D-B58E-3A02FFC20EA9]@0xffffff8029381000->0xffffff8029397fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]@0xffffff802960a000->0xffffff8029631fff

Process name corresponding to current thread: kernel_task
Boot args: -no_compat_check

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000026200000
KernelCache base:  0xffffff8026400000
Kernel slide:      0x0000000026210000
Kernel text base:  0xffffff8026410000
__HIB  text base: 0xffffff8026300000
System model name: MacBookPro10,1 (Mac-C3EC7CD22292981F)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 69134287006
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000001018b9921e
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000a434ce5c8 0x0000000000000000
last started kext at 22810254670: >AudioAUUC	1.70 (addr 0xffffff7fc6985000, size 12288)
loaded kexts:
>AudioAUUC	1.70
>!APlatformEnabler	2.7.0d0
>AGPM	119
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@fileutil	20.036.15
>!AMikeyHIDDriver	131
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.3d9
>!AHDAHardwareConfigDriver	283.15
@Dont_Steal_Mac_OS_X	7.0.0
>!AHDA	283.15
>!AHV	1
>!ADiskImages2	1
>!A!IHD4000Graphics	16.0.1
>!AMikeyDriver	283.15
>!AUpstreamUserClient	3.6.8
>AGDCBacklightControl	6.2.2
>!ASMCLMU	212
>!ABacklight	180.3
>!A!IFramebufferCapri	16.0.1
>!A!ISlowAdaptiveClocking	4.0.0
@GeForce	16.0.0
>!AThunderboltIP	4.0.3
>!AMCCSControl	1.14
>eficheck	1
>ACPI_SMC_PlatformPlugin	1.0.0
>!ASMCPDRC	1.0.0
>!AMuxControl	6.2.2
>!ALPC	3.1
>!AFIVRDriver	4.1.0
@nvidia.NVDAStartup	16.0.0
|IO!BUSBDFU	8.0.3d9
>!UTCKeyEventDriver	256
>!UTCButtons	256
>!UTCKeyboard	256
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1677.81.1
>AirPort.BrcmNIC	1400.1.1
|!ABCM5701Ethernet	11.0.0
>!ASDXC	1.9.0
>!AAHCIPort	346
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
>!A!ICPUPowerManagementClient	222.0.0
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!A!ICPUPowerManagement	222.0.0
@kext.triggers	1.0
|IOSerial!F	11
|IOAVB!F	930.1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@!AGPUWrangler	6.2.2
>!ABacklightExpert	1.1.0
|IOSlowAdaptiveClocking!F	1.0.0
|IOAccelerator!F2	439.52
@nvidia.driver.NVDAGK100Hal	16.0.0
@nvidia.driver.NVDAResman	16.0.0
>!ASMBus!C	1.0.18d1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>IOPlatformPluginLegacy	1.0.0
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>!AGraphicsControl	6.2.2
@!AGraphicsDeviceControl	6.2.2
>!ASMBusPCI	1.0.14d1
|IONDRVSupport	585
|IOGraphics!F	585
>!AThunderboltEDMSink	5.0.3
>!AThunderboltDPOutAdapter	8.1.4
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|Broadcom!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
>!UMultitouch	264
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!ABSDKextStarter	3
|IOSurface	289.3
|IOSkywalk!F	1
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
|IOAHCIBlock!S	332
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
|IO80211!F	1200.12.2
>corecapture	1.0.4
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>mDNSOffloadUserClient	1.0.1b8
|IOAHCI!F	294
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UEHCIPCI	1.2
>usb.!UEHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by tomzre** [comment]
I am having similiar problems but without using graphics program randomly crashes with similar report.

**Comment by cstormsc** [comment]
I Discovered the fault was with the wifi card, since it was a newer model
card and once I replaced, it stopped crashing
Carlos Storms
***@***.***

**Comment by BenSova** [comment]
Closing since this appears to be resolved.
