### ISSUE TITLE
error 1x1 

### ISSUE THREAD

**Issue by lexi1221** [BenSova/Patched-Sur#43]
<img width="602" alt="Screenshot 2020-11-15 at 02 59 30" src="https://user-images.githubusercontent.com/74479050/99161872-b07d3680-26ee-11eb-88c7-4f14009fb224.png">

**Comment by BenSova** [comment]
Tap on the red box, then paste it here. I can't interpret a cut off error.

**Comment by lexi1221** [comment]
Error 1x1
Message: "Password:mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75"
"No WiFi option specified on command line, so checking for 802.11ac...
Found 802.11ac WiFi card, so not installing a WiFi patch.
No patch mode specified on command line. Detecting Mac model...
(Use --2010, --2011, or --2012 command line option to override.)
Detected model: MacBookPro10,1
Detected a 2012-2013 Mac. Using --2012 patch mode.
Installing kexts to:
/

Volume appears to have a Big Sur installation (build 20B29). Continuing.
Volume is mounted from device:  /dev/disk1s5s1
Mounted device is a snapshot. Will now mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

Mounting underlying volume failed. Cannot proceed."

**Comment by BenSova** [comment]
I'm going to just close this because it resembles #42 a bit too much...

**Comment by lexi1221** [comment]
yes can you give the solution please ?

**Comment by BenSova** [comment]
I'll send it in #42 once I figure it out. But, there's no point in having two issues open for the same thing.
