### ISSUE TITLE
'You shut down your computer because of a problem' on every reboot/login

### ISSUE THREAD

**Issue by RainmakerRaw** [BenSova/Patched-Sur#434]
**Describe the bug**
After login following every reboot, a dialog pops up saying 'You shut down your computer because of an error', and asks whether I want to reopen the applications that were open when the device shut down. 

**To Reproduce**
1. Reboot
2. Enter password at login screen, and log in to user account
3. Message pops up every time

**Expected behavior**
The Mac should log in to the new session without error. 

**Screenshots**
![Error](https://i.imgur.com/h1Dv0du.png)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.2.3
 - Mac Model: 13" mid-2012 MacBook Pro (non-retina)
 - Version 0.1.2 beta

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> After login following every reboot, a dialog pops up saying 'You shut down your computer because of an error', and asks whether I want to reopen the applications that were open when the device shut down.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Reboot
> 2. Enter password at login screen, and log in to user account
> 3. Message pops up every time
> 
> **Expected behavior**
> The Mac should log in to the new session without error.
> 
> **Screenshots**
> ![Error](https://camo.githubusercontent.com/920dc8ebac6b731f01558aa5a438019263313160e5e691ca71d44401ab4cb950/68747470733a2f2f692e696d6775722e636f6d2f683144763064752e706e67)
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to: Big Sur v11.2.3
> * Mac Model: 13" mid-2012 MacBook Pro (non-retina)
> * Version 0.1.2 beta

Funny , hey I get that warning sometimes and isn’t because of macOS Big Sur installed in unsupported Mac 💻 is because one of few apps was open when you turn off your Mac , you should click over in open button then restart your Mac if appears again click over open button  again so you will see the white progress bar under the Apple logo is running slow so keep restarting until the warning gone that’s all and next time close off all your apps before shutting down your Mac 💻

**Comment by BenSova** [comment]
Well first of all, that's definitely not your screenshot of that popup, since on Big Sur it looks different, but I assume you didn't think about screenshotting it or didn't know if you could/how to screenshot it. 

The thing is though, it means nothing. You didn't shut down your computer because of a problem, right? That thing can popup without any reason on supported Macs too. There's nothing you or I can do about it.

**Comment by ozziepadilla** [comment]
> Well first of all, that's definitely not your screenshot of that popup, since on Big Sur it looks different, but I assume you didn't think about screenshotting it or didn't know if you could/how to screenshot it.
> 
> The thing is though, it means nothing. You didn't shut down your computer because of a problem, right? That thing can popup without any reason on supported Macs too. There's nothing you or I can do about it.

I am agree with that Ben

**Comment by RainmakerRaw** [comment]
> Well first of all, that's definitely not your screenshot of that popup, since on Big Sur it looks different, but I assume you didn't think about screenshotting it or didn't know if you could/how to screenshot it.

No, I didn't suggest that it was. You know what assume does... ;) I grabbed the image from DDG to better illustrate my report, because the text is identical. I tried screenshot but, presumably because the device hadn't logged in yet, it didn't work. 

> The thing is though, it means nothing. You didn't shut down your computer because of a problem, right? That thing can popup without any reason on supported Macs too. There's nothing you or I can do about it.

I see. Perhaps an issue with Big Sur then, as I've never seen it in normal operation on Catalina (or any OS before through Snow Leopard), unless the machine had indeed been forced to restart. Thanks for your time anyway.

**Comment by RainmakerRaw** [comment]
> and next time close off all your apps before shutting down your Mac computer

I always do, I'm pretty anal about that. I even close the apps in the menu bar.

**Comment by ozziepadilla** [comment]
> > Well first of all, that's definitely not your screenshot of that popup, since on Big Sur it looks different, but I assume you didn't think about screenshotting it or didn't know if you could/how to screenshot it.
> 
> No, I didn't suggest that it was. You know what assume does... ;) I grabbed the image from DDG to better illustrate my report, because the text is identical. I tried screenshot but, presumably because the device hadn't logged in yet, it didn't work.
> 
> > The thing is though, it means nothing. You didn't shut down your computer because of a problem, right? That thing can popup without any reason on supported Macs too. There's nothing you or I can do about it.
> 
> I see. Perhaps an issue with Big Sur then, as I've never seen it in normal operation on Catalina (or any OS before through Snow Leopard), unless the machine had indeed been forced to restart. Thanks for your time anyway.

Hi, that happens when you didn’t close apps and you force to reboot the Mac holding down the power button or when restart in my case was when power get off in my house and when I turn it on I get there warning ⚠️ because I had Apple Music app open IS NOT AN ISSUE because of macOS Big Sur installed in unsupported mac 💻

**Comment by ozziepadilla** [comment]
> > Well first of all, that's definitely not your screenshot of that popup, since on Big Sur it looks different, but I assume you didn't think about screenshotting it or didn't know if you could/how to screenshot it.
> 
> No, I didn't suggest that it was. You know what assume does... ;) I grabbed the image from DDG to better illustrate my report, because the text is identical. I tried screenshot but, presumably because the device hadn't logged in yet, it didn't work.
> 
> > The thing is though, it means nothing. You didn't shut down your computer because of a problem, right? That thing can popup without any reason on supported Macs too. There's nothing you or I can do about it.
> 
> I see. Perhaps an issue with Big Sur then, as I've never seen it in normal operation on Catalina (or any OS before through Snow Leopard), unless the machine had indeed been forced to restart. Thanks for your time anyway.

Just click over OPEN BUTTON until the warning go away that’s all let it go if the apps you had open reopen again then close them and restart the Mac again

**Comment by ozziepadilla** [comment]
> > and next time close off all your apps before shutting down your Mac computer
> 
> I always do, I'm pretty anal about that. I even close the apps in the menu bar.

So make sure if there aren’t some apps that start up when the Mac log in , go to system preferences security and privacy and check in logged items when Mac start up if you see some apps then remove them hiring the -

**Comment by ozziepadilla** [comment]
> > and next time close off all your apps before shutting down your Mac computer
> 
> I always do, I'm pretty anal about that. I even close the apps in the menu bar.

Don’t click over CANCEL button because you will get that warning ⚠️ pop ups over and over if you click over OPEN let the Mac finish log in and wait if some apps was open before it will reopen then close them properly

**Comment by kliere** [comment]
Hi RainmakerRaw,

unfortunately, this has nothing to do with Patched Sur, since this happens on supported machines with 10.2 as well. In my case it stopped with installing 10.3 beta. 

Cheers,

k.

**Comment by RainmakerRaw** [comment]
> Hi RainmakerRaw,
> 
> unfortunately, this has nothing to do with Patched Sur, since this happens on supported machines with 10.2 as well. In my case it stopped with installing 10.3 beta.
> 
> Cheers,
> 
> k.

Thanks for the heads up, kliere. I just tried to upgrade to 11.3 public beta 3 to verify, and got the following ominous warning: 

![Scary Warning](https://i.imgur.com/YVHaCBn.png)

**Comment by ozziepadilla** [comment]
> > Hi RainmakerRaw,
> > unfortunately, this has nothing to do with Patched Sur, since this happens on supported machines with 10.2 as well. In my case it stopped with installing 10.3 beta.
> > Cheers,
> > k.
> 
> Thanks for the heads up, kliere. I just tried to upgrade to 11.3 public beta 3 to verify, and got the following ominous warning:
> 
> ![Scary Warning](https://camo.githubusercontent.com/554fb52022786b193db2bf325d41995ecdead32959e08b4c5bf19c69ab83f224/68747470733a2f2f692e696d6775722e636f6d2f5956486143426e2e706e67)

Actually isn’t possible install macOS big Sur betas just don’t install it

**Comment by RainmakerRaw** [comment]
> > > Hi RainmakerRaw,
> > > unfortunately, this has nothing to do with Patched Sur, since this happens on supported machines with 10.2 as well. In my case it stopped with installing 10.3 beta.
> > > Cheers,
> > > k.
> > 
> > 
> > Thanks for the heads up, kliere. I just tried to upgrade to 11.3 public beta 3 to verify, and got the following ominous warning:
> > ![Scary Warning](https://camo.githubusercontent.com/554fb52022786b193db2bf325d41995ecdead32959e08b4c5bf19c69ab83f224/68747470733a2f2f692e696d6775722e636f6d2f5956486143426e2e706e67)
> 
> Actually isn’t possible install macOS big Sur betas just don’t install it benSova remove it from the catalogue

Ah OK. Thanks again.
