### ISSUE TITLE
Install assistant package damaged

### ISSUE THREAD

**Issue by Arthurjiang0923** [BenSova/Patched-Sur#436]
I click efi boot then install macOS Big Sur. After that, I clicked on reinstall macOS but it says install assistant package is damaged and can’t be used to install macOS. Can any1 help?
![003E26EF-B529-4C64-891A-C779ECFFBB6F](https://user-images.githubusercontent.com/72886992/113778857-c01f0b00-96e1-11eb-97a8-7ec4217f5f7f.jpeg)

**Comment by BenSova** [comment]
This is a duplicate issue. Please search the issue list before creating an issue.
