### ISSUE TITLE
InstallAssistant Damaged and cannot be used

### ISSUE THREAD

**Issue by nicwilson58** [BenSova/Patched-Sur#437]
**Describe the bug**
During install after USB boot and selecting install big sur,  Recovery stops with error (see screenshot) which says "This copy of the install assistant is damaged and cannot be used to install macOS.  From researching this error shows it may be because the certificate is damaged from being modified possibly?

**To Reproduce**
Start from latest version of Catalina,   Macbook Pro 13" Late 2012.  8GB. 512GB SSD
Follow 0.12 installer to create a USB,   (tried 2,  32GB and 64GB)
boot USB via option key as instructed
At recovery menu selected install macos bigsur
stops with error

**Expected behavior**
install big sur

**Screenshots**
<img width="392" alt="Untitled" src="https://user-images.githubusercontent.com/58644781/113800621-9e358f00-979a-11eb-9d6e-bb0fbc74468b.png">

**Desktop (please complete the following information):**
 - Upgrading from: Catalina 10.15.7
- Upgrading to:  Big Sur 11.23
 - Mac Model: Late 2012 Macbook Pro 13"
 - Version V0.12

**Additional context**

tried many times,  downloads from different computers,  variou USB,  same result.

If there are any red boxes, click on them to copy the logs.
None

**Comment by BenSova** [comment]
This is a duplicate issue.

**Comment by nicwilson58** [comment]
hi,Sorry about that I did check first , Since your email i have been back and re read every open issue and have still not found a duplucate so i am stumped which to follow for  resolution to be able to complete the install.cheers
-------- Original message --------From: Ben Sova ***@***.***> Date: 9/4/21  8:05 am  (GMT+10:00) To: BenSova/Patched-Sur ***@***.***> Cc: nicwilson58 ***@***.***>, Author ***@***.***> Subject: Re: [BenSova/Patched-Sur] InstallAssistant Damaged and cannot be used (#437) 
Closed #437.

**Comment by toddanglin** [comment]
Since Google brought me here (and I assume others), here is a link to one of the more active issues discussing this topic: https://github.com/BenSova/Patched-Sur/issues/100
