### ISSUE TITLE
After CMD+OPT+PR wont boot anymore

### ISSUE THREAD

**Issue by jeromeyango** [BenSova/Patched-Sur#44]
![received_673307590040885](https://user-images.githubusercontent.com/74488636/99181188-d266cf80-2767-11eb-827a-c4d93984d83a.jpeg)
I try resetting the pram after which my mid2012 wont boot anymore

**Comment by porcherie** [comment]
Plug in the usb stick you used to install, boot the Mac holding ALT, the boot once from BootEFI, the Mac will turn off, so reboot again holding ALT, the select the HD where you installed BigSur, et voila

**Comment by michelnyx** [comment]
> Plug in the usb stick you used to install, boot the Mac holding ALT, the boot once from BootEFI, the Mac will turn off, so reboot again holding ALT, the select the HD where you installed BigSur, et voila

I did it before and flawless worked.

**Comment by jeromeyango** [comment]
> > Plug in the usb stick you used to install, boot the Mac holding ALT, the boot once from BootEFI, the Mac will turn off, so reboot again holding ALT, the select the HD where you installed BigSur, et voila
> 
> I did it before and flawless worked.

So i need to reinstall again?

**Comment by jeromeyango** [comment]
What if dont have the usb that i use to install anymore, do i need a same macbook 2012 to create a installer?

**Comment by michelnyx** [comment]
> > > Plug in the usb stick you used to install, boot the Mac holding ALT, the boot once from BootEFI, the Mac will turn off, so reboot again holding ALT, the select the HD where you installed BigSur, et voila
> > 
> > 
> > I did it before and flawless worked.
> 
> So i need to reinstall again?

AFAIK, no.

**Comment by porcherie** [comment]
> > > Plug in the usb stick you used to install, boot the Mac holding ALT, the boot once from BootEFI, the Mac will turn off, so reboot again holding ALT, the select the HD where you installed BigSur, et voila
> > 
> > 
> > I did it before and flawless worked.
> 
> So i need to reinstall again?

No need to reinstall, just boot from the usb

**Comment by porcherie** [comment]
> What if dont have the usb that i use to install anymore, do i need a same macbook 2012 to create a installer?

I think you can create it from any Mac and then used on the one that doesn't boot

**Comment by jeromeyango** [comment]
> > What if dont have the usb that i use to install anymore, do i need a same macbook 2012 to create a installer?
> 
> I think you can create it from any Mac and then used on the one that doesn't boot

Okay thank you so much

**Comment by jeromeyango** [comment]
It worked! Thank you!

**Comment by BenSova** [comment]
I'm going to close this, because A) it appears to be resolved, B) this is the software doing what it's told, and that's okay. When you boot into the EFI Boot, it sets the NVRAM boot-args and SIP status, whereas booting with that combination resets the NVRAM and SIP, therefore undoing what the EFI Boot did. There is no issue here, that's macOS running like macOS should.
