### ISSUE TITLE
SSD Write and Read Spead Reduced so MacBook Pro 2012 working so slow

### ISSUE THREAD

**Issue by ahmetozcan999** [BenSova/Patched-Sur#441]
I installed Big Sur but my ssd working so slow. Ssd is working good on Catalina.
In Catalina write 380MB/S Read 470 MB/S but in Big Sur both of 85MB/S
I return Catalina and it is working fast again
Both of Big Sur and Catalina same file system GUID and APFS
How can I solve this problem

**Comment by BenSova** [comment]
This is a duplicate issue... of your own issue....
