### ISSUE TITLE
MacOS Boot Into Black Screen, No Dock, No Multitab, No Trackpad Swipe Up Windows and Full Screen into 2/3 of the screen

### ISSUE THREAD

**Issue by anaszulkifli** [BenSova/Patched-Sur#442]
**Describe the bug**
MacOS Boot Into Black Screen, No Dock, No Multitab, No Trackpad Swipe Up Windows and Full Screen into 2/3 of the screen.

**To Reproduce**
1. Everything has been working fine until recently

**Expected behavior**
If tries to full screen, Mac will do partial full screen and sometimes cant exit full screen

**Screenshots**
https://ibb.co/ssw0P9Q

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.3 Beta]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.12]

**Additional context**
Have been trying switch on/off animations, disable/enable GPU switching mode and patch kext multiple times... no dice. Help please!

If there are any red boxes, click on them to copy the logs.

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> MacOS Boot Into Black Screen, No Dock, No Multitab, No Trackpad Swipe Up Windows and Full Screen into 2/3 of the screen.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Everything has been working fine until recently
> 
> **Expected behavior**
> If tries to full screen, Mac will do partial full screen and sometimes cant exit full screen
> 
> **Screenshots**
> https://ibb.co/ssw0P9Q
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: [e.g. Catalina v10.15.7]
> * Upgrading to: [e.g. Big Sur v11.3 Beta]
> * Mac Model: [e.g. 13" 2012 MacBook Pro]
> * Version [e.g. v0.0.12]
> 
> **Additional context**
> Have been trying switch on/off animations, disable/enable GPU switching mode and patch kext multiple times... no dice. Help please!
> 
> If there are any red boxes, click on them to copy the logs.

It seems you install macOS Big Sur beta I am right? If yes that’s the problem, who doesn’t know that all betas are buggy glitched I have suggested to no install macOS Big Sur beta

**Comment by Monkiey** [comment]
That happens sometimes I just wait a while and the wallpaper shows up, or just reboot the computer again.

**Comment by anaszulkifli** [comment]
6+ hours in, still dark and I have rebooted many times w/ and w/out Patched Kext. Thinking of resetting the NVRAM & SMC. If still fails, will roll-back to non-beta version.

**Comment by ozziepadilla** [comment]
> 6+ hours in, still dark and I have rebooted many times w/ and w/out Patched Kext. Thinking of resetting the NVRAM & SMC. If still fails, will roll-back to non-beta version.

Downgrade to a official release, betas of macOS always aren’t good by experience I can tell you

**Comment by Monkiey** [comment]
Well if you rest NVRAM make sure to have the stick for EFI boot otherwise you ma will get the prohibited sign when you boot.

**Comment by anaszulkifli** [comment]
NVRAM & SMC reset did not work. Tried to downgrade to Release track but was given failed notice (cant downgrade once installed public beta). Instead, upgrading to Developer track which has Beta 8 version which is now working fine like before.

Next release should at least allow users to downgrade back to Release version.
