### ISSUE TITLE
Start up load page

### ISSUE THREAD

**Issue by gabepratts** [BenSova/Patched-Sur#443]
When I upgraded to this, I noticed when I start my computer the loading screen that takes roughly 20 seconds to go to my sign-on. The bar stops halfway and then gets full after 20 seconds. Not sure if that’s normal going forward, or if anyone else is having the same issue.
![2B16991C-F36A-4781-B811-E63C17DB6C3E](https://user-images.githubusercontent.com/82318607/114303493-641b0480-9a9c-11eb-9592-35eca8cdc43d.jpeg)

**Comment by ozziepadilla** [comment]
> When I upgraded to this, I noticed when I start my computer the loading screen that takes roughly 20 seconds to go to my sign-on. The bar stops halfway and then gets full after 20 seconds. Not sure if that’s normal going forward, or if anyone else is having the same issue.
> ![2B16991C-F36A-4781-B811-E63C17DB6C3E](https://user-images.githubusercontent.com/82318607/114303493-641b0480-9a9c-11eb-9592-35eca8cdc43d.jpeg)

It’s normal macOS bog Sur takes time optimizing it’s files and  apps just let it don’t force it to rebooting

**Comment by BenSova** [comment]
It's macOS booting up, not a bug.
