### ISSUE TITLE
[iMac mid 2011] Get black screen on installation restart process (need to press Option)

### ISSUE THREAD

**Issue by hadnet** [BenSova/Patched-Sur#454]
**Describe the bug**
I was able to install Big Sur but I have a problem while installing Big Sur using this patcher (v0.1.2 beta) on my iMac Mid 2011 21,5 (with NVIDIA metal compatible, 1TB SSD, 28GB RAM). The issue I'm having is weird. While installing macOS BigSur with patched bootable USB, after some time there is that part of installation in which iMac reboots couple of times to finish doing its stuff. But, after iMac reboots, the screen is dead black but the iMac is still running forever. So I turned off and on but nothing changes, still the black screen.

HOWEVER

If I hold OPTION key and boot up to boot menu and then choose Macintosh HD drive (the one with BigSur installed) everything works fine. Big Sur started and all is working! But after rebooting again (without option key) - blackness again! Pulling out Bootable USB doesn't work.

What the heck is going on? Why I need to press OPTION on boot up in order to run the OS??

**To Reproduce**
A iMac mid 2011 21.5"
BenSova patcher v.0.1.2 beta

**Expected behavior**
When turn iMac on no need to press OPTION and choose the OS HD in order to start Mac OS Big Sur

**Desktop (please complete the following information):**
 - Upgrading from:  Catalina v10.15.6
- Upgrading to: Big Sur v11.2.3
 - Mac Model: iMac mid 2011 21.5 with GeForce GTX 765M by Nick[D]vB 2GB, 28GB RAM, 1TB SSD
 - Version v0.1.2

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> I was able to install Big Sur but I have a problem while installing Big Sur using this patcher (v0.1.2 beta) on my iMac Mid 2011 21,5 (with NVIDIA metal compatible, 1TB SSD, 28GB RAM). The issue I'm having is weird. While installing macOS BigSur with patched bootable USB, after some time there is that part of installation in which iMac reboots couple of times to finish doing its stuff. But, after iMac reboots, the screen is dead black but the iMac is still running forever. So I turned off and on but nothing changes, still the black screen.
> 
> HOWEVER
> 
> If I hold OPTION key and boot up to boot menu and then choose Macintosh HD drive (the one with BigSur installed) everything works fine. Big Sur started and all is working! But after rebooting again (without option key) - blackness again! Pulling out Bootable USB doesn't work.
> 
> What the heck is going on? Why I need to press OPTION on boot up in order to run the OS??
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> A iMac mid 2011 21.5"
> BenSova patcher v.0.1.2 beta
> 
> **Expected behavior**
> When turn iMac on no need to press OPTION and choose the OS HD in order to start Mac OS Big Sur
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from:  Catalina v10.15.6
> * Upgrading to: Big Sur v11.2.3
> * Mac Model: iMac mid 2011 21.5 with GeForce GTX 765M by Nick[D]vB 2GB, 28GB RAM, 1TB SSD
> * Version v0.1.2

Long Question ? Did you boot the iMac manually when creating the bootable usb finish? Then you hold down option key when you turn on manually the iMac and select EFI boot ? and the iMac shut down itself ? Then you turn it in again holding down option key and selecting install macOS Big Sur ?

**Comment by BenSova** [comment]
![Screen Shot 2021-04-16 at 8 30 42 PM](https://user-images.githubusercontent.com/65474198/115099376-af953e80-9ef2-11eb-977b-6e6c17c428a9.png)

Try changing your startup disk in system preferences.

**Comment by hadnet** [comment]
Tried that but it didn’t work.

**Comment by hadnet** [comment]
Ok, got it. Use the https://github.com/Ausdauersportler/big-sur-micropatcher and after the installation finished did a drag and drop to terminal the remount-sysvol.sh file in USB and run it and then run this command

MYBOARD=`/usr/sbin/ioreg -l | grep board-id | awk -F\" '{ print $4 }' | grep Mac`
/usr/libexec/PlistBuddy -c "Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:$MYBOARD string none" AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

And finally this command:

chmod -R 755 AppleGraphicsControl.kext && chown -R 0:0 AppleGraphicsControl.kext


Restart the OS and now no black screen or need to hold Option.
