### ISSUE TITLE
Impossible to valid password

### ISSUE THREAD

**Issue by AdrienDole** [BenSova/Patched-Sur#46]
Hello, I'm following the tool and I'm stuck on the "Enter your password" screen.

In my password I have the following characters : çà("

Is there a reason that every time I enter my password, I cannot access to the next step ?

![Screenshot 2020-11-15 at 21 33 57](https://user-images.githubusercontent.com/6368012/99196063-4d40e200-278a-11eb-9745-8d63fad62fa6.png)

**Comment by norek1234** [comment]
Can you change then this password on Mac user password section without special characters to avoid this problem?

**Comment by BenSova** [comment]
The quote is the problem. I use quotes in the command to check your password and use your password, and that's probably the reason.

**Comment by BenSova** [comment]
I added some code that should fix this problem. It will be apart of v0.0.4.

**Comment by AdrienDole** [comment]
And do you know when next release will be available ? :)

**Comment by BenSova** [comment]
This should be fixed!

**Comment by AdrienDole** [comment]
Still not working, I'll change my password :)

**Comment by BenSova** [comment]
I added some improvements in v0.0.5, but only for `"`.

**Comment by thunderbird32** [comment]
I too am stuck on this screen. I was able to update from Catalina to Big Sur just fine with the previous version of Patched-Sur, but with the new version (trying to update from 11.2.1 to 11.2.2 by running a new update) I'm stuck at the password prompt. I do **not** have a quotation mark in my password. I have uppercase letters, lower case letters, and numbers.

**Comment by TheMac6ine** [comment]
Hello BenSova, 

i have the same problem on v 0.1.2. I have /& in my PW. When I change it everything works fine. 

Thanks and regards
Stefan

**Comment by BenSova** [comment]
I switched to actual Standard Input instead of Bash Piping, and now it should work fine!
Just tested with my password as literally just `!@#$%^&*()`! 😄

The fix will come with the next release!
