### ISSUE TITLE
After resetting NVRAM, Big Sur won't boot with NO signal

### ISSUE THREAD

**Issue by gustavopi** [BenSova/Patched-Sur#461]
I had to reset my NVRAM in order to make work my scanner. Is a common issue for old printer/scanners in Big Sur and this is the solution pointed by the community. But NVRAM is something you might have to reset for whatever reason.
After the reset, even available in boot menu, Big Sur won't boot. Instead of the apple, there is a NO (prohibited) symbol.
EDIT: also the USB stick with the installation will have the same result.

Steps to the bug:
1. Turn off the Mac
2. Turn on with keys command+alt+R+P pressed until the second "tchaaaannnn" (off and on again)
3. Choose the Big Sur volume or just let it boot if you have only one bootable volume
4. Instead an apple logo, there is a NO symbol, and this way it will stay forever...

I honestly don't know exactly how to fix this, maybe the boot should be able to auto repair or fall into a command line, as some Linux distros.

This will happens with any Big Sur at any time, here is how to fix it:
1. Turn off the Mac
2. Turn on with keys command+S pressed until the apple logo appears, now it will load the Recovery Partition
3. When finished, call the Terminal (thought is in "tools" menu in english version
4. type "nvram boot-args=-no_compat_check"
5. type "reboot"
6. It should reboot and run Big Sur normally again.

It seems this flag tells the boot to make a compatibility verification. When turned on, it won't be possible to set this volume as the default in preferences -> initialization disk, when booting through other macOS volume (in my case I have a Mojave). It will fail compatibility verification. Also, can't change nvram by Terminal because of SIP, have to turn it off or (probably easier) by Recovery Partition.

EDIT: Monkey reminds that there is also the option of Internet Recovery by keys command+option+R

You might help this issue by checking my information in english since I use the portuguese version.

**Comment by Monkiey** [comment]
You have a prohibited symbol all you have to do is if you have the installer USB still boot back in to press opinion on boot and select instead of install macs os big sur select the other option efi boot press and your mac should boot when you reboot.

**Comment by gustavopi** [comment]
> You have a prohibited symbol all you have to do is if you have the installer USB still boot back in to press opinion on boot and select instead of install macs os big sur select the other option efi boot press and your mac should boot when you reboot. If you don't have the stick anymore then you have to boot into the internet recovery by pressing cmd+option+r then type in terminal under utilities this
> nvram boot-args="-no_compat_check"
> (Only Macs that need Patched Kexts) nvram csr-active-config=%7f%08%00%00
> reboot
> 
> refer to the same issue here: [#414 (comment)](https://github.com/BenSova/Patched-Sur/issues/414#issuecomment-800760688)
I have the usb stick. I tried and  it won't boot by the same reason. You can select it but it will show prohibited symbol either. It won't boot any Big Sur anywhere because the way boot is configured.
As I have an old Mac Mini that boots in a 32 bit EFI to a 64 bit OS because of a customized boot, I think maybe something like this can be done with this one - to avoid a known problem.
But your tip of Internet booting is useful if the Recovery Partition fails, thanks.

**Comment by BenSova** [comment]
Not an issue. Kind of how it works. It'll be "resolved" in the next version.
