### ISSUE TITLE
Connecting to iPhone Hotspots Unstable/Faulty

### ISSUE THREAD

**Issue by jackgraddon** [BenSova/Patched-Sur#468]
**Bug Description**
From the WiFi dropdown in the menu bar or from system preferences, you cannot join mobile/iPhone hotspots. The option is there to connect, however when you click on the option, it either does one of three things:

1. "Attempts" to connect indefinitely.
![Screen Shot 2021-04-20 at 5 09 37 PM](https://user-images.githubusercontent.com/61634132/115491160-313ee200-a1fb-11eb-9c2a-eb00cca3379c.png)
2. Doesn't connect at all (instantly drops connection)
3. Displays a message saying that it failed to activate the hotspot (commonly only when hotspot is activated first on the iPhone you are connecting to, even if it has other active connections running).
![Screen Shot 2021-04-20 at 5 13 56 PM](https://user-images.githubusercontent.com/61634132/115491493-ccd05280-a1fb-11eb-974e-1e8f0808cb53.png)

Recently it has connected a few times, but it is a toss up if it works or doesn't. I have notices that if the network is showed as another wifi network in system preferences, it has a higher chance of connecting compared to when it is displayed at the top of the list in the 'family hotspot' section.

**To Reproduce**
1. Click on the wifi icon in the menu bar...
![Screen Shot 2021-04-20 at 5 15 02 PM](https://user-images.githubusercontent.com/61634132/115491596-f2f5f280-a1fb-11eb-8361-04e85c514bca.png)
... or through system preferences.
![Screen Shot 2021-04-20 at 5 25 05 PM](https://user-images.githubusercontent.com/61634132/115492405-76641380-a1fd-11eb-90e1-1872e70c7063.png)
2. Click on your phone's hotspot.
![Screen Shot 2021-04-20 at 5 15 30 PM](https://user-images.githubusercontent.com/61634132/115491630-030dd200-a1fc-11eb-8102-78fa920db5d6.png)
3. See one of the three errors. *(listed above)*

**Expected behavior**
I would expect it to connect and display a connected status like the following:
![Screen Shot 2021-04-20 at 5 17 36 PM](https://user-images.githubusercontent.com/61634132/115491862-74e61b80-a1fc-11eb-8f2a-683531c0d35b.png)
![Screen Shot 2021-04-20 at 5 19 03 PM](https://user-images.githubusercontent.com/61634132/115491892-82030a80-a1fc-11eb-858d-02f82217683d.png)

**Hardware and Software Information:**
 - Running: *macOS Big Sur 11.2.3 (20D91)*
 - Mac Model: *13" 2012 Unibody MacBook Pro (9,2)*
 - Patcher Version: *Latest v0.1.2*
![Screen Shot 2021-04-20 at 5 19 54 PM](https://user-images.githubusercontent.com/61634132/115491978-a0690600-a1fc-11eb-93e3-2ebf711f23b2.png)

**Comment by BenSova** [comment]
This is a known bug and duplicate issue.

See this for possible solutions: https://bensova.gitbook.io/big-sur/possible-fixes/personal-hotspot
