### ISSUE TITLE
Mac mini 2012 - Big Sur 11.2.3 - hangs on Apple logo

### ISSUE THREAD

**Issue by Ritchie333** [BenSova/Patched-Sur#469]
**Describe the bug**
Patched-Sur with macOS Big Sur 11.2.3 on a 2012 Mac mini results in a booted kernel but display hangs on Apple logo.

**To Reproduce**
1. Ensure system is running latest Catalina with all updates
2. Run patched-sur and install Big Sur on a USB drive
3. Boot from the USB drive, and select "Install macOS" from the recovery options
4. Wait for installation to complete

**Expected behavior**
The login window should appear.

**Screenshots**
Not possible

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
 - Upgrading to: Big Sur v11.2.3
 - Mac Model: Mac mini 6,1 (late 2012), Core i5 2GHz, 16GB RAM, 500GB SSD + 1TB HDD. Dual 1080p monitors. Firewire connected to Focusrite Saffire Pro audio interface.
 - Version 0.12 beta

**Additional context**
The system starts up correctly and loads the kernel, and gets as far as loading Quartz, then briefly displays a grey screen, then gets stuck at the Apple logo with the progress bar with a small amount filled in. Waited 15 minutes with no change. Booting in verbose mode shows the kernel and filesystems can be found, otherwise is the same. Attempting to boot in Safe Mode displayed a prohibited sign. However, the kernel appears to be loaded correctly, as the machine can be pinged over the network successfully.

Note : I used a USB disk generated from Patched-sur running on a 13" 2012 MacBook Pro. Is an installer specific to the model of Mac it is run on?

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> Patched-Sur with macOS Big Sur 11.2.3 on a 2012 Mac mini results in a booted kernel but display hangs on Apple logo.
> 
> **To Reproduce**
> 
> 1. Ensure system is running latest Catalina with all updates
> 2. Run patched-sur and install Big Sur on a USB drive
> 3. Boot from the USB drive, and select "Install macOS" from the recovery options
> 4. Wait for installation to complete
> 
> **Expected behavior**
> The login window should appear.
> 
> **Screenshots**
> Not possible
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to: Big Sur v11.2.3
> * Mac Model: Mac mini 6,1 (late 2012), Core i5 2GHz, 16GB RAM, 500GB SSD + 1TB HDD. Dual 1080p monitors. Firewire connected to Focusrite Saffire Pro audio interface.
> * Version 0.12 beta
> 
> **Additional context**
> The system starts up correctly and loads the kernel, and gets as far as loading Quartz, then briefly displays a grey screen, then gets stuck at the Apple logo with the progress bar with a small amount filled in. Waited 15 minutes with no change. Booting in verbose mode shows the kernel and filesystems can be found, otherwise is the same. Attempting to boot in Safe Mode displayed a prohibited sign. However, the kernel appears to be loaded correctly, as the machine can be pinged over the network successfully.
> 
> Note : I used a USB disk generated from Patched-sur running on a 13" 2012 MacBook Pro. Is an installer specific to the model of Mac it is run on?

Do you boot the Mac selecting EFI boot after the usb creating files finished?

**Comment by Ritchie333** [comment]
Yes, I selected EFI Boot (per the instructions). This automatically turned the Mac mini off. I hit the power button, went back into the boot selector, then selected Install MacOS (in green).

**Comment by ozziepadilla** [comment]
> Yes, I selected EFI Boot (per the instructions). This automatically turned the Mac mini off. I hit the power button, went back into the boot selector, then selected Install MacOS (in green).

Ok that’s normal, it takes time when you see the Apple logo let it go it will finish

**Comment by Ritchie333** [comment]
Okay, I'm going to reorganise my hardware a bit so I've got a spare SSD to test installs, then I'll give it another go.

**Comment by ozziepadilla** [comment]
> Okay, I'm going to reorganise my hardware a bit so I've got a spare SSD to test installs, then I'll give it another go. I use this Mac mini daily so knocking out 3-4 hours to restore from Time Machine isn't really practical. (In the long term I'll get an M1 Mac mini when this bug is fixed - https://discussions.apple.com/thread/252131665)

Suggestion don’t contact Apple by phone support  since our Mac aren’t compatible with macOS Big Sur they won’t help it , don’t worry the installing requires patience

**Comment by Ritchie333** [comment]
Repeated the install today, came back 80 minutes later to find the login prompt, and everything seems to be in order, so I'll close this.

**Comment by Ritchie333** [comment]
Not a bug, user error.

**Comment by ozziepadilla** [comment]
> Repeated the install today, came back 80 minutes later to find the login prompt, and everything seems to be in order, so I'll close this.

Great I told you patience is the key 🔑
