### ISSUE TITLE
future updates for macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by paddyj1993** [BenSova/Patched-Sur#47]
Hi there

Thank you so much so for this, worked really smoothly for my mid-2012 Macbook Air 8 GB 1600 MHz DDR3 RAM 1.7 GHz Dual-Core Intel Core i5 Processor. I'm just wondering how to go about getting future Big Sur updates for security/new features/etc. I downloaded the release installer. The Patched Sur software has the update macOS button though mentions updates are only available on the post install Patched Sur. Any help would be really appreciate, thanks again :D

**Comment by BenSova** [comment]
That means you will be able to update with the post install app (the one used for patching kexts) soon. It will be mostly the same process just, with less (to no) prompts. 
Right now, you'll have to use the pre-install app for updating macOS, just like you did to go from Catalina to Big Sur.

**Comment by paddyj1993** [comment]
thank you so much :)
