### ISSUE TITLE
Error when trying to install Kexts with the new version 0.2.0 (Patch)

### ISSUE THREAD

**Issue by real1008** [BenSova/Patched-Sur#476]
**Describe the bug**
When installing Ktexts I get the message: Error 1x1
Message: "sudo: /volume/install: command not found"
Output: " "

(Same message after trying a couple of times)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur Patch 0.2.0
 - Mac Model: 13" 2013 early MacBook Pro

It is mentionned "If you need to, you can unpatch the texts then repatch them which might solve a problem. "
How to unpatch ?

Thank you for your help! ( real.croteau@gmail.com )

**Comment by BenSova** [comment]
This will be fixed with v0.2.1. For right now, you can do one of two things:

- Unplug your USB drive and try patching the kexts.
- Boot into the USB drive and patch the kexts from there (assuming you made it with v0.2.0)

**Comment by real1008** [comment]
Thank you Ben for The fast reply. I do not have any idea how to do that. Which one is the easiest and how I can do that. Thanks again!

Note: see the attachment for the original error message.

Réal

**Comment by real1008** [comment]
I tried the first one, unplugging the USB drive (named «  Install macOS Big Sur ») and then run again  «  patch the Ktexts » but I got a worse error message. See the attachment.

By the way, Click to Copy does not seem to work also.

Réal

**Comment by BenSova** [comment]
GitHub doesn't work with mail attachments, so you'll have to put the image here. 

However, I think I know what error you're talking about, so try my second suggestion:

> Boot into the USB drive and patch the kexts from there (assuming you made it with v0.2.0)

**Comment by real1008** [comment]
Ben, when I go to choose a starter disk in my preference system, I do not see the USB drive named «  Install macOS Big Sur ». So I cannot boot from the USB drive… and any way I do not have any idea what and how to patch the kexts from there… More help is required.

Réal

**Comment by ozziepadilla** [comment]
> Ben, when I go to choose a starter disk in my preference system, I do not see the USB drive named « Install macOS Big Sur ». So I cannot boot from the USB drive… and any way I do not have any idea what and how to patch the kexts from there… More help is required. Réal
> […](#)

I guess you must hold down option key to boot into the usb

**Comment by BenSova** [comment]
System Preferences Startup Disk selection does not allow for USB drives, so yeah you have to boot with option.

**Comment by ozziepadilla** [comment]
> System Preferences Startup Disk selection does not allow for USB drives, so yeah you have to boot with option.

That’s right
