### ISSUE TITLE
error 1x1 "password"

### ISSUE THREAD

**Issue by trestaen** [BenSova/Patched-Sur#48]
hello! this message shows up when patching to kexts on my macbook pro mid-2012. how do i fix this? thanks a lot! 

![image](https://user-images.githubusercontent.com/74523065/99211902-71410980-2804-11eb-94aa-98bf58d691c0.jpg)

**Comment by BenSova** [comment]
1. The error is not password, that's sudo making a mess.
2. Try rebooting into EFI Boot
3. If that doesn't work, boot into Install macOS Big Sur, open Utilities (in the menu bar) -> Terminal then type in `csrutil disable` and press enter then try again.
