### ISSUE TITLE
Error 1x5 when trying to upgrade to 11.3 from 11.2.3

### ISSUE THREAD

**Issue by Tiger-AC** [BenSova/Patched-Sur#485]
**Describe the bug**
Please see the screenshot. And it won't quit by pressing "Ctrl-C". Furthermore, all the subsequent reopen attempts of launching the "Patched Sur" app always cause "unexpected quit" window pop up.

**To Reproduce**
Open "Patched Sur" app and click <Run Updates>.

**Screenshots**
![Error 1x5 Upgrade to 11.3 with Patched Sur v 0.2.1](https://user-images.githubusercontent.com/82495745/116150395-a98b3300-a726-11eb-801a-d51d5222a380.png)

**Desktop**
 - Upgrading from: [Big Sur 11.2.3]
- Upgrading to: [Big Sur 11.3]
 - Mac Model: [iMac 27" Late 2012]
 - Version [v 0.2.1]

**Comment by Tiger-AC** [comment]
After getting nowhere, I restarted the iMac and launched the Patched-Sur app again. I then changed from "Beta" to "Release" (for letting the app automatically picked 11.3, the latest for now). This time around it popped up a window asking to disable "Library Validation" (or Verification). Once the iMac restarted again, the update seems working now: Still in progress...
Also there is a LONG black screen period before showing the white Apple logo and progress bar, which freaked me out.

**Comment by ozziepadilla** [comment]
> After getting nowhere, I restarted the iMac and launched the Patched-Sur app again. I then changed from "Beta" to "Release" for letting the app automatically selecting 11.3, the latest for now. This time around it popped up a window asking to disable "Library Validation" (or Verification). Once the iMac restarted again, the update seems working now: Still in progress... [edited]: Successful !
> Also there is a LONG black screen period before showing the white Apple logo and progress bar, which freaked me out.
> All good now, despite some bugs.
> Well done to BenSova for your good work, much appreciated🙏


You did it right so I read that a lot of people trying to install macOS Big Sur beta 11.3 which is not good benSova remove it from the catalogue

**Comment by Tiger-AC** [comment]
> You did it right so I read that a lot of people trying to install macOS Big Sur beta 11.3 which is not good benSova remove it from the catalogue
Sorry for not make it clear: Both were 11.3 official release. The only difference is that the 1st attempt was via Beta option and the 2nd one was via Release option instead, which picked the official release automatically.

**Comment by BenSova** [comment]
What's your SIP status?

**Comment by Tiger-AC** [comment]
> What's your SIP status?

disabled

**Comment by Ritchie333** [comment]
Also get this error. Mac mini 2012, Core I5, 16GB RAM, 500GB SSD, SIP is disabled.

Error 1x13
Message: "Error: Prepare recovery failed with error: Error Domain=com.apple.OSInstallerSetup.error Code=303 "Installation of macOS could not continue." UserInfo={NSLocalizedDescription=Installation of macOS could not continue., NSLocalizedRecoverySuggestion=Installation requires downloading important content. That content can't be downloaded at this time. Try again later.}"
Output: "Fetching OS Recovery info from server..."

**Comment by BenSova** [comment]
Looks like this is solved.
