### ISSUE TITLE
Failed to Update Patched Sur (Error 1x1)

### ISSUE THREAD

**Issue by hoodooyoudo** [BenSova/Patched-Sur#486]
**Describe the bug**

Looks to be an error updating the patcher app itself - possibly I could just download a new copy?

Error 1x1
Message: "rm: /Applications/Patched Sur.app/Contents/CodeResources: Permission denied
rm: /Applications/Patched Sur.app/Contents/_CodeSignature/CodeResources: Permission denied
rm: /Applications/Patched Sur.app/Contents/_CodeSignature: Permission denied
rm: /Applications/Patched Sur.app/Contents/MacOS/Patched Sur: Permission denied
rm: /Applications/Patched Sur.app/Contents/MacOS: Permission denied
rm: /Applications/Patched Sur.app/Contents/Resources/AppIcon.icns: Permission denied
rm: /Applications/Patched Sur.app/Contents/Resources/Assets.car: Permission denied
rm: /Applications/Patched Sur.app/Contents/Resources: Permission denied
rm: /Applications/Patched Sur.app/Contents/Info.plist: Permission denied
rm: /Applications/Patched Sur.app/Contents/PkgInfo: Permission denied
rm: /Applications/Patched Sur.app/Contents: Permission denied
rm: /Applications/Patched Sur.app: Directory not empty"
Output: ""

**To Reproduce**
1. Go to 'Patched Sur'
2. Click on 'Update macOS' 
3. Click on 'Download Update'

**Expected behavior**
Patch should install

**Screenshots**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/71793074/116151288-87021580-a738-11eb-81d5-54c5e65673ee.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/71793074/116151243-7a7dbd00-a738-11eb-91d1-a9b2a31dd9c8.png">

**Desktop (please complete the following information):**
 - From: Big Sur 11.2.3
 - To: Big Sur 11.3
 - Mac Model: 15" 2012 Retina MacBook Pro
 - Version v0.1.2 to v0.2.1b

**Additional context**
N/A

**Comment by hoodooyoudo** [comment]
Looks like yanking the existing Patched Sur.app and replacing with a fresh download allows me to work around the issue.

**Comment by cstormsc** [comment]
Had the same issue with the same MacBook Pro Retina 2012, also replaced the file and the installer was updated. It is taking too long to write files on the installer, though

**Comment by cstormsc** [comment]
Yes, The creation of the USB installer gave me this error: Error 1x1
Message: "cp: /Applications/Patched Sur.app/Contents/Resources/Patched Sur.app: No such file or directory"
Output: ""

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> 
> Looks to be an error updating the patcher app itself - possibly I could just download a new copy?
> 
> Error 1x1
> Message: "rm: /Applications/Patched Sur.app/Contents/CodeResources: Permission denied
> rm: /Applications/Patched Sur.app/Contents/_CodeSignature/CodeResources: Permission denied
> rm: /Applications/Patched Sur.app/Contents/_CodeSignature: Permission denied
> rm: /Applications/Patched Sur.app/Contents/MacOS/Patched Sur: Permission denied
> rm: /Applications/Patched Sur.app/Contents/MacOS: Permission denied
> rm: /Applications/Patched Sur.app/Contents/Resources/AppIcon.icns: Permission denied
> rm: /Applications/Patched Sur.app/Contents/Resources/Assets.car: Permission denied
> rm: /Applications/Patched Sur.app/Contents/Resources: Permission denied
> rm: /Applications/Patched Sur.app/Contents/Info.plist: Permission denied
> rm: /Applications/Patched Sur.app/Contents/PkgInfo: Permission denied
> rm: /Applications/Patched Sur.app/Contents: Permission denied
> rm: /Applications/Patched Sur.app: Directory not empty"
> Output: ""
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Patched Sur'
> 2. Click on 'Update macOS'
> 3. Click on 'Download Update'
> 4. See error
> 
> **Expected behavior**
> Patch should install
> 
> **Screenshots**
> <img alt="image" width="682" src="https://user-images.githubusercontent.com/71793074/116151288-87021580-a738-11eb-81d5-54c5e65673ee.png">
> 
> <img alt="image" width="327" src="https://user-images.githubusercontent.com/71793074/116151243-7a7dbd00-a738-11eb-91d1-a9b2a31dd9c8.png">
> 
> **Desktop (please complete the following information):**
> 
> * From: Big Sur 11.2.3
> * To: Big Sur 11.3
> * Mac Model: 15" 2012 Retina MacBook Pro
> * Version v0.1.2 to v0.2.1b
> 
> **Additional context**
> N/A

Are you under a user account or admin account in your Mac ? If yes with user account remember that users are restricted to do certain things

**Comment by BenSova** [comment]
This is a new one. I'll probably have to counter this with sudo, if you have a chance, you could try running the patcher with sudo (with the terminal command below) and try updating the patcher app.

`sudo /Applications/Patched\ Sur.app/Contents/MacOS/Patched\ Sur`

**Comment by hoodooyoudo** [comment]
Yep, I get that error with the USB installer as well;

<img width="653" alt="image" src="https://user-images.githubusercontent.com/71793074/116342820-5c4ab680-a837-11eb-9a10-10f5055a1cd3.png">

**Comment by hoodooyoudo** [comment]
And I'm using an admin account

**Comment by hoodooyoudo** [comment]
I think I can see the problem

from terminal I ran _sudo /Applications/Patched\ Sur.app/Contents/MacOS/Patched\ Sur_                           

which returned _sudo: /Applications/Patched Sur.app/Contents/MacOS/Patched Sur: command not found_

so, with Show package contents if I navigate to MacOS/ I can see there's only one app and it's named 'Patched Sur - For Catalina'

<img width="982" alt="image" src="https://user-images.githubusercontent.com/71793074/116343207-1e9a5d80-a838-11eb-8e9e-f3526c7053af.png">

**Comment by hoodooyoudo** [comment]
So basically.. I'm guessing that means I needed to copy over the post-install-app again 😅

I'm seeing a complaint about Library Validation now;
<img width="298" alt="image" src="https://user-images.githubusercontent.com/71793074/116346160-ca927780-a83d-11eb-8986-1f775fd5ff24.png">

if I click Continue I get;

Checking for Library Validation...
2021-04-28 16:19:41.102 defaults[42511:1715696] 
The domain/default pair of (/Library/Preferences/com.apple.security.libraryvalidation.plist, DisableLibraryValidation) does not exist
Checking for SIP...
System Integrity Protection status: disabled.
Library Validation is not set, warning user.
Correct Password

no further action .. and I'm not 100% what the next step should be

**Comment by hoodooyoudo** [comment]
would https://github.com/mologie/macos-disable-library-validation be an option perhaps?

**Comment by BenSova** [comment]
Jeez, you would not need a kernel patch for it. Just run this in Terminal:

```shell
sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool false
```

**Comment by hoodooyoudo** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/71793074/117561390-7ebbba00-b0ea-11eb-93ae-35fb48de280d.png">

success :)

**Comment by Monkiey** [comment]
You need that command to keep it off for the future

**Comment by hoodooyoudo** [comment]
> You need that command to keep it off for the future

I could re-run it next time though yeah?

**Comment by Monkiey** [comment]
Well, it's more convenient to keep it off, it will be fine a virus is a virus regardless of security protections.
