### ISSUE TITLE
Won't Connect to Hotspot or Wifi at Work

### ISSUE THREAD

**Issue by theenglishteacher** [BenSova/Patched-Sur#496]
I completed the update using the latest patcher version(v0.2.1) this morning on my Mid 2012 Macbook Pro from the previous version of Big Sur (I used the previous patcher version to update from Catalina successfully, except the Macbook would not connect to my work wifi any longer) to Big Sur 11.3. Everything worked well and seemed successful, except I cannot get the Macbook Pro to connect to the Wifi Hotspot (AT&T) my workplace gave me to use. Any suggestions are appreciated. You guys are brilliant, btw.

**Comment by silveroffspring** [comment]
Hey, 

same thing, same machine here. I had to run the post installer Patcher for Wifi ect. again and it worked well. 

I think this is no bug, just try the Kext (?) Patcher.

**Comment by BenSova** [comment]
That is a known issue that is shown by the patcher here:
![Screen Shot 2021-04-27 at 3 35 53 PM](https://user-images.githubusercontent.com/65474198/116315797-41603f80-a76e-11eb-9a9f-044b7072ed8d.png)
However, for Personal Hotspot, you can try the options given at the link below for possible fixes for personal hotspot. Maybe they work for WPAN Enterprise too, I don't know.
https://bensova.gitbook.io/big-sur/possible-fixes/personal-hotspot

**Comment by theenglishteacher** [comment]
Thanks. I’ll try running the post installer again. Is that the kexts?

**Comment by theenglishteacher** [comment]
Thank you. I’ll give those instructions a look.

**Comment by BenSova** [comment]
> Thanks. I’ll try running the post installer again. Is that the kexts?

If you already ran it and WiFi works at home, running it again shouldn't make a difference (if anything, it might make it work), but if no WiFi works at all, then yes do it again.

**Comment by theenglishteacher** [comment]
Home wifi does work.

**Comment by BenSova** [comment]
So yeah, try the solutions on the page. 
I'm going to close this issue since both personal hotspots and wpa2 enterprise are covered by their own issues.
