### ISSUE TITLE
Select A USB Volume 

### ISSUE THREAD

**Issue by joejackblack12** [BenSova/Patched-Sur#497]
Ok For some stupid reason patcher Sur is not recognizing my 64GB Flash drive! Why?? Yes it made sure to format it to MacOS Extended Journaled did it like five times and even did a repair disk and the same issue "no compatible drives were detected. Some help please Not sure whats the deal.

**Comment by BenSova** [comment]
It also says to make sure your USB has a GUID Partition Map

**Comment by joejackblack12** [comment]
Correct but there is no option to choose any partition map

**Comment by BenSova** [comment]
You have to show all devices in Disk Utility
![Screen Shot 2021-04-27 at 4 20 53 PM](https://user-images.githubusercontent.com/65474198/116319919-8b4c2400-a774-11eb-8e2e-86851ccf6b46.png)
Then if you select your drive (not it's volume), you'll be given an option for the partition map.

**Comment by joejackblack12** [comment]
See I knew it was something stupid I was missing!! Thanks I got it now.

**Comment by BenSova** [comment]
No problem!

**Comment by theenglishteacher** [comment]
I tried a couple different USB drives I already had before I found one that worked. I used the HP 32GB that I used the origin time when I used the patcher to upgrade from Catalina. It said was going to erase it, and I clicked that was fine—it worked. I don’t have a clue why the 16GB or the other 32GB USB I tried did not work.

**Comment by BenSova** [comment]
Probably because it didn't have the GUID Partition Map like I said earlier.
