### ISSUE TITLE
Error 1x6 when updating MacOs to 11.3

### ISSUE THREAD

**Issue by guilhermelhermegui** [BenSova/Patched-Sur#498]
Error 1x6
Message: "dyld: could not load inserted library '/usr/local/lib/Patched-Sur-Patches/InstallerHax/Hax6/Hax6.dylib' because image not found
"
Output: ""

This is showing right after downloading Kexts and the update, just before starting the process. How to fix?

**Comment by BenSova** [comment]
Restart. Each time you retry the update process, you'll have to restart otherwise you'll probably get that error.

**Comment by 3isenHeiM** [comment]
Yup, got the same error and indeed a reboot solved it !

**Comment by guilhermelhermegui** [comment]
Thanks! Yes, a reboot solved it.
