### ISSUE TITLE
Error Creating USB Installer (Error 1x1) non-Retina MPB mid 2012 update to MacOS 11.3

### ISSUE THREAD

**Issue by smsoylemez90** [BenSova/Patched-Sur#499]
**Describe the bug**
Gives out this error:
Error 1x1
Message: ""
Output: "installer: Package name is InstallAssistant
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An unexpected error occurred while moving files to the final destination.)"

**To Reproduce**
Selecting an USB Volume and then punching in the password results with the error upon progress.

**Expected behavior**
USB is transformed into the installer successfully.

**Desktop (please complete the following information):**
 - Upgrading from: MacOS 11.2.3
- Upgrading to: Big Sur v11.3
 - Mac Model: 13" mid-2012 MacBook Pro, non-Retina
 - Version: v0.2.1

**Comment by BenSova** [comment]
Try the patcher again

**Comment by MarkDaleman** [comment]
I've also got the same issue, i've tried it with the latest version of the patcher.

However, the messages in the error dialog are sometimes different:

![afbeelding](https://user-images.githubusercontent.com/2061273/121429598-6358fe80-c977-11eb-8dec-54842b41c0ad.png)

And

![afbeelding](https://user-images.githubusercontent.com/2061273/121429726-82f02700-c977-11eb-92fc-9174b6a44343.png)


My device info:

- Trying installer on Catalina 10.15.7
- Patch sur version 0.2.1 (96)
- Mac Model: 13' late 2012 macbook pro, retina.

**Comment by smsoylemez90** [comment]
Updated to 11.3 and then 11.4 Release update path without problems after a while.
