### ISSUE TITLE
GarageBand/Logic Pro X Midi devices are not working.

### ISSUE THREAD

**Issue by Emperor-Epitaph** [BenSova/Patched-Sur#50]
Recently there is a bug with Big Sur where Midi Devices were unable to be recognized by  garage band/Logic Pro X. I double checked at first whether if it was a patcher problem or it was my device. I connected the device to my mac book which was running Catalina and it was working just fine.

**Comment by BenSova** [comment]
Maybe this is an issue with Logic Pro? What happens if you try again with the latest version of Big Sur and Logic Pro X?
