### ISSUE TITLE
Error 1x1 Patched Sur.app not found

### ISSUE THREAD

**Issue by rirri93** [BenSova/Patched-Sur#500]
When I try to create the pendrive for installation, I got this error: 
```
Error 1x1
Message: "cp: /Applications/Patched Sur.app/Contents/Resources/Patched Sur.app: No such file or directory"
Output: ""
```
This comes after the copy of all files in the pendrive, and precisely after the program unmounts the pendrive. 

**To Reproduce**
1. Extract Patched Sur to Application folder and launch it
2. Wait the download of BigSur Intaller
3. Wait 100% of copying files in pendrive

**Desktop:**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3
 - Mac Model: 15" 2012 MacBook Pro 2.6GHz Intel I7
 - Version v0.2.1

**Comment by itphonim** [comment]
Hi Rirri93, 
I'm having the same issue, did you manage to get over it.
It seems like Patched Sur.app is getting deleted during patching process,
but I don't know how...
Thank in advance.

**Comment by BenSova** [comment]
This bug was fixed already

**Comment by BenSova** [comment]
Make sure you're using the latest version

**Comment by itphonim** [comment]
Strange, thought I managed it finally, before first launch, I had to rename Patched sur.app to Patched sur v1.app for instance…
Without this, during process the app disappear…
