### ISSUE TITLE
patch kexts does not work on iMac (27-inch, Late 2012)

### ISSUE THREAD

**Issue by motogon** [BenSova/Patched-Sur#501]
**Describe the bug**
patch kexts does not work on iMac (27-inch, Late 2012), After starting there are no errors, a window appears prompting restart (screenshot). When you click on the restart button. Nothing happens. (reboot does not start)

After rebooting with your hands. WIFI is inactive

ps there were no problems with wifi in the previous version  Big Sur 11.2.3

**Screenshots**

![изображение](https://user-images.githubusercontent.com/12997195/116381915-04538600-a81e-11eb-9316-c4f81e4390bd.png)

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.2.3
- Upgrading to: Big Sur v11.3 
 - Mac Model: iMac (27-inch, Late 2012)

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> patch kexts does not work on iMac (27-inch, Late 2012), After starting there are no errors, a window appears prompting restart (screenshot). When you click on the restart button. Nothing happens. (reboot does not start)
> 
> After rebooting with your hands. WIFI is inactive
> 
> ps there were no problems with wifi in the previous version Big Sur 11.2.3
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> ![изображение](https://user-images.githubusercontent.com/12997195/116381915-04538600-a81e-11eb-9316-c4f81e4390bd.png)
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: Big Sur 11.2.3
> * Upgrading to: Big Sur v11.3
> * Mac Model: iMac (27-inch, Late 2012)

You need to reboot your iMac , don’t force to quit that window just reboot it

**Comment by Sven23** [comment]
Exactly I was clicking on "Restart to Finished" nothing was happening. But after reboot by your self in macOS then was working everything. And the wifi also. Don't worry just do it.

**Comment by gregj66** [comment]
I have the same machine as you @motogon and upgraded from 11.2.3. The button itself didn't work, but when I restarted the machine from the System Menu, everything is working fine.

**Comment by BenSova** [comment]
Yeah, I already know about the button not working, it'll be fixed in the next version. Just reboot yourself.

**Comment by motogon** [comment]
Just reboot didn’t help, tried it 2 times. But after turning off and on, wifi worked.

Thank you
