### ISSUE TITLE
Error also when trying to install Kexts with the new version 0.2.1

### ISSUE THREAD

**Issue by real1008** [BenSova/Patched-Sur#502]
**Describe the bug**
Ktexts does not work even after v0.2.1 implemented 
![Message Patch Ktexts](https://user-images.githubusercontent.com/80593014/116386197-8b393c00-a7e7-11eb-8b0f-afe4b59069e5.png)

![Message Unpatch Ktxts](https://user-images.githubusercontent.com/80593014/116386274-a1df9300-a7e7-11eb-8d38-e0450867c81b.png)

![Patch Sur 2012 ?](https://user-images.githubusercontent.com/80593014/116386343-ae63eb80-a7e7-11eb-9058-759bb00f691b.png)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur Patch 0.2.1
 - Mac Model: 13" **2013** Early MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**
Thank you Ben for the quick update with release v.0.2.1 Beta but unfortunatly no luck in that case on my side… I thought it was ok in pm but it was not the case...

With this new release, for both Patch and Unpatch Kexts (interesting improvement) I got the same long message (2 different pictures with the same message that I can sent to you as attachments if you can give me a valid email address to send it to you but essentially saying in red:
===========================
Error 1x1
Message: « mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
Failed to mount underlying volume. » 
Output: « welcome to Patchkexts.sh (for Patch Sur)

Checking environnent…
===========================   

An other point worth of mention (I have also a picture of it) it is said Patched Sur v0.2.1 that it is for a MacBook Pro (13-inches, Mid 2012) but mine is Early 2013.

For now in order to function minimally, I run with Patched-Sur Release v0.2.1 without the Ktexts waiting for some additional instructions from you.

Thanks for your precious help!

**Comment by mxmlnbln** [comment]
Restarting may solve the issue. As mentioned in #42

**Comment by 15wat** [comment]
Have you tried running the post install app to patch the kexts from the usb stick?

**Comment by BenSova** [comment]
I suggest doing what @15wat said. The "Resource Busy" error pretty much can't happen while booted into the installer usb. If you don't have an installer usb, wait 30 minutes, do a reboot, then wait 30 minutes again.

**Comment by real1008** [comment]
Thank you Ben, @15wat and mxmlnbln. Everything seems ok after a restart from the USB Patch. I cross my fingers until tonight hoping no other surprises! 😏 🌷

Note: can we update to the version OS 15.3 now ? See the attachment. I just can see the first 2 lines
![macOS Big Sur 11 3](https://user-images.githubusercontent.com/80593014/116468401-cf0b6000-a83e-11eb-8d00-3b626049e297.png)

**Comment by real1008** [comment]
See my note above. "Note: can we update to the version OS 15.3 now ? See the attachment. I just can only see the first 2 lines"...

**Comment by BenSova** [comment]
Yeah, you can update. I'll check out the bug and hopefully fix it being cut off in the next version.
