### ISSUE TITLE
ERROR 1x250

### ISSUE THREAD

**Issue by ariimac** [BenSova/Patched-Sur#504]
**Describe the bug**
I can't download patched sur on my external drive. I keep getting error 1x250 when creating USB installer. Please help!

**To Reproduce**
1. Select a USB Volume
2. Click on Continue
3. Request Root Permission - Enter Password
4. Creating USB Installer
5. ERROR 1x250

**Expected behavior**
smoothly install patched sur on USB

**Screenshots**

![Screen Shot 2021-04-28 at 12 46 51 PM](https://user-images.githubusercontent.com/83363931/116441838-d111f680-a81f-11eb-80da-7f7b1734397f.png)

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by ariimac** [comment]
by the way I have an iMac 27" Late 2013

**Comment by Finder352** [comment]
Please fill out the "To reproduce" section so that the people who are trying to assist you can attempt to replicate your issue.

**Comment by ariimac** [comment]
> Please fill out the "To reproduce" section so that the people who are trying to assist you can attempt to replicate your issue.

Just filled it out, thanks!

**Comment by Finder352** [comment]
Don't know if this would be a culprit but, are you running the patcher from an admin account or a standard account?

**Comment by ariimac** [comment]
> Don't know if this would be a culprit but, are you running the patcher from an admin account or a standard account?

I'm running the patcher from the Admin account. It was the only way to get past the 'Request Root Permission' part. But this error still pops up. I even ordered a new USB 3.0 drive thinking my other drive was the problem and I get the same error. Thanks for your help I really appreciate it!

**Comment by Monkiey** [comment]
![Screen Shot 2021-04-28 at 12 20 55 PM](https://user-images.githubusercontent.com/28370827/116460704-306e0780-a81c-11eb-9372-1e6b7859ec85.png)
Do You have full disk access enabled, do in system preferences under security and privacy and there is a section called full-disk access.

**Comment by ariimac** [comment]
It worked!! Thank you so much!!

**Comment by Monkiey** [comment]
> It worked!! Thank you so much!!
> […](#)
> Sent from my iPhone
> On Apr 28, 2021, at 3:22 PM, Monkiey ***@***.***> wrote: ﻿ Do You have full disk access enabled, do in system preferences under security and privacy and there is a section called full-disk access. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You are welcome, glad to help
