### ISSUE TITLE
Admin password with special character not work

### ISSUE THREAD

**Issue by Sven23** [BenSova/Patched-Sur#505]
**Describe the bug**
If I you use  example to install kext patching then window popup and ask for the admin password. I type my password with special character like ! and $ but the password not accepting and ask again for the password.

My work around for this Problem is to change my password in my macOS account to a simple password like test123 after that work everything. Why not work with a safety password?

**To Reproduce**
1. Go to 'Patch Kexts'
2. Click on 'Start Patching Kexts'
3. Window Popup for User Name and Password

**Expected behavior**
After filling the fields the window will popup again. I can it repeat like I want and never will be successful. This Problem was with the older Version in Patcher Sur also happening.

**Desktop (please complete the following information):**
 - Upgrading from: [Big Sur v11.2.1]
 - Upgrading to: [Big Sur v11.3]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [v0.2.1 (96)]

**Comment by BenSova** [comment]
This is a duplicate issue. It'll probably be resolved in the next version.
