### ISSUE TITLE
Too laggy on MacBook Pro 8.2

### ISSUE THREAD

**Issue by Doc-gc** [BenSova/Patched-Sur#51]
As said, too laggy on MacBook Pro 8.2, is there something I can do to speed it up? Already disabled animations.

**Comment by kxxc** [comment]
Hi Ben!

is it possible bring the animations disable function to macos 10.15?

**Comment by BenSova** [comment]
> As said, too laggy on MacBook Pro 8.2, is there something I can do to speed it up? Already disabled animations.

As I've said several time, no graphics acceleration in Big Sur is probably a huge reason not to upgrade. There's no real "solution" other than deleting programs you don't need, and even that might not work.

> Hi Ben! Disable Animation Button 10.15 (I'm typing this on mobile so I can't get the full quote)

I can probably throw the button somewhere in the preinstall app. I can see where it might be useful to use _before_ you install Big Sur so the app isn't really slow to launch and what not.

**Comment by BenSova** [comment]
I'm closing this because it's a question, not a bug.
