### ISSUE TITLE
No entry sign, when installing the os 

### ISSUE THREAD

**Issue by Altrai18** [BenSova/Patched-Sur#512]
No entry sign on startup. This is happening when I'm installing the os. It doesn't want to go past the Apple logo and into recovery. I followed every step and formatted the drive correctly, I even changed drives because I thought that could be a issue. 
Macbook mid 2009 
525Gb Ssd 
4Gb ram 

Upgrading from dosdude Catalina patch 

![IMG_20210429_111719](https://user-images.githubusercontent.com/83384680/116529041-c9645780-a8dc-11eb-86ee-81c8b458a5ba.jpg)

**Comment by BenSova** [comment]
Well, that's probably because I don't support your Mac because it would run like a sloth on Big Sur, or you didn't boot into the EFI Boot.
