### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by Antixxxf** [BenSova/Patched-Sur#513]
Issue After Updating from Mac OS Catalina On my MacBook Pro mid 2012 13inch
The keyboard Caps light no longer works I reverted back to the genuine Catalina and the light came back on fine Just docent work when on Big sur patcher maybe its a bug or a Kext is required for it?
I was on Big sur 1.3 Release

**Comment by BenSova** [comment]
It works for me, same Mac. 

To be honest, it's not a priority and something I've ever actually heard about, so I'm going to close this issue. Shift still works, so you can type capitals (like you're supposed to, I don't really understand why caps lock even exists).
