### ISSUE TITLE
MacBook Pro 15 2009 

### ISSUE THREAD

**Issue by Arnold1967-star** [BenSova/Patched-Sur#514]
Installing macOS Big Sur 11.3 with the latest version of your Patcher on an MacBook Pro 15 from 2009 fails already during booting into the USB stick.

What I noticed from many successful and unsuccessful installations: MacBooks from 2011 and 2012 are working properly. MacBooks from 2009 and 2010 are failing most times.

The difference I noticed is linked to the processor generation Intel Core i3, i5 and i7 work fine, Intel Core 2 Duo are mostly failing. Maybe that is not even linked to the CPUs itself but to the fact, if the Mac supports APFS or can be patech witch Dosdudes APFS Patcher http://dosdude1.com/apps/ (works on all controllers except the ones from Nvidia). 

If no APFS Patch is possible currently the boot process is failing. Maybe you can integrate an APFS check or patch...

 - Upgrading from: Catalina v10.15.7 with Dosdude Patcher
- Upgrading to: Big Sur v11.3
 - Mac Model: 15" 2009 MacBook Pro
 - Version v0.2.1

**Comment by BenSova** [comment]
Because of how slow they are, I currently do not support them in my patcher, and honestly I'm not worried about this issue until late into the development of v0.3.0 (which will significantly speed up non-metal Macs, so then I'll fix it).
