### ISSUE TITLE
Error updating to MacOS 11.3

### ISSUE THREAD

**Issue by smsoylemez90** [BenSova/Patched-Sur#516]
**Describe the bug**
Error 1x23
Message: "Installation cannot proceed because the installer is damaged."
Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.
Preparing to run macOS Installer...

Preparing: 0.0%            
Preparing: 0.1%            
Preparing: 0.2%            
Preparing: 0.3%            
Preparing: 0.4%            
Preparing: 0.5%            "

**To Reproduce**
Update on Release 11.3 fails with above error. Re-downloading update file gives the same error, so this happens no matter what.

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.2.3
- Upgrading to: Big Sur v11.3
 - Mac Model:  13" mid-2012 MacBook Pro Non-Retina
 - Version v0.2.1

**Comment by rmcbc** [comment]
Same problem here.
Upgrading from: Big Sur 11.2
Upgrading to: Big Sur v11.3.1
Mac Model: MacMini 2012 server
Version v0.2.1

**Comment by rmcbc** [comment]
Dome times the error changes to:

Error 1x23
Message: "An error occurred loading the update."
Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.
Preparing to run macOS Installer...

Preparing: 0.0%            
Preparing: 0.1%            
Preparing: 0.2%            
Preparing: 0.3%            
Preparing: 0.4%            
Preparing: 2.2%            
Preparing: 2.5%            
Preparing: 2.7%            
Preparing: 2.9%            
Preparing: 3.2%            
Preparing: 3.4%            
Preparing: 3.6%            
Preparing: 3.8%            
Preparing: 4.1%            
Preparing: 4.3%            
Preparing: 4.5%            
Preparing: 4.8%            "

**Comment by Monkiey** [comment]
> Some times the error alternates with:
> 
> Error 1x23
> Message: "An error occurred loading the update."
> Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
> If you do not agree, press CTRL-C and cancel this process immediately.
> Preparing to run macOS Installer...
> 
> Preparing: 0.0%
> Preparing: 0.1%
> Preparing: 0.2%
> Preparing: 0.3%
> Preparing: 0.4%
> Preparing: 2.2%
> Preparing: 2.5%
> Preparing: 2.7%
> Preparing: 2.9%
> Preparing: 3.2%
> Preparing: 3.4%
> Preparing: 3.6%
> Preparing: 3.8%
> Preparing: 4.1%
> Preparing: 4.3%
> Preparing: 4.5%
> Preparing: 4.8% "

That looks like it's working you need to be patient and let it go to around 25% to 30)% and it will restart or maybe even 100% and your mac will update.

**Comment by Monkiey** [comment]
> Some times the error alternates with:
> 
> Error 1x23
> Message: "An error occurred loading the update."
> Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
> If you do not agree, press CTRL-C and cancel this process immediately.
> Preparing to run macOS Installer...
> 
> Preparing: 0.0%
> Preparing: 0.1%
> Preparing: 0.2%
> Preparing: 0.3%
> Preparing: 0.4%
> Preparing: 2.2%
> Preparing: 2.5%
> Preparing: 2.7%
> Preparing: 2.9%
> Preparing: 3.2%
> Preparing: 3.4%
> Preparing: 3.6%
> Preparing: 3.8%
> Preparing: 4.1%
> Preparing: 4.3%
> Preparing: 4.5%
> Preparing: 4.8% "

That is strange, try restating your computer

**Comment by rmcbc** [comment]
> > Some times the error alternates with:
> > Error 1x23
> > Message: "An error occurred loading the update."
> > Output: "By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
> > If you do not agree, press CTRL-C and cancel this process immediately.
> > Preparing to run macOS Installer...
> > Preparing: 0.0%
> > Preparing: 0.1%
> > Preparing: 0.2%
> > Preparing: 0.3%
> > Preparing: 0.4%
> > Preparing: 2.2%
> > Preparing: 2.5%
> > Preparing: 2.7%
> > Preparing: 2.9%
> > Preparing: 3.2%
> > Preparing: 3.4%
> > Preparing: 3.6%
> > Preparing: 3.8%
> > Preparing: 4.1%
> > Preparing: 4.3%
> > Preparing: 4.5%
> > Preparing: 4.8% "
> 
> That is strange, try restating your computer

I did several times and got the same errors.
My initial upgrade was made with micropatcher at least until 11.2, now I could not update anymore with micropatcher nor patched sur.
I also try with 11.4 beta 2 with pached sur, it passes this problem, reboots and after a while says that the installation is invalid.

**Comment by rmcbc** [comment]
Installed a new catalina on an external drive, try to upgrade it on my MacMini 2012 and always get an error that the install media is damaged.
I try Pen USB 16Gb, external USB SSD and external USB HDD, all the same.
It seems the I can't upgrade Big Sur 11.2 or Catalina to 11.3.1 nor 11.2.3. I try all versions of Patch Sur from 1.1 to 2.1.
Don't know what to do any more.

**Comment by Monkiey** [comment]
Try to download the installer package here for 11.3.1:http://swcdn.apple.com/content/downloads/16/05/071-32414-A_33YH16R8HF/28ment5qr993c0l9i1qbh4fuknli9wzglp/InstallAssistant.pkg

**Comment by rmcbc** [comment]
> Try to download the installer package here for 11.3.1:http://swcdn.apple.com/content/downloads/16/05/071-32414-A_33YH16R8HF/28ment5qr993c0l9i1qbh4fuknli9wzglp/InstallAssistant.pkg

With this goes much far in the installation process but gets to a point that gives this error "Storage system verify or repair failed. : (-69716)"

Try it with Patched Sur and Micropatcher both get the same error.

**Comment by BenSova** [comment]
Your OS is corrupt somehow then. I suggest doing a clean install.

**Comment by smsoylemez90** [comment]
I did a clean install a few days ago and updated to 11.3, however it is doing the same thing on the clean install for the update to macOS Big Sur 11.3.1

**Comment by Monkiey** [comment]
> I did a clean install a few days ago and updated to 11.3, however it is doing the same thing on the clean install for the update to macOS Big Sur 11.3.1

Then just update using the usb method that way you don't have to clean install your mac again.

**Comment by smsoylemez90** [comment]
After the clean install, subsequent x.x.1 Release updates seemed like Beta path for some reason but main 11.4 Release installed without a problem through the post install app. Closing the issue.
