### ISSUE TITLE
Parallels Desktop losing network 

### ISSUE THREAD

**Issue by kxxc** [BenSova/Patched-Sur#52]
Parallels Desktop losing network,

don't know if it's related, but I cannot connect to internet any more. 😂

**Comment by norek1234** [comment]
I've checked on mine Mac book Pro late 2012 and have no issue with network.
Are you running the latest Paralles Desktop 16? Didi you ran patch at the end of installing Big sur.
Didi you check any logs of Paralles Desktop. Maybe you should change some network/hardware settings on virutal machine.
What it spec of your mac? Don't thing @BenSova will figure anything out with details and it maybe not an issue with his work but only Paralles Desktop.

**Comment by BenSova** [comment]
Hey @kxxc since November a lot has changed, could you try Parallels again and report back? I don't think this is an issue with the patcher, maybe an issue with Big Sur.

**Comment by Kief5555** [comment]
If this is an issue, you are using a cracked version. I have provided a screenshot, I am not to take blame.
<img width="755" alt="Screen Shot 2021-03-09 at 9 26 53 AM" src="https://user-images.githubusercontent.com/67562560/110511909-990cf380-80b9-11eb-9101-02dcb490e892.png">

**Comment by Kief5555** [comment]
> I've checked on mine Mac book Pro late 2012 and have no issue with network.
> Are you running the latest Paralles Desktop 16? Didi you ran patch at the end of installing Big sur.
> Did you check any logs of Paralles Desktop. Maybe you should change some network/hardware settings on virutal machine.
> What it spec of your mac? Don't thing @BenSova will figure anything out with details and it maybe not an issue with his work but only Paralles Desktop.

This guy is using a cracked

**Comment by kxxc** [comment]
> > I've checked on mine Mac book Pro late 2012 and have no issue with network.
> > Are you running the latest Paralles Desktop 16? Didi you ran patch at the end of installing Big sur.
> > Did you check any logs of Paralles Desktop. Maybe you should change some network/hardware settings on virutal machine.
> > What it spec of your mac? Don't thing @BenSova will figure anything out with details and it maybe not an issue with his work but only Paralles Desktop.
> 
> This guy is using a cracked

your whole family using a cracked

[https://i.imgur.com/Moq8Pay.png](Permanent license)


sorry I no longer using Patched-Sur, so I cannot test it again.

**Comment by kxxc** [comment]
> > I've checked on mine Mac book Pro late 2012 and have no issue with network.
> > Are you running the latest Paralles Desktop 16? Didi you ran patch at the end of installing Big sur.
> > Did you check any logs of Paralles Desktop. Maybe you should change some network/hardware settings on virutal machine.
> > What it spec of your mac? Don't thing @BenSova will figure anything out with details and it maybe not an issue with his work but only Paralles Desktop.
> 
> This guy is using a cracked

your whole family using a cracked

<img src="https://i.imgur.com/Moq8Pay.png">


sorry I no longer using Patched-Sur, so I cannot test it again.
