### ISSUE TITLE
No mouse and keyboard are reconized 

### ISSUE THREAD

**Issue by NoelSur** [BenSova/Patched-Sur#520]
I have an Macbook Air (Late 2010) and when i boot into install mac os i cant move my mouse!!
I do ufi boot but the same problem!

**Comment by Finder352** [comment]
Hey there, we don't support the Late 2010 MacBook Air yet.  If you would like an explanation as to why you can't move your mouse, it's because it operate through a USB 1.1 interface and the Big Sur Recovery environment has no support for USB 1.1.

**Comment by NoelSur** [comment]
> Hey there, we don't support the Late 2010 MacBook Air yet. If you would like an explanation as to why you can't move your mouse, it's because it operates through a USB 1.1 interface and the Big Sur Recovery environment has no support for USB 1.1.

do i can use an another patcher i relly like to run big sur on it?

**Comment by Finder352** [comment]
You can try the OpenCore Legacy Patcher, which does have support for legacy USB 1.1 interfaces and has beta graphics acceleration drivers you can use.  I would not recommend using this MBA on Big Sur for daily use with OCLP though, but if you want to experiment and try it out, OpenCore Legacy Patcher should work fine.

OpenCore Legacy Patcher Repository: https://github.com/dortania/Opencore-Legacy-Patcher

**Comment by NoelSur** [comment]
> You can try the OpenCore Legacy Patcher, which does have support for legacy USB 1.1 interfaces and has beta graphics acceleration drivers you can use. I would not recommend using this MBA on Big Sur for daily use with OCLP though because the beta graphics acceleration drivers can be unstable and buggy, but if you want to experiment and try it out, OpenCore Legacy Patcher should work fine.
> 
> OpenCore Legacy Patcher Repository: https://github.com/dortania/Opencore-Legacy-Patcher

ok i will try thanks!
