### ISSUE TITLE
Next BigSur update ?

### ISSUE THREAD

**Issue by noelecesne** [BenSova/Patched-Sur#53]
Hello,
What about next BigSur Update 11.1 for example ? Is it safe to apply ?
Regards

**Comment by ilovesafaristand** [comment]
Wanted to know this too.
Will BigSur be updated anytime soon?
What are the instructions to upgrade to 11.1 once you are on BigSur?

_BIG thanks and shout out to @BenSova for making this easy to click app!! Kudos!! :)_

**Comment by BenSova** [comment]
Well, you'll start by noticing that the native software update tool, still does not work, so you'll have to use Patched Sur. Note that for the most part I will only recklessly let the Developer update track get the updates right away, the other two update tracks will (normally) have to wait for me to test it.

**Comment by BigMacOS** [comment]
Thanks Ben! We'll wait for the Patched Sur update for 11.1
In the meantime, setup a Paypal donation link!

**Comment by BenSova** [comment]
Sure here's the link shutupaboutthedonations.juststop
