### ISSUE TITLE
Won't restart after patch kexts

### ISSUE THREAD

**Issue by tribal666** [BenSova/Patched-Sur#532]
Hi everybody,

Sorry for my approximative English! 
Firstly I would like to thanks everybody for all the works you make. 
My Late Imac 2012 works with Big Sur...

My problem of the day is when I try to restart after patch kexts It don't want. It stay to the same windows with "Restart".
The update 11.3 correctly performed...

When I retry to patch kexts I have this issue:

"Error 1x1
Message: "mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
Failed to mount underlying volume."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /usr/local/lib/Patched-Sur-Patches
Checking WiFi patch configuration...
No WiFi option specified, so checking for 802.11ac...
No 802.11ac WiFi card detected, using WiFi patch.
Auto-detecting Mac model...
(Override with --2010, --2011, or --2012)
Detected model: iMac13,1
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Installing kexts to volume /

Verifying volume...
Volume has Big Sur build 20E232Correctly volume mount...
Volume is mounted from device  /dev/disk1s5s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1 "

If you have an idea? I'm a newbie!!! 😏

Many thks to all.

Yan

**Comment by BenSova** [comment]
Did you try restarting yourself?

**Comment by ozziepadilla** [comment]
> Hi everybody,
> 
> Sorry for my approximative English!
> Firstly I would like to thanks everybody for all the works you make.
> My Late Imac 2012 works with Big Sur...
> 
> My problem of the day is when I try to restart after patch kexts It don't want. It stay to the same windows with "Restart".
> The update 11.3 correctly performed...
> 
> When I retry to patch kexts I have this issue:
> 
> "Error 1x1
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75
> Failed to mount underlying volume."
> Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> 
> Checking environment...
> We're booted into full macOS.
> Confirming patch location...
> Patch Location: /usr/local/lib/Patched-Sur-Patches
> Checking WiFi patch configuration...
> No WiFi option specified, so checking for 802.11ac...
> No 802.11ac WiFi card detected, using WiFi patch.
> Auto-detecting Mac model...
> (Override with --2010, --2011, or --2012)
> Detected model: iMac13,1
> Checking SIP status
> Checking what volume to patch...
> Booted into full Big Sur, using main volume.
> Installing kexts to volume /
> 
> Verifying volume...
> Volume has Big Sur build 20E232Correctly volume mount...
> Volume is mounted from device /dev/disk1s5s1
> Mounted device is a snapshot.
> Attempting to mount underlying volume
> from device /dev/disk1s5 at temporary mountpoint:
> /System/Volumes/Update/mnt1 "
> 
> If you have an idea? I'm a newbie!!! 😏
> 
> Many thks to all.
> 
> Yan

First off thd Restart button didn’t work you must restart your iMac manually, second , attitude you using a user account or admin account when you run the Patchet-Sur to upgrade to macOS Big Sur ?

**Comment by tribal666** [comment]
> Did you try restarting yourself?

Yes I restarted manually. Wifi seems to be ok but "tethering" with my iPhone won't...

Many many thks.

Yan

**Comment by tribal666** [comment]
> > Hi everybody,
> > Sorry for my approximative English!
> > Firstly I would like to thanks everybody for all the works you make.
> > My Late Imac 2012 works with Big Sur...
> > My problem of the day is when I try to restart after patch kexts It don't want. It stay to the same windows with "Restart".
> > The update 11.3 correctly performed...
> > When I retry to patch kexts I have this issue:
> > "Error 1x1
> > Message: "mount_apfs: volume could not be mounted: Resource busy
> > mount: /System/Volumes/Update/mnt1 failed with 75
> > Failed to mount underlying volume."
> > Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> > Checking environment...
> > We're booted into full macOS.
> > Confirming patch location...
> > Patch Location: /usr/local/lib/Patched-Sur-Patches
> > Checking WiFi patch configuration...
> > No WiFi option specified, so checking for 802.11ac...
> > No 802.11ac WiFi card detected, using WiFi patch.
> > Auto-detecting Mac model...
> > (Override with --2010, --2011, or --2012)
> > Detected model: iMac13,1
> > Checking SIP status
> > Checking what volume to patch...
> > Booted into full Big Sur, using main volume.
> > Installing kexts to volume /
> > Verifying volume...
> > Volume has Big Sur build 20E232Correctly volume mount...
> > Volume is mounted from device /dev/disk1s5s1
> > Mounted device is a snapshot.
> > Attempting to mount underlying volume
> > from device /dev/disk1s5 at temporary mountpoint:
> > /System/Volumes/Update/mnt1 "
> > If you have an idea? I'm a newbie!!! 😏
> > Many thks to all.
> > Yan
> 
> First off thd Restart button didn’t work you must restart your iMac manually, second , attitude you using a user account or admin account when you run the Patchet-Sur to upgrade to macOS Big Sur ?

I used a admin account.

**Comment by BenSova** [comment]
> > Did you try restarting yourself?
> 
> Yes I restarted manually. Wifi seems to be ok but "tethering" with my iPhone won't...
> 
> Many many thks.
> 
> Yan

Tethering/personal hotspots don't work because of authentication problems. Hence why the patcher shows this screen:
![Screen Shot 2021-05-03 at 9 15 16 PM](https://user-images.githubusercontent.com/65474198/116957251-a925f700-ac54-11eb-90f4-b753227a987c.png)
You can, however, try a workaround to fix it. https://bensova.gitbook.io/big-sur/possible-fixes/personal-hotspot

**Comment by tribal666** [comment]
Realy, thank you so much...

I saw this but I don't understand Personal Hotspots is "tethering"! 😬
I try with "turn off bluetooth" and select wifi in preference system and the twice solutions are ok!
It's fine for me...

🙏
