### ISSUE TITLE
16gb read as 15.7

### ISSUE THREAD

**Issue by M0stu** [BenSova/Patched-Sur#533]
**Describe the bug**
i have 16gb which is read as 15.7 and it’s not allowing me to use it

**To Reproduce**

**Expected behavior*
It reads between 15~16.

**Screenshots**
![image](https://user-images.githubusercontent.com/57865081/116905147-e3849980-ac3e-11eb-8a48-393208d075de.jpg)

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7] yes
- Upgrading to: [e.g. Big Sur v11.3 Beta 1, Big Sur v11.3]
 - Mac Model: [e.g. 13" 2012 MacBook Pro Mid 2012]
 - Version [e.g. v0.2.1]

**Additional context**
Thanks for this great patch but this must be edited to be between 15.5GB ~ 16 GB

**Comment by BenSova** [comment]
I don't actually do size checks on installers (yet).

Here's more info on how to make your drive compatible: https://bensova.gitbook.io/big-sur/preinstall-catalina/select-usb-volume

**Comment by M0stu** [comment]
Thank you so much
I appreciate your help and I apologize for not understanding but it’s my
first time with MacBook pro and i felt so happy that people like you exist
so i can enjoy the last Updated while I’m unable to offer for new versions.
Thanks again ❤️😊
