### ISSUE TITLE
My computer ran the updater and stayed on 11.3 after "updating" to 11.3.1

### ISSUE THREAD

**Issue by Monkiey** [BenSova/Patched-Sur#538]
**Describe the bug**
I rand the updaer with the install pkg that I downloaded for 11.3.1 and after reboot from update, its is still on 11.3

**To Reproduce**
1. Go to Update macos
2. Click on view other versions
3. Scroll down to 'installassistant.pkg'
4.Update macos
5.Then check about this mac 

**Expected behavior**
I expected the updater to put me on 11.3.1 after updating from 11.3

**Screenshots**
![Screen Shot 2021-05-03 at 8 16 04 PM](https://user-images.githubusercontent.com/28370827/116957297-63fdc700-ac4c-11eb-803a-710d16a1e8b7.png)
**Desktop (please complete the following information):**
 - Upgrading from: 11.3 
- Upgrading to: 11.3.1
 - Mac Model: 21.5 inch Late 2013 iMac (14,1)
 - Version [0.2.1(96)]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
I responded to you on the discord, but here's what I responded with for reference or anyone else who gets this issue.
![Screen Shot 2021-05-03 at 9 30 27 PM](https://user-images.githubusercontent.com/65474198/116958156-e4292a00-ac56-11eb-8d5b-d350d3d1bcb4.png)
![Screen Shot 2021-05-03 at 9 31 39 PM](https://user-images.githubusercontent.com/65474198/116958180-f30fdc80-ac56-11eb-9423-d30765ddee02.png)
![Screen Shot 2021-05-03 at 9 31 54 PM](https://user-images.githubusercontent.com/65474198/116958197-fc994480-ac56-11eb-986a-0d618ec63d5c.png)
Basically: Just try again.

**Comment by Monkiey** [comment]
Should I close this issue or leave it up for anyone else who has this problem

**Comment by BenSova** [comment]
Close, we got it fixed and this will still index in Google either way.
