### ISSUE TITLE
Patch Kexts post install fails Late 2013 iPac 27"

### ISSUE THREAD

**Issue by felsmann** [BenSova/Patched-Sur#54]
Install went well and Mac is running fine (I have wifi and USB works) so not sure if I even need to run the kexts but I am getting this error...
![Screen Shot 2020-11-16 at 8 41 53 AM](https://user-images.githubusercontent.com/13898210/99281906-e7834300-27e7-11eb-9c8d-3e38e7536768.png)
I booted in EFI per directions and tried again with no luck

**Comment by felsmann** [comment]
> Having the same issue with my late 2013 27"
> 
> Curious if anyone has a solution.

Turns out based on others on Reddit, that we may not need it for our Model... So just ignore it...
I have been running it all day without a hiccup....

**Comment by BenSova** [comment]
Yeah, you don't need it, so I'll just close this because it's a duplicate...
