### ISSUE TITLE
Wifi pretty dodgy

### ISSUE THREAD

**Issue by yusuftor** [BenSova/Patched-Sur#545]
I've installed 11.3 on my 2012 15" MBP. I patched the kexts, but the wifi is still pretty dodgy - most of the time it won't automatically connect to my wifi. I then open up Network Preferences and sometimes my preferred wifi connection doesn't exist on the list. Other times it does exist but when I click on it it gives an error about the network not existing. I have to turn wifi off, wait a few seconds and turn it back on and give it another go. Eventually it works, but this happens everytime I close and reopen my computer. Is there anyway to improve this?

**Desktop**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3
 - Mac Model: 15" 2012 MacBook Pro
 - Version: v0.2.1

**Comment by BenSova** [comment]
Sounds like a Big Sur bug if your preferred WiFi connection isn't saved.

**Comment by yusuftor** [comment]
It’s saved as the preferred network but it just rarely connects automatically and acts like it doesn’t exist. Highly unlikely to be a big sur bug

**Comment by BenSova** [comment]
Sounds like another issue already on this repo then.
