### ISSUE TITLE
Issue Creating USB Installer when password contains $ (dollar sign)

### ISSUE THREAD

**Issue by ofSascha** [BenSova/Patched-Sur#546]
**Describe the bug**
When attempting to use Patched Sur v0.2.0 or v0.2.1 both fail without error at the part where it prompts for the password to erase the USB volume. If I run it from the terminal, when I enter the password 'Correct Password' is output, but it just reprompts for the password again, never proceeding:

Checking if the volume is synthesized
/dev/disk1 (synthesized):
Volume is synthesized, this is incompatible
Found compatible volumes.
Correct Password

**To Reproduce**
1. Ensure account password contains a dollar sign '$'
2. Open Patched Sur
3. Continue until it prompts for the password to erase the usb disk

**Expected behavior**
Should continue to create the installer after confirming the password

**Desktop (please complete the following information):**
- Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3.1
 - Mac Model: Mac Mini Server Late 2012
 - Version v0.2.1
![About_This_Mac_and_New_Issue_·_BenSova_Patched-Sur_and_Default__zsh_](https://user-images.githubusercontent.com/9116169/117209896-ff19ac80-adc4-11eb-8166-266e4acd8486.png)

**Comment by BenSova** [comment]
This is covered by another issue
