### ISSUE TITLE
Unable to automatically switch airpods pro

### ISSUE THREAD

**Issue by ctkcoding** [BenSova/Patched-Sur#549]
**Describe the bug**
Macbook pro 2012

**To Reproduce**
1. Login with same apple id on iphone and macbook
2. Connect airpods pro to iphone
3. Airpods are recognized by macbook but not connected. Starting play of media on macbook will not automatically play on airpods, and switching between devices requires selecting airpods pro in bluetooth menu

**Expected behavior**
1. Login with same apple id on iphone and macbook
2. Connect airpods pro to iphone
3. Airpods are recognized by macbook and connected. Starting play of media on macbook will automatically pause phone media and play mac media on airpods

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3.1
 - Mac Model: 15" 2012 MacBook Pro, not retina
 - Version v0.2.1

How can I take logs on my macbook to help diagnose this? The feature seems buggy even on supported macs, so I'd like to check if I am having this issue as a regular mac would or if it is related to something missing on my unsupported computer

**Comment by BenSova** [comment]
This is a problem with Big Sur. It was a buggy feature to being with and it still is.
