### ISSUE TITLE
Tried Creating Install Media 

### ISSUE THREAD

**Issue by Skinnyman180** [BenSova/Patched-Sur#56]
I have a late 2013 iMac. I was trying to create install media on external drive and a Flash Drive. I got  same error both times.

Error 1 X 1

Password:Sudo: Volumes/Patched-Sur/patch-usb.sh: Command not found

Restarted twice. Tested both drives and mac couldn't use either as install media.

**Comment by BenSova** [comment]
Did you move the app to your Applications folder and off of the DMG? Was there a link to the applications folder inside the DMG signaling that you need to move it? Did I make a mock-up image that I posted on Reddit telling people that they aren't supposed to move it to their applications folder?

If the answers are YES, NO, and YES, you may close this issue.

**Comment by Skinnyman180** [comment]
I tried moving it at first. Then deleted it and tried again. So, I am running it from the DMG.

**Comment by Skinnyman180** [comment]
I didn't see anything signaling I needed to move it. At first I thought I needed to like majority of applications. Then when I was getting same error, I deleted the app and any traces of it. Then downloaded again and ran out of dmg. Same error. Same error using Flash Drive and the external hard drive.
