### ISSUE TITLE
No option to install after second reboot

### ISSUE THREAD

**Issue by mthuc** [BenSova/Patched-Sur#568]
**Describe the bug**
After creating the installer on to my USB, I reboot and see and select EFI Boot (purple). However, after the second restart, I only have the option to select my internal drive.

**To Reproduce**
1. Create installer
2. Restart (holding option) and select EFI boot
3. Restart again (holding option)

**Expected behavior**
Should I be expecting to see the same boot options after the second reboot?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3.1
 - Mac Model: mid 2012 Retina Macbook Pro
 - Version Patched Sur 0.2.1 Beta

**Additional context**
I am using a Staples 64 GB USB if that makes any difference.

During the first reboot, I have the option to select my internal drive, Install macOS, and EFI boot.

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> After creating the installer on to my USB, I reboot and see and select EFI Boot (purple). However, after the second restart, I only have the option to select my internal drive.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create installer
> 2. Restart (holding option) and select EFI boot
> 3. Restart again (holding option)
> 
> **Expected behavior**
> Should I be expecting to see the same boot options after the second reboot?
> 
> **Screenshots**
> N/A
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to: Big Sur v11.3.1
> * Mac Model: mid 2012 Retina Macbook Pro
> * Version Patched Sur 0.2.1 Beta
> 
> **Additional context**
> I am using a Staples 64 GB USB if that makes any difference.
> 
> During the first reboot, I have the option to select my internal drive, Install macOS, and EFI boot.

You must hold down option in the second time too , did you did it?

**Comment by mthuc** [comment]
Yes, I held Option down the second time. If I select my internal drive again and retry I can see the EFI boot again, and select that and go back to this issue where I only have the internal drive to select.

**Comment by ozziepadilla** [comment]
> Yes, I held Option down the second time. If I select my internal drive again and retry I can see the EFI boot again, and select that and go back to this issue where I only have the internal drive to select.

You did it wrong , in the second time you must select install macOS Big Sur not the hard drive because in one of the steps is where you have to select where to install macOS Big Sur then select the hard drive

**Comment by ozziepadilla** [comment]
> Yes, I held Option down the second time. If I select my internal drive again and retry I can see the EFI boot again, and select that and go back to this issue where I only have the internal drive to select.

Here is a sample , first time select EFI boot, when you turn the Mac back on select the middle option not the HDD 
![Uploading 758D513A-3C12-4130-83CE-53A96D479B6B.png…]()

**Comment by ozziepadilla** [comment]
![3595DC7B-A346-4AE7-90AD-924D78A75713](https://user-images.githubusercontent.com/78187370/118012087-b1e68f00-b31e-11eb-94c8-184e6042b5e6.jpeg)

**Comment by ozziepadilla** [comment]
> > Yes, I held Option down the second time. If I select my internal drive again and retry I can see the EFI boot again, and select that and go back to this issue where I only have the internal drive to select.
> 
> You did it wrong , in the second time you must select install macOS Big Sur not the hard drive because in one of the steps is where you have to select where to install macOS Big Sur then select the hard drive

Here is where you have to select the HDD 
![Uploading B0A4F5D9-EDA1-4D0A-B9F7-49FCE901AAE5.png…]()

**Comment by mthuc** [comment]
The first time, I do see these 3 options, and  select EFI Boot.

After the second reboot, even holding option, I do not see the other options, only my internal drive.

**Comment by ozziepadilla** [comment]
Here is where you have to select the HDD after other steps 
![DD9452D7-FB5C-4875-BE5B-7F7D36CE9ABA](https://user-images.githubusercontent.com/78187370/118012746-62ed2980-b31f-11eb-9983-7d24e65cd836.png)

**Comment by ozziepadilla** [comment]
> The first time, I do see these 3 options, and select EFI Boot.
> 
> After the second reboot, even holding option, I do not see the other options, only my internal drive.

Do something first , browse the usb drive and there you can see 6 items , three folder and three files of not?

**Comment by mthuc** [comment]
I see the following:
```
ArchiveBin
Install macOS Big Sur
InstallerHax
KextPatches
Patched Sur
PatchKexts.sh
```

If I do the following steps, will it proceed the same? (Since the second reboot doesn't have the install option?):

1. Reboot and select EFI boot
2. Reboot and select internal drive
3. Reboot and select Install macOS

**Comment by ozziepadilla** [comment]
> I see the following:
> 
> ```
> ArchiveBin
> Install macOS Big Sur
> InstallerHax
> KextPatches
> Patched Sur
> PatchKexts.sh
> ```
> 
> If I do the following steps, will it proceed the same? (Since the second reboot doesn't have the install option?):
> 
> 1. Reboot and select EFI boot
> 2. Reboot and select internal drive
> 3. Reboot and select Install macOS

The second boot must have all three options as the first time so do this ,, unplug the usb and reboot your Mac the plug back in the usb make sure you can see it in your desktop screen then shut off your Mac , before the sound child keep holding down option key, then select   EFI boot do it again , turn back on your Mac then select install macOS Big Sur

**Comment by BenSova** [comment]
The option isn't just going to disappear. The USB is plugged in, the EFI Boot doesn't change anything like that, and nothing else should be effecting it. Try unplugging the drive and plugging it back in.

**Comment by mthuc** [comment]
Closing as performing the following steps allowed installation:

```
1. Reboot and select EFI boot
2. Reboot and select internal drive
3. Reboot and select Install macOS
```
