### ISSUE TITLE
Trouble Copying Files

### ISSUE THREAD

**Issue by Skinnyman180** [BenSova/Patched-Sur#57]
Hello. I'm a beginner at trying this. My email is Skinnyman180@me.com. Someone please help.

My latest error is path specified was invalid. I downloaded and ran the program from my downloads. As soon as I entered my password and pressed continue, I got this error.

Also, previous installation failed because I kept getting blessed tool error when trying to change start up disk in System Preferences AND in recovery.

**Comment by BenSova** [comment]
You never have to change the start up disk. I suggest trying again with 11.0.1 20B50, the new version of macOS Apple released.
