### ISSUE TITLE
Patch Kexts can't restart my Mac

### ISSUE THREAD

**Issue by martin81d** [BenSova/Patched-Sur#573]
I've installed Big Sur on a 2012 Mac Mini and everything went fine. I ran Patch Kexts to restore Wifi, the patching completed and I got the 'restart' button, but nothing happens when I click on it; that is, it changes colour when I click it, but the Mac won't restart. I've tried manually restarting it, but I still have no wifi. I've tried it several times (including unpatching & patching again) and still nothing. I have the Mac online via ethernet, so it's not a huge deal, but I'd like to sort it out.

 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.3.1
 - Mac Model: 2012 Mac Mini

**Comment by ozziepadilla** [comment]
> I've installed Big Sur on a 2012 Mac Mini and everything went fine. I ran Patch Kexts to restore Wifi, the patching completed and I got the 'restart' button, but nothing happens when I click on it; that is, it changes colour when I click it, but the Mac won't restart. I've tried manually restarting it, but I still have no wifi. I've tried it several times (including unpatching & patching again) and still nothing. I have the Mac online via ethernet, so it's not a huge deal, but I'd like to sort it out.
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to: Big Sur v11.3.1
> * Mac Model: 2012 Mac Mini



> I've installed Big Sur on a 2012 Mac Mini and everything went fine. I ran Patch Kexts to restore Wifi, the patching completed and I got the 'restart' button, but nothing happens when I click on it; that is, it changes colour when I click it, but the Mac won't restart. I've tried manually restarting it, but I still have no wifi. I've tried it several times (including unpatching & patching again) and still nothing. I have the Mac online via ethernet, so it's not a huge deal, but I'd like to sort it out.
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to: Big Sur v11.3.1
> * Mac Model: 2012 Mac Mini

Ok unpatch the kexts then reboot manually and again patched the kexts with the usb installer plugged don’t hit the reboot button because doesn’t work, reboot manually , unplug the Ethernet cable

**Comment by martin81d** [comment]
> > I've installed Big Sur on a 2012 Mac Mini and everything went fine. I ran Patch Kexts to restore Wifi, the patching completed and I got the 'restart' button, but nothing happens when I click on it; that is, it changes colour when I click it, but the Mac won't restart. I've tried manually restarting it, but I still have no wifi. I've tried it several times (including unpatching & patching again) and still nothing. I have the Mac online via ethernet, so it's not a huge deal, but I'd like to sort it out.
> > 
> > * Upgrading from: Catalina v10.15.7
> > * Upgrading to: Big Sur v11.3.1
> > * Mac Model: 2012 Mac Mini
> 
> > I've installed Big Sur on a 2012 Mac Mini and everything went fine. I ran Patch Kexts to restore Wifi, the patching completed and I got the 'restart' button, but nothing happens when I click on it; that is, it changes colour when I click it, but the Mac won't restart. I've tried manually restarting it, but I still have no wifi. I've tried it several times (including unpatching & patching again) and still nothing. I have the Mac online via ethernet, so it's not a huge deal, but I'd like to sort it out.
> > 
> > * Upgrading from: Catalina v10.15.7
> > * Upgrading to: Big Sur v11.3.1
> > * Mac Model: 2012 Mac Mini
> 
> Ok unpatch the kexts then reboot manually and again patched the kexts with the usb installer plugged don’t hit the reboot button because doesn’t work, reboot manually , unplug the Ethernet cable

Thanks, I'll give this a try. Do you mean keep the ethernet unplugged for all of this or just at the end?

**Comment by ozziepadilla** [comment]
Yes unplugged it before rebooting then turn the Mac back on check if you get the wifi working

**Comment by BenSova** [comment]
Don't unpatch if you don't need to, just reboot the Mac, it's a known issue that the button does nothing, and that's fine. Just reboot

**Comment by martin81d** [comment]
No, none of that worked. In fact things are worse now. Patch Kexts gave me this error when I tried to patch:

Error 1x1
Message: "a BootKernelExtensions.kc
a SystemKernelExtensions.kc
Error Domain=KMErrorDomain Code=71 "Unable to resolve dependencies: 'com.apple.driver.AppleIntelCFLGraphicsFramebuffer' names a dependency on 'com.apple.AppleGraphicsDeviceControl', which was not found." UserInfo={NSLocalizedDescription=Unable to resolve dependencies: 'com.apple.driver.AppleIntelCFLGraphicsFramebuffer' names a dependency on 'com.apple.AppleGraphicsDeviceControl', which was not found.}
kmutil failed. Check the logs for more info."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /Volumes/Install macOS Big Sur
Checking WiFi patch configuration...
No WiFi option specified, so checking for 802.11ac...
No 802.11ac WiFi card detected, using WiFi patch.
Auto-detecting Mac model...
(Override with --2010, --2011, or --2012)
Detected model: Macmini6,2
Detected a 2012-2013 Mac. Using --2012 patches.
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Installing kexts to volume /

Verifying volume...
Volume has Big Sur build 20E241Correctly volume mount...
Volume is mounted from device  /dev/disk1s5s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

Checking for KernelCollection backup...
Backup not found. Performing backup now. This may take a few minutes.
Backing up original KernelCollections to:
/System/Volumes/Update/mnt1/System/Library/KernelCollections/KernelCollections-20E241.tar.lz4
Begin replacing kexts...
Beginning patched IO80211Family.kext installation
Installing mojave-hybrid WiFi patch
Prepare for kmutil
Rebuilding boot collection...
Rebuilding system collection...
"

Also, Ethernet keeps dropping the connection every few seconds, making internet impossible.

**Comment by martin81d** [comment]
Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.

**Comment by ozziepadilla** [comment]
> Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.

Don’t get panic , let’s go step by step 
1-macOS Big Sur installation was successfully?
2-wifi didn’t work after macOS Big Sur get installed?
3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb?
4-did you unplug the usb while run Patchet Kexts ? 
5-when the process of Patchet Kexts finished  you reboot manually your Mac with the usb plugged?

**Comment by martin81d** [comment]
> > Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.
> 
> Don’t get panic , let’s go step by step
> 1-macOS Big Sur installation was successfully? - _Yes. Otherwise works fine._
> 2-wifi didn’t work after macOS Big Sur get installed? - _No, no wifi fresh off the install_
> 3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb? - _I think I ran it from the USB. I've tried it from both so many times I can't remember for sure, but I was following a YouTube tutorial and they ran it from the USB, so I must have done that._
> 4-did you unplug the usb while run Patchet Kexts ? - _Not the first couple of times. Later I did_
> 5-when the process of Patchet Kexts finished you reboot manually your Mac with the usb plugged? -_Yes_.

**Comment by ozziepadilla** [comment]
> > Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.
> 
> Don’t get panic , let’s go step by step
> 1-macOS Big Sur installation was successfully? - _Yes. Otherwise works fine._
> 2-wifi didn’t work after macOS Big Sur get installed? - _No, no wifi fresh off the install_
> 3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb? - _I think I ran it from the USB. I've tried it from both so many times I can't remember for sure, but I was following a YouTube tutorial and they ran it from the USB, so I must have done that._
> 4-did you unplug the usb while run Patchet Kexts ? - _Not the first couple of times. Later I did_
> 5-when the process of Patchet Kexts finished you reboot manually your Mac with the usb plugged? -_Yes_.

Can you post a picture of any errors shows up when Patchet Kexts ? Not just copy and paste everything like above 👆 just a picture but in this use the Patchet-Sur app not from the usb , Mac mini 2012 right ?

**Comment by martin81d** [comment]
> > > Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.
> > 
> > 
> > Don’t get panic , let’s go step by step
> > 1-macOS Big Sur installation was successfully? - _Yes. Otherwise works fine._
> > 2-wifi didn’t work after macOS Big Sur get installed? - _No, no wifi fresh off the install_
> > 3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb? - _I think I ran it from the USB. I've tried it from both so many times I can't remember for sure, but I was following a YouTube tutorial and they ran it from the USB, so I must have done that._
> > 4-did you unplug the usb while run Patchet Kexts ? - _Not the first couple of times. Later I did_
> > 5-when the process of Patchet Kexts finished you reboot manually your Mac with the usb plugged? -_Yes_.
> 
> Can you post a picture of any errors shows up when Patchet Kexts ? Not just copy and paste everything like above 👆 just a picture but in this use the Patchet-Sur app not from the usb , Mac mini 2012 right ?
> 
> Ps make sure you are log in under admin account

Okay, it is a Mac mini 2012, I am logged in as admin. The patch kexts looks like this when I run it. (It spends about 30 seconds patching before this appears)

![Screen Shot 2021-05-15 at 01 59 41](https://user-images.githubusercontent.com/84187767/118341972-a3b49080-b521-11eb-8d61-636f883aec16.png)

No other errors show.

Thanks for all your help so far BTW

**Comment by ozziepadilla** [comment]
> > > > Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.
> > > 
> > > 
> > > Don’t get panic , let’s go step by step
> > > 1-macOS Big Sur installation was successfully? - _Yes. Otherwise works fine._
> > > 2-wifi didn’t work after macOS Big Sur get installed? - _No, no wifi fresh off the install_
> > > 3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb? - _I think I ran it from the USB. I've tried it from both so many times I can't remember for sure, but I was following a YouTube tutorial and they ran it from the USB, so I must have done that._
> > > 4-did you unplug the usb while run Patchet Kexts ? - _Not the first couple of times. Later I did_
> > > 5-when the process of Patchet Kexts finished you reboot manually your Mac with the usb plugged? -_Yes_.
> > 
> > 
> > Can you post a picture of any errors shows up when Patchet Kexts ? Not just copy and paste everything like above 👆 just a picture but in this use the Patchet-Sur app not from the usb , Mac mini 2012 right ?
> > Ps make sure you are log in under admin account
> 
> Okay, it is a Mac mini 2012, I am logged in as admin. The patch kexts looks like this when I run it. (It spends about 30 seconds patching before this appears)
> 
> ![Screen Shot 2021-05-15 at 01 59 41](https://user-images.githubusercontent.com/84187767/118341972-a3b49080-b521-11eb-8d61-636f883aec16.png)
> 
> No other errors show.
> 
> Thanks for all your help so far BTW

Ok in the first time you ran the Patchet Kexts shows that error ? Because I read above you get to the green button to restart but it didn’t work, there is where you have to reboot manually, so question are you able to create a new partition to install Catalina then do all the procedures to upgrade to macOS Big Sur ? A friend of mine get that error all the time in every macOS Big Sur version , I suggested to create a new partition and now everything works perfectly, do you have many personal data? Pictures and others files are up in iCloud you won’t lose them  if you can do all that then you can transfer all your data to the new partition and erase it after then your HDD will resizing automatically, to download Catalina isn’t complicate

**Comment by ozziepadilla** [comment]
> > > > Update: ethernet works fine now after another restart. Patching still not getting me anywhere with WiFi.
> > > 
> > > 
> > > Don’t get panic , let’s go step by step
> > > 1-macOS Big Sur installation was successfully? - _Yes. Otherwise works fine._
> > > 2-wifi didn’t work after macOS Big Sur get installed? - _No, no wifi fresh off the install_
> > > 3-did you go to the Patchet-Sur app in your folder apps then run Patchet Kexts from there or the usb? - _I think I ran it from the USB. I've tried it from both so many times I can't remember for sure, but I was following a YouTube tutorial and they ran it from the USB, so I must have done that._
> > > 4-did you unplug the usb while run Patchet Kexts ? - _Not the first couple of times. Later I did_
> > > 5-when the process of Patchet Kexts finished you reboot manually your Mac with the usb plugged? -_Yes_.
> > 
> > 
> > Can you post a picture of any errors shows up when Patchet Kexts ? Not just copy and paste everything like above 👆 just a picture but in this use the Patchet-Sur app not from the usb , Mac mini 2012 right ?
> > Ps make sure you are log in under admin account
> 
> Okay, it is a Mac mini 2012, I am logged in as admin. The patch kexts looks like this when I run it. (It spends about 30 seconds patching before this appears)
> 
> ![Screen Shot 2021-05-15 at 01 59 41](https://user-images.githubusercontent.com/84187767/118341972-a3b49080-b521-11eb-8d61-636f883aec16.png)
> 
> No other errors show.
> 
> Thanks for all your help so far BTW

Sometimes the installation get messing up with something but a fresh installation it’s the quick solution

**Comment by martin81d** [comment]
I think I'll just leave it as it is. As I said above, the ethernet works fine, the wifi is not a deal-breaker. All the other wireless functions work, including Airdrop, so I won't mess with it any further. Thanks for your help anyway. Maybe someone else with the same problem will find this thread and your advice above will be helpful.

**Comment by yunie01** [comment]
Hi I'm having the same problem , I have a mid 2012 MacBook Pro and the WiFi isn't working . When I try to install kexts I click on the restart button it doesn't do anything . I tried to uninstall the kexts as mentioned earlier in the comments & im getting this error message : 

Error 1x1
Message: "mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
Failed to mount underlying volume."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /Volumes/Install macOS Big Sur
Uninstalling kexts.
Checking WiFi patch configuration...
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Uninstalling patched kexts from volume /

Verifying volume...
Volume has Big Sur build 20E241Correctly volume mount...
Volume is mounted from device  /dev/disk1s2s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s2 at temporary mountpoint:
/System/Volumes/Update/mnt1

"


Someone please help me, I can't use an Ethernet & I need wifi on Mac for upcoming exams !! 😓

**Comment by ozziepadilla** [comment]
> Hi I'm having the same problem , I have a mid 2012 MacBook Pro and the WiFi isn't working . When I try to install kexts I click on the restart button it doesn't do anything . I tried to uninstall the kexts as mentioned earlier in the comments & im getting this error message :
> 
> Error 1x1
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75
> Failed to mount underlying volume."
> Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> 
> Checking environment...
> We're booted into full macOS.
> Confirming patch location...
> Patch Location: /Volumes/Install macOS Big Sur
> Uninstalling kexts.
> Checking WiFi patch configuration...
> Checking SIP status
> Checking what volume to patch...
> Booted into full Big Sur, using main volume.
> Uninstalling patched kexts from volume /
> 
> Verifying volume...
> Volume has Big Sur build 20E241Correctly volume mount...
> Volume is mounted from device /dev/disk1s2s1
> Mounted device is a snapshot.
> Attempting to mount underlying volume
> from device /dev/disk1s2 at temporary mountpoint:
> /System/Volumes/Update/mnt1
> 
> "
> 
> Someone please help me, I can't use an Ethernet & I need wifi on Mac for upcoming exams !! 😓

Ok , did you reboot your Mac 💻? The button doesn’t work you must reboot manually

**Comment by ozziepadilla** [comment]
> Hi I'm having the same problem , I have a mid 2012 MacBook Pro and the WiFi isn't working . When I try to install kexts I click on the restart button it doesn't do anything . I tried to uninstall the kexts as mentioned earlier in the comments & im getting this error message :
> 
> Error 1x1
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75
> Failed to mount underlying volume."
> Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> 
> Checking environment...
> We're booted into full macOS.
> Confirming patch location...
> Patch Location: /Volumes/Install macOS Big Sur
> Uninstalling kexts.
> Checking WiFi patch configuration...
> Checking SIP status
> Checking what volume to patch...
> Booted into full Big Sur, using main volume.
> Uninstalling patched kexts from volume /
> 
> Verifying volume...
> Volume has Big Sur build 20E241Correctly volume mount...
> Volume is mounted from device /dev/disk1s2s1
> Mounted device is a snapshot.
> Attempting to mount underlying volume
> from device /dev/disk1s2 at temporary mountpoint:
> /System/Volumes/Update/mnt1
> 
> "
> 
> Someone please help me, I can't use an Ethernet & I need wifi on Mac for upcoming exams !! 😓

If you did the unpatched kexts so you have to patch them again but reboot manually don’t hit the button

**Comment by yunie01** [comment]
@ozziepadilla How do I reboot manually ? I'm also unsure if they unpatched cause when I tried I got that error message

**Comment by ozziepadilla** [comment]
> @ozziepadilla How do I reboot manually ? I'm also unsure if they unpatched cause when I tried I got that error message

The same way you turn off the Mac that’s reboot , when is boot up if you don’t have wifi then go to the Patchet-Sur app Patchet Kexts again but in this time don’t hit the button if goes in green just restart your Mac manually don’t force to shut it off

**Comment by BenSova** [comment]
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75

Your Mac was "optimizing". Give it time. Before you patch the kexts again, give it 10 minutes.

**Comment by ozziepadilla** [comment]
> > Message: "mount_apfs: volume could not be mounted: Resource busy
> > mount: /System/Volumes/Update/mnt1 failed with 75
> 
> Your Mac was "optimizing". Give it time. Before you patch the kexts again, give it 10 minutes.

Leave it alone it’s normal

**Comment by yunie01** [comment]
@BenSova okay so wait to patch the kexts then manually restart or do I wait then unpatch ?

**Comment by ozziepadilla** [comment]
> > Message: "mount_apfs: volume could not be mounted: Resource busy
> > mount: /System/Volumes/Update/mnt1 failed with 75
> 
> Your Mac was "optimizing". Give it time. Before you patch the kexts again, give it 10 minutes.

Sorry Ben thought was the guy lol 😝

**Comment by ozziepadilla** [comment]
> @BenSova okay so wait to patch the kexts then manually restart or do I wait then unpatch ?

Yes manually after Patchet Kexts finished

**Comment by yunie01** [comment]
@ozziepadilla Okay I'll wait and patch then see if it fixes anything . For some reason my Mac isn't connecting to other networks so hopefully this fixes everything );

**Comment by ozziepadilla** [comment]
> @ozziepadilla Okay I'll wait and patch then see if it fixes anything . For some reason my Mac isn't connecting to other networks so hopefully this fixes everything );

It will you will see

**Comment by yunie01** [comment]
So when I rebooted I was connected to my WiFi , but for some reason I cant connect to my WiFi extender ? All my other apple products are connected , when I try to connect it says network can't be found? I had no issues with Catalina ? Is this related to the patched sur ?

**Comment by ozziepadilla** [comment]
> So when I rebooted I was connected to my WiFi , but for some reason I cant connect to my WiFi extender ? All my other apple products are connected , when I try to connect it says network can't be found? I had no issues with Catalina ? Is this related to the patched sur ?

Wait for benSova for a better answer , unless your Mac it’s connected to wifi

**Comment by yunie01** [comment]
@ozziepadilla Okay I'll wait for Ben to answer cause I thought the kexts would solve the issue so I can connect to all my WiFi networks . It's weird that it's not working

**Comment by ozziepadilla** [comment]
> @ozziepadilla Okay I'll wait for Ben to answer cause I thought the kexts would solve the issue so I can connect to all my WiFi networks . It's weird that it's not working

I don’t know if patched Sur interfere with those wifi extenders because it didn’t work with personal hotspot

**Comment by yunie01** [comment]
@BenSova @ozziepadilla  Update ; hey guys , I patched the kexts but the WiFi issue was still there so I unpatched my kexts and got this error  when I tried to patch my kexts, I can't copy it in because I have no connection 

![image](https://user-images.githubusercontent.com/84282574/118643268-37ad8300-b7d4-11eb-99de-98beb25a5732.jpeg)

**Comment by ozziepadilla** [comment]
> @BenSova @ozziepadilla Update ; hey guys , I patched the kexts but the WiFi issue was still there so I unpatched my kexts and got this error when I tried to patch my kexts, I can't copy it in because I have no connection
> 
> ![image](https://user-images.githubusercontent.com/84282574/118643268-37ad8300-b7d4-11eb-99de-98beb25a5732.jpeg)

Are you using the Patchet-Sur app to Patchet Kexts or from the usb installer?

**Comment by yunie01** [comment]
@ozziepadilla I'm using the app that's on my Mac

**Comment by ozziepadilla** [comment]
> @ozziepadilla I'm using the app that's on my Mac

Don’t unpatched, try Patchet Kexts with the usb installer when finish unplug the usb and restart your Mac should be work

**Comment by yunie01** [comment]
@ozziepadilla im sorry I'm really a noob when it comes to these things how do I install from usb ![image](https://user-images.githubusercontent.com/84282574/118655626-a04f2c80-b7e1-11eb-9717-5c1738182fb0.jpeg)

**Comment by ozziepadilla** [comment]
> @ozziepadilla im sorry I'm really a noob when it comes to these things how do I install from usb ![image](https://user-images.githubusercontent.com/84282574/118655626-a04f2c80-b7e1-11eb-9717-5c1738182fb0.jpeg)

Don’t touch anything from there , when I said Patchet Kexts with the usb means , go to your apps folder find Patchet-Sur app go to Patchet Kexts option then get in there but with the usb plugged run Patchet Kexts

**Comment by ozziepadilla** [comment]
> @ozziepadilla im sorry I'm really a noob when it comes to these things how do I install from usb ![image](https://user-images.githubusercontent.com/84282574/118655626-a04f2c80-b7e1-11eb-9717-5c1738182fb0.jpeg)

When you open the Patchet-Sur app go there and Patchet Kexts with the usb plugged don’t hit the green button when finish just restart your Mac manually 
![Uploading 7A4F7A1C-5EBD-4349-A5E0-4503FBF38A1E.jpeg…]()

**Comment by ozziepadilla** [comment]
![70A5EDEB-5BE1-44D7-A7D4-8B7123F8D498](https://user-images.githubusercontent.com/78187370/118657512-8dc0fd00-b7b9-11eb-97dd-a7f788022515.jpeg)

**Comment by yunie01** [comment]
@ozziepadilla  got that same error message when I tried to patch kexts with usb plugged in ):

**Comment by ozziepadilla** [comment]
> @ozziepadilla got that same error message when I tried to patch kexts with usb plugged in ):

Where are you from ?

**Comment by yunie01** [comment]
@ozziepadilla I'm from UK

**Comment by ozziepadilla** [comment]
> @ozziepadilla I'm from UK

Take the invitation to come to discord there you can get hell from others

**Comment by yunie01** [comment]
@ozziepadilla can you send it again please

**Comment by ozziepadilla** [comment]
> @ozziepadilla can you send it again please

hey come check out Discord with me https://discord.gg/KXFhtZ3M

**Comment by yunie01** [comment]
@ozziepadilla the link isn't working for me ):

**Comment by ozziepadilla** [comment]
> @ozziepadilla the link isn't working for me ):
Try it now 

https://discord.gg/KXFhtZ3M

**Comment by BenSova** [comment]
The main part of this issue is fixed in code and will be fixed with the next release, so closing. Open a new issue if you have any other issues with Patch Kexts
