### ISSUE TITLE
big Sur Os patched v0.2.1

### ISSUE THREAD

**Issue by jamestaylor1994** [BenSova/Patched-Sur#577]
having issues with patched sur version 0.2.1 it keeps telling that patched sur would like to make changes and to enter my password, but it never works i enter but the message keeps coming back -_- i cannot skip this step it wants me to enter my password HELP

**Comment by ozziepadilla** [comment]
> having issues with patched sur version 0.2.1 it keeps telling that patched sur would like to make changes and to enter my password, but it never works i enter but the message keeps coming back -_- i cannot skip this step it wants me to enter my password HELP

Change your actual password to another easy password like abc123 your actual password may contents symbols and it won’t work until you use a alphanumeric password without symbols

**Comment by jamestaylor1994** [comment]
My password is space bar 4 times lol , u think changing my password would work ?

**Comment by ozziepadilla** [comment]
> My password is space bar 4 times lol , u think changing my password would work ?

Definitely I help other people with the same issue , changing password with numbers and letters

**Comment by BenSova** [comment]
> My password is space bar 4 times lol , u think changing my password would work ?

Yes, yes I do.

**Comment by ozziepadilla** [comment]
> My password is space bar 4 times lol , u think changing my password would work ?

It worked right ? If yes come over and close this case

**Comment by jamestaylor1994** [comment]
I have not tried as soon as i go home i will give it a try hopefully it dose !

**Comment by jamestaylor1994** [comment]
Its WORKED amazing thank u very much !
