### ISSUE TITLE
Where is the Install app downloaded?

### ISSUE THREAD

**Issue by jfmoots** [BenSova/Patched-Sur#58]
Trying to find the original Install macOS Big Sur.app so that I copy and archive it. Where is it downloaded? The installer says it's downloaded on my system somewhere but I can't find it.

**Comment by BenSova** [comment]
The InstallAssistant.pkg is inside /Users/you/.patched-sur (the folder is a dot file, so you'll have to show it with CMD+SHIFT+PERIOD) and the Install macOS Big Sur should have appeared in your applications folder.
