### ISSUE TITLE
OpenGL disabled

### ISSUE THREAD

**Issue by fuzenco** [BenSova/Patched-Sur#588]
**Describe the bug**
Photoshop is reporting that OpenGL is disabled, so any 3D features are not functioning now. In Preferences > Performance, there is a setting to Use Graphics Processor. In my case it’s NVIDIA GeForce GT 650M. The checkbox used to be able to be clicked, but now everything is grayed out.

![Screen Shot 2021-05-24 at 6 32 04 PM](https://user-images.githubusercontent.com/173683/119414836-5b823480-bcbe-11eb-9520-b797093713dd.png)
![Screen Shot 2021-05-24 at 6 23 30 PM](https://user-images.githubusercontent.com/173683/119414807-47d6ce00-bcbe-11eb-9eb3-4d45b5dacb15.png)
![Screen Shot 2021-05-24 at 6 23 47 PM](https://user-images.githubusercontent.com/173683/119414809-486f6480-bcbe-11eb-8014-ae6f23598b9a.png)

 I’m running the latest Photoshop release 22.4.1.

I don’t know if after installing Big Sur Patched months ago, if I even tried using 3D in Photoshop after that. I just noticed this issue today. And perhaps it’s affecting other apps relying on OpenGL?

It’s perhaps a small price to pay for being able to run Big Sur on this old hardware. Would be nice to get it back up if possible.

**Comment by fuzenco** [comment]
Well, it looks like it’s actually Apple who dropped support for OpenGL in Big Sur. So apparently nothing that Patched can do anything about.

https://stackoverflow.com/questions/65802625/develop-using-opengl-4-x-on-osx-big-sur

**Comment by BenSova** [comment]
Yeah, nothing I can do
