### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Skinnyman180** [BenSova/Patched-Sur#59]
![Screen Shot 2020-11-17 at 12 41 52 PM](https://user-images.githubusercontent.com/57806696/99432853-589f2500-28d2-11eb-9fd5-4fb3cf82f904.png)

**Comment by BenSova** [comment]
*\*Click to copy.\** That's the new feature coming in v0.0.4. It's going to be text under the red box. So people make issues that I can understand.
