### ISSUE TITLE
Cant patch kexts

### ISSUE THREAD

**Issue by banolka** [BenSova/Patched-Sur#594]
**Describe the bug**
Cant patch kexts

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to:  Big Sur v11.4
 - Mac Model: Mac Mini Late 2012
 - -Version v0.2.1

**Additional context**
```
Error 1x1
Message: "mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
Failed to mount underlying volume."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /usr/local/lib/Patched-Sur-Patches
Checking WiFi patch configuration...
No WiFi option specified, so checking for 802.11ac...
No 802.11ac WiFi card detected, using WiFi patch.
Auto-detecting Mac model...
(Override with --2010, --2011, or --2012)
Detected model: Macmini6,1
Detected a 2012-2013 Mac. Using --2012 patches.
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Installing kexts to volume /

Verifying volume...
Volume has Big Sur build 20F71Correctly volume mount...
Volume is mounted from device  /dev/disk1s5s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

"
```

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> Cant patch kexts
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Upgrading from: Catalina v10.15.7
> * Upgrading to:  Big Sur v11.4
> * Mac Model: Mac Mini Late 2012
> * -Version v0.2.1
> 
> **Additional context**
> 
> ```
> Error 1x1
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75
> Failed to mount underlying volume."
> Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> 
> Checking environment...
> We're booted into full macOS.
> Confirming patch location...
> Patch Location: /usr/local/lib/Patched-Sur-Patches
> Checking WiFi patch configuration...
> No WiFi option specified, so checking for 802.11ac...
> No 802.11ac WiFi card detected, using WiFi patch.
> Auto-detecting Mac model...
> (Override with --2010, --2011, or --2012)
> Detected model: Macmini6,1
> Detected a 2012-2013 Mac. Using --2012 patches.
> Checking SIP status
> Checking what volume to patch...
> Booted into full Big Sur, using main volume.
> Installing kexts to volume /
> 
> Verifying volume...
> Volume has Big Sur build 20F71Correctly volume mount...
> Volume is mounted from device  /dev/disk1s5s1
> Mounted device is a snapshot.
> Attempting to mount underlying volume
> from device /dev/disk1s5 at temporary mountpoint:
> /System/Volumes/Update/mnt1
> 
> "
> ```

Get this link join to the discord post you’d issues and in support room 1,/ or 3 https://discord.gg/q3MyF2Pk

**Comment by BenSova** [comment]
Wait 5 minutes, reboot, wait 5 minutes, patch
