### ISSUE TITLE
Patched Sur doesn't copy anything to USB install media

### ISSUE THREAD

**Issue by Mattemattias** [BenSova/Patched-Sur#596]
**Problem:**
Various attempts of running the patcher always lead to the same result: Everything seems to work fine: after formatting the USB media, I instantly get the "Finished!" screen at the end, but then the USB installer drive is empty (and also no hard drive activity is shown in activity monitor).

**I tried:**
- various downloads / macOS versions
- running the patch from another admin account
- to locate the installer the patch has downloaded to copy it to the USB drive myself, but couldn't find it.
- "Redownload" option, but that got stuck: The download screen instantly showed a completed download progress bar, so no new download was initiated. Although the bar is complete, the patch doesn't move to the next step/screen in this case

**Steps to reproduce the behavior**
1. Started the patch from DMG
2. Used "Update" option
3. Chose install from "Release" (tried various 11.0.1 to 11.4, i also tried "Redownload")
3. Entered my password
4. Picked the USB drive and started the patch 

**Expected behavior**
After formatting the disk the patch would normally copy the installer package to the drive, right? In my case it directly shows the "Finished!" screen and tells me to reboot into the drive, but that's empty.

**Desktop**
 - Upgrading from: Catalina v10.15.7
 - Upgrading to: Big Sur v 11.0.1 / 11.3 / 11.4 (downloaded all of these, but none was copied to the USB drive)
 - Mac Model: MacBook Pro 15" early 2013 
 - Version: v0.1.2 (64)

**Comment by Kunolobo** [comment]
try with the latest one 0.21. You are using version 0.12

**Comment by Mattemattias** [comment]
Oh true, that was quite idiotic. I tried the latest version, but the result remains precisely the same. No errors, but the USB stick remains empty :-/  I think, now something is not working correctly with the formatting. It no longer seems that PatchedSur formats the media. It keeps its old name, but still the "finished!" screen appears. Any ideas? Thx!

**Comment by ozziepadilla** [comment]
> Oh true, that was quite idiotic. I tried the latest version, but the result remains precisely the same. No errors, but the USB stick remains empty :-/ I think, now something is not working correctly with the formatting. It no longer seems that PatchedSur formats the media. It keeps its old name, but still the "finished!" screen appears. Any ideas? Thx!

You must erase the usb drive with disk utility first 
See the right commands in the attachment 
![083455D9-DB39-4B57-BDB8-278A2E12CE66](https://user-images.githubusercontent.com/78187370/120073200-6560ba80-c065-11eb-9e60-7623b9384e8f.jpeg)

**Comment by ozziepadilla** [comment]
> Oh true, that was quite idiotic. I tried the latest version, but the result remains precisely the same. No errors, but the USB stick remains empty :-/ I think, now something is not working correctly with the formatting. It no longer seems that PatchedSur formats the media. It keeps its old name, but still the "finished!" screen appears. Any ideas? Thx!

And to select the right unit of your usb go to the menu bar in View then select SHOW ALL DEVICES see the attachment you must select the usb bog the volume from the bottom 
![123AF995-3062-442E-8E2D-D7DC8CE98120](https://user-images.githubusercontent.com/78187370/120073312-be305300-c065-11eb-9819-3cf2cfc70e4f.jpeg)

**Comment by Mattemattias** [comment]
I had already tried that with those settings (as the patch before said sth like "no compatible device detected") After that it recognised the usb, but the result was the same :-/ But thanks anyway!!

**Comment by BenSova** [comment]
@Mattemattias This is a macOS bug. Evidently, no commands are being run by the patcher which is something that should never happen and logically cannot happen. Something is wrong with your OS installation, and I don't know what. Try another Mac if you can, there's absolutely nothing I can do if macOS isn't letting the app run code.

**Comment by Mattemattias** [comment]
Hey Ben. Thanks for the support! You won't believe it, but it seems it helped me: I tried using my other admin account, changed the admin password to sth without special characters (as i considered the patch might not understand the german keyboard that i use. maybe that's bullshit, i don't know anything about programing...) and it seems to work now. 40% of the installer are already copied :) thanks a lot for your work! Was very nice to see the UX of the patch grow over the different versions.

**Comment by ozziepadilla** [comment]
> Hey Ben. Thanks for the support! You won't believe it, but it seems it helped me: I tried using my other admin account, changed the admin password to sth without special characters (as i considered the patch might not understand the german keyboard that i use. maybe that's bullshit, i don't know anything about programing...) and it seems to work now. 40% of the installer are already copied :) thanks a lot for your work! Was very nice to see the UX of the patch grow over the different versions.

Keep this in your mind Patchet-Sur does not support password with any symbols just letters or mixed with numbers
