### ISSUE TITLE
Brightness control stopped working after 11.3

### ISSUE THREAD

**Issue by datuck** [BenSova/Patched-Sur#611]
**Describe the bug**
After upgrading to Big Sur 11.3 the brightness is maxed and cannot be turned down either by settings, keys, or control center. 

**To Reproduce**
1. Press Brightness Up Key (F5) or Brightness Down key (F6)
2. Nothing happens
3. Navigate to control center and try to change brightness
4. Nothing happens
5. Reset the NVRAM and also reset the SMC by unplugging the battery, pressing the power switch while in powerless state for several seconds, then reboot.
6. Issue persisted

**Expected behavior**
If I downgrade back to Big Sur 11.2 the brightness slider and brightness keys work again.

**Screenshots**
Brightness slider is locked at full brightness
![image](https://user-images.githubusercontent.com/51359198/120699551-5fa01600-c465-11eb-8b26-46e0e82f26b3.png)

No brightness slider in the display section
![image](https://user-images.githubusercontent.com/51359198/120699768-adb51980-c465-11eb-8fbd-c1632d055a83.png)

![image](https://user-images.githubusercontent.com/51359198/120700465-8c086200-c466-11eb-9b0d-c547d691d24e.png)

**Desktop (please complete the following information):**
 - Upgrading from: Big Sur 11.2 
- Upgrading to: Big Sur 11.3 (upgraded to Big Sur 11.5 beta 2 and same issue)
 - Mac Model: 13" 2012 MacBook Air A1466
 - Version: Patched Sur 0.2.1

**Additional context**
I'm hoping for some kind of workaround or if a patched kext can be injected to fix this issue.

**Comment by ozziepadilla** [comment]
join the discord Patchet-Sur support, tasks the invitation and go to support room 1,2 or 3 post your issues and someone will help you 
https://discord.gg/vps47hZb

**Comment by datuck** [comment]
Not sure if this is related to the actual patcher and may be a bug within Mac OS 11.3+.

**Comment by datuck** [comment]
MacBook Air 5,2 brightness controls and slider completely missing from the UI and cannot adjust via keyboard keys either. Confirmed issue persists in 11.3, 11.4, and 12.0.  Confirmed issue with separate isolated setups of Patched Sur and OCLP. 

No issue in 11.2.3.

**Comment by ozziepadilla** [comment]
When you upgrade to macOS Big Sur 11.2.3 you did it with Patchet-Sur ?

**Comment by datuck** [comment]
11.2.3 was using Patched Sur.

**Comment by datuck** [comment]
Not an issue with the patcher, issue with macOS 11.3+. Closing this and will wait for a fix.
