### ISSUE TITLE
App Store not signing in after Big Sur 11.4 patch on Macbook Pro Mid-2012 

### ISSUE THREAD

**Issue by Higmil6969** [BenSova/Patched-Sur#614]
**Describe the bug**
The title explains it. All is well with the installation except for one thing, unfortunately. I cannot access App Store because of this. I have check my date and time and its correct. I can sign in on everything else but the App store. Thank you for answering!

**Comment by ozziepadilla** [comment]
> **Describe the bug**
> The title explains it. All is well with the installation except for one thing, unfortunately. I cannot access App Store because of this. I have check my date and time and its correct. I can sign in on everything else but the App store. Thank you for answering!

Reboot your Mac and try to log in again

**Comment by Higmil6969** [comment]
I have tried it already, it still will not sign in. I have actually signed out of Apple ID altogether and tried to sign in again, but now it does not even work for that anymore. I cannot sign in my Apple ID on my MacBook.

**Comment by ozziepadilla** [comment]
Go to www.iCloud.com log in and let me know how it goes

**Comment by ozziepadilla** [comment]
When you re-open the App Store again, go to Store > Sign In and enter your Apple ID details to sign in again. Sign in again using your Apple ID email address and password. If that doesn't work, try signing out and signing in again from System Preferences > Apple ID …did you check all these steps already ?

**Comment by ozziepadilla** [comment]
I didn’t see any outages from here


![Uploading DFF77FBB-300A-4927-A270-47C76144B302.png…]()

**Comment by Higmil6969** [comment]
I've actually tried logging in on icloud.com on safari. It asked me the password of my "admin account". I thought it was referring to my laptop password, but it was not. I also entered my cloud account, it also was not. May I ask if this is something that occasionally happens on this specific MacOS patch? Thank you

**Comment by ozziepadilla** [comment]
> I've actually tried logging in on icloud.com on safari. It asked me the password of my "admin account". I thought it was referring to my laptop password, but it was not. I also entered my cloud account, it also was not. May I ask if this is something that occasionally happens on this specific MacOS patch? Thank you

See isn’t macOS Big Sur 11.4 issues is your Apple ID account

**Comment by Higmil6969** [comment]
Pardon?

**Comment by Higmil6969** [comment]
You mean, the problem is my apple ID, not the OS?

**Comment by ozziepadilla** [comment]
> Pardon?

The issues you are having isn’t related to macOS Big Sur update  when you log in from iCloud.com and there ask for you Mac password  and you type it in is to authenticate and allow you to access your iCloud

**Comment by Higmil6969** [comment]
Well, I have already resolved that. It is now logging in, so the problem now must be either my Apple ID or the patcher. I can't say that its the case for the former since I've tried several apple ids and it still wont work

**Comment by ozziepadilla** [comment]
> You mean, the problem is my apple ID, not the OS?

Correct , go to your Mac and change your Mac admin  password then try to log into iCloud.com and when you prompted type your new Mac password

**Comment by ozziepadilla** [comment]
> Well, I have already resolved that. It is now logging in, so the problem now must be either my Apple ID or the patcher. I can't say that its the case for the former since I've tried several apple ids and it still wont work

Did your password contains symbols or just letters and numbers ? Because Patchet-Sur doesn’t support password with any special characters like &@)$%#} etc etc

**Comment by ozziepadilla** [comment]
If you got this issue solved you can close it

**Comment by Higmil6969** [comment]
My admin account doesnt have any special characters, but my icloud account's password does have it.

**Comment by ozziepadilla** [comment]
> My admin account doesnt have any special characters, but my icloud account's password does have it.

So that may be the issues you have with your iCloud account

**Comment by Higmil6969** [comment]
But I have tried a different account and it's still doing it :(

**Comment by ozziepadilla** [comment]
> My admin account doesnt have any special characters, but my icloud account's password does have it.

I had the same issues long time ago with my iMac can’t log in to the App Store books and iTunes but it wasn’t the macOS because it was high Sierra that I have installed the issues was in my iCloud account then after I change the password and link my Mac password everything works perfectly

**Comment by Higmil6969** [comment]
Oh my God I think I solved it. Yes it the fricking account! not my apple id but my admin account! I made another laptop and app store works there

**Comment by ozziepadilla** [comment]
> Oh my God I think I solved it. Yes it the fricking account! not my apple id but my admin account! I made another laptop and app store works there

Told you my friend

**Comment by Higmil6969** [comment]
THANK YOU SO MUCH!

**Comment by ozziepadilla** [comment]
> THANK YOU SO MUCH!

No problem anytime
