### ISSUE TITLE
Error 1x1 Message 

### ISSUE THREAD

**Issue by Stvjr711** [BenSova/Patched-Sur#615]
**Describe the bug**![image](https://user-images.githubusercontent.com/85360257/120832852-bcafd080-c526-11eb-9e49-861cbbf0e637.png)A clear and concise description of what the bug is.![image](https://user-images.githubusercontent.com/85360257/120832966-d4875480-c526-11eb-8bba-7db291aaec3b.png)![image](https://user-images.githubusercontent.com/85360257/120832991-dcdf8f80-c526-11eb-9526-fa3db22429f9.png)**To Reproduce**

**Expected behavior**
I was able to download macOS Big Sur on my mid 2012 macbook pro  that was running catalina. I was successfully able to run Patch Kexts to have my bluetooth and wifi appropriately but after a few days the wifi stopped working. I was able to Unpatch Kexts successfully but now i am not able to Patch Kexts. This error message below keeps coming up.    

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**
[Patches Sur Error Message .docx](https://github.com/BenSova/Patched-Sur/files/6599900/Patches.Sur.Error.Message.docx)

**Comment by ozziepadilla** [comment]
Before you do something else and get a big mess up with your Mac , don’t ever unpatched Kexts, do this , with the usb installer you created before , hood you still have it if not so create a new one, reinstall macOS Big Sur then Patchet Kexts again , u know all the procedures hold down option key the select  EFI boot turn back on ur Mac then install macOS Big Sur

**Comment by BenSova** [comment]
Known issue, fixed on my side, reinstall macOS for now.

**Comment by Stvjr711** [comment]
It worked. thank you
