### ISSUE TITLE
Log in 

### ISSUE THREAD

**Issue by TheOfficialGriffin** [BenSova/Patched-Sur#62]
Hi I’m just wondering if it’s normal for the log in time to take very long for the first time of use

**Comment by BenSova** [comment]
Well depends, if you have a 2011 or below Mac, you just discovered what "no graphics acceleration" truly means. Otherwise, if it's only the first time, I'm not concerned.

**Comment by TheOfficialGriffin** [comment]
I have a 2012 iMac 21,5inch
