### ISSUE TITLE
Freezes when EFI boot is clicked

### ISSUE THREAD

**Issue by MassaneMan10** [BenSova/Patched-Sur#620]
In the boot options menu, I click EFI boot but then it freezes then restarts into macos catilina. I am using a 2012 mac mini.

**Comment by MassaneMan10** [comment]
The EFI boot logo is also just the default logo

**Comment by silveroffspring** [comment]
When you boot the first time into the boot options and choose EFI Boot your Mac will shut down. Thats normal. 

After that you start your Mac again into the boot options (holding alt down). Than you choose to install macOS.

**Comment by MassaneMan10** [comment]
It didn't shut down though. It froze then it restarted.

**Comment by MassaneMan10** [comment]
I just tried after it restarted and it is still showing the null symbol

**Comment by MassaneMan10** [comment]
Re installed it onto the USB and it is now working fine

**Comment by Clem-** [comment]
Hi, I think that you **didn't click on the right EFI boot**. You must **plug the USB stick with the BigSur installer** first and select the EFI boot from this drive. It will then shut down immediately.
I also have an EFI boot that froze the screen and restart the computer after a minute or so. I think it is from an old linux or bootcamp.

I ran into a similar issue after upgrading with the post-install app : 
I had the prohibited/null icon and even selecting EFI from the USB Installer, I could not boot my MacbookPro mid 2012.

I am currently reinstalling it with the USB, as you mentioned.
Thanks
