### ISSUE TITLE
Password not accepted at USB installer creation 

### ISSUE THREAD

**Issue by arunp1783** [BenSova/Patched-Sur#627]
Using Patched-Sur 2.1 at the USB intaller creation - password isn't accepted.  Installing from latest version of Catalina.
Open for suggestions.

**Comment by ozziepadilla** [comment]
If you password contains special characters it won’t work you must change it for letters or mixed with numbers like 123abc not symbols like $&%#^++{} any symbol

**Comment by BenSova** [comment]
Known issue, already fixed on my Sadie and will be released with the next version.
