### ISSUE TITLE
Instalation cannot proceed because the installer is damaged

### ISSUE THREAD

**Issue by Nanasenpai** [BenSova/Patched-Sur#630]
I tried to upgrade from Catalina, 10.15.7, followed the steps one by one, but during the instalation after 7-10 minutes it stops and shows me this error as per on picture attached.
-my hardware is Macbook pro retina 2012 a1398 15’
[Error picture link](https://share.icloud.com/photos/0FfGRWmNsCcJWKI-t07Ad0JUw)

**Comment by ozziepadilla** [comment]
> I tried to upgrade from Catalina, 10.15.7, followed the steps one by one, but during the instalation after 7-10 minutes it stops and shows me this error as per on picture attached.
> -my hardware is Macbook pro retina 2012 a1398 15’
> [Error picture link](https://share.icloud.com/photos/0FfGRWmNsCcJWKI-t07Ad0JUw)

Hi, ok try it again and when you get that error don’t click on the Ok or CANCEL buttons  press and hold the power button until your Mac shuts off itself then turn it back on don’t press any key just let it goes then you will get the apple logo screen and the progress bar let it finish

**Comment by Nanasenpai** [comment]
Hi, sadly it didn’t worked. It booted back to Catalina, just by long pressing the power button and restarting the device.

**Comment by Nanasenpai** [comment]
> > I tried to upgrade from Catalina, 10.15.7, followed the steps one by one, but during the instalation after 7-10 minutes it stops and shows me this error as per on picture attached.
> > -my hardware is Macbook pro retina 2012 a1398 15’
> > [Error picture link](https://share.icloud.com/photos/0FfGRWmNsCcJWKI-t07Ad0JUw)
> 
> Hi, ok try it again and when you get that error don’t click on the Ok or CANCEL buttons press and hold the power button until your Mac shuts off itself then turn it back on don’t press any key just let it goes then you will get the apple logo screen and the progress bar let it finish

Hi, sadly it didn’t worked. It booted back to Catalina, just by long pressing the power button and restarting the device.

**Comment by ozziepadilla** [comment]
> > > I tried to upgrade from Catalina, 10.15.7, followed the steps one by one, but during the instalation after 7-10 minutes it stops and shows me this error as per on picture attached.
> > > -my hardware is Macbook pro retina 2012 a1398 15’
> > > [Error picture link](https://share.icloud.com/photos/0FfGRWmNsCcJWKI-t07Ad0JUw)
> > 
> > 
> > Hi, ok try it again and when you get that error don’t click on the Ok or CANCEL buttons press and hold the power button until your Mac shuts off itself then turn it back on don’t press any key just let it goes then you will get the apple logo screen and the progress bar let it finish
> 
> Hi, sadly it didn’t worked. It booted back to Catalina, just by long pressing the power button and restarting the device.

Try one more time , don’t close the error and tell me how many minutes remaining can you read , if in this time doesn’t we can try another trick

**Comment by BenSova** [comment]
@ozziepadilla That's a different problem.

**Comment by BenSova** [comment]
There's already an open issue for this, so I'm going to close it.

The error explains what to do, just recreate the installer with Patched Sur then try again.

**Comment by toddanglin** [comment]
Since Google brought me here (and I assume others), here is a link to the most active thread on the issue with the damaged installer error: https://github.com/BenSova/Patched-Sur/issues/100
