### ISSUE TITLE
"Other Volumes in Container" along with an "Update" drive created while trying to install Big Sur

### ISSUE THREAD

**Issue by CM436again** [BenSova/Patched-Sur#632]
While trying to install Big Sur, I noticed there was only 19gb of storage left, not enough to install it. I restarted back into Catalina to see what was up with the storage and i noticed there was an "update" drive that was taking up 100gb up storage, about 50gb in Macintosh HD and 50gb in the Macintosh HD - Data. I previously installed it earlier today and this didn't happen. Anyone know how to get rid of it? This may not even be a problem with the patcher but i'm not sure.
![Screen Shot 2021-06-16 at 9 10 34 PM](https://user-images.githubusercontent.com/86034498/122325574-15e51000-cee8-11eb-9bf6-bf092326183e.png)

**Comment by BenSova** [comment]
It's not taking up 100GBs, it looks like it has only a couple MBs. The 100GBs of storage used up is your Macintosh HD and Untitled - Data volumes.
