### ISSUE TITLE
no backlight early 2013 MBP 

### ISSUE THREAD

**Issue by helpmyass** [BenSova/Patched-Sur#637]
so after installing mac os big sur using the patcher it worked for about 3 days then my backlight stopped working and is temperamental the system also isn't showing the second GPU  ![Uploading 64244922282__7A3CC987-8073-4671-8281-DCA2E1BF7F2E 2.JPG…]()
![RenderedImage](https://user-images.githubusercontent.com/86084456/122572565-c4eb2e00-d045-11eb-9ba7-b41d68654b97.JPG)

**Comment by BenSova** [comment]
Sounds like a hardware problem. The patches won't just "randomly" stop working, they either work or they don't.

**Comment by BenSova** [comment]
Actually, that's clearly not patcher bug because that screenshot is from Yosemite, and if it's a problem on Yosemite, then it's a hardware bug.

**Comment by helpmyass** [comment]
yes ben it is temperamental with anything newer than sierra and it has only stopped since i did the patcher on Catalina

**Comment by helpmyass** [comment]
there wouldn't be anything in that patcher that rewrites the code at all for the older Nvidia chip would there??

**Comment by BenSova** [comment]
I don't change with the firmware, only the software (which would only affect Big Sur, and I only have code for WiFi on that model).

**Comment by helpmyass** [comment]
> I don't change with the firmware, only the software (which would only affect Big Sur, and I only have code for WiFi on that model).

okay thank you then in that case it does seem to be a hardware issues thank you
