### ISSUE TITLE
Finder not working

### ISSUE THREAD

**Issue by AndreyZarembo** [BenSova/Patched-Sur#640]
**Describe the bug**
Finder not opening on mac after big sur install. Just doesn't open. Reboot and killing doesn't help.

**Details**
Finder not opening, nothing on Desktop, right-click not working...

**Expected behavior**
Finder works as expected )

**Screenshots**
![Device Info](https://user-images.githubusercontent.com/473710/122967501-318e6180-d393-11eb-90f2-25fb55ce29fb.png)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina 10.15.7
- Upgrading to: Big Sur 11.4
 - Mac Model: iMac 14,1 21.5-inch Late 2013
 - Version v0.2.1(96)

**Additional context**
- Reboot not helped
- Killall and restart not helped
- Open from terminal not helped and no logs/errors
- Nothing about Finder in system log

**Comment by ozziepadilla** [comment]
Hi, reboot your iMac and let it finish the indexing , it takes some time don’t  worry I have the same iMac

**Comment by AndreyZarembo** [comment]
@ozziepadilla Thanks! After about half an hour everything works fine.
