### ISSUE TITLE
error 1x137

### ISSUE THREAD

**Issue by wmikolaj** [BenSova/Patched-Sur#648]
while "creating usb installer"...
...I am getting the following error message 

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.4
 - Mac Model: 13" mid 2012 MacBook Pro (not retina)
 - Version v0.2.1
![137](https://user-images.githubusercontent.com/45784858/123504119-b14c5280-d657-11eb-92e3-38a9ab9b76c3.png)

**Comment by silveroffspring** [comment]
Have you used the right type of partition?

Do you have another USB Stick to try the installation?

**Comment by wmikolaj** [comment]
Not handy but I will buy if it might be the reason. Almost brand new sandisk. Partition type is correct for sure.  Saturday, 26 June 2021, 08:35AM +02:00 from silveroffspring  ***@***.*** :

**Comment by BenSova** [comment]
That's the error that shows up when you kill bash with Activity Monitor. I guess it could also happen if bash crashes, but there's really no reason that would happen. So it's either a user error or a bash bug, but not a patcher bug.
