### ISSUE TITLE
Does not finish patching usb 3.0 or 3.1. It is freezing

### ISSUE THREAD

**Issue by john7887** [BenSova/Patched-Sur#65]
Does not finish patching usb 3.0 or 3.1. It is freezing
![Screen Shot 2020-11-19 at 00 26 11](https://user-images.githubusercontent.com/74682554/99584135-f93e3380-29fd-11eb-8212-103473a1467f.png)

**Comment by bas1123** [comment]
Did you give it enough time? It took 45 min with mine

**Comment by john7887** [comment]
more than four hours it is freezing

**Comment by javierprz** [comment]
Same problem here. It has been patching USB for more than 6 hours and still continues...

**Comment by plopezsaiz** [comment]
Same problem, it only copied 29.2 MB to the USB drive.

**Comment by Jxid** [comment]
Here it copied 12.22 GB and now it says patching USB for more that 4 hours.Is it something wrong?

**Comment by harmon599** [comment]
I have the same issue

**Comment by BenSova** [comment]
Closing in favor of #156 where there has been more discussion.
