### ISSUE TITLE
Password File install Error

### ISSUE THREAD

**Issue by Rango98** [BenSova/Patched-Sur#66]
![Screen Shot 2020-11-18 at 4 09 37 PM](https://user-images.githubusercontent.com/74685130/99591839-5ebe0000-29bd-11eb-9ecb-03d2b555b88f.png)

I appreciate the help

**Comment by vly** [comment]
@Rango98 you probably pointed `swcdn.apple.com` to localhost?

**Comment by Rango98** [comment]
Appreciate the reply, I did not get a chance to enter anything.  I received this message after entering my password, which is four numbers.

**Comment by BenSova** [comment]
It looks like it downloaded a corrupt package. You could try downloading one yourself or trying again with 11.0.1 20B50 (it's the same thing as 11.0.1 20B29, just a different build number as far as I know). Patched Sur should be choosing 20B50 over 20B29.

**Comment by Rango98** [comment]
I tried that build, I am still getting the same error.

**Comment by rtwright68** [comment]
I'm seeing the same error, it comes up immediately after entering my password.  Tried it on a couple Macs, same result.

**Comment by Rango98** [comment]
Checking in to see if you have any suggestions on how to get past this?

**Comment by BenSova** [comment]
Try again I guess. A corrupt download is really the only possible reason.

I'm closing this issue since it probably was a corrupt download (or a bug with Apple's thing).
