### ISSUE TITLE
Am I 2 stupid??

### ISSUE THREAD

**Issue by peterdmann** [BenSova/Patched-Sur#664]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by peterdmann** [comment]
Am I 2 stupid. I would update my old MacBook Pro Retina, Early 2013.

But it will not selected any usb sticks. 

What is wrong?

Thanks
<img width="585" alt="Bildschirmfoto 2021-07-12 um 13 58 16" src="https://user-images.githubusercontent.com/87315891/125292107-06f05280-e31a-11eb-8b4e-26f808d7b26c.png">

**Comment by ozziepadilla** [comment]
That means you usb isn’t errase with the right commands must 
Mac OS extended journaled 
Guid partition map 
![3AE29B55-37B4-46A8-9DDA-9D5932C18681](https://user-images.githubusercontent.com/78187370/125292454-7bae9700-e2f0-11eb-856a-a40efcdd72ad.jpeg)

**Comment by peterdmann** [comment]
Ok, first thank you for your answer, sorry, but I can not find it with Catalina ;-(

**Comment by ozziepadilla** [comment]
> Ok, first thank you for your answer, sorry, but I can not find it with Catalina ;-(

Go to disk utility then to the menu bar “View” then select “ Show all devices “ and u will see your usb drive not the volume then select it and erase as shown in the pictures 
![BA5F470D-A2D5-4BC7-8BF4-8916BF6CEC57](https://user-images.githubusercontent.com/78187370/125293437-69812880-e2f1-11eb-886d-fcd24647bfa6.png)
![85C27722-AFD2-41DD-B89F-AD2221243B1E](https://user-images.githubusercontent.com/78187370/125293439-69812880-e2f1-11eb-981e-dedda1387168.png)

**Comment by peterdmann** [comment]
YOU made my day, thank you!!

**Comment by ozziepadilla** [comment]
No problem
