### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by AlexanderKharin** [BenSova/Patched-Sur#669]
![Снимок экрана 2021-07-20 в 20 33 11](https://user-images.githubusercontent.com/27703066/126369898-a0b0ed47-b2d9-4f5e-aceb-a50377ac5cc4.png)
Error 1x139
Message: "/bin/bash: line 1:  1312 Done                    echo 7350
      1313 Segmentation fault: 11  | sudo -S /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume '/Volumes/Big' --nointeraction"
Output: ""

**Comment by BenSova** [comment]
Hmm can you join the discord server (https://discord.gg/2DxVn4HDX6) and try the RC2 I sent (https://discord.com/channels/783554999791255585/783866390716219403/869595900182401084)? If it doesn't work, we can debug more, just ping me.

**Comment by BenSova** [comment]
Closing as there was no response.
