### ISSUE TITLE
Plug in USB installer and try again

### ISSUE THREAD

**Issue by ajrade** [BenSova/Patched-Sur#67]
Hello everyone,

I installed Big Sur on my Mac mini 2012 late. I used clean install (formatted SSD with previous Catalina).
Now I will not able to install kext. I did not search Big Sur patch in my Apps nor Launchpad :-(
So I downloaded it from this page and I am getting the callings:"Plug in USB installer and try again". My USB installer is inserted and viewable on my desktop. Mac was rebooted too without success. What could I do to get installing kexts ?

Thanx.
Rade

PS: How could I run .sh files ???
![Snímek obrazovky 2020-11-18 v 16 45 50](https://user-images.githubusercontent.com/74689858/99605942-9cbb2400-29bd-11eb-8da4-59f13ef46076.png)

**Comment by jtslvrs** [comment]
I am having the same issue. Hopefully, we can get this figured out.

**Comment by bas1123** [comment]
Hi, go to terminal and input this command: “/Volumes/Install macOS Big Sur/patch-kexts.sh”. (include the quotes). Then reboot. You should have the kexts implemented.

**Comment by jtslvrs** [comment]
Hi, it appears to return: "no such file or directory", referring to /Volumes/Install.

**Comment by bas1123** [comment]
Erase the usb, go to disk utility and format it to macOS extended journal GUID Partition Map and then run patched sur and start the process again. Patched Sur will erase your usb and install and do its work. Then try again.

**Comment by BenSova** [comment]
> Hi, it appears to return: "no such file or directory", referring to /Volumes/Install.

You forgot the quotes.

**Comment by BenSova** [comment]
This looks like the installer is mounted at a different mount point then what Patched Sur expects. Try restarting your Mac and trying again.

**Comment by ajrade** [comment]
> Hi, go to terminal and input this command: “/Volumes/Install macOS Big Sur/patch-kexts.sh”. (include the quotes). Then reboot. You should have the kexts implemented.
> […](#)
> On Nov 18, 2020, 19:46 -0500, ajrade ***@***.***>, wrote: Hello everyone, I installed Big Sur on my Mac mini 2012 late. I used clean install (formatted SSD with previous Catalina). Now I will not able to install kext. I did not search Big Sur patch in my Apps nor Launchpad :-( So I downloaded it from this page and I am getting the callings:"Plug in USB installer and try again". My USB installer is inserted and viewable on my desktop. Mac was rebooted too without success. What could I do to get installing kexts ? Thanx. Rade — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi,

It works for me. Thanks a lot, man :)

**Comment by juanmusico** [comment]
> This looks like the installer is mounted at a different mount point then what Patched Sur expects. Try restarting your Mac and trying again.

Hi, thanks for the patcher, I check and my usb stick is in the Imac main window, 
![Screen Shot 2020-12-15 at 08 49 38](https://user-images.githubusercontent.com/76047168/102211530-7d2af480-3eb2-11eb-9b7e-147e9e1436d3.png)


How can I run a the terminal command for that location to install kexts and enjoy?

Thanks a lot 
Pd:
![Screen Shot 2020-12-15 at 08 50 33](https://user-images.githubusercontent.com/76047168/102211606-9a5fc300-3eb2-11eb-867a-a811d2510815.png)

Thats my volumes

**Comment by BenSova** [comment]
This bug has been patched as of Patched Sur v0.1.0.
