### ISSUE TITLE
The Patched Sur doesn't open with MacOs 10.15.7 (19H1217)

### ISSUE THREAD

**Issue by doriansgithub** [BenSova/Patched-Sur#670]
The app requires OS 11?

**Comment by Monkiey** [comment]
> The app requires OS 11?

you must have downloaded the post-install app make sure you download the right file patched sur dmg that will be the app that helps you upgrade to macOS 11 from Catalina

hope this helps

**Comment by BenSova** [comment]
User error, so I'm closing this.

**Comment by doriansgithub** [comment]
I downloaded the latest of both the post and the patch and when the post opens, the patch shows with the not compatible symbol.

**Comment by Monkiey** [comment]
> I downloaded the latest of both the post and the patch and when the post opens, the patch shows with the not compatible symbol.
> […](#)

can you send a screenshot?

**Comment by doriansgithub** [comment]
Downloaded from here.

**Comment by BenSova** [comment]
Don't use email to send pictures, go to https://github.com/BenSova/Patched-Sur/issues/670 and send it from there.

**Comment by Monkiey** [comment]
i see that you download both files just click on patched sur dmg not post install dmg

**Comment by Monkiey** [comment]
you will use the post-app once you are on macOS 11 to patch kexts(so you can have wifi and conectivty features) and etc

**Comment by doriansgithub** [comment]
That worked! Thanks!!

**Comment by doriansgithub** [comment]
Brand new Thumb Drive, can’t get a GUID on it. Any ideas why that would be in the year 2021?

**Comment by Monkiey** [comment]
> Brand new Thumb Drive, can’t get a GUID on it. Any ideas why that would be in the year 2021?
> […](#)

didi you use disk utility

**Comment by doriansgithub** [comment]
First, thank you for answering my messages.


I had to search and finally found the solution.

https://discussions.apple.com/thread/4946118 <https://discussions.apple.com/thread/4946118>

Crazy world!!

Thanks again for all the help!

**Comment by Monkiey** [comment]
> First, thank you for answering my messages. I had to search and finally found the solution. https://discussions.apple.com/thread/4946118 <https://discussions.apple.com/thread/4946118> Crazy world!! Thanks again for all the help!
> […](#)

great, I am glad you got it to work

**Comment by doriansgithub** [comment]
Finished installation and did the kext and logged in. The screen is blinking.

**Comment by Monkiey** [comment]
what is your mac model?

**Comment by doriansgithub** [comment]
Found the problem. cDock needed updating.

It’s looking good!

Thanks!

**Comment by Monkiey** [comment]
> Found the problem. cDock needed updating. It’s looking good! Thanks!
> […](#)

wonderful, enjoy big sur
