### ISSUE TITLE
MacBook Late 2009 13" (white plastic) - No power indicator and charging...

### ISSUE THREAD

**Issue by uriversity** [BenSova/Patched-Sur#673]
Preexisting condition: successfully upgraded from El Capitan to Catalina. SSD drive and 8 GB of ram on board.
Ran the patch, saw the process undergo, got back to in the morning to find the machine powered off with no green led on (led on the connector), OS won't boot with the forbidden sign.
Running on battery, booting via recovery into the USB/patcher fires up a rudimentary-looking desktop, simple colors style desktop background with no wifi icon in the tray by the clock and the battery shows 20% remaining which inevitably dwindled down to no juice at all as I initiated further retires to either reboot as normal or begin the installation process all over again - to the point that currently, machine is lifeless with or without the actual battery within it, plugged in to the motherboard!
Won't turn on whatsoever.
Would seem reasonable to lose wifi or graphical capabilities however seems odd to lose the ability to simply get the current to run so to power on directly from the adapter (again, even when battery isn't connected inside).
Regardless, charger feels warm after a while in the power socket in the wall, even without attachment to the machine or so non is the wiser - until I lay my hands on a similar power adapter to test or get a reading that confirms charger proper operation.

Thank you in advance for any clues or ideas while I hunt down another adapter and/or attempt to replace depleted battery with a charged one for further investigations.

Uri.

**Comment by BenSova** [comment]
I don’t know how you got that far, but this patcher does not support pre-2012 Macs currently (though, no hardware problems would be caused if you did run it, Patched Sur is not the culprit for any of those weird problems). 

I suggest staying away from Patched Sur until I add official support for those Macs.
