### ISSUE TITLE
What is "Post-Install-Extra.zip"?

### ISSUE THREAD

**Issue by diparrag** [BenSova/Patched-Sur#68]
What is "Post-Install-Extra.zip"?
When should I use this file?

![image](https://user-images.githubusercontent.com/10927383/99680280-ddad4a00-2a4a-11eb-83f0-fa465eaa11ab.png)

**Comment by bas1123** [comment]
You use it when you’re updating from Catalina to kext to install wifi. Don’t use it if you’re doing a clean install

**Comment by diparrag** [comment]
I'll do a upgrade from Catalina. I'm currently downloading MacOS Big Sur (release version).
So, Do I extract the file from zip and install the app later upgrade to Big Sur?

![image](https://user-images.githubusercontent.com/10927383/99682400-26fe9900-2a4d-11eb-83f7-cc75a50b9e12.png)

**Comment by bas1123** [comment]
Yes

**Comment by bas1123** [comment]
Yeah or input this command with the quotes: “/Volumes/Install macOS Big Sur/patch-kexts.sh”

This command will also kext

**Comment by BenSova** [comment]
You do not need it. It is the post install app, but Patched Sur already has it downloaded in the dmg.
