### ISSUE TITLE
Patch Kexts

### ISSUE THREAD

**Issue by LeugimDev** [BenSova/Patched-Sur#680]
Hello, when updating to macos 11.5, the computer did not restart and I repeated the process, it seems that the download of the Patch Kexts failed and now when I go to install them it gives me a failure, since it does not detect them on the computer. How can i fix this?

This is my Error

```

> Error 1x1
> Message: "mount_apfs: volume could not be mounted: Resource busy
> mount: /System/Volumes/Update/mnt1 failed with 75
> Failed to mount underlying volume."
> Output: "Welcome to PatchKexts.sh (for Patched Sur)!
> 
> Checking environment...
> We're booted into full macOS.
> Confirming patch location...
> Patch Location: /usr/local/lib/Patched-Sur-Patches
> Checking WiFi patch configuration...
> No WiFi option specified, so checking for 802.11ac...
> No 802.11ac WiFi card detected, using WiFi patch.
> Auto-detecting Mac model...
> (Override with --2010, --2011, or --2012)
> Detected model: MacBookPro10,1
> Detected a 2012-2013 Mac. Using --2012 patches.
> Checking SIP status
> Checking what volume to patch...
> Booted into full Big Sur, using main volume.
> Installing kexts to volume /
> 
> Verifying volume...
> Volume has Big Sur build 20G71Correctly volume mount...
> Volume is mounted from device  /dev/disk1s5s1
> Mounted device is a snapshot.
> Attempting to mount underlying volume
> from device /dev/disk1s5 at temporary mountpoint:
> /System/Volumes/Update/mnt1
> 
> "

```

**Comment by BenSova** [comment]
> If you see the "Optimizing Your Mac" notification, give it time. It uses the volume that Patch Kexts needs to modify, so you cannot patch the kexts while that is going. If you do, you might run into weird errors (usually concerning mounting a volume saying the resource is busy). It's best to give this process 5 to 15 minutes (if you have an HDD or Fusion Drive, give it the full 15). This error can be solved by trying again when the "Optimizing Your Mac" process is done.

- From the terrible [Patched Sur docs](https://bensova.gitbook.io/big-sur/postinstall-after-upgrade/patching-the-kexts)

**Comment by LeugimDev** [comment]
3 days have passed since the message. Is there a way to force the download, update or installation of the patches?

**Comment by LeugimDev** [comment]
Well, curiously, I have tried again and everything solved ... we will have to laugh, it had been like this since Thursday and I had restarted the computer several times and left hours without activity.  as we say in my work ... is to appear the computer and work everything.  Thank you and I hope to see some of your tools for MacOS Monterrey ☺️
