### ISSUE TITLE
Unable to download from App Store 

### ISSUE THREAD

**Issue by pmcd** [BenSova/Patched-Sur#683]
Hi All,

Successfully installed Patch Sur on a Mid 2012 MB 15" Non Retina. Used v0.2.1(96). Ran all the Patch Kexts. 

I am unable to download directly from the App Store. Its starts the process and then stops.

I changed my iCloud password and Admin password. No joy. 

I deleted cach prefs. No Joy.

Date and time are correct.

Any suggestions?

Apart from that. Awesome work to be able to use this on an unsupported Mac. Brilliant.

**Comment by BenSova** [comment]
Sounds more like a Big Sur bug, not a patcher bug. The patcher doesn't affect anything other than how the software interacts with the hardware. Software working with services problems is a software bug.
