### ISSUE TITLE
When it enters the recovery screen the trackpad and keyboard become unresponsive.

### ISSUE THREAD

**Issue by djj0e** [BenSova/Patched-Sur#688]
When it enters the recovery screen the trackpad and keyboard become unresponsive. An external mouse also doesn’t work.

1. Hold option then select efi (Purple)
2. Hold option select Install MacOS Big Sur
3. After the Mac boots to recovery screen it becomes unresponsive.

System Info
 - Upgrading from: [Catalina v10.15.7]
- Upgrading to: [Big Sur v11.5.1]
 - Mac Model: [MacBook 13-inch, Late 2009 (White Unibody)]
 - Version [e.g. v0.2.1]
![6366ECE2-81A3-484B-A935-C836886FA940](https://user-images.githubusercontent.com/88333774/127889762-7cf15781-3aaa-4d54-9ab7-febf4b4c5423.jpeg)
![62824E29-C542-4C5E-8314-A54502C4D8C6](https://user-images.githubusercontent.com/88333774/127889786-8303a9e4-41a4-4a91-9e62-bcdeb49a4820.jpeg)

**Comment by BenSova** [comment]
I don't currently support that model
