### ISSUE TITLE
Error 1x1

### ISSUE THREAD

**Issue by antofou** [BenSova/Patched-Sur#69]
Hi, I try to install Big Sur thanks to you patch, and at stage" creating install media" I encountered this : 
Can you help me ? 
![Capture d’écran 2020-11-19 à 20 29 26](https://user-images.githubusercontent.com/74736825/99714474-ebdc8400-2aa5-11eb-87d0-a608af1c412d.png)

**Comment by BenSova** [comment]
The mount point for the installer is incorrect. I suggest making sure you have no other drives that macOS might confuse with Install macOS Big Sur and try again. **Also** you are using Patched Sur v0.0.2 (a?) when you should be using v0.0.3 to update to the release versions.

**Comment by antofou** [comment]
Thanks for your answers, I'll retry, unmounting all the other drives.
I'm astonished to see the v0.0.2a because I was pretty sur I've downloaded the v0.0.3.
However, I'll try later and let you know about it.

Thanks.

**Comment by antofou** [comment]
Nice, it's much better, I am able to go to the end. So now I have Big Sur on my Mac, but when I tried to patch Kexts I had this new error : 
![Capture d’écran 2020-11-20 à 19 16 40](https://user-images.githubusercontent.com/74736825/99835473-ebef8900-2b64-11eb-91a4-db526863bbb1.png)

**Comment by BenSova** [comment]
You can reboot, but nothing will happen. Try booting into the installer usb and running csrutil disable then trying again with patch kexts.

**Comment by antofou** [comment]
Well, I tried to reboot with cmd+R to run csrutil disable in the terminal. The reboot scared me cause I had a 45minutes dark screen with a downloading bar before accessing the to the Recovery Mode. And then the csrutil disable fonction did not work at all. 
So I'm still not able to patch kexts. But the iMac seems to work good. So I don't know if I must pursuit the patch or not.

Anyway, thanks a lot for your work. That's awesome to run Big Sur on my Mac.

**Comment by kzooking37** [comment]
I tried the csrutil disable and now I get this error: Error 1x1
Message: "Password:"
"csr-active-config appears to be set incorrectly:
csr-active-config	%10%08%00%00

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option."

**Comment by BenSova** [comment]
@antofou @kzooking37 You both seem to have 2013 iMacs, so you don't need to patch the kexts. I'm tracking a proofing idea for this in another issue, so I assume I can close this. If I'm wrong, feel free to reopen it.
