### ISSUE TITLE
csrutil disable then press enter....Not working 

### ISSUE THREAD

**Issue by iceguy147** [BenSova/Patched-Sur#692]
csrutil disable command not found

**Comment by BenSova** [comment]
You're booted into Mountain Lion, not El Capitan or later when csrutil was introduced. Use Cmd-Opt-R recovery then disable it. After that, you'll need to install recovery from the Patched Sur app so you can get some form of Cmd-R recovery (right now, you might have done Cmd-R, but you got Cmd-Shift-Opt-R, Install Recovery gives you back Cmd-R for quick things like csrutil). You will have no way to reinstall Big Sur from any recovery though, so you should hold on to your Installer USB that has a handy EFI Boot tool for disabling SIP that's instant.
