### ISSUE TITLE
'Creating USB Installer' page description not fully visible

### ISSUE THREAD

**Issue by jeffthejeffthejeff** [BenSova/Patched-Sur#694]
On the latest version (v0.2.1), during the installation process, on the 'Creating USB Installer' screen the description isn't fully visible as it cuts off 3 lines through where "allowing for" should be written.

![Creating USB Installer](https://user-images.githubusercontent.com/58886949/128522075-d4cb4cdb-61ae-459a-868e-c14ccae56f15.png)

**Comment by BenSova** [comment]
SwiftUI likes to act crazy and there's nothing really I can do about it. I have most things setup to show all lines, but they like to refuse sometimes.
