### ISSUE TITLE
Will this work on a Mac pro 3.1

### ISSUE THREAD

**Issue by treforparr** [BenSova/Patched-Sur#7]
And is there any way of integrating your software to make it work up with a Mac pro 3.1 Ready for the release of big sur This looks like a great tool it reminds me a dos dude patcher

**Comment by johncaling40** [comment]
What are the exact specs of the Mac right now?

**Comment by BenSova** [comment]
The Mac Pros would need a lot of changes from how my patcher currently works, so your best bet would be StarPlayrX's Big Mac Patcher.

**Comment by RevaliOnGithub** [comment]
Yeah just use his patcher.
