### ISSUE TITLE
Patching Kexts with 802.11ac Wifi

### ISSUE THREAD

**Issue by bocabimmer** [BenSova/Patched-Sur#70]
First off, thank you for all your hard work on this. So I have successfully installed Big Sur and was patching the kexts. I have a 15" MBP early 2013. I have upgraded the wifi card to the 802.11ac card from later models to enable Apple Watch unlocking.

When patching the kexts, below is the error message I get. Considering my unique circumstances, is this a problem? Everything seems to be working right now except the computer gets hot every once and a while. 

Thank you.

Error 1x1
Message: "Password:a BootKernelExtensions.kc
a SystemKernelExtensions.kc"
"No WiFi option specified on command line, so checking for 802.11ac...
Found 802.11ac WiFi card, so not installing a WiFi patch.
No patch mode specified on command line. Detecting Mac model...
(Use --2010, --2011, or --2012 command line option to override.)
Detected model: MacBookPro10,1
Detected a 2012-2013 Mac. Using --2012 patch mode.
Installing kexts to:
/

Volume appears to have a Big Sur installation (build 20B29). Continuing.
Volume is mounted from device:  /dev/disk1s5s1
Mounted device is a snapshot. Will now mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

Checking for KernelCollections backup...
Backup not found. Performing backup now. This may take a few minutes.
Backing up original KernelCollections to:
/System/Volumes/Update/mnt1/System/Library/KernelCollections/KernelCollections-20B29.tar.lz4
Beginning patched IO80211Family.kext installation
patch-kexts.sh encountered an internal error while installing the WiFi patch.
This is a patcher bug. patch-kexts.sh cannot continue."

**Comment by BenSova** [comment]
You have a 2012 Mac, that means you're good to go for everything but WiFi. You upgraded your Wifi card, so you are good to go in Big Sur, no need to patch the kexts.

**Comment by bocabimmer** [comment]
Thanks.
