### ISSUE TITLE
install recovery error

### ISSUE THREAD

**Issue by linux3** [BenSova/Patched-Sur#700]
im getting this error while trying to patched recovery from patched sur

Error 1x6
Message: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ia601405.us.archive.org"
Output: ""

im using macbook pro mid 2012 15"

**Comment by BenSova** [comment]
That's not a bug with the patcher but rather your Firewall/Whatever that's blocking sites.

**Comment by linux3** [comment]
> That's not a bug with the patcher but rather your Firewall/Whatever that's blocking sites.

![Screen Shot 2021-08-09 at 10 50 21 PM](https://user-images.githubusercontent.com/19578637/128726526-2e88b2e1-3f3a-4e17-bc30-64b72ff7cd43.png)

this is what i get sir i dont have any firewalls please help huhu

**Comment by BenSova** [comment]
Something is blocking the patcher's connection to https://ia601405.us.archive.org, and there's nothing I can do about it 🤷‍♂️

**Comment by linux3** [comment]
> Something is blocking the patcher's connection to https://ia601405.us.archive.org, and there's nothing I can do about it 🤷‍♂️ 

Can i just download it manually?
