### ISSUE TITLE
Patch-Kexts error

### ISSUE THREAD

**Issue by kaanakyalcin** [BenSova/Patched-Sur#701]
Macbook pro mid 2012 has been upgraded successfully at last week.
But today suddenly wifi stopped working.

I try to execute un patch  and patch kexts again.

But It gives below error.

Error 1x1 
Message: "mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
Failed to mount underlying volume."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /usr/local/lib/Patched-Sur-Patches
Checking WiFi patch configuration...
No WiFi option specified, so checking for 802.11ac...
No 802.11ac WiFi card detected, using WiFi patch.
Auto-detecting Mac model...
(Override with --2010, --2011, or --2012)
Detected model: MacBookPro9,2
Detected a 2012-2013 Mac. Using --2012 patches.
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Installing kexts to volume /

Verifying volume...
Volume has Big Sur build 20G80Correctly volume mount...
Volume is mounted from device  /dev/disk1s5s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

How can I fix this?

**Comment by BenSova** [comment]
Wait 15 minutes, reboot, wait 15 minutes again, patch.

You can also reboot into the Installer USB and patch from there.

**Comment by BenSova** [comment]
Also for the life of everything, don't unpatch using v0.2.1 or anything earlier.

**Comment by kaanakyalcin** [comment]
Waiting didn't work.
I updated the Mac to 11.5.2 from 11.5.1
and then try to execute patch-kexts

It worked!
