### ISSUE TITLE
Imac 2012 problema while downloading macOS 

### ISSUE THREAD

**Issue by gui-coder** [BenSova/Patched-Sur#707]
Error 1x28
Message: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0  762k    0     0  4767k      0  0:42:28 --:--:--  0:42:28 4737k
  0 11.5G    0 2687k    0     0  2223k      0  1:31:04  0:00:01  1:31:03 2221k
  0 11.5G    0 2687k    0     0  1214k      0  2:46:42  0:00:02  2:46:40 1214k
  0 11.5G    0 13.6M    0     0  4434k      0  0:45:39  0:00:03  0:45:36 4433k
  0 11.5G    0 32.9M    0     0  8124k      0  0:24:55  0:00:04  0:24:51 8122k
  0 11.5G    0 52.7M    0     0  10.2M      0  0:19:22  0:00:05  0:19:17 10.3M
  0 11.5G    0 73.6M    0     0  11.8M      0  0:16:37  0:00:06  0:16:31 14.2M
  0 11.5G    0 86.0M    0     0  11.9M      0  0:16:30  0:00:07  0:16:23 16.7M
  0 11.5G    0  104M    0     0  12.7M      0  0:15:31  0:00:08  0:15:23 17.9M
  1 11.5G    1  122M    0     0  13.3M      0  0:14:46  0:00:09  0:14:37 17.8M
  1 11.5G    1  141M    0     0  13.9M      0  0:14:13  0:00:10  0:14:03 17.7M
  1 11.5G    1  162M    0     0  14.5M      0  0:13:33  0:00:11  0:13:22 17.9M
  1 11.5G    1  182M    0     0  14.9M      0  0:13:12  0:00:12  0:13:00 19.2M
  1 11.5G    1  200M    0     0  15.2M      0  0:12:57  0:00:13  0:12:44 19.4M
  1 11.5G    1  219M    0     0  15.5M      0  0:12:44  0:00:14  0:12:30 19.4M
  2 11.5G    2  239M    0     0  15.7M      0  0:12:31  0:00:15  0:12:16 19.5M
  2 11.5G    2  258M    0     0  15.9M      0  0:12:23  0:00:16  0:12:07 18.9M
  2 11.5G    2  260M    0     0  15.0M      0  0:13:08  0:00:17  0:12:51 15.1M
  2 11.5G    2  260M    0     0  14.2M      0  0:13:54  0:00:18  0:13:36 11.5M
  2 11.5G    2  273M    0     0  14.2M      0  0:13:50  0:00:19  0:13:31 10.8M
  2 11.5G    2  291M    0     0  14.4M      0  0:13:40  0:00:20  0:13:20 10.4M
  2 11.5G    2  295M    0     0  13.8M      0  0:14:16  0:00:21  0:13:55 7418k
  2 11.5G    2  295M    0     0  13.2M      0  0:14:56  0:00:22  0:14:34 7170k
  2 11.5G    2  295M    0     0  12.6M      0  0:15:36  0:00:23  0:15:13 7169k
  2 11.5G    2  295M    0     0  12.1M      0  0:16:16  0:00:24  0:15:52 4354k
  2 11.5G    2  295M    0     0  11.6M      0  0:16:57  0:00:25  0:16:32  796k
  2 11.5G    2  295M    0     0  11.2M      0  0:17:37  0:00:26  0:17:11     0
  2 11.5G    2  295M    0     0  10.8M      0  0:18:17  0:00:27  0:17:50     0
  2 11.5G    2  295M    0     0  10.4M      0  0:18:57  0:00:28  0:18:29     0
  2 11.5G    2  307M    0     0  10.5M      0  0:18:43  0:00:29  0:18:14 2591k
  2 11.5G    2  331M    0     0  10.9M      0  0:18:00  0:00:30  0:17:30 7550k
  2 11.5G    2  352M    0     0  11.3M      0  0:17:28  0:00:31  0:16:57 11.8M
  3 11.5G    3  372M    0     0  11.5M      0  0:17:04  0:00:32  0:16:32 15.9M
  3 11.5G    3  376M    0     0  11.3M      0  0:17:29  0:00:33  0:16:56 16.2M
  3 11.5G    3  376M    0     0  10.9M      0  0:18:01  0:00:34  0:17:27 13.2M
  3 11.5G    3  382M    0     0  10.8M      0  0:18:11  0:00:35  0:17:36 10.2M
  3 11.5G    3  401M    0     0  11.0M      0  0:17:49  0:00:36  0:17:13 9939k
  3 11.5G    3  421M    0     0  11.3M      0  0:17:26  0:00:37  0:16:49 9968k
  3 11.5G    3  441M    0     0  11.5M      0  0:17:04  0:00:38  0:16:26 13.5M
  3 11.5G    3  460M    0     0  11.7M      0  0:16:48  0:00:39  0:16:09 17.4M
  4 11.5G    4  480M    0     0  11.9M      0  0:16:30  0:00:40  0:15:50 19.7M
  4 11.5G    4  495M    0     0  11.9M      0  0:16:30  0:00:41  0:15:49 18.0M
  4 11.5G    4  505M    0     0  12.0M      0  0:16:28  0:00:42  0:15:46 16.9M
  4 11.5G    4  514M    0     0  11.9M      0  0:16:35  0:00:43  0:15:52 14.4M
  4 11.5G    4  527M    0     0  11.9M      0  0:16:33  0:00:44  0:15:49 13.2M
  4 11.5G    4  545M    0     0  12.0M      0  0:16:21  0:00:45  0:15:36 13.0M
  4 11.5G    4  566M    0     0  12.2M      0  0:16:05  0:00:46  0:15:19 14.9M
  4 11.5G    4  588M    0     0  12.4M      0  0:15:52  0:00:47  0:15:05 16.2M
  5 11.5G    5  606M    0     0  12.6M      0  0:15:41  0:00:48  0:14:53 18.5M
  5 11.5G    5  611M    0     0  12.3M      0  0:15:58  0:00:49  0:15:09 16.0M
  5 11.5G    5  611M    0     0  12.1M      0  0:16:17  0:00:50  0:15:27 12.5M
  5 11.5G    5  611M    0     0  11.8M      0  0:16:37  0:00:51  0:15:46 8729k
  5 11.5G    5  611M    0     0  11.6M      0  0:16:56  0:00:52  0:16:04 4689k
  5 11.5G    5  611M    0     0  11.4M      0  0:17:16  0:00:53  0:16:23  963k
  5 11.5G    5  611M    0     0  11.2M      0  0:17:35  0:00:54  0:16:41     0
  5 11.5G    5  611M    0     0  11.0M      0  0:17:55  0:00:55  0:17:00     0
  5 11.5G    5  611M    0     0  10.8M      0  0:18:14  0:00:56  0:17:18     0
  5 11.5G    5  611M    0     0  10.6M      0  0:18:33  0:00:57  0:17:36     0
  5 11.5G    5  611M    0     0  10.4M      0  0:18:53  0:00:58  0:17:55     0
  5 11.5G    5  611M    0     0  10.2M      0  0:19:12  0:00:59  0:18:13     0
  5 11.5G    5  611M    0     0  10.1M      0  0:19:32  0:01:00  0:18:32     0
  5 11.5G    5  611M    0     0   9.9M      0  0:19:51  0:01:01  0:18:50     0
  5 11.5G    5  611M    0     0   9.7M      0  0:20:11  0:01:02  0:19:09     0
  5 11.5G    5  611M    0     0  9873k      0  0:20:30  0:01:03  0:19:27     0
  5 11.5G    5  611M    0     0  9719k      0  0:20:49  0:01:04  0:19:45     0
  5 11.5G    5  611M    0     0  9719k      0  0:20:49  0:01:04  0:19:45     0
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds"
Output: ""
![Captura de Tela 2021-08-13 às 18 10 29](https://user-images.githubusercontent.com/51805784/129418785-1a2e43b1-d85f-4c32-b6c7-a9ddae8366ef.png)

**Comment by BenSova** [comment]
Your Internet stability is not a patcher bug 🤷‍♂️. You can download it manually if you want.
