### ISSUE TITLE
Kexts (Wi-Fi) not working after update on BigSur 11.5.2 on iMac 2012

### ISSUE THREAD

**Issue by kor4insky** [BenSova/Patched-Sur#708]
Error 1x1
Message: "a BootKernelExtensions.kc
a SystemKernelExtensions.kc
Error Domain=KMErrorDomain Code=71 "Unable to resolve dependencies: 'com.apple.driver.AppleIntelFramebufferAzul' names a dependency on 'com.apple.AppleGraphicsDeviceControl', which was not found." UserInfo={NSLocalizedDescription=Unable to resolve dependencies: 'com.apple.driver.AppleIntelFramebufferAzul' names a dependency on 'com.apple.AppleGraphicsDeviceControl', which was not found.}
kmutil failed. Check the logs for more info."
Output: "Welcome to PatchKexts.sh (for Patched Sur)!

Checking environment...
We're booted into full macOS.
Confirming patch location...
Patch Location: /usr/local/lib/Patched-Sur-Patches
Checking WiFi patch configuration...
No WiFi option specified, so checking for 802.11ac...
No 802.11ac WiFi card detected, using WiFi patch.
Auto-detecting Mac model...
(Override with --2010, --2011, or --2012)
Detected model: iMac13,2
Detected a 2012-2013 Mac. Using --2012 patches.
Checking SIP status
Checking what volume to patch...
Booted into full Big Sur, using main volume.
Installing kexts to volume /

Verifying volume...
Volume has Big Sur build 20G95Correctly volume mount...
Volume is mounted from device  /dev/disk1s5s1
Mounted device is a snapshot.
Attempting to mount underlying volume
from device /dev/disk1s5 at temporary mountpoint:
/System/Volumes/Update/mnt1

Checking for KernelCollection backup...
Backup not found. Performing backup now. This may take a few minutes.
Backing up original KernelCollections to:
/System/Volumes/Update/mnt1/System/Library/KernelCollections/KernelCollections-20G95.tar.lz4
Begin replacing kexts...
Beginning patched IO80211Family.kext installation
Installing mojave-hybrid WiFi patch
Prepare for kmutil
Rebuilding boot collection...
Rebuilding system collection...
"

**Comment by BenSova** [comment]
Solution: Don't unpatch the kexts in the first place.

Better Solution from non-tired Ben: Reinstall macOS (not clean install, just reinstall).
