### ISSUE TITLE
Amazing job!  Need help with Error 1x2

### ISSUE THREAD

**Issue by DRM1234** [BenSova/Patched-Sur#71]
2012 Mac Mini - I am getting the following error when attempting to Patch Kexts:

Error 1x2
/bin/bash: -C: line 0: unexpected EOF while looking for matching ‘ “
/bin/bash: -C: line 1: syntax error: unexpected end of file

You have done a fantastic job creating this! I would've never been able to install Big Sur without your help. Thanks a ton!

**Comment by BenSova** [comment]
Can you try again with the latest patcher version?
