### ISSUE TITLE
Passwords issue

### ISSUE THREAD

**Issue by TurboSebo** [BenSova/Patched-Sur#710]
Can't install if password has special characters (my password had ";" character and patched sur couldn't accept administrator password), so I had to change password to "qwerty" to install update.

**Comment by BenSova** [comment]
Fixed already in v1.0.0rcs, if you search the issue list you'll see I've already closed several issues about this.

**Comment by Metroid-Prime** [comment]
https://github.com/BenSova/Patched-Sur/issues/46

@BenSova  I found out the same thing. Where is 1.0.0rcs?  The latest I found was 0.2.1 beta and am using that now.

PS: TY again for all your work on this.  This may save my life

**Comment by BenSova** [comment]
They're on the Ursinia Projects Discord. (link near the bottom of the README)

**Comment by BenSova** [comment]
Gonna close this since this is (and has been for a while) fixed now
