### ISSUE TITLE
Success 

### ISSUE THREAD

**Issue by suletetes** [BenSova/Patched-Sur#713]
Everything works very good thanks so much. Mac mid 2012. Thanks alot. I downloaded my big Sur software here I think is easy you just have to import it to patch sur here[Here](https://mrmacintosh.com/macos-big-sur-full-installer-database-download-directly-from-apple/)

**Comment by tmustopalamin** [comment]
on my mbp 2011 late, it happened after i applied post install, previously camera work normally but the wifi didnt work
