### ISSUE TITLE
iTunes opening alone

### ISSUE THREAD

**Issue by ThalesAugusto0** [BenSova/Patched-Sur#719]
**Describe the bug**
iTunes keeps opening by itself, I've tried to delete a file that prevents this but it didn't work, You close it, and almost instantly it opens again.

**Desktop (please complete the following information):**
- Upgrading to: [e.g. Big Sur v11.5.2]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.2.1]

**Comment by BenSova** [comment]
A) iTunes doesn't exist on macOS Big Sur, that's evidently a custom/modified copy that you have.
B) Software bugs are not patcher bugs.

**Comment by ThalesAugusto0** [comment]
I'm sorry, my external keyboard is opening the music app
