### ISSUE TITLE
Bigsur 11.1 beta

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#72]
@BenSova Apple released the Big Sur 11.1 beta, is patched sur compatible?

**Comment by BenSova** [comment]
The is no InstallAssistant.pkg for it, so I can't support it.

**Comment by BenSova** [comment]
Apple released one a little bit ago, so if you want to try it out, use the Developer beta track. I'm trying it right now.

**Comment by KevinMllrd** [comment]
I installed MacOS 11.0.1 with Patched-Sur V0.0.3.
I'm trying to upgrade to MacOS 11.1 but I'm stuck at the password entry step after selecting "Install macOS Big Sur Beta" step 11 of the Read Me.
My password is not recognized.
My only option is to reboot without being able to start the installation.

**Comment by KevinMllrd** [comment]
@BenSova Did you succeed in updating MacOS Big Sur from 11.0.1 to 11.1?

**Comment by BenSova** [comment]
@KevinMllrd Yeah, I kind of cheated though. It was a combination of Patched Sur and OpenCore. I convinced my Mac it was a 16" MBP with Open Core then used the native Software Update tool and later patched my kexts with Patched Sur. This is the first time I've done that and at the time there was no InstallAssistant.pkg so I took it as a reasonable time to try it.

By the way, FireVault does not work with Big Sur, I probably need to put a more prominent warning about that somewhere.

**Comment by KevinMllrd** [comment]
@BenSova I read, too late, that FireVault doesn't work with Big Sur. 
A warning in the Read ME would be a good thing. I followed it step by step.
A solution to fix the FiIreVault problem?

**Comment by BenSova** [comment]
@KevinMllrd Not that I know of. I assume that's an Apple Bug, but I'm not sure if it's an bug on supported Macs as well.

**Comment by ramonenghaw** [comment]
@BenSova Is it still necessary to use Opencore? even with InstallAssistant.pkg?

**Comment by BenSova** [comment]
@ramonenghaw No, I used Open Core because I wanted to be able to speed up normal software updates when I don't need to test Patched Sur, or update to versions that don't have the install assistant. In most cases, I would not recommend it, since using it is risky. ￼

**Comment by ramonenghaw** [comment]
@BenSova I understand your reasoning, but do we already have installassistant.pkg? In this case, would you just update the big sur that already has patched sur, or would you have to do a new installation?

**Comment by BenSova** [comment]
@ramonenghaw It's the same process you use to update Catalina to Big Sur. Make a usb and reinstall macOS with that to update it. No need to clean install. Soon I plan to make that process easier, maybe with a startosinstall command that could skip the usb entirely, but for right now you'll have to create the usb.

I haven't tested using the package myself, so the beta is only available through the Developer update track, but I'll add it to the Public Beta if somebody tests it.
