### ISSUE TITLE
NVRAM Error message

### ISSUE THREAD

**Issue by aniceberg** [BenSova/Patched-Sur#73]
iMac (21.5-inch, Late 2013) - iMac14,1

Everything seems to be working fine, but cannot patch Kexts with v0.0.3 Beta.

![image](https://user-images.githubusercontent.com/646958/99808776-5ece1500-2b0f-11eb-9e85-19f2f4e8bdcb.png)

**Comment by donmichele1** [comment]
I had to boot in the install big Sur stick and run via terminal  csrutil disable and csrutil authenticated-root disable. booting back in big Sur patch kexts is working, but - if you reset csrutil with csrutil enable big Sur won't boot anymore.

**Comment by BenSova** [comment]
Late 2013 iMacs don't need for you to patch your kexts. And yes, SIP has to be off for Patched Big Sur to work.

**Comment by donmichele1** [comment]
thanks for your comment, @BenSova BenSova that's absolutely right for iMac late 2013 - but - I had installed on an external ssd and booted also my macbook pro mid 2012 - and there i need wifi and of course the kexts patch. It is not so good leaving sip disabled in this machine. is there a workaround?

**Comment by BenSova** [comment]
No, Patched Sur has to modify system files to get WiFi and other things working. You could try running csrutil enable and csrutil authenticated-root disable but I'm not sure if that will boot or leave Wifi working.

**Comment by donmichele1** [comment]
so I did: running csrutil enable and csrutil authenticated-root disable. works! thanks for the hint @BenSova 

![Bildschirmfoto 2020-11-21 um 00 59 09](https://user-images.githubusercontent.com/74462450/99861365-1efe4080-2b96-11eb-9a4b-b6abe702c6e2.png)
