### ISSUE TITLE
required nvram value missing

### ISSUE THREAD

**Issue by doggielover** [BenSova/Patched-Sur#735]
After I updated to 1.0.0 patched sur was saying required nvram value missing. It is occuring on my imac 14,1 I have tried the sulotion but it still is there.

**Comment by Monkiey** [comment]
is this issue occurring after patching the boot plist

**Comment by doggielover** [comment]
> is this issue occurring after patching the boot plist

I don't know what that is

**Comment by Monkiey** [comment]
> > is this issue occurring after patching the boot plist
> 
> yes

okay to fix all you have do is reboot your mac

**Comment by Monkiey** [comment]
hopefully that fixes the issue

**Comment by Monkiey** [comment]
> > is this issue occurring after patching the boot plist
> 
> yes
> ![Screen Shot 2021-08-24 at 11 54 27 am](https://user-images.githubusercontent.com/70128537/130543296-2ac16b16-5550-4e3a-9163-c79ade95c5ff.png)

okay try to force quit patched sur and reboot your Mac that popup is bugged

**Comment by doggielover** [comment]
hopefully it works if it does'nt I'l try a nvram reset

**Comment by Monkiey** [comment]
> hopefully it works if it does'nt I'l try a nvram reset

okay

**Comment by doggielover** [comment]
> > hopefully it works if it does'nt I'l try a nvram reset
> 
> okay



> > > is this issue occurring after patching the boot plist
> > 
> > 
> > yes
> > ![Screen Shot 2021-08-24 at 11 54 27 am](https://user-images.githubusercontent.com/70128537/130543296-2ac16b16-5550-4e3a-9163-c79ade95c5ff.png)
> 
> okay try to force quit patched sur and reboot your Mac that popup is bugged

That same thing happens in my programing it's a hard issue to fix.
