### ISSUE TITLE
Can't scroll list of drives

### ISSUE THREAD

**Issue by xander-tk7** [BenSova/Patched-Sur#74]
Hi, appreciate the work you've already done on this. Not sure if I have a feature request or a bug... I can't see my USB drive because of the other drives I have inside the machine (Mac Pro 2012), so need a way to fully scroll the list, or have them laid out in a different way? Thanks again, Xan.

<img width="612" alt="Screenshot 2020-11-20 at 18 30 47" src="https://user-images.githubusercontent.com/19893814/99836808-8bf5e400-2b5e-11eb-80e5-9fa9e18c60b3.png">

**Comment by BenSova** [comment]
Yeah I'm working on laying them out another way, I distinctly remember putting a scroll view there though...

**Comment by xander-tk7** [comment]
Thanks for the reply :) haha the scrolling works up and down, not side to side 😁 so I can see the top of the names and the bottom of the names very well!

**Comment by kennedy** [comment]
I am having the same issue with being unable to scroll through my volumes side to side.

**Comment by xander-tk7** [comment]
Thanks for the validation kennedy. I needed it tbh. Hoping BenSova will come to the rescue for us.

**Comment by kennedy** [comment]
0.0.4 has the side scrolling :)

**Comment by BenSova** [comment]
I just improved it even more with v0.0.5, and I tested it, so I can close this issue.
