### ISSUE TITLE
No Wifi on MacBook Pro 2012

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [BenSova/Patched-Sur#75]
Hello, 

is there a patch available to install the wifi driver for the macbook pro 2012? Because I've searched and I couldn't find anything. Thanks for the installation program, everything works at home except the wifi. Thanks

**Comment by BenSova** [comment]
Did you run the post install app (Patched Sur in your Application click on Patch Kexts once you launch it)? Because I have the same MacBook Pro and you show no indication of running it.

**Comment by TechComputerServiceDunkerque** [comment]
> Did you run the post install app (Patched Sur in your Application click on Patch Kexts once you launch it)? Because I have the same MacBook Pro and you show no indication of running it.

I'll have a look, thanks for your answer, as everything is in English and I'm French, it's hard to understand because everything is in English.

**Comment by TechComputerServiceDunkerque** [comment]
Thank you, I hadn't seen the option, everything works very well. Thanks for the work.
