### ISSUE TITLE
2012 MBP Flashing screen and question mark

### ISSUE THREAD

**Issue by duvidel** [BenSova/Patched-Sur#751]
**Describe the bug**
One of our 2012 MacBook Pro has a flashing screen and question mark. We have the energy saver settings for battery and power adapter set to "never" turn off, in part because the particular computer has a bad power plug on the logic board and we didn't know about it when we bought it. If the plug comes out, it will shut off. However, the mag lite plug is secure in the computer and in an UPS. We don't think the problem is one of consistent electricity. 

We used the patcher to disable animations and graphics switching. 

Aside from age of the particular computer, is there anything I'm missing in Big Sur that would account for the problem? 
I'm not sure I can reproduce the screen freezing, but there's an arrow and a question mark on a black screen. Normally, cut computer should just awaken from sleeping like by pressing a key. If I have to press the power button, it doesn't awaken from sleep mode, but rather turns off. 

I can try an NVRAM reset after my wife is done using the computer. Beyond that, I have no idea. 

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.
- Upgrading to: Big Sur v11.5.2
 - Mac Model: 13" 2012 MacBook Pro
 - Version [e.g. v0.0.4]- unsure

Thanks. Be safe and well.

**Comment by BenSova** [comment]
This is not a patcher bug. Your firmware is not detecting the OS, and the patcher doesn't even touch things like that.

**Comment by duvidel** [comment]
Okee dokee. Thanks! 

Sincerely, 

David Mitchell Jacobs Schwartz
(314) 363-8087
***@***.***
https://www.dmjs.us

Pronouns: he, him, his
Most importantly, I want to create an inclusive world which is ours!

On Sep 1, 2021, at 6:51 PM, Ben ***@***.***> wrote:

﻿
This is not a patcher bug. Your firmware is not detecting the OS, and the patcher doesn't even touch things like that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
