### ISSUE TITLE
Accesibility not working after login sometimes

### ISSUE THREAD

**Issue by shines75** [BenSova/Patched-Sur#754]
Hi, Ben! Remember me? I’m italian and I’ve a MBP 15” mid 2012. A few months ago, a strange but nagging bug began to manifest itself: sometimes, after logging in, some apps like PopChar or Default Folder show pop-up windows, in which they complain that they can’t obtain accessibility permissions.
So, I go to Settings->Security->Privacy->Accessibility, and every time the list is empty and inaccessible - that is, you can’t add apps to the list!! Why?

**Comment by shines75** [comment]
Oh, I forgot: now I use Big Sur 11.5.2.

**Comment by BenSova** [comment]
You never could in the first place. Apps have to ask first, then you unlock the preference pane and press the checkmark.

And as I said before: Software bugs are not patcher bugs.

**Comment by shines75** [comment]
Just a tip: if someone else had run into the same problem, follow this [link](https://www.macworld.com/article/347452/how-to-fix-macos-accessibility-permission-when-an-app-cant-be-enabled.html).
