### ISSUE TITLE
sip is disabled

### ISSUE THREAD

**Issue by doggielover** [BenSova/Patched-Sur#756]
I am getting an error when patching boot.plist with is:
Error 1x1
Message: "[ERROR] SIP is on, which prevents the patcher from patching the kexts. Boot into the purple EFI Boot on the installer USB to fix this."
Output: "Checking environment...
[INFO] We're booted into full macOS.
[INFO] Using usr lib source.

Confirming patch location...
Welcome to PatchSystem.sh (for Patched Sur)!
Note: This script is still in alpha stages.

[INFO] Patch Location: /usr/local/lib/Patched-Sur-Patches
Checking csr-active-config...
"
I have sip disabled so I am confused.

**Comment by BenSova** [comment]
BUT you never ran `csrutil authenticated-root disable`
