### ISSUE TITLE
Error 1x1 | Password:sudo: 

### ISSUE THREAD

**Issue by ppnJTH** [BenSova/Patched-Sur#76]
Hi, I try to install Big Sur thanks to you patch, and at stage" creating install media" I encountered this:

Error 1x1
Password:sudo: /Volumes/patched-Sur/.patch-usb.sh: command not found

(MacBook Pro Mid 2012)
![Schermata 2020-11-16 alle 11 26 38](https://user-images.githubusercontent.com/74538739/99874442-5c8bb980-2be8-11eb-93a9-53b2883f242c.png)

Can you help me ?

**Comment by BenSova** [comment]
Guys... please... read the instructions. Where is the Applications folder link in the dmg? It's not supposed to go into your Applications. You are supposed to run it off the dmg. The dmg has several essential files that need to be used for the app to run.

**Comment by hugydoc** [comment]
Sorry but i don't understand
I Put Pached sur in the applications or i let it in the dmg ?
Thanks

**Comment by BenSova** [comment]
You keep it on the dmg.

**Comment by hugydoc** [comment]
It's good
thanks a lot

**Comment by hugydoc** [comment]
please where i can download Patched sur
I can't find
