### ISSUE TITLE
Mac OS Big SUR 11.6

### ISSUE THREAD

**Issue by sdahlmann** [BenSova/Patched-Sur#763]
How I can install Mac OS Big SUR 11.6 with the Patcher? I can‘t download the 11.6 MAC OS. Failed the full installer from Apple? Many thanks for your help.

**Comment by tchek** [comment]
Hi


I have the same issue here on iMac Late 2013. I'm on Big Sur 11.5.2 perfectly update with Patched Sur V 1.0.0 (115), but I have no alert for Big sur Update 11.6 et when i clic on Update, Patched Sur say there is no update.

Thanks for the lights

Cheers and take care

Bruno

**Comment by eshimischi** [comment]
It's not available yet, need to wait a little more, guys, same story and i'm patiently waiting

**Comment by tchek** [comment]
OK thanks eshimischi 👍🏻

**Comment by BenSova** [comment]
Not a bug, there's a discussion around it if you want to know what's going on. #762
