### ISSUE TITLE
After formatting drive and reinstalling Catalina Safari won't open.

### ISSUE THREAD

**Issue by LordSLC** [BenSova/Patched-Sur#772]
So after advertising my 20 1213 inch MacBook Pro for sale, I was messaged by an interested buyer, this individual requested that I restore the software from the Big Sur that I had installed with patched sur back to catalina, so I prepared a install USB, I waved the hard drive clean and installed a fresh clean copy of Catalina, after booting into macOS I found that Safari will not display a window at all, I was able to get chrome to work by copying the dot app file from my primary workstation to USB and transferring it over but no matter what I've tried including completely reinstalling again seems to be doing the trick.

Is there anything left over in the hardware or Pram or anything else that could be causing issues?

And if so is there a means of returning it back to factory? Or am I just sitting on a system that I have ruined for standard operation?

Thank you in advance,

Lex.

**Comment by BenSova** [comment]
Patched Sur's remains (two values in the NVRAM, just to skip a compatibility check) would not cause any of those problems. Patched Sur doesn't even touch the main software to begin with. This is probably some weird Safari bug.

**Comment by Monkiey** [comment]
So to elaborate on Ben statement make sure you rest pram

**Comment by Monkiey** [comment]
And your Mac will be fine

**Comment by BenSova** [comment]
That's not what I meant lol. I said that it won't change anything because it simply skips a compatibility check.

**Comment by Monkiey** [comment]
I said that it won't change anything because it simply skips a compatibility check.

Oh okay

**Comment by Monkiey** [comment]
Yeah but if he rest his pram that could help
