### ISSUE TITLE
Mid-2012 MBP - Seeking Firmware Patch For Sound And Display 

### ISSUE THREAD

**Issue by duvidel** [BenSova/Patched-Sur#774]
I currently use MacOS 11.6 and the newest patcher 1.0. I have apparently weird firmware issues. It’s not so much the sound as the icon keeps coming up in the middle of the screen so that’s pretty weird. In terms of display, after a while without use, instead of a normal screen, there’s black with a white outline arrow. I’ve turned off the display contrast and the graphics animation using the patcher

Is there a firmware patch devised by Ben Sova or someone else for sound and display for a 2012 MBP? If I need to return to a previous patcher, will it work with Big Sur 11.6?  When I open a different patcher, can I just run it once from the desktop or another file location, or do I need to take out version 1.0 and replace it with the old one? 

Thanks. Be safe and well. 

Thanks. Be safe and well. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by BenSova** [comment]
This sounds more hardware than patcher related.

**Comment by duvidel** [comment]
I know it sounds more hardware related. Is there a fix for the problems? Thanks. 

Sincerely, 

David Mitchell Jacobs Schwartz
(314) 363-8087
***@***.***
https://www.dmjs.us

Pronouns: he, him, his
Most importantly, I want to create an inclusive world which is ours!

On Sep 23, 2021, at 9:59 PM, Ben ***@***.***> wrote:

﻿
This sounds more hardware than patcher related.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
