### ISSUE TITLE
Finder not show left panel

### ISSUE THREAD

**Issue by dungInte** [BenSova/Patched-Sur#775]
**Expected behavior**
After update I can't see anything in finder. No left panel. I try to restart and shutdown but not thing change. It's is a bug or something that I don't know bout new update.

**Screenshots**
![finder not show left panel](https://user-images.githubusercontent.com/39627917/134756440-dfee5736-67f0-417c-9e0c-e6fd8bbfa2ca.png)

 - Upgrading from: [Catalina v10.15.7]
- Upgrading to: [Big Sur v11.6 ]
 - Mac Model: [15" Mid 2012 MacBook Pro]

**Comment by BenSova** [comment]
That's a really cursed Big Sur bug, but I'm not an Apple dev so I can't help you there.
