### ISSUE TITLE
Buttons not visible during install process

### ISSUE THREAD

**Issue by cetipool** [BenSova/Patched-Sur#79]
**Describe the bug**
The buttons seem to be cut off with labels not visible.  Can click on a small portion of the button and it works, but have no idea what I'm clicking.

<img width="511" alt="Screen Shot 2020-11-22 at 9 19 16 PM" src="https://user-images.githubusercontent.com/68999434/99903604-bb485480-2d08-11eb-88f3-6f1fb6d4f5e1.png">
<img width="510" alt="Screen Shot 2020-11-22 at 9 18 45 PM" src="https://user-images.githubusercontent.com/68999434/99903611-c0a59f00-2d08-11eb-9dd3-26f2a0d7864b.png">
<img width="510" alt="Screen Shot 2020-11-22 at 9 18 34 PM" src="https://user-images.githubusercontent.com/68999434/99903614-c307f900-2d08-11eb-937d-752c2158637f.png">
<img width="514" alt="Screen Shot 2020-11-22 at 9 18 24 PM" src="https://user-images.githubusercontent.com/68999434/99903617-c602e980-2d08-11eb-94c7-a75ba774208e.png">
<img width="520" alt="Screen Shot 2020-11-22 at 9 18 17 PM" src="https://user-images.githubusercontent.com/68999434/99903620-c7ccad00-2d08-11eb-87fc-9f550918fa49.png">

**Desktop (please complete the following information):**
- Upgrading from: Catalina 10.15.1
- Upgrading to: Big Sur 
- Mac Model: Mac Pro 5,1

<img width="600" alt="Screen Shot 2020-11-22 at 9 23 21 PM" src="https://user-images.githubusercontent.com/68999434/99903651-f77bb500-2d08-11eb-9388-70af44733b46.png">

**Comment by BenSova** [comment]
Update to Catalina 10.15.7. You are the only person that has reported this, and I suspect a bugged version of Catalina.

**Comment by Stefan-CPlanet** [comment]
I can Verify as someone who had the same issue.
10.15.1 gave the same error. I had an issue updating, Installed Catalina again from the store on top of my system (doesn't delete data) to get 10.15.7 and the issue is solved.

**Comment by BenSova** [comment]
This seems to be an Apple Bug therefore nothing can be done and not an issue of Patched Sur. Please stay on the latest versions of macOS, even when planning to patch to a new version of macOS.
