### ISSUE TITLE
Reset installer

### ISSUE THREAD

**Issue by greenimpala** [BenSova/Patched-Sur#8]
How can I reset all data and start again? Removing `~/.patched-sur` has resulted in an app error.

**Comment by BenSova** [comment]
If you start completely from the beginning and remove _everything_ in that directory, everything should work fine. What error does it show?

**Comment by datuck** [comment]
I tried to do that and I'm getting this error now.

`Error 1x1
Message: "Password:Error 2x1: Installer Not Found"
"Welcome to Patched Sur! (v0.0.2 build 10)
This script *should only* be used through
the Patched Sur app unless being tested
for patcher development

Detecting Installer USB at /Volumes/Install macOS Big Sur [Beta]...
Installer USB was not detected.
Please be sure to not rename the USB before
running patch-usb.sh.
"`

**Comment by datuck** [comment]
I'm getting this error when trying to start again.

Error 1x1
Message: "Password:Error 2x1: Installer Not Found"
"Welcome to Patched Sur! (v0.0.2 build 10)
This script *should only* be used through
the Patched Sur app unless being tested
for patcher development

Detecting Installer USB at /Volumes/Install macOS Big Sur [Beta]...
Installer USB was not detected.
Please be sure to not rename the USB before
running patch-usb.sh.

**Comment by BenSova** [comment]
So... I broke Patched Sur with v0.0.3 *really bad*. Download it again, I fixed it a while ago.

**Comment by ai-utt** [comment]
> So... I broke Patched Sur with v0.0.3 _really bad_. Download it again, I fixed it a while ago.

the new version fixed it for me at first, then tried using the same patched usb on a different mac -MacBook pro mid 2012- but after booting from the usb and clicking 'install macOS big sur beta' it never opens, like the system on the usb is still functional and all other options works but the install macOS... just the button stays grey and doesn't open (waited for more than 30 mins).

.

after that i tried to re-patch the usb from the MacBook pro and got the same error as **datuck**, the error happens for me after the 'select a usb volume' step:

> I'm getting this error when trying to start again.
> 
> Error 1x1
> Message: "Password:Error 2x1: Installer Not Found"
> "Welcome to Patched Sur! (v0.0.2 build 10)
> This script _should only_ be used through
> the Patched Sur app unless being tested
> for patcher development
> 
> Detecting Installer USB at /Volumes/Install macOS Big Sur [Beta]...
> Installer USB was not detected.
> Please be sure to not rename the USB before
> running patch-usb.sh.

**Comment by greenimpala** [comment]
<img width="612" alt="Screenshot 2020-11-12 at 11 21 46" src="https://user-images.githubusercontent.com/1367878/98934120-7f77e880-24d9-11eb-842a-583e32481562.png">
It's a nice idea this tool but at the moment there are too many bugs :) I will install manually.

**Comment by BenSova** [comment]
[Try This](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

**Comment by Twistashio** [comment]
Ok, I was having the same issue as well and this so far seems to work for me. Ill keep you updated

**Comment by Twistashio** [comment]
Ok I got an error but not sure how to get a log from it. 
![Screen Shot 2020-11-12 at 11 15 57 AM](https://user-images.githubusercontent.com/63883616/98965793-73d7f200-24d8-11eb-89ea-002dbd25074c.png)

**Comment by ai-utt** [comment]
> Try This

Error 1x1
Password:sudo: /Applications/Install macOS Big Sur Beta.app/Contents/Resources/createinstallmedia: command not found

**Comment by Twistashio** [comment]
Im going to try to reinstall the assistant package and see if that changes anything.

**Comment by BenSova** [comment]
I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

**Comment by ai-utt** [comment]
> I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

Error 1x1
Message: "Password:"
"installer: Error - the package path specified was invalid: '/Users/user/.patched-sur/InstallAssistant.pkg'."

**Comment by Twistashio** [comment]
Seems to be copying the installer for me now. Ill let it run for a while

**Comment by ai-utt** [comment]
interesting! why am i getting the error msg, I'll fully remove the installer, reboot and then i hope it works for me too.

**Comment by Twistashio** [comment]
I had it reinstall the install assistant as well. So maybe that helped

**Comment by ai-utt** [comment]
> I had it reinstall the install assistant as well. So maybe that helped

that worked for me, thank u. 

i had to reinstall them too by deleting the ".patched-sur" folder from /Users/user/.patched-sur
it's a hidden folder so had to show the hidden files by pressing Command+Shift+Dot

**Comment by ai-utt** [comment]
btw @BenSova can one of the first steps is to checks if there is already a ".patched-sur" folder, if yes so it gets deleted.

so people won't have the same issue we had. thank you.

**Comment by Twistashio** [comment]
It also auto deletes old installations when you install it again. Mines deleted the old one before installing

**Comment by ai-utt** [comment]
> It also auto deletes old installations when you install it again. Mines deleted the old one before installing

sorry, it auto delete old installations of what?

**Comment by ai-utt** [comment]
i

> I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)

it works!

**Comment by Twistashio** [comment]
Great I decided to wait until the release of big sur. Im installing it now

**Comment by Twistashio** [comment]
Where can I find the log output, there seems to be an error with installing the final release of Big Sur

**Comment by kimromanov** [comment]
Same problem. 

> i
> 
> > I think found the bug. [I'm 99% sure this will work.](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.3/Patched-Sur.dmg)
> 
> it works!

Doesn't help



> > I had it reinstall the install assistant as well. So maybe that helped
> 
> that worked for me, thank u.
> 
> i had to reinstall them too by deleting the ".patched-sur" folder from /Users/user/.patched-sur
> 
> note:
> it's a hidden folder so had to show the hidden files by pressing Command+Shift+Dot

Doesn't help

**Comment by BenSova** [comment]
@kimromanov What is the error? I'm not a magician.

**Comment by BenSova** [comment]
Btw the invalid package at path error is a result of Apple's servers being down, so I suggest trying to download it again.

**Comment by jlgra** [comment]
mise a jour sur catilina super ca a marcher du premier coup sup macbook pro 2012

**Comment by hugydoc** [comment]
Error 1x1
Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

I try 3 times and the same ????
How can resset ?

**Comment by BenSova** [comment]
> Error 1x1
> 
> Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found
> 
> 
> 
> I try 3 times and the same ????
> 
> How can resset ?

Follow the instructions, don't move the app to your applications folder. Run it like a .pkg file, keep it on the dmg and keep the dmg mounted. That is a totally unrelated issue to this.

**Comment by hugydoc** [comment]
hello
can you give me the adress where i can download Patched Sur
Thanks

**Comment by BenSova** [comment]
@hugydoc https://github.com/BenSova/Patched-Sur/releases/latest

**Comment by BenSova** [comment]
> btw @BenSova can one of the first steps is to check if there is already a ".patched-sur" folder, if yes so it gets deleted.
> so people won't have the same issue we had. thank you. 

@hugydoc @Twistashio 

I don't do this mainly because some users requested the opposite thing, which is if you already downloaded the InstallAssistant.pkg and you run into an error, redownloading the InstallAssistant.pkg is a waste of time.

The only time the app purposely deletes the InstallAssistant is when you go to download a new one and when you see the finished screen. 

Unless there's a better way, I'm not sure how to address this. I'm thinking of adding a redownload button next to the Use macOS 11.0.1, but I'm not sure what the basis of this issue is and what to do about it. What's your guys suggestions?

**Comment by BenSova** [comment]
![Screen Shot 2020-12-31 at 10 24 49 AM](https://user-images.githubusercontent.com/65474198/103419942-70fd9300-4b52-11eb-8419-249a081d2816.png)
Since there hasn't been any further discussion on this issue, I'm going to close it. I've added the only logical addition I can add to fix this, so I'm not sure what else I could do.

**Comment by sam20201** [comment]
hi Ben,

I received the following error on the new version 6:

Error 1x1
Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"
Output: ""

**Comment by BenSova** [comment]
You also got the popup telling you that the Patched Sur DMG is not detected right?

**Comment by sam20201** [comment]
No I didnt.

**Comment by sam20201** [comment]
I tried to do it again, but I received the following error again:

Error 1x1
Message: "Error: -69888: Couldn't unmount disk"
Output: "Started erase on disk4
Unmounting disk
The volume on disk4 couldn't be unmounted because it is in use by process 7530 (diskimages-helper)"

**Comment by jona45** [comment]
when I put in my password it goes blank and does not move on
