### ISSUE TITLE
Stuck in password window (iMac late 2013)

### ISSUE THREAD

**Issue by YBStark** [BenSova/Patched-Sur#82]
Hello,

While trying to upgrade to Big Sur, I am stuck in the password window (just after OS X download).
Nothing happen, I entered my password many times until the "continue" button become red.

Many thanks for your help.

**Comment by AdrienDole** [comment]
Does your password contain chars like " or ' ?

I've had this problem and to bypass I changed my password to a simple one only for the update then after I'll change back to the previous one

**Comment by YBStark** [comment]
> Does your password contain chars like " or ' ?
> 
> I've had this problem and to bypass I changed my password to a simple one only for the update then after I'll change back to the previous one

Hi AdrienDole,

Thank you very much! Indeed it is composed with special char.

**Comment by BenSova** [comment]
Yeah, I fixed it for " but not '. Note to self I guess.

**Comment by plopezsaiz** [comment]
> Does your password contain chars like " or ' ?
> 
> I've had this problem and to bypass I changed my password to a simple one only for the update then after I'll change back to the previous one

Worked for me! Thank you.

**Comment by BenSova** [comment]
Closing in support of #46.
