### ISSUE TITLE
Recovery mode rejecting password

### ISSUE THREAD

**Issue by KevinMllrd** [BenSova/Patched-Sur#83]
I installed MacOS 11.0.1 with Patched-Sur V0.0.3 on my MacBook Pro 15" (Retina, mi-2012) without any problems.
<img width="520" alt="Capture d’écran 2020-11-22 à 15 53 57" src="https://user-images.githubusercontent.com/74859891/99907136-5f1b0b80-2cdb-11eb-9ad7-2322d1262461.png">

I'm trying to upgrade to MacOS 11.1 Beta with V0.0.4 but I'm stuck at the password entry step after selecting "Install macOS Big Sur Beta" step 11 of the Read Me.
![IMG_7082](https://user-images.githubusercontent.com/74859891/99908240-c471fb00-2ce1-11eb-9a9c-8d1663b6c7ff.jpg)

My password is not recognized.
![IMG_7083](https://user-images.githubusercontent.com/74859891/99908247-ccca3600-2ce1-11eb-8bb8-4dcace6b3db1.jpg)

My only option is to reboot without being able to start the installation.

I try to disable FileVault but get error -69550 when I try to do it via fdesetup. It also doesn't work when I try to disable it in the System Preferences.

_Originally posted by @KevinMllrd in https://github.com/BenSova/Patched-Sur/issues/72#issuecomment-731734826_

**Comment by BenSova** [comment]
Nice to know that my custom icons work on some Macs. (Mine doesn't work with them, which is really annoying to me).

Addressing your issue: FileVault does not work in Big Sur, I'm not sure if this is an Apple bug or not.

**Comment by BenSova** [comment]
@KevinMllrd Can you run a command in terminal for me? `fdesetup status` I would just like to know the output.

**Comment by KevinMllrd** [comment]
The result is 
`FileVault is On.
`

**Comment by BenSova** [comment]
Okay, thanks. I will make the warning bigger and more severe (Patched Sur will refuse to work) now. I'm not sure why it failed to turn back off, but we'll see if there is some way to fix it.

**Comment by KevinMllrd** [comment]
Hello,
I just noticed when I open my Terminal the name "Galaxy-A10-de-Eter". 
Is there a link between the machine name change and the problem I'm having with FileVault?
I did not create the name "Galaxy-A10-of-Eter".
Normally it's "MacBook-Pro-de-Kevin".

`Last login: Wed Dec 16 09:30:12 on console`
`Galaxy-A10-de-Eter:~ kevinmllrd$ pwd`
`/Users/kevinmllrd`
`Galaxy-A10-de-Eter:~ kevinmllrd$ 
`

**Comment by molekulek** [comment]
I had exactly the same problem with password...

**Comment by m-a-v** [comment]
> Okay, thanks. I will make the warning bigger and more severe (Patched Sur will refuse to work) now. I'm not sure why it failed to turn back off, but we'll see if there is some way to fix it.

Unfortunately, I also fell into this trap. It's pretty clear if you read the manual on the big-sur-micropatcher site (which I didn't before). It would be very important to test this or to document it in the meantime on the GitHub page.

I read somewhere that you can use a Time Machine backup to reinstall the system, but I haven't tried it yet. Has anyone done this with success? If so, how exactly does one have to proceed?
Does anyone know by chance how a Time Machine restore behaves if you have an additional Boot Camp partition?

Recovery Mode doesn't work for me anymore either. It always comes the mode which starts via Internet. When I activate the recovery partition (using Open Core), I also have to enter the password. The credentials are not accepted. That's exactly what the error -69550 means. A restore via Apple ID does not work either. I guess to disable fdesetup you have to have SIP enabled. That would make sense in my opinion ...

**Comment by BenSova** [comment]
![Screen Shot 2020-12-26 at 7 41 16 AM](https://user-images.githubusercontent.com/65474198/103153443-c5b59e00-474d-11eb-9506-ed27f2274660.png)
Better?

Anyway, I'm going to add some proofing in the next release, if any of you want to update to 11.1, just do what @m-a-v said. Make a 11.0.1 Time Machine backup and create an 11.1 installer usb with Patched Sur then wipe your drive and install macOS with it and restore the backup.

**Comment by BenSova** [comment]
> Recovery Mode doesn't work for me anymore either.
That's just a general problem with patching nothing to do with FileVault, however I have a theory on how I can bring it back (along with a couple of Patched Sur utilities).

**Comment by m-a-v** [comment]
Thank you.

Anyone can confirm this: Is the FileVault error (?) a limitation because of having System Integrity Protection (SIP) disabled. Or is this a bug introduced with Big Sur? If it is a bug, has it been fixed with macOS 11.1?

When reinstalling 11.1 from scratch, when can the user choose to enable/disable FileVault? I don't remember actively selecting that when installing macOS (although I can't rule that out either).

**Comment by m-a-v** [comment]
> Nice to know that my custom icons work on some Macs.

I have also those icons. I had interpreted the EFI icon to mean this is not bootable as it is crossed through in red.

**Comment by BenSova** [comment]
> Anyone can confirm this: Is the FileVault error (?) a limitation because of having System Integrity Protection (SIP) disabled. Or is this a bug introduced with Big Sur? If it is a bug, has it been fixed with macOS 11.1?

I'm not sure, but that sounds reasonable. 

> When reinstalling 11.1 from scratch, when can the user choose to enable/disable FileVault? I don't remember actively selecting that when installing macOS (although I can't rule that out either).

I just did a fresh install on my Mac, as I upgraded from a 256 GB SSD to a 1 TB SSD, and it came disabled by default. 

> I have also those icons. I had interpreted the EFI icon to mean this is not bootable as it is crossed through in red.

Yeah, it's purple on my current working copy so it doesn't show that meaning anymore and shows something more like get rid of this symbol.

**Comment by molekulek** [comment]
I can't turn off FileVault and I get the message in console "FileVault was not disabled (-69550)"

**Comment by DovidBirk** [comment]
Just confirming right now - other people are having this problem and it is a work in progress? Is that correct? 
I had the same issue on 2 separate macbook pros mid 2012. One 13 in. One 15 in. Both rejected the password. 
The alternative of signing in with Apple ID was also rejected. 
Thank you again for all your help.

**Comment by BenSova** [comment]
There's no way I can fix this problem. FileVault never worked on unsupported Macs, and probably never will. I already implemented a proofing feature into my working copy of Patched Sur that will come with v0.1.0 that will completely prevent people from upgrading if they have FileVault on.

**Comment by DovidBirk** [comment]
The thread was unclear to me. Is it the fire vault that is causing the problem? And there is no way to work around this? 
Is there something I can check on or change to work around this password issue?

Dovid Birk
917 841 3256
ChabadCornell.com

**Comment by DovidBirk** [comment]
Re the comment above. I never brought up the issue of a fire vault. Is that the reason I'm getting my password rejected? How come this wasn't an issue to get to 11.1. That worked fine. 
Should I try turning my fire vault off in settings and then installing Big Sur? That seems like a simple step. Are there any concerns in doing that?

**Comment by BenSova** [comment]
The big problem is that you can't turn off FileVault with settings. You have to wipe your disk, install Big Sur and restore from a backup. There's no workaround.

**Comment by DovidBirk** [comment]
Okay. So what to do? Will you be releasing updates with the patcher that will avoid this issue? Should I just wait? Or do I need to turn off fire vault and wipe the disk?
Please advise. Thank you.

Dovid Birk | Rabbi | LLB BSc
Program Director, Chabad Cornell
ChabadCornell.com <http://www.chabadcornell.com/>
917 841 3256 | Ithaca NY

Mission: Materialize the Spiritual and Spiritualize the Material

Chabad’s work this last fall in pics >> HERE <https://mailchi.mp/93b1917b45fa/what-a-semester-thank-you-for-making-it-possible>

Change Jewish life forever at Cornell with a NEW Chabad >> HERE <https://www.buildchabadcornell.com/>

**Comment by BenSova** [comment]
A new update coming out will avoid other people from getting this issue, but won't directly fix it. You'll need to wipe your disk and restore from a backup.

**Comment by DovidBirk** [comment]
Okay. So what are the steps? 

Go to settings - turn off fire vault?
Then wipe disk using disk utility?
Afterward choose reinstall OSX and use the USB I just made for Big Sur 11.2?
All my info is backed up using iCloud. 

I’m sorry for this level of detail, but if you can share the steps, or refer me to a video that goes through the steps, that would be easiest. 

Thank you again. 

Dovid Birk
917 841 3256
ChabadCornell.com

**Comment by m-a-v** [comment]
@DovidBirk You can't disable File Vault. You will need a Time Machine backup and then you would make a clean install using a USB installer. By default File Vault will be disabled for the fresh install, as @BenSova also mentioned above. I have no experience with iCloud. Personally, I would make a backup via Time Machine if I were you.

**Comment by m-a-v** [comment]
I think this issue should be closed as soon as v1.0 is out.

**Comment by DovidBirk** [comment]
What’s the best method to do a clean install? And wiping the disk?

Also, is this 100% the issue?

How come this wasn’t an issue for the install of Big Sur 11.1?

Dovid Birk
917 841 3256
ChabadCornell.com

**Comment by DovidBirk** [comment]
I’m sorry. I need help here. According to Apple, you can just turn off fire vault: https://support.apple.com/guide/mac-help/turn-off-filevault-encryption-on-mac-mchlp2560/11.0/mac/11.0 <https://support.apple.com/guide/mac-help/turn-off-filevault-encryption-on-mac-mchlp2560/11.0/mac/11.0>

That being said, if that won’t help, do we know for sure it’s the fire vault that is causing this password rejection?

If so, and I need to wipe my disk and reinstall then: 

1. Is the USB that I made from the 11.2 install good? Or is it just an update? If so, how do I make a Big Sur USB for a clean install? 

2. Whats the procedure to wipe the disk and reinstall Big Sur? Is this with disk utility? Erase HD? 

3. Please help. 

Thank you.

Dovid Birk | Rabbi | LLB BSc
Program Director, Chabad Cornell
ChabadCornell.com <http://www.chabadcornell.com/>
917 841 3256 | Ithaca NY

Mission: Materialize the Spiritual and Spiritualize the Material

Chabad’s work this last fall in pics >> HERE <https://mailchi.mp/93b1917b45fa/what-a-semester-thank-you-for-making-it-possible>

Change Jewish life forever at Cornell with a NEW Chabad >> HERE <https://www.buildchabadcornell.com/>

**Comment by BenSova** [comment]
You cannot just turn off FileVault on unsupported Macs. It fails each time. Also, yes we are 100% sure that it is because FileVault.

**Comment by DovidBirk** [comment]
Okay. I'll do the erase. Thank you. Can you help me with the other questions?

1. Is the USB that I made from the 11.2 install good? Or is it just an update? If so, how do I make a Big Sur USB for a clean install?

2. Whats the procedure to wipe the disk and reinstall Big Sur? Is this with disk utility? Erase HD?

Thank you.

**Comment by BenSova** [comment]
1. Yes it's good
2. Yes, use disk utility

**Comment by DovidBirk** [comment]
Can you confirm these steps:
Sign out of ICloud
Turn off "find my Mac"
Restart and hold Command & R
Disk Utility
Erase SSD - OSX Journaled and Guid Partition
Then click "reinstall Mac OS" and choose the USB Big Sur Installer 11.2
Or is should I replace step 6 with restarting the Mac and holding down the ALT key. And then boot into EFI and then Big Sur Installer? Or skip the EFI step and just install Big Sur?

Any help here is much appreciated. 

And then you are saying that fire vault will be turned off?

Dovid Birk | Rabbi | LLB BSc
Program Director, Chabad Cornell
ChabadCornell.com <http://www.chabadcornell.com/>
917 841 3256 | Ithaca NY

Mission: Materialize the Spiritual and Spiritualize the Material

Chabad’s work this last fall in pics >> HERE <https://mailchi.mp/93b1917b45fa/what-a-semester-thank-you-for-making-it-possible>

Change Jewish life forever at Cornell with a NEW Chabad >> HERE <https://www.buildchabadcornell.com/>

**Comment by BenSova** [comment]
1. Sign out of icloud and find my mac
2. Restart into the installer usb
3. Click Erase Disk which is in one of the menus in the menu bar even if you don't enter your passowrd.
4. I'm pretty sure that will try to reboot into Recovery mode afterwards, so instead boot into the EFI Boot then the installer again
5. Click Install macOS Big Sur then the name for your drive (probably Macintosh HD)
6. Boot back into the installer usb and run `/Volumes/"Image Volume"/patch-kexts.sh /Volumes/"Macintosh HD"` (replace Macintosh HD with the name of your drive, which is probably Macintosh HD, keep all the quotes) in Terminal (under the utilites menu)
7. Boot back into macOS and continue setup restoring from the backup when given the option, I'm not sure if this is required, but if it has an option to move over only files and not settings, do that. I don't think it's necessary, but I could be wrong.

**Comment by DovidBirk** [comment]
Thank you. 

Dovid Birk
917 841 3256
ChabadCornell.com

**Comment by DovidBirk** [comment]
Dude. It worked. Champion. MacBook 13in running perfectly on Big Sur 11.2. Firevault is off. Wifi is working. 

THANK YOU SO MUCH! Will do the same thing on my MacBook 15in later this week or next week. 

Dovid Birk | Rabbi | LLB BSc
Program Director, Chabad Cornell
ChabadCornell.com <http://www.chabadcornell.com/>
917 841 3256 | Ithaca NY

Mission: Materialize the Spiritual and Spiritualize the Material

Chabad’s work this last fall in pics >> HERE <https://mailchi.mp/93b1917b45fa/what-a-semester-thank-you-for-making-it-possible>

Change Jewish life forever at Cornell with a NEW Chabad >> HERE <https://www.buildchabadcornell.com/>

**Comment by Brendianer** [comment]
Looks great. Will work on this tonight.
Just a question: what do you mean with Step 7?

**Comment by DovidBirk** [comment]
I booted into the USB and ran the terminal command after Big Sur was already installed. So step 7 wasn't necessary.

**Comment by BenSova** [comment]
Step 7 is just go through the macOS setup assistant

**Comment by BenSova** [comment]
I released Patched Sur v0.0.5 which will prevent new users from running into this problem. I'll leave this issue open though because some people might not know they have FileVault on, and they will want to know how to fix it.

**Comment by JJFUENTES22** [comment]
> I released Patched Sur v0.0.5 which will prevent new users from running into this problem. I'll leave this issue open though because some people might not know they have FileVault on, and they will want to know how to fix it.

I actually upgraded into Big Sur 11.1 with v0.0.5 So now, am trying to jump to 11.2 but i noticed that my filevault is also on and cant be turned off so not sure what would be the next appropriate step. Appreciate for all the help you given thus far BenSova.

**Comment by BenSova** [comment]
Look here -> https://github.com/BenSova/Patched-Sur/issues/83#issuecomment-772913509

**Comment by JJFUENTES22** [comment]
> Look here -> [#83 (comment)](https://github.com/BenSova/Patched-Sur/issues/83#issuecomment-772913509)

Alright Sweet! thank you

**Comment by isheepman** [comment]
What do I erase the usb or the hhd/ssd

**Comment by BenSova** [comment]
SSD

**Comment by BenSova** [comment]
Closing since this doesn't really matter anymore.
