### ISSUE TITLE
Stuck Prohibitory Symbol after boot from USB

### ISSUE THREAD

**Issue by AdrienDole** [BenSova/Patched-Sur#84]
Hello,

Once process completed and rebooting to see the USB Installation.

I've pressed on this one and now I face the screen I'm sharing on this issue.

Any idea ?
![IMG_0193](https://user-images.githubusercontent.com/6368012/99908706-5c70e400-2ce4-11eb-9497-ec7486ebadba.JPG)

**Comment by Monkiey** [comment]
Did you boot into the EFI(yellow drive first)it should shutdown your mac? Then turn on your mac again and press the option and boot into the boot drives selection menu again its time to select the Install macOS Big Sur drive.

From the instructions in the README
Select the yellow EFI Boot drive, (if there are multiple unplug and replug in your drive and select the EFI Boot that disappeared and reappeared). Then, your Mac will quickly turn off, so turn it back on while, again, holding down Option/Alt. Then, select Install macOS Big Sur Beta.

**Comment by Morrile37** [comment]
I had this very same problem, realised my mistake, and now it's installing

**Comment by AdrienDole** [comment]
Hello everybody !

Such a great community.

Indeed I didn't start EFI Boot at first ..

But still even though I managed to install Big Sur properly, I found out that when I hard reset my Mac, while pressing the Option/alt Button, I cannot go the the selection of the Hard Drive I want to boot from.

It's a miracle that only with the soft reboot I managed to install Big Sur.

But to conclude, I'm on Big Sur, that's great news :)

**Comment by mabeljarsdel** [comment]
@BenSova Hi!

I have the same problem.

I've used Version 0.2.1 (96) to prepare a 16gb USB install of Big Sur 14. The patch was successfully installed on USB.
The iMac specifications attached. 

Error: when I'm trying to boot from the USB installer I'm getting the same image and after 30-40 seconds the iMac shuts down itself. 

I tried also to run the CMD+Option+R, but I got a black screen with following error:
```
Error: 8000000000000003, Cannot load 'EFI/Drivers/TestSupport.efi'
Status: 0x00000003
```

Please help.

![Screen Shot 2021-05-26 at 22 05 47](https://user-images.githubusercontent.com/55481321/119717124-94f9a200-be6e-11eb-94d6-25e571a9ba3f.png)

**Comment by BenSova** [comment]
What happens if you boot into the EFI Boot?

**Comment by mabeljarsdel** [comment]
Sorry @BenSova to disturbing you. I fixed it.
I installed yesterday Big Sur 11.3, but cannot update it to 11.4, is it possible?

**Comment by BenSova** [comment]
This video explains updating with the patcher pretty well. The UI changed a bit since this, but all the buttons are named the same/similar thing.

https://www.youtube.com/watch?v=Pl08ozRtTK4

**Comment by Monkiey** [comment]
![Screen Shot 2021-05-27 at 7 02 00 AM](https://user-images.githubusercontent.com/28370827/119840094-85537b00-beb9-11eb-8a4c-f9c049d2644c.png)
All you have to do is open the post-install app the same one you use to patch kexts and click on run updates, this will get you to 11.4

**Comment by mabeljarsdel** [comment]
Thanks a mil @Monkiey & @BenSova!
