### ISSUE TITLE
Error 1x250

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#85]
Error 1x250
Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100%
2020-11-22 11:38:41.334 createinstallmedia[2607:78331] There was an error parsing the Info.plist for the bundle at URL <0x7f8e55bd0560>: NSCocoaErrorDomain - 3840
Couldn't mount dmg /Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
"Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

**Comment by BenSova** [comment]
I think this has been fixed with the latest version of macOS and patcher.

**Comment by BenSova** [comment]
Since no one has reported this bug in a while and I talked to some other people that got it working with much more recent versions of macOS and the patcher, I will close this issue.
