### ISSUE TITLE
Post-Install Error

### ISSUE THREAD

**Issue by Skinnyman180** [BenSova/Patched-Sur#87]
I created the USB installer and installed Big Sur. But when I went to run the patch program afterwards, I keep getting this error. I tried rebooting into EFI but still get it.

...nvram: Error getting variable - 'csr active-config',iokit/common data
String variable - 'csr active-config': (iokit.common) data not found
...(can't read myself) appears to be set incorrectly.

boot the setters EFI utility, then book back into macOS

**Comment by iMiMx** [comment]
On what device? I had this with my Late 2013 iMac, turned out that it didn't actually need any post-install patches - if you run 'patch-kext.sh --force' from the cli, it spits out an explicit message stating as such.

**Comment by BenSova** [comment]
Yeah, this issue could use some proofing and is a duplicate so I'm just going to close this to remove the clutter off of the repo...
