### ISSUE TITLE
After install Big Sur Macbook Pro 13pol (7.1) dont boot.

### ISSUE THREAD

**Issue by MrBaffu** [BenSova/Patched-Sur#88]
**Describe the bug**
After install Big Sur Macbook Pro 13pol (7.1) dont boot.
![IMG_1755](https://user-images.githubusercontent.com/74886521/99925299-5d256c80-2d1c-11eb-86a7-5f8b773cb01c.jpeg)

**To Reproduce**
Followed your instructions:
1. Create the USB driver patched using Catalina. No error.
2. Boot with EFI first
3. Boot and install. No error message in the process.
4. After the reboot the just got the Apple message "Your computer restarted because of a problem. Press a key or wait a few seconds to continue starting up"

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.X
- Upgrading to: Big Sur v11.0.1
 - Mac Model: 13" 2010 Mid MacBook Pro
 - Version: v0.0.4

I have 2 SSDs. One with High Sierra and Bootcamp to Windows and the other with Catalina.  If I boot the computer from High Sierra it works.

**Comment by jamesbird883** [comment]
Hello, I have same result. Do you find a solution ?

**Comment by john7887** [comment]
I have same problem. I patched via micropatcher v 0.5.1

**Comment by MrBaffu** [comment]
@jamesbird883 , so far I didn't find solution. Please let me know if you found it.

@john7887 , I also tried micropatcher v0.5.1 before and got the exactly the same behavior.

Both of you, do you have more than one disk or partition?

Cheers,

**Comment by john7887** [comment]
I have only ssd

**Comment by john7887** [comment]
> I have only ssd



> @jamesbird883 , so far I didn't find solution. Please let me know if you found it.
> 
> @john7887 , I also tried micropatcher v0.5.1 before and got the exactly the same behavior.
> 
> Both of you, do you have more than one disk or partition?
> 
> Cheers,

I have only ssd

**Comment by outgalaxy** [comment]
I have same problem. when will be fixed this problem? Dosdude very worked fast, Bensova works very slow

**Comment by BenSova** [comment]
I don't have to respond to see. Plus, there are tons of people bothering me, I can't investigate each one.

**Comment by BenSova** [comment]
First and foremost, try booting into Safe Mode (shift on boot)

> when will be fixed this problem?

I need to diagnose the problem before I fix it. You got to learn this about indie developers, whether it be me, dosdude1, or someone else, **there is rarely ever an eta**.

> Dosdude very worked fast, Bensova works very slowly

I almost deleted your comment because of that message. I'm a living, breathing human, with a job. I don't spend 100% of my time one this.

> Macbook Pro 13pol (7.1)

That Mac won't have graphics acceleration on Big Sur, making it completely unusable, you have to consider that. I will try to help with the problem, but that Mac is way to old to run Big Sur well.

**Comment by outgalaxy** [comment]
Happy new year my friend! Please fix it asap, thanks.

**Comment by BenSova** [comment]
Can somebody please try booting into safe mode?

**Comment by outgalaxy** [comment]
My friend, I have macOS catalina, Please write me what can I do after install big sur and try safe mode? What are you interested for fix this bug

**Comment by MrBaffu** [comment]
> I have same problem. when will be fixed this problem? Dosdude worked very fast, Bensova works very slowly

@outgalaxy I really hope that you express yourself badly by some language knowledge. @BenSova has no obligation at all.

@BenSova,  Man, your work is fantastic already. Thank you!

**Comment by MrBaffu** [comment]
> Can somebody please try booting into safe mode?

@BenSova, I have this "old" MacBook for one 10 year just as a regular user, even I'm working with IT all my life. I really want to help on this troubleshooting, but you may need some patience.

To give you some context: The device that I'm using for tests has 2 SSD drives. I replaced the DVD driver. In one of the SSD I'm running High Sierra and Windows 10 using BootCamp. In the other drive I had only Catalina. I had tried updated it direct from Catalina to BigSur and also tried any clean installation.

I just tried to boot into safe mode and got the same error. During the loading bar the Mac boot again... over and over.

Please, let me know what should be the next step to troubleshooting it.

Thank you!

**Comment by BenSova** [comment]
@MrBaffu Try ⌘V on boot. It still won't help, but it will show some information that might help with troubleshooting. When you do this, you'll see an excessive amount of text. I just need that last bit where it completely stops scrolling. It'll show some text that should look separated from everything else. Could you send a screenshot of that?

**Comment by MrBaffu** [comment]
@BenSova, I tried to get the end of the log, but it reboot to fast. Is there any way to disable auto-boot? I tried to google but no success.
 Anyway, I see that the Drive available for boot is the "BigSur - DATA". Shouldn't be the "BigSur"?

See some photos. Guide me how to get the full log.

![IMG_1865](https://user-images.githubusercontent.com/74886521/104796688-53a60700-5797-11eb-9ba9-aae281d872a9.jpg)
![IMG_1866](https://user-images.githubusercontent.com/74886521/104796689-54d73400-5797-11eb-90ae-81aa8df58f1b.jpg)
![IMG_1868](https://user-images.githubusercontent.com/74886521/104796690-56a0f780-5797-11eb-9abb-776c565e1b84.jpg)

Cheers

**Comment by outgalaxy** [comment]
> > I have same problem. when will be fixed this problem? Dosdude worked very fast, Bensova works very slowly
> 
> @outgalaxy I really hope that you express yourself badly by some language knowledge. @BenSova has no obligation at all.
> 
> @BenSova, Man, your work is fantastic already. Thank you!

Is your name George?

**Comment by BenSova** [comment]
Boot into macOS recovery, open Terminal under the Utilities menu, and run this command:
```
nvram boot-args="-no_compat_check debug=0x100 keepsyms=1"
```
After that, try again with verbose mode and send pictures. If you ever want to undo those changes, boot into the EFI Boot on the installer USB.

**Comment by MrBaffu** [comment]
@BenSova there is the log :-)
Hope it can help
![IMG_1873](https://user-images.githubusercontent.com/74886521/105111656-1cd63680-5aa0-11eb-8e18-622dcba89144.jpeg)
.
Thank you!

**Comment by guicz** [comment]
![069CA01F-E5AC-4D26-BDF2-6C0E36B192AE](https://user-images.githubusercontent.com/21048575/107850767-a6e59680-6de3-11eb-93b7-1098260ef093.jpeg)

ouch

Anyone knows how to deal with it without having to reformat?

**Comment by BenSova** [comment]
I got to find another place to put this.
# Boot into the EFI Boot.

**Comment by MrBaffu** [comment]
Dear All, specially @BenSova .
I just sold my Macbook Pro 13pol (7.1) Mid 2010. So I can't help anymore.
Best Regards

**Comment by MrBaffu** [comment]
Dear All, specially @BenSova .
I just sold my Macbook Pro 13pol (7.1) Mid 2010. So I can't help anymore.
Best Regards
