### ISSUE TITLE
error createinstallmedia

### ISSUE THREAD

**Issue by ramonenghaw** [BenSova/Patched-Sur#9]
I'm trying to install Release Candidate 2, when the files are going to be copied to the usb sticker, the following message appears:

Error 1x1
Password: sudo: / Applications / Install macOS Big Sur Beta.app//Contents/Resources/createinstallmedia: command not found

**Comment by BenSova** [comment]
I accidentally left it in testing mode, so I just re-uploaded it try that.

**Comment by BenSova** [comment]
It worked for someone else, so I assume it will work here, since it is the same issue.
