### ISSUE TITLE
Beta 0.0.4 --Fehler (14) (Error) 1x252 Password

### ISSUE THREAD

**Issue by schmutzige-dame** [BenSova/Patched-Sur#92]
Beta 0.0.4 --Error (14) (Error) 1x252 Password: Erasing Disk: 0% .... 10% Error erasing disk error number (-69888,0) An Error occurred ereasing the disk.
Used on BigSur 11.01, iMac 21.5, Late 2013
Three different USB sticks from other brands used this error again and again!

The error listed above does not occur under Beta 0.0.3 (13)!

Used on BigSur 11.01, iMac 21.5, Late 2013

The error no longer occurred with Beta 0.0.3 (13) under Catalina 10.15.6 - a 16GB USB slap stick could be created with BigSur. iMac 21.5, late 2013

__________________________________________________

Beta 0.0.4 --Fehler (14) (Error) 1x252 Password: Erasing Disk: 0% ....10% Error erasing disk error number (-69888,0) An Error occurred ereasing the disk. 
Verwendet unter BigSur 11.01, iMac 21.5, Ende 2013
Drei verschiedene USB-Stick anderer Marken verwendet immer wieder dieser Fehler!

Der oben aufgefürhrte Fehler tritt nicht unter Beta 0.0.3 (13) auf!

Verwendet unter BigSur 11.01, iMac 21.5, Ende 2013

Der Fehler ist nicht mehr mit Beta 0.0.3 (13) unter Catalina 10.15.6 aufgetreten es konnte ein 16GB USB-Patsch-Stick mit BigSur erstelltwerden. iMac 21.5, Ende 2013

**Comment by TechComputerServiceDunkerque** [comment]
I have the same mistake

**Comment by schmutzige-dame** [comment]
So now both versions Beta 0.0.3 (13) and Beta 0.0.4 (14) are unusable for us! Shame!

_______________________________________________________________________

Somit sind nun beide Versionen Beta 0.0.3 (13) und Beta 0.0.4 (14) für uns unbrauchbar! Schad!

**Comment by BenSova** [comment]
It's an Apple bug. Out of my control. I'm probably just going to end up rewriting the script myself to have it create the usb my way and skip that double erase. (#89)

**Comment by schmutzige-dame** [comment]
Ok warten wir mal. Danke für die Antwort.

**Comment by schmutzige-dame** [comment]
Good day,

the error still persists. Creating a USB stick under MacOS BigSur 11.0.1 iMag 21.5 at the end of 2013 is not possible with Patched-Sur (14) 0.0.4. After a short time, the following error continues to be displayed:
Error 1x252
Password: Erasing disk: 0% ... 10% ...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

Will the bug be fixed in the new version?

Best regards
_____________________________________________________

Guten Tag,

der Fehler besteht immer noch. Ein erstellen eines USB-Sticks unter MacOS BigSur 11.0.1 iMag 21,5 Ende 2013 ist mit Patched-Sur (14) 0.0.4 nicht möglich. Nach kurzer Zeit wird weiterhin folgender Fehler angezeigt: 
Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

Wird der Fehler erst in der neuen Version behoben werden?

Beste Grüße

**Comment by BenSova** [comment]
Once again, this is out of my control. I'm running a command that Apple built and I have no way of modifying how it works.

**Comment by AndreasLueck** [comment]
Hallo schmutzige Dame, ich hatte das gleiche Problem am MacMini von 2012. Wobei mein Fehler eher war, das der Stick zwar formatiert hat, aber keinen Daten im Anschluß kopiert wurden. Er blieb leer... 
Lösung: Mit einem neueren Macbook Pro (bereits Big Sur drauf) konnte ich dann den Stick ordentlich erstellen. Dieser hat dann den MacMini gepatched. Danach wollte das Patch Kext Tool nicht, aber indem ich das Patch Kext Script vom Stick in mein Terminal-Fenster gezogen habe, ging's zumindest so.
Nun habe ich Big Sur auf dem MacMini, aber aktuell kein Bluetooth und kein Internet, trotz LAN. Mal sehen woran das noch liegt...
Viel Erfolg!
----------------
So there is a trick to bypass problems with creating the stick: just take another Mac (if you got one).

**Comment by BenSova** [comment]
It's the same command each time. A different Mac shouldn't change the output. And I'm not going to use that as advice because of the fact I don't want "where is the post install app" questions.

**Comment by gufranco** [comment]
Same bug, but I was able to run the patch manually. I executed the createinstallmedia command to create the Big Sur installer and, after a few minutes of waiting, executed patch-usb.sh from ~/.patched-sur

**Comment by BenSova** [comment]
This is going to be tracked in #154 because there is more discussion there.
