### ISSUE TITLE
Error Beta 0.0.3 (13) Download Install Assistand Package

### ISSUE THREAD

**Issue by schmutzige-dame** [BenSova/Patched-Sur#93]
Download Install Assistand Package
Error: 

the package path specified was invalid: Users/xxxxx/.patched-sur/Insta............... ab hier wirde der Schriftzug nicht weiter angezeigt. 

Beta 0.0.3 (13) was used under Catalinsa 10.15.6 iMac at the end of 2013

__________________________________________________________________________________

Laden Sie das Install Assistand-Paket herunter
Error:

Der angegebene Paketpfad war ungültig: Benutzer / xxxxx / .patched-sur / Insta ............... ab hier wirde der Schriftzug nicht weitergehende.

Beta 0.0.3 (13) wurde Ende 2013 unter Catalinsa 10.15.6 iMac verwendet

**Comment by BenSova** [comment]
I'm not supporting v0.0.3 anymore. It's a legacy version.
