### ISSUE TITLE
Beta (13) 0.0.3 breaks off again!

### ISSUE THREAD

**Issue by schmutzige-dame** [BenSova/Patched-Sur#96]
ASother bug in beta 0.0.3 (13)

Now the Patched-Sur Beta 13 software cancels the writing process with the following message.

----- @executable_path /../ Frameworks / IAESD.framework / Version / A / IAESD .......
tall macOS Big Sur.app/Coneterns/Resources/createinstallmedia .....
DID find:
... Sur.app/contents/Rescorces/../Framework/IAESD.Framework/Version/A/
..... Sur.app/contents/Rescorces/../Framework/IAESD.Framework/Version/A/

Tried several times no more creating the stick possible.

Used on macOS Catalina 10.15.6 iMac 21.0 late 2013

_________________________________________________________________

Ein erneute Bug in Beta 0.0.3 (13)

nun bricht die Software Patched-Sur Beta 13 den schreibvorgang mit folgender meldung ab.

----- @executable_path/../Frameworks/IAESD.framework/Version/A/IAESD....... 
tall macOS Big Sur.app/Coneterns/Resources/createinstallmedia.....
DID find:
... Sur.app/contents/Rescorces/../Framework/IAESD.Framework/Version/A/
.....Sur.app/contents/Rescorces/../Framework/IAESD.Framework/Version/A/

Mehrmals probiert kein erstellen des Sticks mehr möglich. 

Verwendet unter macOS Catalina 10.15.6 iMac 21.0 Ende 2013

**Comment by BenSova** [comment]
Once again, I don't support any older versions once a new one comes out. I will support people upgrading to a newer version if something went wrong and they can't get WiFi working or are stuck with prohibited symbol and similar, but not just random errors.

**Comment by schmutzige-dame** [comment]
Dear ben,

Please explain to me how you should create a boot stick under Mojave or Catalina if your software no longer supports it?

I don't want to switch to BigSur yet because it still has too many bugs. So I'd rather stay on Mojave. I also skipped Catalina.

But I have friends whom I like to help and who would also like to create a BigSur Stick under Mojave or Catalina. But that is no longer possible. Too bad.


__________________________________________

Lieber Ben, 

bitte erklären Sie mir dann mal wie man unter Mojave oder Catalina einen  Bootstick erstellen soll wenn ihre Software das nicht mehr unterstützt?

Ich möchte noch nicht auf BigSur umsteigen, da es noch zu viele Bugs hat. Daher möchte ich lieber auf Mojave bleiben. Catalina habe ich auch übersprungen. 

Ich habe aber Freunde denen ich gerne helfe und auch gerne einen BigSur Stick unter Mojave oder Catalina erstellen möchte. Doch das geht nun nicht mehr. Schade. 

Mit freundlichen Grüßen

Sincerely yours

**Comment by BenSova** [comment]
I mean older versions of Patched Sur, not macOS. I support anyone on Catalina and higher and the he latest version of Patched Sur.

**Comment by schmutzige-dame** [comment]
yes, and this same mistake has just occurred again under Catalina.

________________________________________________________________________

ja, und genau dieser Fehler ist gerade wieder unter Catalina aufgetreten.
