### ISSUE TITLE
Error 1x1 patch-usb.sh: command not found

### ISSUE THREAD

**Issue by Kenzi-K** [BenSova/Patched-Sur#97]
Error 1x1
Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

USB Installer Create Error

**Comment by BenSova** [comment]
Guys, you got to at some point understand that "Right Click to Open" does not mean "Drag to Applications Folder".

**Comment by Kenzi-K** [comment]
THX.
Install USB and Big Sur installation completed successfully.

**Comment by xerman5** [comment]
> Guys, you got to at some point understand that "Right Click to Open" does not mean "Drag to Applications Folder".

I didn't do that. I opened the application as indicated.
