### ISSUE TITLE
Error 1x1 - Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

### ISSUE THREAD

**Issue by xerman5** [BenSova/Patched-Sur#98]
**Error 1x1**
Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found

I get this error when the program is in the second step, creating the usb installer. The patcher formats the usb drive and names it "Install macOS Big Sur". I think there is no volume name "Patched-Sur".

I downloaded "InstallAssistant.pkg" by myself because my connection is quite weak and I get an error when I'm trying to download it using the program.

¿Any idea of what can I do to make it work?
Thanks.

**Comment by BenSova** [comment]
I'm going to start keeping a list: #97 and more.

**Comment by xerman5** [comment]
Again, I didn't move the application anywhere.
Following the instructions I opened it using the right mouse button.

**Comment by BenSova** [comment]
And the dmg that you downloaded was still mounted?

**Comment by xerman5** [comment]
Maybe that was it, I'm going to check it right now. Thanks!

**Comment by xerman5** [comment]
Solved, that was it, the download was not mounted. 
Thank you.
