### ISSUE TITLE
Nach Update auf BIG SUR kein Wlan mehr 

### ISSUE THREAD

**Issue by Knurry** [BenSova/Patched-Sur#99]
Nachdem ich meinen MAcbook Pro 2012 auf das BIGSur geupdatet habe geht das Wlan nicht mehr . ich kann es nicht mehr anstellen . 
Muss ich noch etwas machen um das es geht andere treiber installieren ? 

hätte da gern eine genauere beschreibung da ja einige das problem haben aber ich finde keine lösung

**Comment by KevinMllrd** [comment]
This is indicated in the Read Me:

13. After the installer is done, (it will take a while and appear to get stuck), log in to your Mac and **open Patched Sur from your Applications folder or LaunchPad**.

14. Open the Patch Kexts section and enter your password. Then, you should be able to reboot and enjoy Big Sur!

**Comment by Knurry** [comment]
ok das war es der Button für das password war verdeckt 

Besten Dank
